from batch1 import D
CARDS = {}

# 73: Deep Stunning adverts collage
CARDS['b20_deepstun'] = ('burg', {
 'en': D("CANCER ADVERTISING", "Who will protect desperate patients?", "The picture shows Turkish adverts and TV captions that promise a cure for cancer", None, None,
   [("What the adverts say:", "a \"Turkish revolution in cancer treatment\", a method called \"Deep Stunning\", recovery from stage 4 cancer, \"do not lose hope\"."),
    ("The term:", "\"deep stunning\" comes from animal slaughter: making the animal deeply unconscious before it is killed. It is not a standard medical term."),
    ("The evidence:", "no evidence or published data in the peer-reviewed medical literature. The term appears only in advertising videos and short case stories."),
    ("Herbal products:", "none has been proven to prevent or cure cancer in humans. \"Natural\" does not mean \"safe\"."),
    ("The risk:", "lost time and resources, possible side effects, and a smaller chance of treatment for patients who could be treated.")],
   "Anyone who promises a \"miracle cure\" must be questioned on evidence, publications and ethical oversight."),
 'de': D("KREBSWERBUNG", "Wer schützt verzweifelte Patienten?", "Das Bild zeigt türkische Anzeigen und TV-Einblendungen, die Heilung von Krebs versprechen", None, None,
   [("Was die Werbung sagt:", "eine „türkische Revolution in der Krebstherapie“, eine Methode namens „Deep Stunning“, Heilung von Krebs im Stadium 4, „Verlieren Sie nicht die Hoffnung“."),
    ("Der Begriff:", "„Deep Stunning“ stammt aus der Schlachtung: die tiefe Betäubung des Tieres vor dem Töten. Es ist kein üblicher medizinischer Begriff."),
    ("Die Evidenz:", "keine Belege und keine veröffentlichten Daten in der begutachteten Fachliteratur. Der Begriff kommt nur in Werbevideos und kurzen Fallgeschichten vor."),
    ("Pflanzliche Produkte:", "für keines ist belegt, dass es Krebs beim Menschen verhindert oder heilt. „Natürlich“ heißt nicht „sicher“."),
    ("Das Risiko:", "Verlust von Zeit und Mitteln, mögliche Nebenwirkungen und geringere Behandlungschancen für behandelbare Patienten.")],
   "Wer eine „Wunderheilung“ verspricht, muss nach Evidenz, Publikationen und ethischer Kontrolle gefragt werden."),
 'es': D("PUBLICIDAD SOBRE EL CÁNCER", "¿Quién protegerá a los pacientes desesperados?", "La imagen muestra anuncios y rótulos de televisión turcos que prometen curar el cáncer", None, None,
   [("Lo que dicen los anuncios:", "una «revolución turca en el tratamiento del cáncer», un método llamado «Deep Stunning», curación del cáncer en estadio 4, «no pierda la esperanza»."),
    ("El término:", "«deep stunning» procede del sacrificio de animales: dejar al animal profundamente inconsciente antes de matarlo. No es un término médico habitual."),
    ("La evidencia:", "no hay pruebas ni datos publicados en la literatura médica revisada por pares. El término solo aparece en vídeos publicitarios y relatos breves de casos."),
    ("Productos a base de plantas:", "ninguno ha demostrado prevenir o curar el cáncer en humanos. «Natural» no significa «seguro»."),
    ("El riesgo:", "pérdida de tiempo y recursos, posibles efectos adversos y menos posibilidades de tratamiento para pacientes tratables.")],
   "A quien promete una «cura milagrosa» hay que exigirle pruebas, publicaciones y control ético."),
 'ru': D("РЕКЛАМА ЛЕЧЕНИЯ РАКА", "Кто защитит отчаявшихся пациентов?", "На изображении турецкая реклама и телевизионные титры, обещающие излечение от рака", None, None,
   [("Что говорит реклама:", "«турецкая революция в лечении рака», метод под названием «Deep Stunning», излечение от рака 4-й стадии, «не теряйте надежду»."),
    ("Термин:", "«deep stunning» взят из убоя животных: глубокое оглушение животного перед убоем. Это не общепринятый медицинский термин."),
    ("Доказательства:", "в рецензируемой медицинской литературе нет ни доказательств, ни опубликованных данных. Термин встречается только в рекламных видео и кратких описаниях случаев."),
    ("Растительные средства:", "ни для одного не доказано, что оно предотвращает или излечивает рак у человека. «Натуральное» не значит «безопасное»."),
    ("Риск:", "потеря времени и средств, возможные побочные эффекты и меньшие шансы на лечение у излечимых пациентов.")],
   "У каждого, кто обещает «чудесное исцеление», нужно требовать доказательства, публикации и этический контроль."),
 'zh': D("癌症广告", "谁来保护走投无路的患者？", "图中是土耳其的广告和电视字幕，都在承诺治愈癌症", None, None,
   [("广告怎么说：", "“癌症治疗的土耳其革命”、名为“Deep Stunning”的方法、4期癌症康复、“不要绝望”。"),
    ("这个术语：", "“deep stunning”来自动物屠宰，指宰杀前使动物陷入深度昏迷。它不是标准的医学术语。"),
    ("证据：", "同行评议的医学文献中没有任何证据或已发表的数据。该术语只出现在广告视频和简短的病例叙述中。"),
    ("草药产品：", "没有任何一种被证实能在人体预防或治愈癌症。“天然”不等于“安全”。"),
    ("风险：", "浪费时间和资源，可能出现不良反应，并降低本可治疗的患者的治疗机会。")],
   "对任何承诺“神奇疗法”的人，都必须追问证据、发表的论文和伦理监督。"),
 'hi': D("कैंसर के विज्ञापन", "लाचार मरीज़ों की रक्षा कौन करेगा?", "चित्र में तुर्की के विज्ञापन और टीवी कैप्शन हैं, जो कैंसर ठीक करने का वादा करते हैं", None, None,
   [("विज्ञापन क्या कहते हैं:", "\"कैंसर के इलाज में तुर्की क्रांति\", \"Deep Stunning\" नाम की विधि, स्टेज 4 कैंसर से मुक्ति, \"निराश न हों\"।"),
    ("यह शब्द:", "\"deep stunning\" पशु वध से आया है: वध से पहले पशु को गहरी बेहोशी में डालना। यह कोई मानक चिकित्सा शब्द नहीं है।"),
    ("प्रमाण:", "समकक्ष-समीक्षित चिकित्सा साहित्य में कोई प्रमाण या प्रकाशित आँकड़े नहीं हैं। यह शब्द केवल विज्ञापन वीडियो और छोटी केस कहानियों में मिलता है।"),
    ("हर्बल उत्पाद:", "किसी के बारे में यह सिद्ध नहीं हुआ कि वह मनुष्यों में कैंसर को रोकता या ठीक करता है। \"प्राकृतिक\" का अर्थ \"सुरक्षित\" नहीं है।"),
    ("जोखिम:", "समय और संसाधनों की हानि, संभावित दुष्प्रभाव, और इलाज योग्य मरीज़ों के लिए इलाज की कम संभावना।")],
   "जो भी \"चमत्कारी इलाज\" का वादा करे, उससे प्रमाण, प्रकाशन और नैतिक निगरानी के बारे में पूछा जाना चाहिए।"),
 'ja': D("がん治療の広告", "追い詰められた患者を誰が守るのか", "画像はトルコの広告とテレビのテロップで、がんが治ると約束している", None, None,
   [("広告の文句：", "「がん治療におけるトルコの革命」、「Deep Stunning」という方法、ステージ4のがんからの回復、「希望を捨てないで」。"),
    ("この用語：", "「deep stunning」は家畜のと畜で使われる言葉で、と畜前に動物を深い意識消失状態にすることを指す。標準的な医学用語ではない。"),
    ("エビデンス：", "査読付き医学文献には根拠も公表データもない。この用語は広告動画と短い症例の語りにしか出てこない。"),
    ("ハーブ製品：", "ヒトでがんを予防または治癒すると証明されたものは一つもない。「天然」は「安全」を意味しない。"),
    ("リスク：", "時間と資源の損失、起こりうる副作用、そして治療可能な患者の治療機会の低下。")],
   "「奇跡の治療」を約束する者には、必ず根拠、論文、倫理的な監督を問わなければならない。"),
})

# 74: National drug, national team
CARDS['b20_milli'] = ('navy', {
 'en': D("A PAGE FROM HISTORY", "National drug and national team", "Headlines keep announcing Turkey's \"first domestic drug candidate\". This article was written 12 years earlier.",
   [("1 in 10,000", "molecules studied reaches the market as a drug"), ("15 years", "at least, for that process"), ("$49.5 bn", "R&D spending of PhRMA companies in 2011"), ("~$15 bn", "Turkey's total drug turnover")], None,
   [("The headlines:", "\"Türkiye's first domestic drug candidate\", \"a giant step in 'national drug' production\", \"stage 2 reached in the national drug goal\"."),
    ("The cost:", "estimates of the average R&D cost range from 400 million to 1.7 billion dollars. A top-level clinical trial costs around 100 million dollars."),
    ("Who pays:", "the private sector wants the state to pay for R&D and to keep the profit for itself."),
    ("What is realistic:", "Turkey has a strong, modern drug industry. Its R&D is on formulation, and quality biosimilars can be made.")],
   "R&D starts by investing in the scientist."),
 'de': D("EIN BLATT AUS DER GESCHICHTE", "Nationales Arzneimittel und Nationalmannschaft", "Schlagzeilen verkünden immer wieder den „ersten einheimischen Arzneimittelkandidaten“ der Türkei. Dieser Artikel wurde 12 Jahre zuvor geschrieben.",
   [("1 von 10.000", "untersuchten Molekülen kommt als Arzneimittel auf den Markt"), ("15 Jahre", "dauert dieser Prozess mindestens"), ("49,5 Mrd. $", "F&E-Ausgaben der PhRMA-Firmen 2011"), ("~15 Mrd. $", "gesamter Arzneimittelumsatz der Türkei")], None,
   [("Die Schlagzeilen:", "„Der erste einheimische Arzneimittelkandidat der Türkei“, „Riesenschritt bei der Herstellung des ‚nationalen Arzneimittels‘“, „Phase 2 beim Ziel nationales Arzneimittel erreicht“."),
    ("Die Kosten:", "Schätzungen der durchschnittlichen F&E-Kosten reichen von 400 Millionen bis 1,7 Milliarden Dollar. Eine hochrangige klinische Studie kostet rund 100 Millionen Dollar."),
    ("Wer zahlt:", "die Privatwirtschaft will, dass der Staat die F&E bezahlt, und den Gewinn selbst behalten."),
    ("Was realistisch ist:", "die Türkei hat eine starke, moderne Arzneimittelindustrie. Ihre F&E betrifft die Formulierung, und hochwertige Biosimilars sind möglich.")],
   "F&E beginnt mit der Investition in den Wissenschaftler."),
 'es': D("UNA PÁGINA DE LA HISTORIA", "Medicamento nacional y selección nacional", "Los titulares anuncian una y otra vez el «primer candidato a medicamento nacional» de Turquía. Este artículo se escribió 12 años antes.",
   [("1 de 10.000", "moléculas estudiadas llega al mercado como medicamento"), ("15 años", "como mínimo dura ese proceso"), ("49.500 M$", "gasto en I+D de las empresas de PhRMA en 2011"), ("~15.000 M$", "facturación total de medicamentos de Turquía")], None,
   [("Los titulares:", "«El primer candidato a medicamento nacional de Turquía», «un paso de gigante en la producción del 'medicamento nacional'», «se pasó a la fase 2 en el objetivo del medicamento nacional»."),
    ("El coste:", "las estimaciones del coste medio de I+D van de 400 millones a 1.700 millones de dólares. Un ensayo clínico de alto nivel cuesta unos 100 millones de dólares."),
    ("Quién paga:", "el sector privado quiere que el Estado pague la I+D y quedarse con el beneficio."),
    ("Lo realista:", "Turquía tiene una industria farmacéutica fuerte y moderna. Su I+D se centra en la formulación, y puede fabricar biosimilares de calidad.")],
   "La I+D empieza invirtiendo en el científico."),
 'ru': D("СТРАНИЦА ИСТОРИИ", "Национальное лекарство и национальная сборная", "Заголовки снова и снова объявляют о «первом отечественном кандидате в лекарства» Турции. Эта статья была написана 12 годами раньше.",
   [("1 из 10 000", "изученных молекул выходит на рынок как лекарство"), ("15 лет", "как минимум занимает этот процесс"), ("49,5 млрд $", "расходы компаний PhRMA на НИОКР в 2011 году"), ("~15 млрд $", "весь оборот лекарств в Турции")], None,
   [("Заголовки:", "«Первый отечественный кандидат в лекарства Турции», «гигантский шаг в производстве „национального лекарства“», «в проекте национального лекарства начат 2-й этап»."),
    ("Стоимость:", "оценки средней стоимости НИОКР составляют от 400 миллионов до 1,7 миллиарда долларов. Клиническое исследование высокого уровня стоит около 100 миллионов долларов."),
    ("Кто платит:", "частный сектор хочет, чтобы за НИОКР платило государство, а прибыль оставалась ему."),
    ("Что реалистично:", "в Турции сильная современная фармацевтическая промышленность. Её НИОКР касаются лекарственных форм, и качественные биоаналоги выпускать можно.")],
   "НИОКР начинаются с инвестиций в учёного."),
 'zh': D("历史的一页", "国产药与国家队", "新闻标题一再宣布土耳其的“首个国产候选药物”。本文写于12年前。",
   [("万分之一", "被研究的分子最终能作为药物上市"), ("15年", "这一过程至少需要的时间"), ("495亿美元", "2011年PhRMA成员企业的研发支出"), ("约150亿美元", "土耳其药品总营业额")], None,
   [("新闻标题：", "“土耳其首个国产候选药物”、“‘国产药’生产迈出一大步”、“国产药目标进入第2阶段”。"),
    ("成本：", "对平均研发成本的估计在4亿至17亿美元之间。一项高水平临床试验约需1亿美元。"),
    ("谁来付钱：", "私营部门希望由国家承担研发费用，利润则归自己。"),
    ("现实的做法：", "土耳其拥有强大而现代的制药工业。其研发集中在制剂上，并且能够生产高质量的生物类似药。")],
   "研发要从投资科学家开始。"),
 'hi': D("इतिहास का एक पन्ना", "राष्ट्रीय दवा और राष्ट्रीय टीम", "सुर्खियाँ बार-बार तुर्की के \"पहले स्वदेशी दवा उम्मीदवार\" की घोषणा करती हैं। यह लेख 12 साल पहले लिखा गया था।",
   [("10,000 में 1", "अध्ययन किए गए अणुओं में से दवा बनकर बाज़ार पहुँचता है"), ("15 साल", "इस प्रक्रिया में कम से कम लगते हैं"), ("49.5 अरब $", "2011 में PhRMA कंपनियों का R&D खर्च"), ("~15 अरब $", "तुर्की का कुल दवा कारोबार")], None,
   [("सुर्खियाँ:", "\"तुर्की का पहला स्वदेशी दवा उम्मीदवार\", \"'राष्ट्रीय दवा' के उत्पादन में विशाल कदम\", \"राष्ट्रीय दवा के लक्ष्य में दूसरा चरण शुरू\"।"),
    ("लागत:", "औसत R&D लागत के अनुमान 40 करोड़ से 1.7 अरब डॉलर तक हैं। एक उच्च स्तरीय नैदानिक परीक्षण की लागत लगभग 10 करोड़ डॉलर है।"),
    ("भुगतान कौन करे:", "निजी क्षेत्र चाहता है कि R&D का खर्च सरकार उठाए और मुनाफ़ा उसके पास रहे।"),
    ("यथार्थवादी क्या है:", "तुर्की में मज़बूत और आधुनिक दवा उद्योग है। उसका R&D फ़ॉर्मूलेशन पर है, और गुणवत्तापूर्ण बायोसिमिलर बनाए जा सकते हैं।")],
   "R&D की शुरुआत वैज्ञानिक में निवेश से होती है।"),
 'ja': D("歴史の一ページ", "国産医薬品とナショナルチーム", "見出しは繰り返しトルコ「初の国産医薬品候補」を報じる。この記事はその12年前に書かれた。",
   [("1万分の1", "研究された分子のうち医薬品として市場に出る割合"), ("15年", "その過程に最低でもかかる期間"), ("495億ドル", "2011年のPhRMA加盟企業の研究開発費"), ("約150億ドル", "トルコの医薬品総売上高")], None,
   [("見出し：", "「トルコ初の国産医薬品候補」、「『国産医薬品』製造で大きな一歩」、「国産医薬品の目標で第2段階へ」。"),
    ("コスト：", "平均的な研究開発費の推定は4億ドルから17億ドル。高水準の臨床試験1件に約1億ドルかかる。"),
    ("誰が払うのか：", "民間部門は研究開発費を国に負担させ、利益は自分のものにしたがっている。"),
    ("現実的なこと：", "トルコには強力で近代的な製薬産業がある。その研究開発は製剤が中心で、高品質のバイオシミラーは製造できる。")],
   "研究開発は科学者への投資から始まる。"),
})

# 76: Those who deceive cancer patients
CARDS['b20_kandir'] = ('teal', {
 'en': D("CANCER AND FALSE HOPE", "Those who deceive cancer patients", "The picture shows Turkish adverts and headlines for herbal \"cancer cures\"", None, None,
   [("What the adverts say:", "\"success in lung cancer without chemotherapy\", \"phytotherapy support in cancer treatment\" for a long list of cancers, \"treats cancer in 20 days\"."),
    ("Nobel myths:", "posts cite \"Nobel-winning professors\". The work of Honjo and Allison (Nobel Prize 2018) led to immunotherapy with PD-1 and CTLA-4 inhibitors, not to herbal treatment."),
    ("Phytotherapy:", "at most a supportive or complementary method. No plant has been found that eliminates cancer in humans."),
    ("The evidence:", "effects have mostly been shown only in the laboratory or in animal models."),
    ("Interactions:", "herbal products can interact with medicines and reduce the effect of treatment.")],
   "Phytotherapy cannot replace chemotherapy, radiotherapy, surgery or immunotherapy. Do not believe charlatans who advertise on social media."),
 'de': D("KREBS UND FALSCHE HOFFNUNG", "Wer Krebspatienten täuscht", "Das Bild zeigt türkische Anzeigen und Schlagzeilen für pflanzliche „Krebsheilungen“", None, None,
   [("Was die Werbung sagt:", "„Erfolg bei Lungenkrebs ohne Chemotherapie“, „Phytotherapie-Unterstützung in der Krebsbehandlung“ für eine lange Liste von Krebsarten, „behandelt Krebs in 20 Tagen“."),
    ("Nobel-Mythen:", "Beiträge berufen sich auf „Nobelpreis-Professoren“. Die Arbeiten von Honjo und Allison (Nobelpreis 2018) führten zur Immuntherapie mit PD-1- und CTLA-4-Inhibitoren, nicht zu pflanzlicher Behandlung."),
    ("Phytotherapie:", "höchstens eine unterstützende oder ergänzende Methode. Es wurde keine Pflanze gefunden, die Krebs beim Menschen beseitigt."),
    ("Die Evidenz:", "Wirkungen wurden meist nur im Labor oder in Tiermodellen gezeigt."),
    ("Wechselwirkungen:", "pflanzliche Produkte können mit Arzneimitteln interagieren und die Wirkung der Therapie verringern.")],
   "Phytotherapie kann Chemotherapie, Strahlentherapie, Operation oder Immuntherapie nicht ersetzen. Glauben Sie Scharlatanen nicht, die in sozialen Medien werben."),
 'es': D("CÁNCER Y FALSA ESPERANZA", "Quienes engañan a los pacientes con cáncer", "La imagen muestra anuncios y titulares turcos de «curas del cáncer» con plantas", None, None,
   [("Lo que dicen los anuncios:", "«éxito en cáncer de pulmón sin quimioterapia», «apoyo de fitoterapia en el tratamiento del cáncer» para una larga lista de cánceres, «trata el cáncer en 20 días»."),
    ("Mitos del Nobel:", "las publicaciones citan a «profesores premiados con el Nobel». El trabajo de Honjo y Allison (Nobel 2018) condujo a la inmunoterapia con inhibidores de PD-1 y CTLA-4, no a tratamientos con plantas."),
    ("Fitoterapia:", "como mucho, un método de apoyo o complementario. No se ha encontrado ninguna planta que elimine el cáncer en humanos."),
    ("La evidencia:", "los efectos se han demostrado casi siempre solo en el laboratorio o en modelos animales."),
    ("Interacciones:", "los productos a base de plantas pueden interactuar con los medicamentos y reducir el efecto del tratamiento.")],
   "La fitoterapia no puede sustituir a la quimioterapia, la radioterapia, la cirugía ni la inmunoterapia. No crea a los charlatanes que se anuncian en redes sociales."),
 'ru': D("РАК И ЛОЖНАЯ НАДЕЖДА", "Те, кто обманывает онкологических больных", "На изображении турецкая реклама и заголовки о растительных «средствах от рака»", None, None,
   [("Что говорит реклама:", "«успех при раке лёгкого без химиотерапии», «фитотерапевтическая поддержка в лечении рака» для длинного списка опухолей, «лечит рак за 20 дней»."),
    ("Нобелевские мифы:", "публикации ссылаются на «профессоров, получивших Нобелевскую премию». Работы Хондзё и Эллисона (Нобелевская премия 2018 года) привели к иммунотерапии ингибиторами PD-1 и CTLA-4, а не к лечению травами."),
    ("Фитотерапия:", "в лучшем случае вспомогательный или дополнительный метод. Растение, устраняющее рак у человека, не найдено."),
    ("Доказательства:", "эффекты большей частью показаны только в лаборатории или на животных моделях."),
    ("Взаимодействия:", "растительные средства могут взаимодействовать с лекарствами и снижать эффект лечения.")],
   "Фитотерапия не может заменить химиотерапию, лучевую терапию, операцию или иммунотерапию. Не верьте шарлатанам, рекламирующим себя в социальных сетях."),
 'zh': D("癌症与虚假希望", "欺骗癌症患者的人", "图中是土耳其宣传草药“治癌”的广告和新闻标题", None, None,
   [("广告怎么说：", "“不用化疗成功治疗肺癌”、针对一长串癌症的“癌症治疗中的植物疗法支持”、“20天治好癌症”。"),
    ("诺贝尔神话：", "帖子常引用“获得诺贝尔奖的教授”。本庶佑和艾利森（2018年诺贝尔奖）的研究带来的是PD-1和CTLA-4抑制剂免疫治疗，而不是草药治疗。"),
    ("植物疗法：", "最多只是支持性或补充性方法。至今没有发现能在人体消除癌症的植物。"),
    ("证据：", "其作用大多只在实验室或动物模型中得到证明。"),
    ("相互作用：", "草药产品可能与药物相互作用，并降低治疗效果。")],
   "植物疗法不能替代化疗、放疗、手术或免疫治疗。不要相信在社交媒体上做广告的江湖骗子。"),
 'hi': D("कैंसर और झूठी उम्मीद", "कैंसर के मरीज़ों को धोखा देने वाले", "चित्र में तुर्की के विज्ञापन और सुर्खियाँ हैं, जो जड़ी-बूटियों से \"कैंसर के इलाज\" का प्रचार करते हैं", None, None,
   [("विज्ञापन क्या कहते हैं:", "\"बिना कीमोथेरेपी के फेफड़े के कैंसर में सफलता\", कैंसर की लंबी सूची के लिए \"कैंसर के इलाज में फ़ाइटोथेरेपी सहायता\", \"20 दिन में कैंसर का इलाज\"।"),
    ("नोबेल के मिथक:", "पोस्ट \"नोबेल विजेता प्रोफ़ेसरों\" का हवाला देती हैं। होंजो और एलिसन (नोबेल पुरस्कार 2018) के काम से PD-1 और CTLA-4 अवरोधकों वाली इम्यूनोथेरेपी निकली, जड़ी-बूटी का इलाज नहीं।"),
    ("फ़ाइटोथेरेपी:", "अधिक से अधिक एक सहायक या पूरक विधि। मनुष्यों में कैंसर को ख़त्म करने वाला कोई पौधा नहीं मिला है।"),
    ("प्रमाण:", "प्रभाव अधिकतर केवल प्रयोगशाला या पशु मॉडलों में दिखाए गए हैं।"),
    ("पारस्परिक क्रिया:", "हर्बल उत्पाद दवाओं के साथ क्रिया कर सकते हैं और इलाज का असर घटा सकते हैं।")],
   "फ़ाइटोथेरेपी कीमोथेरेपी, रेडियोथेरेपी, सर्जरी या इम्यूनोथेरेपी की जगह नहीं ले सकती। सोशल मीडिया पर विज्ञापन करने वाले ढोंगियों पर विश्वास न करें।"),
 'ja': D("がんと偽りの希望", "がん患者をだます人々", "画像はトルコの広告と見出しで、薬草による「がん治療」を宣伝している", None, None,
   [("広告の文句：", "「化学療法なしで肺がんに成功」、多数のがんを並べた「がん治療における植物療法サポート」、「20日でがんを治す」。"),
    ("ノーベル賞の神話：", "投稿は「ノーベル賞を受賞した教授」を引き合いに出す。本庶佑とアリソン（2018年ノーベル賞）の研究が導いたのはPD-1阻害薬とCTLA-4阻害薬による免疫療法であり、薬草治療ではない。"),
    ("植物療法：", "せいぜい支持的または補完的な方法である。ヒトのがんを消失させる植物は見つかっていない。"),
    ("エビデンス：", "効果はほとんどが実験室か動物モデルで示されただけである。"),
    ("相互作用：", "ハーブ製品は医薬品と相互作用し、治療効果を弱めることがある。")],
   "植物療法は化学療法、放射線療法、手術、免疫療法の代わりにはならない。SNSで広告を出すペテン師を信じてはいけない。"),
})
