from batch1 import D
from batch2 import BM
CARDS = {}

# 92 — Placebo (poster; EN image copied from the paired English article)
CARDS['plasebo'] = ('purple', {
 'de': D("PLACEBO", "Die echte Biologie der Scheinbehandlung und ihre klinische Bedeutung", "Heilt das Medikament oder die Erwartung?"),
 'es': D("PLACEBO", "La biología real del tratamiento simulado y su significado clínico", "¿Cura el fármaco o la expectativa?"),
 'ru': D("ПЛАЦЕБО", "Реальная биология мнимого лечения и её клиническое значение", "Лечит лекарство или ожидание?"),
 'zh': D("安慰剂", "“假治疗”的真实生物学及其临床意义", "治病的是药物，还是期待？"),
 'hi': D("प्लेसीबो", "नकली उपचार का असली जीवविज्ञान और उसका नैदानिक अर्थ", "इलाज दवा करती है, या अपेक्षा?"),
 'ja': D("プラセボ", "偽の治療が持つ本物の生物学と臨床的意味", "治すのは薬か、それとも期待か"),
})

# 93 — FDA and TITCK independence
CARDS['fdatitck'] = ('navy', {
 'en': D("CONFLICT OF INTEREST", "Are the FDA and TİTCK really independent?", "Two regulators, one shared problem", None, None,
   [("FDA:", "advisory committees of scientists, relatively high transparency, a financial tie to industry through user fees (PDUFA), and conflict-of-interest management that a GAO report found unclear."),
    ("TİTCK:", "a centralised structure that can decide quickly, but with limited transparency, advisory processes that are not clear and no openly defined conflict-of-interest system."),
    ("The paradox:", "the best expert is often the expert with industry ties."),
    ("The shared problem:", "consultancy, research funding and academic relationships. Conflict of interest cannot be removed entirely."),
    ("The real question:", "not whether conflict of interest exists, but how it is managed.")],
   "The FDA is more transparent but complex; TİTCK is more closed but centralised. Neither is fully independent."),
 'de': D("INTERESSENKONFLIKT", "Sind FDA und TİTCK wirklich unabhängig?", "Zwei Behörden, ein gemeinsames Problem", None, None,
   [("FDA:", "Beratungsausschüsse aus Wissenschaftlern, relativ hohe Transparenz, finanzielle Bindung an die Industrie über Gebühren (PDUFA) und ein Umgang mit Interessenkonflikten, den ein GAO-Bericht als unklar bewertete."),
    ("TİTCK:", "zentrale Struktur mit schnellen Entscheidungen, aber begrenzte Transparenz, unklare Beratungsprozesse und kein offen definiertes System für Interessenkonflikte."),
    ("Das Paradox:", "der beste Experte ist oft der Experte mit Industriebeziehungen."),
    ("Das gemeinsame Problem:", "Beratertätigkeit, Forschungsgelder und akademische Beziehungen. Interessenkonflikte lassen sich nie ganz beseitigen."),
    ("Die eigentliche Frage:", "nicht ob es Interessenkonflikte gibt, sondern wie mit ihnen umgegangen wird.")],
   "Die FDA ist transparenter, aber komplex; die TİTCK ist geschlossener, aber zentral. Keine ist völlig unabhängig."),
 'es': D("CONFLICTO DE INTERESES", "¿Son realmente independientes la FDA y la TİTCK?", "Dos reguladores, un problema común", None, None,
   [("FDA:", "comités asesores de científicos, transparencia relativamente alta, vínculo financiero con la industria mediante tasas (PDUFA) y una gestión de conflictos de intereses que un informe de la GAO consideró poco clara."),
    ("TİTCK:", "estructura centralizada que decide con rapidez, pero con transparencia limitada, procesos de asesoramiento poco claros y sin un sistema de conflictos de intereses definido abiertamente."),
    ("La paradoja:", "el mejor experto suele ser el experto vinculado a la industria."),
    ("El problema común:", "consultorías, fondos de investigación y relaciones académicas. El conflicto de intereses no puede eliminarse del todo."),
    ("La verdadera cuestión:", "no si existe el conflicto de intereses, sino cómo se gestiona.")],
   "La FDA es más transparente pero compleja; la TİTCK es más cerrada pero centralizada. Ninguna es plenamente independiente."),
 'ru': D("КОНФЛИКТ ИНТЕРЕСОВ", "Действительно ли независимы FDA и TİTCK?", "Два регулятора, одна общая проблема", None, None,
   [("FDA:", "консультативные комитеты из учёных, относительно высокая прозрачность, финансовая связь с индустрией через сборы (PDUFA) и управление конфликтом интересов, которое отчёт GAO признал нечётким."),
    ("TİTCK:", "централизованная структура с быстрыми решениями, но ограниченной прозрачностью, неясными консультативными процедурами и без открыто определённой системы конфликта интересов."),
    ("Парадокс:", "лучший эксперт часто оказывается экспертом, связанным с индустрией."),
    ("Общая проблема:", "консультирование, исследовательское финансирование и академические связи. Полностью устранить конфликт интересов невозможно."),
    ("Главный вопрос:", "не в том, есть ли конфликт интересов, а в том, как им управляют.")],
   "FDA прозрачнее, но сложнее; TİTCK закрытее, но централизованнее. Ни одно из ведомств не является полностью независимым."),
 'zh': D("利益冲突", "FDA和TİTCK真的独立吗？", "两家监管机构，一个共同问题", None, None,
   [("FDA：", "由科学家组成的咨询委员会，透明度相对较高，通过使用者付费（PDUFA）与产业存在财务联系，美国政府问责局（GAO）报告认为其利益冲突管理不够清晰。"),
    ("TİTCK：", "集中式架构，决策快，但透明度有限，咨询程序不明确，没有公开界定的利益冲突制度。"),
    ("悖论：", "最好的专家往往就是与产业有关系的专家。"),
    ("共同问题：", "顾问工作、研究经费和学术关系。利益冲突无法完全消除。"),
    ("真正的问题：", "不在于利益冲突是否存在，而在于如何管理。")],
   "FDA更透明但更复杂；TİTCK更封闭但更集中。两者都不是完全独立的。"),
 'hi': D("हितों का टकराव", "क्या FDA और TİTCK वास्तव में स्वतंत्र हैं?", "दो नियामक, एक साझा समस्या", None, None,
   [("FDA:", "वैज्ञानिकों की सलाहकार समितियाँ, अपेक्षाकृत अधिक पारदर्शिता, शुल्क (PDUFA) के ज़रिए उद्योग से वित्तीय संबंध और हितों के टकराव का प्रबंधन, जिसे GAO रिपोर्ट ने अस्पष्ट पाया।"),
    ("TİTCK:", "केंद्रीकृत ढाँचा जो तेज़ी से निर्णय ले सकता है, पर सीमित पारदर्शिता, अस्पष्ट सलाह प्रक्रियाएँ और हितों के टकराव की कोई खुले तौर पर परिभाषित व्यवस्था नहीं।"),
    ("विरोधाभास:", "सबसे अच्छा विशेषज्ञ अक्सर वही होता है जिसका उद्योग से संबंध है।"),
    ("साझा समस्या:", "परामर्श, शोध अनुदान और शैक्षणिक संबंध। हितों का टकराव पूरी तरह मिटाया नहीं जा सकता।"),
    ("असली सवाल:", "यह नहीं कि हितों का टकराव है या नहीं, बल्कि यह कि उसे कैसे सँभाला जाता है।")],
   "FDA अधिक पारदर्शी पर जटिल है; TİTCK अधिक बंद पर केंद्रीकृत। दोनों में से कोई पूरी तरह स्वतंत्र नहीं।"),
 'ja': D("利益相反", "FDAとTİTCKは本当に独立しているのか", "二つの規制当局、一つの共通の問題", None, None,
   [("FDA：", "科学者による諮問委員会、比較的高い透明性、手数料（PDUFA）を通じた産業との財政的つながり、そしてGAO報告書が不明確と指摘した利益相反の管理。"),
    ("TİTCK：", "中央集権的で決定は速いが、透明性は限られ、諮問の過程は明確でなく、利益相反の制度も公に定義されていない。"),
    ("パラドックス：", "最良の専門家は、しばしば産業と関係のある専門家である。"),
    ("共通の問題：", "コンサルタント業務、研究資金、学術的関係。利益相反を完全になくすことはできない。"),
    ("本当の問い：", "利益相反があるかどうかではなく、どう管理するかである。")],
   "FDAはより透明だが複雑、TİTCKはより閉鎖的だが集権的。どちらも完全には独立していない。"),
})

# 94 — The "100% tariff"
CARDS['tarife'] = ('burg', {
 'en': D("US DRUG TARIFFS", "The truth about the '100% tariff': a drug war or global bargaining?", "The tariffs are not applied to everyone", None, None,
   [("Who is exempt:", "generics are outside the scope, there are many exemptions, and companies that sign manufacturing or pricing agreements are spared. It is a conditional bargaining mechanism."),
    ("Big companies are protected:", "the largest firms secured protection through deals with the administration."),
    ("Small biotechs are now the target:", "companies without the scale to build US plants or negotiate prices carry the risk."),
    ("Pressure on the global system:", "the demand for lower US prices pushes on the United Kingdom, Europe and Australia to pay more.")],
   "A medicine is no longer only a health product; it is a tool at the centre of global economic and political power."),
 'de': D("US-ARZNEIMITTELZÖLLE", "Die Wahrheit über den «100-%-Zoll»: Arzneimittelkrieg oder globales Feilschen?", "Die Zölle gelten nicht für alle", None, None,
   [("Wer ausgenommen ist:", "Generika fallen nicht darunter, es gibt zahlreiche Ausnahmen, und Firmen mit Produktions- oder Preisabkommen bleiben verschont. Es ist ein Mechanismus des bedingten Verhandelns."),
    ("Große Konzerne sind geschützt:", "die größten Firmen sicherten sich Schutz durch Abkommen mit der Regierung."),
    ("Kleine Biotechs im Visier:", "Firmen ohne die Größe für US-Werke oder Preisverhandlungen tragen das Risiko."),
    ("Druck auf das globale System:", "die Forderung nach niedrigeren US-Preisen drängt Großbritannien, Europa und Australien, mehr zu zahlen.")],
   "Ein Arzneimittel ist nicht mehr nur ein Gesundheitsprodukt, sondern ein Instrument im Zentrum globaler wirtschaftlicher und politischer Macht."),
 'es': D("ARANCELES DE EE. UU. A LOS MEDICAMENTOS", "La verdad del «arancel del 100 %»: ¿guerra farmacéutica o regateo global?", "Los aranceles no se aplican a todos", None, None,
   [("Quién queda exento:", "los genéricos quedan fuera, hay numerosas exenciones y se libran las empresas que firman acuerdos de producción o de precios. Es un mecanismo de negociación condicionada."),
    ("Las grandes empresas, protegidas:", "las mayores compañías obtuvieron protección mediante acuerdos con la Administración."),
    ("Las pequeñas biotecnológicas, en el punto de mira:", "las empresas sin tamaño para construir plantas en EE. UU. o negociar precios asumen el riesgo."),
    ("Presión sobre el sistema global:", "la exigencia de precios más bajos en EE. UU. presiona al Reino Unido, Europa y Australia para que paguen más.")],
   "El medicamento ya no es solo un producto sanitario; es una herramienta en el centro del poder económico y político global."),
 'ru': D("ПОШЛИНЫ США НА ЛЕКАРСТВА", "Правда о «100-процентной пошлине»: лекарственная война или глобальный торг?", "Пошлины применяются не ко всем", None, None,
   [("Кто освобождён:", "дженерики не подпадают, исключений много, а компании, подписавшие соглашения о производстве или ценах, получают освобождение. Это механизм условного торга."),
    ("Крупные компании защищены:", "крупнейшие фирмы обеспечили себе защиту сделками с администрацией."),
    ("Теперь под ударом малые биотехи:", "риск несут компании, которым не хватает масштаба, чтобы строить заводы в США или договариваться о ценах."),
    ("Давление на мировую систему:", "требование снизить цены в США вынуждает Великобританию, Европу и Австралию платить больше.")],
   "Лекарство больше не только продукт здравоохранения; это инструмент в центре глобальной экономической и политической власти."),
 'zh': D("美国药品关税", "“100%关税”的真相：药品战争，还是全球讨价还价？", "关税并非对所有人适用", None, None,
   [("谁被豁免：", "仿制药不在范围内，豁免项目众多，签署了生产或价格协议的企业可以免征。这是一种有条件的谈判机制。"),
    ("大企业获得保护：", "最大的几家公司通过与政府达成协议获得了保护。"),
    ("小型生物技术公司成为目标：", "没有规模在美国建厂或谈判价格的企业承担风险。"),
    ("对全球体系的压力：", "美国要求降价，迫使英国、欧洲和澳大利亚支付更高价格。")],
   "药品已不再只是健康产品，而是全球经济与政治权力中心的一件工具。"),
 'hi': D("अमेरिकी दवा शुल्क", "'100% टैरिफ़' का सच: दवा युद्ध या वैश्विक सौदेबाज़ी?", "शुल्क सब पर लागू नहीं होते", None, None,
   [("किसे छूट है:", "जेनेरिक दायरे से बाहर हैं, छूटें बहुत हैं, और उत्पादन या मूल्य समझौते करने वाली कंपनियाँ बच जाती हैं। यह सशर्त सौदेबाज़ी की व्यवस्था है।"),
    ("बड़ी कंपनियाँ सुरक्षित:", "सबसे बड़ी कंपनियों ने प्रशासन से समझौते करके सुरक्षा हासिल की।"),
    ("अब निशाने पर छोटी बायोटेक:", "जिन कंपनियों के पास अमेरिका में संयंत्र लगाने या कीमत पर मोलभाव का पैमाना नहीं, जोखिम उन्हीं पर है।"),
    ("वैश्विक व्यवस्था पर दबाव:", "अमेरिका में कम कीमत की माँग ब्रिटेन, यूरोप और ऑस्ट्रेलिया पर अधिक भुगतान का दबाव डालती है।")],
   "दवा अब केवल स्वास्थ्य उत्पाद नहीं; यह वैश्विक आर्थिक और राजनीतिक शक्ति के केंद्र का औज़ार है।"),
 'ja': D("米国の医薬品関税", "「100%関税」の真実：医薬品戦争か、世界規模の駆け引きか", "関税はすべてに適用されるわけではない", None, None,
   [("除外されるもの：", "ジェネリックは対象外で、多数の免除があり、製造や価格の合意を結んだ企業は免れる。条件付きの交渉の仕組みである。"),
    ("大企業は守られた：", "最大手は政権との合意によって保護を得た。"),
    ("今の標的は小規模バイオ企業：", "米国に工場を建てたり価格交渉をしたりする規模のない企業がリスクを負う。"),
    ("世界の制度への圧力：", "米国での値下げ要求は、英国、欧州、オーストラリアにより高い支払いを迫る。")],
   "医薬品はもはや単なる保健製品ではなく、世界の経済的・政治的権力の中心にある道具である。"),
})

# 95 — Fracture in the US biomedical system
CARDS['biyomed'] = ('dark', {
 'en': D("UNITED STATES", "A fracture in the US biomedical system", "Science grows with funding. When funding is cut, the system does not just shrink; it changes direction.",
   [("≈ $2.45 billion", "in cuts as NIH funding reductions begin and DEI programmes are removed"), ("23% down", "cancer research"), ("43% down", "mental health research"), ("75%", "of scientists are considering leaving the country")], None, None,
   "The global balance of science is shifting and new drug development is slowing."),
 'de': D("USA", "Bruch im biomedizinischen System der USA", "Wissenschaft wächst mit Förderung. Wird sie gekürzt, schrumpft das System nicht nur, es ändert die Richtung.",
   [("≈ 2,45 Mrd. $", "Kürzungen: NIH-Mittel werden gestrichen, DEI-Programme abgeschafft"), ("−23 %", "Krebsforschung"), ("−43 %", "Forschung zur psychischen Gesundheit"), ("75 %", "der Wissenschaftler erwägen, das Land zu verlassen")], None, None,
   "Das globale Gleichgewicht der Wissenschaft verschiebt sich, die Entwicklung neuer Medikamente verlangsamt sich."),
 'es': D("ESTADOS UNIDOS", "Fractura en el sistema biomédico de EE. UU.", "La ciencia crece con financiación. Cuando se recorta, el sistema no solo se encoge: cambia de rumbo.",
   [("≈ 2.450 M$", "en recortes: empiezan los recortes a los NIH y se eliminan los programas DEI"), ("−23 %", "investigación del cáncer"), ("−43 %", "investigación en salud mental"), ("75 %", "de los científicos se plantea emigrar")], None, None,
   "El equilibrio científico mundial cambia y el desarrollo de nuevos fármacos se frena."),
 'ru': D("США", "Перелом в биомедицинской системе США", "Наука растёт за счёт финансирования. Когда его урезают, система не просто сжимается, она меняет направление.",
   [("≈ 2,45 млрд $", "сокращений: урезано финансирование NIH, отменены программы DEI"), ("−23 %", "исследования рака"), ("−43 %", "исследования психического здоровья"), ("75 %", "учёных думают об отъезде из страны")], None, None,
   "Мировой научный баланс смещается, а разработка новых лекарств замедляется."),
 'zh': D("美国", "美国生物医学体系的断裂", "科学靠经费成长。经费被削减时，体系不只是缩小，而是改变方向。",
   [("约24.5亿美元", "被削减：NIH经费开始削减，DEI项目被取消"), ("下降23%", "癌症研究"), ("下降43%", "精神健康研究"), ("75%", "的科学家考虑离开美国")], None, None,
   "全球科学格局正在改变，新药研发正在放缓。"),
 'hi': D("संयुक्त राज्य अमेरिका", "अमेरिकी बायोमेडिकल व्यवस्था में दरार", "विज्ञान धन से बढ़ता है। धन कटने पर व्यवस्था केवल सिकुड़ती नहीं, दिशा बदल लेती है।",
   [("≈ 2.45 अरब $", "की कटौती: NIH के अनुदान घटने लगे, DEI कार्यक्रम हटाए गए"), ("23% कमी", "कैंसर शोध"), ("43% कमी", "मानसिक स्वास्थ्य शोध"), ("75%", "वैज्ञानिक देश छोड़ने पर विचार कर रहे हैं")], None, None,
   "विज्ञान का वैश्विक संतुलन बदल रहा है और नई दवाओं का विकास धीमा हो रहा है।"),
 'ja': D("米国", "米国の生物医学システムに走る亀裂", "科学は資金で育つ。資金が削られると、システムは縮むだけでなく向きを変える。",
   [("約24.5億ドル", "の削減：NIHの資金削減が始まり、DEIプログラムは廃止"), ("23%減", "がん研究"), ("43%減", "精神保健研究"), ("75%", "の科学者が国外への移住を検討")], None, None,
   "世界の科学の均衡が変わり、新薬開発は減速している。"),
})

# 96 — Why are medicines unavailable in Turkey
CARDS['ilacyok'] = ('dark', {
 'en': D("DRUG SHORTAGES", "Why can't medicines be found in Turkey?", "The clash between a fixed price and a dynamic market", None, None,
   [("Rigid price regulation:", "the state sets a fixed, low drug price."),
    ("An unrealistic exchange rate:", "prices are calculated with a fixed euro rate far below the real market rate."),
    ("The result:", "companies cannot cover their production costs and stop supplying the market."),
    ("Turkey and the US compared:", "in Turkey the price is controlled by the state and detached from the real market; in the US the price is free, competition is chaotic and sellers set what the market will bear.")],
   "A drug shortage is not simply a lack of supply. It is a system problem: the price does not reflect market conditions."),
 'de': D("ARZNEIMITTELENGPÄSSE", "Warum sind Medikamente in der Türkei nicht zu bekommen?", "Der Konflikt zwischen festem Preis und dynamischem Markt", None, None,
   [("Starre Preisregulierung:", "der Staat legt einen festen, niedrigen Arzneimittelpreis fest."),
    ("Ein unrealistischer Wechselkurs:", "die Preise werden mit einem festen Eurokurs weit unter dem tatsächlichen Marktkurs berechnet."),
    ("Die Folge:", "die Firmen können ihre Produktionskosten nicht decken und beliefern den Markt nicht mehr."),
    ("Türkei und USA im Vergleich:", "in der Türkei ist der Preis staatlich kontrolliert und vom realen Markt entkoppelt; in den USA ist der Preis frei, der Wettbewerb chaotisch, und die Verkäufer bestimmen den Preis.")],
   "Ein Arzneimittelengpass ist nicht einfach ein Angebotsmangel. Er ist ein Systemproblem: Der Preis spiegelt die Marktbedingungen nicht wider."),
 'es': D("DESABASTECIMIENTO", "¿Por qué no se encuentran medicamentos en Turquía?", "El choque entre un precio fijo y un mercado dinámico", None, None,
   [("Regulación rígida de precios:", "el Estado fija un precio bajo e invariable."),
    ("Un tipo de cambio irreal:", "los precios se calculan con un euro fijo muy por debajo del tipo real de mercado."),
    ("El resultado:", "las empresas no cubren sus costes de producción y dejan de abastecer el mercado."),
    ("Turquía y EE. UU.:", "en Turquía el precio lo controla el Estado y está desconectado del mercado real; en EE. UU. el precio es libre, la competencia caótica y lo fijan los vendedores.")],
   "El desabastecimiento no es simplemente falta de oferta. Es un problema del sistema: el precio no refleja las condiciones del mercado."),
 'ru': D("ДЕФИЦИТ ЛЕКАРСТВ", "Почему в Турции не найти лекарства?", "Конфликт фиксированной цены и динамичного рынка", None, None,
   [("Жёсткое регулирование цен:", "государство устанавливает фиксированную низкую цену."),
    ("Нереалистичный курс:", "цены рассчитываются по фиксированному курсу евро, намного ниже реального рыночного."),
    ("Результат:", "компании не покрывают производственные затраты и перестают поставлять лекарства на рынок."),
    ("Турция и США:", "в Турции цену контролирует государство, и она оторвана от реального рынка; в США цена свободная, конкуренция хаотична, а цену определяют продавцы.")],
   "Дефицит лекарств не является просто нехваткой предложения. Это системная проблема: цена не отражает рыночные условия."),
 'zh': D("药品短缺", "为什么在土耳其买不到药？", "固定价格与动态市场的冲突", None, None,
   [("僵化的价格管制：", "国家规定固定且偏低的药价。"),
    ("不现实的汇率：", "药价按固定欧元汇率计算，远低于真实市场汇率。"),
    ("结果：", "企业无法覆盖生产成本，于是停止向市场供药。"),
    ("土耳其与美国的比较：", "在土耳其，价格由国家控制，与真实市场脱节；在美国，价格自由，竞争混乱，由卖方定价。")],
   "药品短缺不是简单的供应不足，而是体系问题：价格没有反映市场条件。"),
 'hi': D("दवाओं की कमी", "तुर्की में दवाएँ क्यों नहीं मिलतीं?", "स्थिर कीमत और गतिशील बाज़ार का टकराव", None, None,
   [("कठोर मूल्य नियमन:", "सरकार दवा की स्थिर और कम कीमत तय करती है।"),
    ("अवास्तविक विनिमय दर:", "कीमतें एक स्थिर यूरो दर से निकाली जाती हैं, जो असली बाज़ार दर से बहुत नीचे है।"),
    ("नतीजा:", "कंपनियाँ उत्पादन लागत नहीं निकाल पातीं और बाज़ार में दवा देना बंद कर देती हैं।"),
    ("तुर्की और अमेरिका:", "तुर्की में कीमत सरकार के नियंत्रण में है और असली बाज़ार से कटी हुई; अमेरिका में कीमत मुक्त है, प्रतिस्पर्धा अराजक, और कीमत विक्रेता तय करते हैं।")],
   "दवा की कमी सीधे-सीधे आपूर्ति की कमी नहीं है। यह व्यवस्था की समस्या है: कीमत बाज़ार की स्थितियों को नहीं दर्शाती।"),
 'ja': D("医薬品不足", "なぜトルコでは薬が手に入らないのか", "固定価格と動く市場の衝突", None, None,
   [("硬直的な価格規制：", "国が固定の低い薬価を定める。"),
    ("現実離れした為替レート：", "薬価は、実勢よりはるかに低い固定ユーロレートで計算される。"),
    ("その結果：", "企業は製造原価を回収できず、市場への供給をやめる。"),
    ("トルコと米国の比較：", "トルコでは価格は国が管理し、実際の市場から切り離されている。米国では価格は自由で、競争は混沌とし、売り手が価格を決める。")],
   "医薬品不足は単なる供給不足ではない。価格が市場の状況を反映しないという、制度の問題である。"),
})

# 97 — Semaglutide: effective or dangerous
CARDS['semayan'] = ('teal', {
 'en': D("SCIENCE, FACTS AND EXAGGERATION", "Semaglutide: effective, or dangerous?", "Ozempic, Wegovy, Rybelsus: a GLP-1 receptor agonist approved by the FDA for type 2 diabetes and obesity", None, None,
   [("How it works:", "it suppresses appetite and slows gastric emptying."),
    ("The best-known side effects:", "gastrointestinal: nausea, vomiting, diarrhoea or constipation, abdominal pain. Common and dose dependent, seen in up to 70% of patients; they follow from the drug's normal mechanism and mostly ease or pass when the dose is reduced."),
    ("Rare but serious risks:", "vision loss is very rare, around 1 in 10,000. Gastroparesis shows a 3.7-fold relative risk, but the absolute risk is low."),
    ("Myth:", "'serious side effects are very common' and 'it causes serious complications in everyone'. Fact: the risks are serious but rare.")],
   "Semaglutide is neither a miracle nor a disaster. Its risks should be neither played down nor exaggerated.",
   "Sources: Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
 'de': D("WISSENSCHAFT, FAKTEN UND ÜBERTREIBUNG", "Semaglutid: wirksam oder gefährlich?", "Ozempic, Wegovy, Rybelsus: ein GLP-1-Rezeptoragonist, von der FDA für Typ-2-Diabetes und Adipositas zugelassen", None, None,
   [("Wirkweise:", "dämpft den Appetit und verlangsamt die Magenentleerung."),
    ("Die bekanntesten Nebenwirkungen:", "gastrointestinal: Übelkeit, Erbrechen, Durchfall oder Verstopfung, Bauchschmerzen. Häufig und dosisabhängig, bei bis zu 70 % der Patienten; sie folgen aus dem normalen Wirkmechanismus und lassen meist nach, wenn die Dosis gesenkt wird."),
    ("Seltene, aber ernste Risiken:", "Sehverlust ist sehr selten, etwa 1 von 10.000. Bei Gastroparese ist das relative Risiko 3,7-fach, das absolute Risiko aber gering."),
    ("Mythos:", "«schwere Nebenwirkungen sind sehr häufig» und «es macht bei jedem schwere Komplikationen». Fakt: die Risiken sind ernst, aber selten.")],
   "Semaglutid ist weder Wunder noch Katastrophe. Seine Risiken sollte man weder verharmlosen noch übertreiben.",
   "Quellen: Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
 'es': D("CIENCIA, HECHOS Y EXAGERACIONES", "Semaglutida: ¿eficaz o peligrosa?", "Ozempic, Wegovy, Rybelsus: un agonista del receptor de GLP-1 aprobado por la FDA para la diabetes tipo 2 y la obesidad", None, None,
   [("Cómo actúa:", "reduce el apetito y enlentece el vaciado gástrico."),
    ("Los efectos adversos más conocidos:", "gastrointestinales: náuseas, vómitos, diarrea o estreñimiento, dolor abdominal. Frecuentes y dependientes de la dosis, hasta en el 70 % de los pacientes; derivan del mecanismo normal del fármaco y suelen ceder al reducir la dosis."),
    ("Riesgos raros pero graves:", "la pérdida de visión es muy rara, en torno a 1 de cada 10.000. En la gastroparesia el riesgo relativo es 3,7 veces mayor, pero el riesgo absoluto es bajo."),
    ("Mito:", "«los efectos graves son muy frecuentes» y «causa complicaciones graves a todos». Realidad: los riesgos son graves pero raros.")],
   "La semaglutida no es ni un milagro ni un desastre. Sus riesgos no deben minimizarse ni exagerarse.",
   "Fuentes: Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
 'ru': D("НАУКА, ФАКТЫ И ПРЕУВЕЛИЧЕНИЯ", "Семаглутид: эффективен или опасен?", "Оземпик, Вегови, Ребелсас: агонист рецепторов ГПП-1, одобренный FDA для лечения диабета 2 типа и ожирения", None, None,
   [("Как действует:", "подавляет аппетит и замедляет опорожнение желудка."),
    ("Самые известные побочные эффекты:", "желудочно-кишечные: тошнота, рвота, диарея или запор, боль в животе. Частые и дозозависимые, до 70 % пациентов; они вытекают из обычного механизма действия и чаще всего ослабевают при снижении дозы."),
    ("Редкие, но серьёзные риски:", "потеря зрения очень редка, около 1 на 10 000. Для гастропареза относительный риск выше в 3,7 раза, но абсолютный риск низок."),
    ("Миф:", "«серьёзные побочные эффекты очень часты» и «у всех вызывает тяжёлые осложнения». Факт: риски серьёзны, но редки.")],
   "Семаглутид не чудо и не катастрофа. Его риски нельзя ни преуменьшать, ни преувеличивать.",
   "Источники: Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
 'zh': D("科学、事实与夸大", "司美格鲁肽：有效，还是危险？", "Ozempic、Wegovy、Rybelsus：获FDA批准用于2型糖尿病和肥胖症的GLP-1受体激动剂", None, None,
   [("作用方式：", "抑制食欲，减慢胃排空。"),
    ("最常见的副作用：", "胃肠道反应：恶心、呕吐、腹泻或便秘、腹痛。常见且与剂量相关，最多见于70%的患者；这是药物正常机制的结果，减量后大多减轻或消失。"),
    ("罕见但严重的风险：", "视力丧失非常罕见，约万分之一。胃轻瘫的相对风险为3.7倍，但绝对风险很低。"),
    ("误区：", "“严重副作用非常普遍”“对每个人都会造成严重并发症”。事实：风险严重但罕见。")],
   "司美格鲁肽既不是奇迹，也不是灾难。其风险既不应被轻视，也不应被夸大。",
   "来源：Nauck MA 等，Lancet 2016；Wilding JP 等，NEJM 2021；FDA药物安全通报 2023。"),
 'hi': D("विज्ञान, तथ्य और अतिशयोक्ति", "सेमाग्लूटाइड: प्रभावी या ख़तरनाक?", "ओज़ेम्पिक, वेगोवी, राइबेल्सस: टाइप 2 मधुमेह और मोटापे के लिए FDA से स्वीकृत GLP-1 रिसेप्टर एगोनिस्ट", None, None,
   [("यह कैसे काम करता है:", "भूख दबाता है और पेट के खाली होने को धीमा करता है।"),
    ("सबसे जाने-माने दुष्प्रभाव:", "पाचन तंत्र के: मतली, उल्टी, दस्त या कब्ज़, पेट दर्द। आम और खुराक पर निर्भर, 70% तक रोगियों में; ये दवा की सामान्य क्रिया का नतीजा हैं और खुराक घटाने पर अधिकतर कम हो जाते हैं।"),
    ("दुर्लभ पर गंभीर जोखिम:", "दृष्टि हानि बहुत दुर्लभ है, लगभग 10,000 में 1। गैस्ट्रोपैरेसिस में सापेक्ष जोखिम 3.7 गुना है, पर निरपेक्ष जोखिम कम है।"),
    ("मिथक:", "'गंभीर दुष्प्रभाव बहुत आम हैं' और 'यह हर किसी में गंभीर जटिलताएँ करता है'। तथ्य: जोखिम गंभीर हैं पर दुर्लभ।")],
   "सेमाग्लूटाइड न चमत्कार है, न आपदा। इसके जोखिमों को न कम आँकें, न बढ़ा-चढ़ाकर बताएँ।",
   "स्रोत: Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
 'ja': D("科学、事実、そして誇張", "セマグルチド：有効か、危険か", "オゼンピック、ウゴービ、リベルサス：2型糖尿病と肥満症にFDAが承認したGLP-1受容体作動薬", None, None,
   [("作用の仕組み：", "食欲を抑え、胃排出を遅らせる。"),
    ("よく知られた副作用：", "消化器症状：吐き気、嘔吐、下痢または便秘、腹痛。頻度が高く用量依存的で、最大70%の患者にみられる。薬の通常の作用機序によるもので、減量すると多くは軽くなるか消える。"),
    ("まれだが重大なリスク：", "視力喪失は非常にまれで、約1万人に1人。胃不全麻痺の相対リスクは3.7倍だが、絶対リスクは低い。"),
    ("誤解：", "「重い副作用は非常に多い」「誰にでも重い合併症を起こす」。事実：リスクは重大だがまれである。")],
   "セマグルチドは奇跡でも災厄でもない。リスクは軽視も誇張もすべきでない。",
   "出典：Nauck MA et al., Lancet 2016; Wilding JP et al., NEJM 2021; FDA Drug Safety Communication 2023."),
})

# 98 — Turkish pharma sector: production but no innovation
CARDS['sektor'] = ('navy', {
 'en': D("TURKEY'S PHARMACEUTICAL SECTOR", "There is production. Where is the innovation?", "Companies grow, and in the end they are sold",
   [("750+", "pharmaceutical companies"), ("60-80", "local manufacturers"), ("5-10", "companies doing innovative R&D")], None,
   [("Where do the incentives go?", "R&D incentives end up in marketing and generic production."),
    ("Where are the trained people?", "brain drain."),
    ("The result:", "companies for sale, bought by foreign investors."),
    ("Production in Turkey, profit abroad.", "")],
   "There is production, but no innovation."),
 'de': D("DIE TÜRKISCHE PHARMABRANCHE", "Produktion gibt es. Wo bleibt die Innovation?", "Firmen wachsen, und am Ende werden sie verkauft",
   [("750+", "Pharmaunternehmen"), ("60-80", "einheimische Hersteller"), ("5-10", "Firmen mit innovativer Forschung und Entwicklung")], None,
   [("Wohin fließt die Förderung?", "F&E-Förderung landet in Marketing und Generikaproduktion."),
    ("Wo sind die Fachkräfte?", "Abwanderung ins Ausland."),
    ("Das Ergebnis:", "Firmen zum Verkauf, übernommen von ausländischen Investoren."),
    ("Produktion in der Türkei, Gewinn im Ausland.", "")],
   "Es gibt Produktion, aber keine Innovation."),
 'es': D("EL SECTOR FARMACÉUTICO TURCO", "Hay producción. ¿Dónde está la innovación?", "Las empresas crecen y, al final, se venden",
   [("750+", "empresas farmacéuticas"), ("60-80", "fabricantes locales"), ("5-10", "empresas con I+D innovadora")], None,
   [("¿Adónde van los incentivos?", "los incentivos de I+D acaban en marketing y producción de genéricos."),
    ("¿Dónde está el personal formado?", "fuga de cerebros."),
    ("El resultado:", "empresas en venta, compradas por inversores extranjeros."),
    ("Producción en Turquía, beneficio en el exterior.", "")],
   "Hay producción, pero no innovación."),
 'ru': D("ФАРМАЦЕВТИЧЕСКИЙ СЕКТОР ТУРЦИИ", "Производство есть. А где инновации?", "Компании растут, а в итоге продаются",
   [("750+", "фармацевтических компаний"), ("60-80", "местных производителей"), ("5-10", "компаний с инновационными НИОКР")], None,
   [("Куда уходят льготы?", "поддержка НИОКР оседает в маркетинге и производстве дженериков."),
    ("Где подготовленные кадры?", "утечка мозгов."),
    ("Итог:", "компании на продажу, их покупают иностранные инвесторы."),
    ("Производство в Турции, прибыль за рубежом.", "")],
   "Производство есть, инноваций нет."),
 'zh': D("土耳其制药业", "有生产，创新在哪里？", "企业做大，最后被卖掉",
   [("750+", "家制药公司"), ("60-80", "家本土生产商"), ("5-10", "家从事创新研发的企业")], None,
   [("激励去了哪里？", "研发激励最终流向营销和仿制药生产。"),
    ("受过训练的人才在哪里？", "人才外流。"),
    ("结果：", "待售的企业，被外国投资者收购。"),
    ("生产在土耳其，利润在国外。", "")],
   "有生产，却没有创新。"),
 'hi': D("तुर्की का दवा क्षेत्र", "उत्पादन है। नवाचार कहाँ है?", "कंपनियाँ बढ़ती हैं, और अंत में बिक जाती हैं",
   [("750+", "दवा कंपनियाँ"), ("60-80", "स्थानीय निर्माता"), ("5-10", "नवाचारी अनुसंधान करने वाली कंपनियाँ")], None,
   [("प्रोत्साहन कहाँ जाते हैं?", "अनुसंधान के प्रोत्साहन विपणन और जेनेरिक उत्पादन में चले जाते हैं।"),
    ("प्रशिक्षित लोग कहाँ हैं?", "प्रतिभा पलायन।"),
    ("नतीजा:", "बिकाऊ कंपनियाँ, जिन्हें विदेशी निवेशक ख़रीदते हैं।"),
    ("उत्पादन तुर्की में, मुनाफ़ा बाहर।", "")],
   "उत्पादन है, पर नवाचार नहीं।"),
 'ja': D("トルコの製薬産業", "生産はある。イノベーションはどこに？", "企業は成長し、最後には売却される",
   [("750+", "製薬会社"), ("60-80", "国内製造業者"), ("5-10", "革新的な研究開発を行う企業")], None,
   [("奨励策はどこへ行くのか：", "研究開発の奨励は、営業とジェネリック生産に流れる。"),
    ("育った人材はどこに：", "頭脳流出。"),
    ("結果：", "売りに出される企業、外国投資家による買収。"),
    ("生産はトルコで、利益は国外へ。", "")],
   "生産はあるが、イノベーションはない。"),
})

# 99 — Semaglutide patent expiry
CARDS['sempatent'] = ('blue', {
 'en': D("OZEMPIC · WEGOVY", "Semaglutide: the patent ends, the game changes", "Critical date: 24 March 2026, when the patent expires in India", None, None,
   [("What will change:", "generics enter the market, competition increases and prices fall."),
    ("The outcome:", "more access, more demand and a bigger market."),
    ("The hidden effect:", "the definition of obesity is widening. 'Metabolic obesity' from BMI 27 creates a new patient population."),
    ("For Turkey:", "use may rise, the health system may come under strain, and the 'weight-loss drug' trend may grow.")],
   "A patent expiry changes not only the price, but the definition of the disease."),
 'de': D("OZEMPIC · WEGOVY", "Semaglutid: Das Patent läuft aus, das Spiel ändert sich", "Stichtag: 24. März 2026, Patentablauf in Indien", None, None,
   [("Was sich ändert:", "Generika kommen auf den Markt, der Wettbewerb nimmt zu, die Preise fallen."),
    ("Die Folge:", "mehr Zugang, mehr Nachfrage und ein größerer Markt."),
    ("Der versteckte Effekt:", "die Definition der Adipositas weitet sich aus. «Metabolische Adipositas» ab BMI 27 schafft eine neue Patientengruppe."),
    ("Für die Türkei:", "die Anwendung kann zunehmen, das Gesundheitssystem unter Druck geraten und der Trend zum «Abnehmmittel» wachsen.")],
   "Ein Patentablauf verändert nicht nur den Preis, sondern auch die Definition der Krankheit."),
 'es': D("OZEMPIC · WEGOVY", "Semaglutida: se acaba la patente, cambia el juego", "Fecha clave: 24 de marzo de 2026, vencimiento de la patente en la India", None, None,
   [("Qué cambiará:", "entran los genéricos, aumenta la competencia y bajan los precios."),
    ("El resultado:", "más acceso, más demanda y un mercado mayor."),
    ("El efecto oculto:", "la definición de obesidad se amplía. La «obesidad metabólica» desde un IMC de 27 crea una nueva población de pacientes."),
    ("Para Turquía:", "el uso puede aumentar, el sistema sanitario puede verse tensionado y la moda del «fármaco para adelgazar» puede crecer.")],
   "El fin de una patente cambia no solo el precio, sino la definición de la enfermedad."),
 'ru': D("ОЗЕМПИК · ВЕГОВИ", "Семаглутид: патент истёк, правила игры меняются", "Ключевая дата: 24 марта 2026 года, истечение патента в Индии", None, None,
   [("Что изменится:", "на рынок выходят дженерики, конкуренция растёт, цены падают."),
    ("Итог:", "больше доступа, больше спроса и больший рынок."),
    ("Скрытый эффект:", "определение ожирения расширяется. «Метаболическое ожирение» с ИМТ от 27 создаёт новую группу пациентов."),
    ("Для Турции:", "применение может вырасти, система здравоохранения может оказаться под давлением, а мода на «препарат для похудения» усилиться.")],
   "Истечение патента меняет не только цену, но и определение болезни."),
 'zh': D("OZEMPIC · WEGOVY", "司美格鲁肽：专利到期，格局改变", "关键日期：2026年3月24日，印度专利到期", None, None,
   [("会发生什么变化：", "仿制药进入市场，竞争加剧，价格下降。"),
    ("结果：", "可及性更高、需求更大、市场更大。"),
    ("隐性影响：", "肥胖的定义正在扩大。BMI 27以上的“代谢性肥胖”造就了新的患者群体。"),
    ("对土耳其：", "用药量可能上升，医疗体系可能承压，“减肥药”风潮可能扩大。")],
   "专利到期改变的不只是价格，还有疾病的定义。"),
 'hi': D("ओज़ेम्पिक · वेगोवी", "सेमाग्लूटाइड: पेटेंट ख़त्म, खेल बदल रहा है", "निर्णायक तारीख़: 24 मार्च 2026, भारत में पेटेंट की समाप्ति", None, None,
   [("क्या बदलेगा:", "जेनेरिक दवाएँ बाज़ार में आएँगी, प्रतिस्पर्धा बढ़ेगी और कीमतें गिरेंगी।"),
    ("नतीजा:", "अधिक पहुँच, अधिक माँग और बड़ा बाज़ार।"),
    ("छिपा हुआ असर:", "मोटापे की परिभाषा फैल रही है। BMI 27 से 'मेटाबॉलिक मोटापा' रोगियों का नया समूह बनाता है।"),
    ("तुर्की के लिए:", "उपयोग बढ़ सकता है, स्वास्थ्य व्यवस्था पर दबाव आ सकता है और 'वज़न घटाने की दवा' का चलन बढ़ सकता है।")],
   "पेटेंट की समाप्ति केवल कीमत नहीं, बीमारी की परिभाषा भी बदलती है।"),
 'ja': D("オゼンピック · ウゴービ", "セマグルチド：特許が切れ、ゲームが変わる", "重要な日付：2026年3月24日、インドで特許満了", None, None,
   [("何が変わるか：", "ジェネリックが市場に参入し、競争が激しくなり、価格が下がる。"),
    ("その結果：", "アクセスの拡大、需要の増加、市場の拡大。"),
    ("隠れた影響：", "肥満の定義が広がっている。BMI 27以上の「代謝性肥満」が新たな患者層を生む。"),
    ("トルコにとって：", "使用が増え、医療制度に負担がかかり、「やせ薬」ブームが広がる可能性がある。")],
   "特許切れは価格だけでなく、病気の定義も変える。"),
})
