def D(k, t, s, stats=None, ph=None, pts=None, msg=None, src=None):
    return dict(k=k, t=t, s=s, stats=stats, ph=ph, pts=pts, msg=msg, src=src)

CARDS = {}

# 5 — GLP-1 and sudden vision loss
CARDS['vision'] = ('navy', {
 'en': D("GLP-1 DRUGS", "GLP-1 drugs and sudden vision loss", "NAION risk: there is a safety signal; causality is not yet proven",
   [("~1 in 10,000", "EMA: very rare"), ("EMA", "NAION warning added to semaglutide product information"), ("TGA", "Possible-risk warning added to product information"), ("FDA", "Review ongoing; no label change")], None,
   [("The evidence is mixed.", "Some studies report a small association; others find none."), ("Warning sign:", "sudden, painless vision loss in one eye. See an eye doctor immediately."), ("Do not stop on your own.", "Do not stop your medicine without consulting your doctor.")]),
 'de': D("GLP-1-MEDIKAMENTE", "GLP-1-Medikamente und plötzlicher Sehverlust", "NAION-Risiko: Es gibt ein Sicherheitssignal; Kausalität ist noch nicht belegt",
   [("~1 von 10.000", "EMA: sehr selten"), ("EMA", "NAION-Warnhinweis in die Produktinformation von Semaglutid aufgenommen"), ("TGA", "Hinweis auf mögliches Risiko in die Produktinformation aufgenommen"), ("FDA", "Prüfung läuft; keine Änderung der Fachinformation")], None,
   [("Die Evidenz ist uneinheitlich.", "Einige Studien berichten einen geringen Zusammenhang, andere keinen."), ("Warnzeichen:", "plötzlicher, schmerzloser Sehverlust auf einem Auge. Sofort zum Augenarzt."), ("Nicht eigenmächtig absetzen.", "Setzen Sie Ihr Medikament nicht ohne ärztliche Rücksprache ab.")]),
 'es': D("FÁRMACOS GLP-1", "Fármacos GLP-1 y pérdida súbita de visión", "Riesgo de NAION: hay una señal de seguridad; la causalidad aún no está demostrada",
   [("~1 de 10.000", "EMA: muy raro"), ("EMA", "Advertencia de NAION añadida a la ficha de semaglutida"), ("TGA", "Advertencia de posible riesgo añadida a la información del producto"), ("FDA", "Revisión en curso; sin cambio de etiquetado")], None,
   [("La evidencia es contradictoria.", "Algunos estudios notifican una pequeña asociación; otros, ninguna."), ("Señal de alarma:", "pérdida de visión súbita e indolora en un ojo. Acuda de inmediato al oftalmólogo."), ("No lo suspenda por su cuenta.", "No deje su medicamento sin consultar a su médico.")]),
 'ru': D("ПРЕПАРАТЫ ГПП-1", "Препараты ГПП-1 и внезапная потеря зрения", "Риск НАИОН: сигнал безопасности есть; причинная связь пока не доказана",
   [("~1 на 10 000", "EMA: очень редко"), ("EMA", "Предупреждение о НАИОН внесено в информацию о семаглутиде"), ("TGA", "Предупреждение о возможном риске внесено в информацию о препарате"), ("FDA", "Проверка продолжается; инструкция не изменена")], None,
   [("Данные противоречивы.", "Одни исследования сообщают о слабой связи, другие её не находят."), ("Тревожный признак:", "внезапная безболезненная потеря зрения на один глаз. Немедленно обратитесь к офтальмологу."), ("Не отменяйте самостоятельно.", "Не прекращайте приём лекарства без консультации с врачом.")]),
 'zh': D("GLP-1类药物", "GLP-1类药物与突发性视力丧失", "NAION风险：存在安全性信号，因果关系尚未证实",
   [("约万分之一", "EMA：非常罕见"), ("EMA", "司美格鲁肽产品信息中已加入NAION警示"), ("TGA", "产品信息中已加入潜在风险警示"), ("FDA", "仍在审查；说明书未变更")], None,
   [("证据并不一致。", "有的研究报告了轻微关联，有的没有发现关联。"), ("警示信号：", "单眼突然出现无痛性视力丧失，请立即就诊眼科。"), ("不要自行停药。", "未咨询医生前不要停用药物。")]),
 'hi': D("GLP-1 दवाएँ", "GLP-1 दवाएँ और अचानक दृष्टि-हानि", "NAION का जोखिम: सुरक्षा संकेत है; कारण-संबंध अभी सिद्ध नहीं",
   [("~10,000 में 1", "EMA: बहुत दुर्लभ"), ("EMA", "सेमाग्लूटाइड की उत्पाद जानकारी में NAION चेतावनी जोड़ी गई"), ("TGA", "उत्पाद जानकारी में संभावित जोखिम की चेतावनी जोड़ी गई"), ("FDA", "समीक्षा जारी; लेबल में बदलाव नहीं")], None,
   [("प्रमाण मिले-जुले हैं।", "कुछ अध्ययन हल्का संबंध बताते हैं; कुछ में कोई संबंध नहीं मिला।"), ("चेतावनी संकेत:", "एक आँख में अचानक, बिना दर्द के दृष्टि-हानि। तुरंत नेत्र चिकित्सक से मिलें।"), ("खुद से बंद न करें।", "डॉक्टर से सलाह लिए बिना दवा बंद न करें।")]),
 'ja': D("GLP-1受容体作動薬", "GLP-1受容体作動薬と突然の視力低下", "NAIONのリスク：安全性シグナルはあるが、因果関係は未証明",
   [("約1万人に1人", "EMA：非常にまれ"), ("EMA", "セマグルチドの製品情報にNAIONの警告を追加"), ("TGA", "製品情報に潜在的リスクの警告を追加"), ("FDA", "審査継続中。添付文書の変更なし")], None,
   [("エビデンスは一致していない。", "わずかな関連を報告する研究もあれば、関連を認めない研究もある。"), ("警告サイン：", "片眼の突然の痛みのない視力低下。直ちに眼科を受診する。"), ("自己判断で中止しない。", "医師に相談せずに薬をやめないこと。")]),
})

# 6 — Why are drugs so expensive (Public Citizen)
CARDS['pahali'] = ('blue', {
 'en': D("PUBLIC CITIZEN", "Why are drugs so expensive?", "Monopoly power drives prices up",
   [("~$400,000", "Median annual list price of a new drug"), ("> $1 million", "Cell and gene therapies"), ("3–4×", "What the US pays for the same drugs compared with other countries")], "4 STEPS TO A SOLUTION",
   [("1.", "Price negotiation for all drugs"), ("2.", "Stop excessive annual price increases"), ("3.", "Fight patent and monopoly abuses"), ("4.", "Cap patients' out-of-pocket payments")],
   "Affordable drugs and strong innovation are possible together.", "Source: Public Citizen, 24 March 2026"),
 'de': D("PUBLIC CITIZEN", "Warum sind Medikamente so teuer?", "Monopolmacht treibt die Preise in die Höhe",
   [("~400.000 $", "Medianer jährlicher Listenpreis eines neuen Medikaments"), ("> 1 Mio. $", "Zell- und Gentherapien"), ("3–4×", "So viel mehr zahlen die USA für dieselben Medikamente als andere Länder")], "4 SCHRITTE ZUR LÖSUNG",
   [("1.", "Preisverhandlungen für alle Medikamente"), ("2.", "Übermäßige jährliche Preiserhöhungen stoppen"), ("3.", "Patent- und Monopolmissbrauch bekämpfen"), ("4.", "Zuzahlungen der Patienten deckeln")],
   "Bezahlbare Medikamente und starke Innovation sind gemeinsam möglich.", "Quelle: Public Citizen, 24. März 2026"),
 'es': D("PUBLIC CITIZEN", "¿Por qué son tan caros los medicamentos?", "El poder de monopolio dispara los precios",
   [("~400.000 $", "Mediana del precio de lista anual de un fármaco nuevo"), ("> 1 millón $", "Terapias celulares y génicas"), ("3–4×", "Lo que paga EE. UU. por los mismos fármacos frente a otros países")], "4 PASOS PARA LA SOLUCIÓN",
   [("1.", "Negociación de precios para todos los medicamentos"), ("2.", "Frenar las subidas anuales excesivas"), ("3.", "Combatir los abusos de patentes y monopolios"), ("4.", "Poner un tope al pago de bolsillo del paciente")],
   "Medicamentos asequibles e innovación sólida son posibles a la vez.", "Fuente: Public Citizen, 24 de marzo de 2026"),
 'ru': D("PUBLIC CITIZEN", "Почему лекарства такие дорогие?", "Монопольная власть поднимает цены",
   [("~400 000 $", "Медианная годовая прейскурантная цена нового лекарства"), ("> 1 млн $", "Клеточная и генная терапия"), ("в 3–4 раза", "больше других стран платят США за те же лекарства")], "4 ШАГА К РЕШЕНИЮ",
   [("1.", "Переговоры о цене по всем лекарствам"), ("2.", "Остановить чрезмерные ежегодные повышения цен"), ("3.", "Бороться со злоупотреблениями патентами и монополией"), ("4.", "Ограничить расходы пациента из собственного кармана")],
   "Доступные лекарства и сильные инновации возможны одновременно.", "Источник: Public Citizen, 24 марта 2026 г."),
 'zh': D("PUBLIC CITIZEN", "药品为什么这么贵？", "垄断力量推高价格",
   [("约40万美元", "一种新药年度标价的中位数"), ("超过100万美元", "细胞和基因疗法"), ("3–4倍", "同样的药品，美国支付的价格是其他国家的倍数")], "解决问题的4个步骤",
   [("1.", "对所有药品进行价格谈判"), ("2.", "制止过高的年度涨价"), ("3.", "打击专利和垄断滥用"), ("4.", "为患者自付费用设置上限")],
   "价格可负担的药品与强劲的创新可以并存。", "来源：Public Citizen，2026年3月24日"),
 'hi': D("PUBLIC CITIZEN", "दवाएँ इतनी महँगी क्यों हैं?", "एकाधिकार की ताक़त कीमतें बढ़ाती है",
   [("~4,00,000 डॉलर", "नई दवा की वार्षिक सूची-कीमत की माध्यिका"), ("10 लाख डॉलर से अधिक", "सेल और जीन थेरेपी"), ("3–4 गुना", "उन्हीं दवाओं के लिए अमेरिका अन्य देशों से इतना अधिक चुकाता है")], "समाधान के 4 कदम",
   [("1.", "सभी दवाओं के लिए मूल्य वार्ता"), ("2.", "अत्यधिक वार्षिक मूल्य-वृद्धि रोकना"), ("3.", "पेटेंट और एकाधिकार के दुरुपयोग से लड़ना"), ("4.", "मरीज़ की जेब से होने वाले भुगतान पर सीमा")],
   "किफ़ायती दवाएँ और मज़बूत नवाचार साथ-साथ संभव हैं।", "स्रोत: Public Citizen, 24 मार्च 2026"),
 'ja': D("PUBLIC CITIZEN", "薬はなぜこれほど高いのか", "独占力が価格を押し上げる",
   [("約40万ドル", "新薬の年間定価の中央値"), ("100万ドル超", "細胞・遺伝子治療"), ("3〜4倍", "同じ薬に対して米国が他国より多く支払う倍率")], "解決への4つのステップ",
   [("1.", "すべての医薬品で価格交渉を行う"), ("2.", "過度な年次値上げを止める"), ("3.", "特許と独占の乱用と闘う"), ("4.", "患者の自己負担に上限を設ける")],
   "手の届く薬価と力強いイノベーションは両立できる。", "出典：Public Citizen、2026年3月24日"),
})

# 7 — Can money buy a licence to break the law (ICIJ)
CARDS['parasi'] = ('dark', {
 'en': D("2010–2025 · 12 COMPANIES · 25 CASES · 10 COUNTRIES", "Can money buy a licence to break the law?", None,
   [("$696 billion", "Revenue"), ("$1.7 billion", "Fines"), ("~0.24%", "Fines as a share of revenue")], "WHAT THE CASES WERE ABOUT",
   [("Bribery", ""), ("Misleading promotion", ""), ("Blocking competition", ""), ("Patent games", ""), ("The real question in Türkiye:", "why are the sanctions of TİTCK and SGK not transparent?")],
   "A penalty, or a cost of doing business?", "Data: ICIJ, Cancer Calculus"),
 'de': D("2010–2025 · 12 UNTERNEHMEN · 25 FÄLLE · 10 LÄNDER", "Kann man sich mit Geld eine Lizenz zum Rechtsbruch kaufen?", None,
   [("696 Mrd. $", "Umsatz"), ("1,7 Mrd. $", "Strafen"), ("~0,24 %", "Anteil der Strafen am Umsatz")], "WORUM ES IN DEN FÄLLEN GING",
   [("Bestechung", ""), ("Irreführende Werbung", ""), ("Behinderung des Wettbewerbs", ""), ("Patentspiele", ""), ("Die eigentliche Frage in der Türkei:", "Warum sind die Sanktionen von TİTCK und SGK nicht transparent?")],
   "Strafe oder Geschäftskosten?", "Daten: ICIJ, Cancer Calculus"),
 'es': D("2010–2025 · 12 EMPRESAS · 25 CASOS · 10 PAÍSES", "¿Puede el dinero comprar una licencia para delinquir?", None,
   [("696.000 M$", "Ingresos"), ("1.700 M$", "Multas"), ("~0,24 %", "Multas como proporción de los ingresos")], "DE QUÉ TRATABAN LOS CASOS",
   [("Soborno", ""), ("Promoción engañosa", ""), ("Bloqueo de la competencia", ""), ("Juegos de patentes", ""), ("La verdadera pregunta en Turquía:", "¿por qué no son transparentes las sanciones de TİTCK y SGK?")],
   "¿Una multa o un coste del negocio?", "Datos: ICIJ, Cancer Calculus"),
 'ru': D("2010–2025 · 12 КОМПАНИЙ · 25 ДЕЛ · 10 СТРАН", "Можно ли за деньги купить право нарушать закон?", None,
   [("696 млрд $", "Выручка"), ("1,7 млрд $", "Штрафы"), ("~0,24 %", "Доля штрафов в выручке")], "О ЧЁМ БЫЛИ ДЕЛА",
   [("Взятки", ""), ("Вводящая в заблуждение реклама", ""), ("Препятствование конкуренции", ""), ("Патентные игры", ""), ("Главный вопрос в Турции:", "почему санкции TİTCK и SGK непрозрачны?")],
   "Штраф или издержки ведения бизнеса?", "Данные: ICIJ, Cancer Calculus"),
 'zh': D("2010–2025 · 12家公司 · 25起案件 · 10个国家", "有钱就能买到违法许可证吗？", None,
   [("6960亿美元", "收入"), ("17亿美元", "罚款"), ("约0.24%", "罚款占收入的比例")], "这些案件涉及什么",
   [("行贿", ""), ("误导性推广", ""), ("阻碍竞争", ""), ("专利游戏", ""), ("土耳其的真正问题：", "TİTCK和SGK的处罚为什么不透明？")],
   "是惩罚，还是经营成本？", "数据：ICIJ，Cancer Calculus"),
 'hi': D("2010–2025 · 12 कंपनियाँ · 25 मामले · 10 देश", "क्या पैसे से अपराध करने का लाइसेंस खरीदा जा सकता है?", None,
   [("696 अरब डॉलर", "आय"), ("1.7 अरब डॉलर", "जुर्माना"), ("~0.24%", "आय के अनुपात में जुर्माना")], "मामले किस बारे में थे",
   [("रिश्वत", ""), ("भ्रामक प्रचार", ""), ("प्रतिस्पर्धा में बाधा", ""), ("पेटेंट के खेल", ""), ("तुर्किये में असली सवाल:", "TİTCK और SGK की कार्रवाइयाँ पारदर्शी क्यों नहीं हैं?")],
   "दंड, या कारोबार की लागत?", "डेटा: ICIJ, Cancer Calculus"),
 'ja': D("2010〜2025年 · 12社 · 25件 · 10か国", "金があれば違法行為の免許を買えるのか", None,
   [("6,960億ドル", "収益"), ("17億ドル", "罰金"), ("約0.24%", "収益に占める罰金の割合")], "事件の内容",
   [("贈賄", ""), ("誤解を招く販促", ""), ("競争の妨害", ""), ("特許を使った駆け引き", ""), ("トルコでの本当の問い：", "TİTCKとSGKの制裁はなぜ透明でないのか")],
   "罰か、それとも事業コストか", "データ：ICIJ「Cancer Calculus」"),
})

# 8 — Diagnostic inflation (poster)
CARDS['tanisal'] = ('teal', {
 'de': D("BITTERE MEDIZIN", "Diagnostische Inflation und das Geschäft mit der Krankheit", None),
 'es': D("MEDICINA AMARGA", "Inflación diagnóstica y quienes engañan con la enfermedad", None),
 'ru': D("ГОРЬКОЕ ЛЕКАРСТВО", "Диагностическая инфляция и торговля болезнями", None),
 'zh': D("苦口良药", "诊断膨胀与“贩卖疾病”", None),
 'hi': D("कड़वी दवा", "निदान की बढ़ती सीमाएँ और बीमारी के नाम पर छल", None),
 'ja': D("苦い薬", "診断インフレと「病気づくり」", None),
})

# 10 — Drug research on soldiers (poster)
CARDS['askerler'] = ('dark', {
 'en': D("BITTER MEDICINE", "Drug research on soldiers", None),
 'de': D("BITTERE MEDIZIN", "Arzneimittelforschung an Soldaten", None),
 'es': D("MEDICINA AMARGA", "Investigación de fármacos en soldados", None),
 'ru': D("ГОРЬКОЕ ЛЕКАРСТВО", "Исследования лекарств на солдатах", None),
 'zh': D("苦口良药", "在士兵身上进行的药物研究", None),
 'hi': D("कड़वी दवा", "सैनिकों पर दवा अनुसंधान", None),
 'ja': D("苦い薬", "兵士を対象とした医薬品研究", None),
})

# 11 — Pricing decree
CARDS['kararname'] = ('burg', {
 'en': D("BITTER MEDICINE", "A decree that protects industry and overlooks the pharmacist", None,
   [("80 → 75 → 70%", "Reference product price in years 1, 2 and 3: the price cut is spread over 3 years"), ("145 pages", "In the guideline, 'patient' does not appear in the context of medicines and 'access' is never mentioned"), ("2 days", "Time given before entry into force")], None,
   [("Tiered price protection.", "The price reduction is phased in over three years."), ("Value without criteria.", "The clinical and economic criteria of value-based pricing are not yet defined."), ("The pharmacist is left out of the reform.", "No structural improvement in margins and scales.")],
   "Conclusion: a selective reform. Flexibility for industry, silence for pharmacists and patients."),
 'de': D("BITTERE MEDIZIN", "Ein Erlass, der die Industrie schützt und den Apotheker übersieht", None,
   [("80 → 75 → 70 %", "Preis des Referenzprodukts im 1., 2. und 3. Jahr: Die Preissenkung wird auf 3 Jahre verteilt"), ("145 Seiten", "Im Leitfaden kommt „Patient“ im Arzneimittelkontext nicht vor, „Zugang“ wird nie erwähnt"), ("2 Tage", "Frist bis zum Inkrafttreten")], None,
   [("Gestufter Preisschutz.", "Die Preissenkung wird über drei Jahre gestreckt."), ("Wert ohne Maßstab.", "Die klinischen und ökonomischen Kriterien der wertbasierten Preisbildung sind noch nicht definiert."), ("Der Apotheker bleibt außerhalb der Reform.", "Keine strukturelle Verbesserung bei Margen und Staffeln.")],
   "Fazit: eine selektive Reform. Flexibilität für die Industrie, Schweigen gegenüber Apothekern und Patienten."),
 'es': D("MEDICINA AMARGA", "Un decreto que protege a la industria y no ve al farmacéutico", None,
   [("80 → 75 → 70 %", "Precio del producto de referencia en los años 1, 2 y 3: la bajada se reparte en 3 años"), ("145 páginas", "En la guía, «paciente» no aparece en el contexto del medicamento y «acceso» no se menciona nunca"), ("2 días", "Plazo hasta la entrada en vigor")], None,
   [("Protección de precios escalonada.", "La reducción de precio se aplica gradualmente en tres años."), ("Valor sin criterios.", "Aún no se han definido los criterios clínicos y económicos de la fijación de precios basada en el valor."), ("El farmacéutico queda fuera de la reforma.", "Sin mejora estructural en márgenes y escalas.")],
   "Conclusión: una reforma selectiva. Flexibilidad para la industria, silencio para farmacéuticos y pacientes."),
 'ru': D("ГОРЬКОЕ ЛЕКАРСТВО", "Постановление, которое защищает промышленность и не замечает аптекаря", None,
   [("80 → 75 → 70 %", "Цена референтного препарата в 1-й, 2-й и 3-й год: снижение растянуто на 3 года"), ("145 страниц", "В руководстве слово «пациент» в контексте лекарств не встречается, а «доступ» не упомянут ни разу"), ("2 дня", "Срок до вступления в силу")], None,
   [("Ступенчатая защита цен.", "Снижение цены растянуто на три года."), ("Ценность без критериев.", "Клинические и экономические критерии ценообразования на основе ценности ещё не определены."), ("Аптекарь остался вне реформы.", "Структурного улучшения наценок и шкал нет.")],
   "Вывод: избирательная реформа. Гибкость для промышленности, молчание для аптекарей и пациентов."),
 'zh': D("苦口良药", "保护产业、却看不见药师的法令", None,
   [("80 → 75 → 70%", "参照产品在第1、2、3年的价格：降价分3年完成"), ("145页", "指南中没有在药品语境下出现“患者”，也从未提到“可及性”"), ("2天", "距生效的时间")], None,
   [("阶梯式价格保护。", "降价在三年内逐步实施。"), ("有“价值”，无标准。", "基于价值定价的临床和经济标准尚未界定。"), ("药师被排除在改革之外。", "利润率和分级标准没有结构性改善。")],
   "结论：选择性的改革。对产业灵活，对药师和患者沉默。"),
 'hi': D("कड़वी दवा", "उद्योग को बचाने वाला, फार्मासिस्ट को न देखने वाला आदेश", None,
   [("80 → 75 → 70%", "संदर्भ उत्पाद की कीमत पहले, दूसरे और तीसरे वर्ष में: कटौती 3 वर्षों में फैलाई गई"), ("145 पृष्ठ", "दिशानिर्देश में दवा के संदर्भ में “मरीज़” नहीं है और “पहुँच” का ज़िक्र तक नहीं"), ("2 दिन", "लागू होने से पहले दिया गया समय")], None,
   [("चरणबद्ध मूल्य संरक्षण।", "कीमत में कटौती तीन वर्षों में चरणों में होगी।"), ("मूल्य है, मापदंड नहीं।", "मूल्य-आधारित मूल्य निर्धारण के नैदानिक और आर्थिक मापदंड अभी परिभाषित नहीं हैं।"), ("फार्मासिस्ट सुधार से बाहर।", "मुनाफ़े की दरों और स्लैब में कोई संरचनात्मक सुधार नहीं।")],
   "निष्कर्ष: चुनिंदा सुधार। उद्योग के लिए लचीलापन, फार्मासिस्ट और मरीज़ के लिए चुप्पी।"),
 'ja': D("苦い薬", "産業を守り、薬剤師を見ない政令", None,
   [("80 → 75 → 70%", "先発品価格の1年目・2年目・3年目：引き下げは3年に分散"), ("145ページ", "ガイドラインでは医薬品の文脈で「患者」は登場せず、「アクセス」は一度も出てこない"), ("2日", "施行までの猶予")], None,
   [("段階的な価格保護。", "価格引き下げは3年かけて実施される。"), ("価値はあるが基準がない。", "価値に基づく価格設定の臨床的・経済的基準はまだ定義されていない。"), ("薬剤師は改革の外。", "利益率と区分に構造的な改善はない。")],
   "結論：選択的な改革。産業には柔軟性、薬剤師と患者には沈黙。"),
})

# 12 — Alzheimer drugs (Cochrane)
_AS = "Nonino F, et al. Cochrane Database Syst Rev. 2026;CD013674"
CARDS['alzheimer'] = ('purple', {
 'en': D("COCHRANE REVIEW · 16 APRIL 2026", "Are Alzheimer's drugs ineffective?", "Amyloid-beta antibodies: no clinically meaningful benefit at 18 months, and a clear increase in ARIA risk",
   [("17 trials", "20,342 participants; mean age 70–74"), ("0.85 points", "ADAS-Cog difference (70-point test); threshold 2–4 points"), ("0.29 points", "CDR-SB difference (18-point scale); threshold 1–2 points"), ("+107 per 1,000", "More ARIA-E (brain oedema) cases than with placebo")], None,
   [("Daily living skills:", "ADCS-ADL, SMD 0.09. Below 0.2 is regarded as negligible."), ("ARIA-H (microbleeds):", "about a 2-fold increase in the donanemab and lecanemab trials."), ("Reporting gap:", "only 4 of the 17 trials reported symptomatic ARIA-E separately, and only 1 reported symptomatic ARIA-H."), ("Serious adverse events and all-cause mortality:", "no difference from placebo.")],
   "A statistically significant difference is not a clinically meaningful one.", "Source: " + _AS),
 'de': D("COCHRANE-REVIEW · 16. APRIL 2026", "Sind Alzheimer-Medikamente wirkungslos?", "Amyloid-beta-Antikörper: kein klinisch bedeutsamer Nutzen nach 18 Monaten, aber deutlich erhöhtes ARIA-Risiko",
   [("17 Studien", "20.342 Teilnehmer; Durchschnittsalter 70–74"), ("0,85 Punkte", "ADAS-Cog-Differenz (70-Punkte-Test); Schwelle 2–4 Punkte"), ("0,29 Punkte", "CDR-SB-Differenz (18-Punkte-Skala); Schwelle 1–2 Punkte"), ("+107 pro 1.000", "Mehr ARIA-E-Fälle (Hirnödem) als unter Placebo")], None,
   [("Alltagsfähigkeiten:", "ADCS-ADL, SMD 0,09. Unter 0,2 gilt als unbedeutend."), ("ARIA-H (Mikroblutungen):", "etwa 2-fach erhöht in den Studien zu Donanemab und Lecanemab."), ("Berichtslücke:", "Nur 4 der 17 Studien berichteten symptomatische ARIA-E gesondert, nur 1 symptomatische ARIA-H."), ("Schwere unerwünschte Ereignisse und Gesamtmortalität:", "kein Unterschied zu Placebo.")],
   "Ein statistisch signifikanter Unterschied ist noch kein klinisch bedeutsamer.", "Quelle: " + _AS),
 'es': D("REVISIÓN COCHRANE · 16 DE ABRIL DE 2026", "¿Son ineficaces los fármacos para el Alzheimer?", "Anticuerpos antiamiloide beta: sin beneficio clínicamente relevante a los 18 meses y con un claro aumento del riesgo de ARIA",
   [("17 ensayos", "20.342 participantes; edad media 70–74"), ("0,85 puntos", "Diferencia en ADAS-Cog (prueba de 70 puntos); umbral 2–4 puntos"), ("0,29 puntos", "Diferencia en CDR-SB (escala de 18 puntos); umbral 1–2 puntos"), ("+107 por 1.000", "Más casos de ARIA-E (edema cerebral) que con placebo")], None,
   [("Actividades de la vida diaria:", "ADCS-ADL, DME 0,09. Por debajo de 0,2 se considera insignificante."), ("ARIA-H (microhemorragias):", "aumento de unas 2 veces en los ensayos de donanemab y lecanemab."), ("Laguna de información:", "solo 4 de los 17 ensayos comunicaron por separado la ARIA-E sintomática y solo 1 la ARIA-H sintomática."), ("Acontecimientos adversos graves y mortalidad por cualquier causa:", "sin diferencias frente a placebo.")],
   "Una diferencia estadísticamente significativa no es una diferencia clínicamente relevante.", "Fuente: " + _AS),
 'ru': D("КОКРЕЙНОВСКИЙ ОБЗОР · 16 АПРЕЛЯ 2026", "Неэффективны ли лекарства от болезни Альцгеймера?", "Антитела к бета-амилоиду: клинически значимой пользы за 18 месяцев нет, а риск ARIA заметно выше",
   [("17 исследований", "20 342 участника; средний возраст 70–74 года"), ("0,85 балла", "Разница по ADAS-Cog (тест из 70 баллов); порог 2–4 балла"), ("0,29 балла", "Разница по CDR-SB (шкала из 18 баллов); порог 1–2 балла"), ("+107 на 1000", "Больше случаев ARIA-E (отёк мозга), чем на плацебо")], None,
   [("Навыки повседневной жизни:", "ADCS-ADL, СРС 0,09. Значение ниже 0,2 считается несущественным."), ("ARIA-H (микрокровоизлияния):", "рост примерно в 2 раза в исследованиях донанемаба и леканемаба."), ("Пробел в отчётности:", "лишь 4 из 17 исследований отдельно сообщили о симптомной ARIA-E и только 1 о симптомной ARIA-H."), ("Серьёзные нежелательные явления и общая смертность:", "различий с плацебо нет.")],
   "Статистически значимое различие не означает клинически значимого.", "Источник: " + _AS),
 'zh': D("COCHRANE系统综述 · 2026年4月16日", "阿尔茨海默病药物无效吗？", "抗β-淀粉样蛋白抗体：18个月时未见有临床意义的获益，ARIA风险明显升高",
   [("17项试验", "20,342名受试者；平均年龄70–74岁"), ("0.85分", "ADAS-Cog差值（70分量表）；阈值2–4分"), ("0.29分", "CDR-SB差值（18分量表）；阈值1–2分"), ("每1000人多107例", "ARIA-E（脑水肿）病例多于安慰剂组")], None,
   [("日常生活能力：", "ADCS-ADL，SMD 0.09。低于0.2被视为可忽略。"), ("ARIA-H（微出血）：", "在多奈单抗和仑卡奈单抗试验中约增加2倍。"), ("报告缺口：", "17项试验中仅4项单独报告了有症状的ARIA-E，仅1项报告了有症状的ARIA-H。"), ("严重不良事件和全因死亡率：", "与安慰剂无差异。")],
   "统计学上有显著差异，并不等于有临床意义。", "来源：" + _AS),
 'hi': D("कोक्रेन समीक्षा · 16 अप्रैल 2026", "क्या अल्ज़ाइमर की दवाएँ बेअसर हैं?", "एमिलॉयड-बीटा एंटीबॉडी: 18 महीनों में चिकित्सकीय रूप से सार्थक लाभ नहीं, और ARIA का जोखिम स्पष्ट रूप से बढ़ा",
   [("17 परीक्षण", "20,342 प्रतिभागी; औसत आयु 70–74"), ("0.85 अंक", "ADAS-Cog में अंतर (70 अंकों का परीक्षण); सीमा 2–4 अंक"), ("0.29 अंक", "CDR-SB में अंतर (18 अंकों का पैमाना); सीमा 1–2 अंक"), ("1,000 में +107", "प्लेसीबो की तुलना में ARIA-E (मस्तिष्क शोथ) के अधिक मामले")], None,
   [("दैनिक जीवन के कौशल:", "ADCS-ADL, SMD 0.09। 0.2 से कम को नगण्य माना जाता है।"), ("ARIA-H (सूक्ष्म रक्तस्राव):", "डोनानेमैब और लेकानेमैब के परीक्षणों में लगभग 2 गुना वृद्धि।"), ("रिपोर्टिंग की कमी:", "17 में से केवल 4 परीक्षणों ने लक्षणयुक्त ARIA-E अलग से बताया और केवल 1 ने लक्षणयुक्त ARIA-H।"), ("गंभीर प्रतिकूल घटनाएँ और कुल मृत्यु दर:", "प्लेसीबो से कोई अंतर नहीं।")],
   "सांख्यिकीय रूप से सार्थक अंतर, चिकित्सकीय रूप से सार्थक नहीं होता।", "स्रोत: " + _AS),
 'ja': D("コクランレビュー · 2026年4月16日", "アルツハイマー病治療薬は効かないのか", "抗アミロイドβ抗体：18か月時点で臨床的に意味のある効果はなく、ARIAのリスクは明らかに上昇",
   [("17試験", "参加者20,342人、平均年齢70〜74歳"), ("0.85点", "ADAS-Cogの差（70点満点）。閾値は2〜4点"), ("0.29点", "CDR-SBの差（18点満点）。閾値は1〜2点"), ("1,000人あたり+107例", "プラセボよりARIA-E（脳浮腫）が多い")], None,
   [("日常生活動作：", "ADCS-ADL、SMD 0.09。0.2未満は無視できるとされる。"), ("ARIA-H（微小出血）：", "ドナネマブとレカネマブの試験で約2倍に増加。"), ("報告の欠落：", "症候性ARIA-Eを別に報告したのは17試験中4試験のみ、症候性ARIA-Hは1試験のみ。"), ("重篤な有害事象と全死亡：", "プラセボとの差なし。")],
   "統計学的に有意な差は、臨床的に意味のある差ではない。", "出典：" + _AS),
})

# 13 — Creatine
CARDS['kreatin'] = ('blue', {
 'en': D("TODAY'S FASHION", "Creatine: should everyone take it?", "Does it really make sense for a healthy, well-nourished adult who is not an athlete to take creatine every day?",
   [("~95%", "of the body's creatine is in skeletal muscle"), ("33 trials", "2024 meta-analysis: favourable effects on some physical measures, but the evidence quality was rated low"), ("~1 kg", "extra lean mass reported in some meta-analyses when creatine is added to resistance exercise")], None,
   [("Creatine is not a vitamin.", "It is made in the liver and kidneys and also comes from meat and fish. A healthy person does not have to take it from outside."), ("Strongest evidence: physical performance.", "With resistance exercise it may increase muscle strength and lean mass more than exercise alone."), ("Ageing and sarcopenia.", "Current evidence supports creatine together with resistance exercise. There is no strong evidence that creatine alone protects an inactive older person.")]),
 'de': D("DER TREND DES TAGES", "Kreatin: Sollte es jeder einnehmen?", "Ist es für einen gesunden, gut ernährten Erwachsenen, der kein Sportler ist, wirklich sinnvoll, täglich Kreatin zu nehmen?",
   [("~95 %", "des Kreatins im Körper befinden sich im Skelettmuskel"), ("33 Studien", "Metaanalyse 2024: günstige Effekte auf einige körperliche Messgrößen, aber Evidenzqualität als niedrig bewertet"), ("~1 kg", "zusätzliche fettfreie Masse in einigen Metaanalysen, wenn Kreatin zum Krafttraining hinzukommt")], None,
   [("Kreatin ist kein Vitamin.", "Es wird in Leber und Nieren gebildet und stammt auch aus Fleisch und Fisch. Ein gesunder Mensch muss es nicht von außen zuführen."), ("Stärkste Evidenz: körperliche Leistung.", "Zusammen mit Krafttraining kann es Muskelkraft und fettfreie Masse stärker steigern als Training allein."), ("Altern und Sarkopenie.", "Die Evidenz stützt Kreatin zusammen mit Krafttraining. Es gibt keinen starken Beleg, dass Kreatin allein einen inaktiven älteren Menschen schützt.")]),
 'es': D("LA MODA DEL MOMENTO", "Creatina: ¿debería tomarla todo el mundo?", "¿Tiene realmente sentido que un adulto sano, bien alimentado y no deportista tome creatina a diario?",
   [("~95 %", "de la creatina del cuerpo está en el músculo esquelético"), ("33 ensayos", "Metaanálisis de 2024: efectos favorables en algunas medidas físicas, pero con calidad de la evidencia baja"), ("~1 kg", "de masa magra adicional en algunos metaanálisis al añadir creatina al ejercicio de fuerza")], None,
   [("La creatina no es una vitamina.", "Se sintetiza en el hígado y los riñones y también procede de la carne y el pescado. Una persona sana no necesita tomarla de fuera."), ("La evidencia más sólida: el rendimiento físico.", "Con ejercicio de fuerza puede aumentar la fuerza muscular y la masa magra más que el ejercicio solo."), ("Envejecimiento y sarcopenia.", "La evidencia respalda la creatina junto con el ejercicio de fuerza. No hay pruebas sólidas de que la creatina sola proteja a una persona mayor inactiva.")]),
 'ru': D("МОДА ДНЯ", "Креатин: нужен ли он всем?", "Есть ли смысл здоровому, хорошо питающемуся взрослому, не спортсмену, принимать креатин каждый день?",
   [("~95 %", "креатина в организме находится в скелетных мышцах"), ("33 исследования", "Метаанализ 2024 года: положительное влияние на некоторые физические показатели, но качество доказательств низкое"), ("~1 кг", "дополнительной безжировой массы в ряде метаанализов при добавлении креатина к силовым упражнениям")], None,
   [("Креатин не витамин.", "Он синтезируется в печени и почках и поступает с мясом и рыбой. Здоровому человеку не обязательно получать его извне."), ("Самые сильные доказательства: физическая работоспособность.", "Вместе с силовыми упражнениями он может увеличивать силу мышц и безжировую массу больше, чем одни упражнения."), ("Старение и саркопения.", "Данные поддерживают сочетание креатина с силовыми упражнениями. Убедительных доказательств, что один креатин защищает малоподвижного пожилого человека, нет.")]),
 'zh': D("当下流行", "肌酸：人人都该服用吗？", "一个健康、营养良好、不是运动员的成年人，每天服用肌酸真的有意义吗？",
   [("约95%", "的体内肌酸存在于骨骼肌中"), ("33项试验", "2024年荟萃分析：对部分身体指标有积极作用，但证据质量被评为低"), ("约1公斤", "部分荟萃分析显示，在抗阻训练基础上加用肌酸可多增加的瘦体重")], None,
   [("肌酸不是维生素。", "它在肝脏和肾脏合成，也来自肉类和鱼类。健康人不必额外补充。"), ("最有力的证据：体能表现。", "与抗阻训练联合使用时，肌肉力量和瘦体重的增加可能多于单纯训练。"), ("衰老与肌少症。", "现有证据支持肌酸与抗阻训练联合使用。没有有力证据表明不运动的老年人单用肌酸能起到保护作用。")]),
 'hi': D("आज का चलन", "क्रिएटिन: क्या सबको लेना चाहिए?", "क्या एक स्वस्थ, अच्छा खाने वाले, गैर-खिलाड़ी वयस्क के लिए रोज़ क्रिएटिन लेना वाक़ई सार्थक है?",
   [("~95%", "शरीर का क्रिएटिन कंकाल पेशियों में होता है"), ("33 परीक्षण", "2024 का मेटा-विश्लेषण: कुछ शारीरिक मापों पर अनुकूल प्रभाव, पर प्रमाण की गुणवत्ता निम्न आँकी गई"), ("~1 किलो", "कुछ मेटा-विश्लेषणों में प्रतिरोध व्यायाम के साथ क्रिएटिन जोड़ने पर अतिरिक्त वसा-रहित द्रव्यमान")], None,
   [("क्रिएटिन विटामिन नहीं है।", "यह यकृत और गुर्दों में बनता है और मांस-मछली से भी मिलता है। स्वस्थ व्यक्ति को इसे बाहर से लेना ज़रूरी नहीं।"), ("सबसे मज़बूत प्रमाण: शारीरिक प्रदर्शन।", "प्रतिरोध व्यायाम के साथ यह केवल व्यायाम की तुलना में पेशी-बल और वसा-रहित द्रव्यमान अधिक बढ़ा सकता है।"), ("बुढ़ापा और सार्कोपीनिया।", "प्रमाण क्रिएटिन और प्रतिरोध व्यायाम के संयोजन का समर्थन करते हैं। निष्क्रिय बुज़ुर्ग को अकेला क्रिएटिन बचाता है, इसका ठोस प्रमाण नहीं।")]),
 'ja': D("いまの流行", "クレアチン：誰もが摂るべきか", "健康で栄養状態がよく、アスリートでもない成人が毎日クレアチンを摂ることに本当に意味はあるのか",
   [("約95%", "体内のクレアチンは骨格筋にある"), ("33試験", "2024年のメタ解析：一部の身体指標に好ましい効果。ただしエビデンスの質は低いと評価"), ("約1kg", "レジスタンス運動にクレアチンを加えた場合の除脂肪量の上乗せ（一部のメタ解析）")], None,
   [("クレアチンはビタミンではない。", "肝臓と腎臓で合成され、肉や魚からも摂取される。健康な人が外から補う必要はない。"), ("最も強いエビデンスは身体パフォーマンス。", "レジスタンス運動と併用すると、運動のみより筋力と除脂肪量が増える可能性がある。"), ("加齢とサルコペニア。", "現在のエビデンスが支持するのはクレアチンとレジスタンス運動の併用。運動しない高齢者がクレアチンだけで守られるという強い根拠はない。")]),
})

# 14 — Teva investigation
CARDS['teva'] = ('burg', {
 'en': D("DRUG POLICY", "The Teva investigation", "Allegations of a divisional-patent strategy and misleading information",
   [("6 Aug 2026", "The Turkish Competition Board opened an investigation into Teva (decision 26-28/804-M) under Article 6 of Law No. 4054"), ("$503 million", "Fine in Europe in 2024 over Copaxone (multiple sclerosis); still under appeal")], None,
   [("Türkiye, 2026, allegation:", "delaying generic competition through a divisional-patent strategy."), ("Second allegation:", "misleading information given to health authorities about competing products."), ("Europe, 2024, allegation:", "delaying generic competition through patent strategy."), ("Why it matters:", "the first named, concrete case of the 'divisional patent' mechanism described in the Competition Authority's August 2026 pharmaceutical sector report.")],
   "Same company, same kind of allegation, two different jurisdictions."),
 'de': D("ARZNEIMITTELPOLITIK", "Die Teva-Untersuchung", "Vorwurf einer Teilpatent-Strategie und irreführender Angaben",
   [("6. Aug. 2026", "Die türkische Wettbewerbsbehörde leitete eine Untersuchung gegen Teva ein (Beschluss 26-28/804-M) nach Artikel 6 des Gesetzes Nr. 4054"), ("503 Mio. $", "Geldbuße in Europa 2024 wegen Copaxone (Multiple Sklerose); noch im Rechtsmittelverfahren")], None,
   [("Türkei, 2026, Vorwurf:", "Verzögerung des Generikawettbewerbs durch eine Teilpatent-Strategie."), ("Zweiter Vorwurf:", "irreführende Angaben gegenüber Gesundheitsbehörden über Konkurrenzprodukte."), ("Europa, 2024, Vorwurf:", "Verzögerung des Generikawettbewerbs durch Patentstrategie."), ("Warum es wichtig ist:", "der erste namentliche, konkrete Fall des „Teilpatent“-Mechanismus, den der Sektorbericht der Wettbewerbsbehörde vom August 2026 beschreibt.")],
   "Dasselbe Unternehmen, dieselbe Art von Vorwurf, zwei verschiedene Rechtsräume."),
 'es': D("POLÍTICA FARMACÉUTICA", "La investigación sobre Teva", "Acusaciones de estrategia de patentes divisionales e información engañosa",
   [("6 ago. 2026", "La autoridad turca de competencia abrió una investigación sobre Teva (decisión 26-28/804-M) conforme al artículo 6 de la Ley n.º 4054"), ("503 M$", "Multa en Europa en 2024 por Copaxone (esclerosis múltiple); aún en apelación")], None,
   [("Turquía, 2026, acusación:", "retrasar la competencia de genéricos mediante una estrategia de patentes divisionales."), ("Segunda acusación:", "información engañosa a las autoridades sanitarias sobre productos competidores."), ("Europa, 2024, acusación:", "retrasar la competencia de genéricos mediante la estrategia de patentes."), ("Por qué importa:", "es el primer caso concreto y con nombre del mecanismo de «patente divisional» descrito en el informe sectorial de agosto de 2026.")],
   "La misma empresa, el mismo tipo de acusación, dos jurisdicciones distintas."),
 'ru': D("ЛЕКАРСТВЕННАЯ ПОЛИТИКА", "Расследование в отношении Teva", "Обвинения в стратегии выделенных патентов и в предоставлении вводящих в заблуждение сведений",
   [("6 авг. 2026", "Совет по конкуренции Турции начал расследование в отношении Teva (решение 26-28/804-M) по статье 6 Закона № 4054"), ("503 млн $", "Штраф в Европе в 2024 году по делу о Копаксоне (рассеянный склероз); обжалуется")], None,
   [("Турция, 2026, обвинение:", "задержка конкуренции со стороны дженериков с помощью стратегии выделенных патентов."), ("Второе обвинение:", "вводящие в заблуждение сведения о конкурирующих препаратах, переданные органам здравоохранения."), ("Европа, 2024, обвинение:", "задержка конкуренции дженериков с помощью патентной стратегии."), ("Почему это важно:", "первый конкретный случай с названием компании для механизма «выделенного патента», описанного в отраслевом отчёте за август 2026 года.")],
   "Та же компания, тот же тип обвинения, две разные юрисдикции."),
 'zh': D("药品政策", "对梯瓦（Teva）的调查", "涉嫌采用分案专利策略并提供误导性信息",
   [("2026年8月6日", "土耳其竞争委员会依据第4054号法律第6条对梯瓦立案调查（决定号26-28/804-M）"), ("5.03亿美元", "2024年在欧洲因Copaxone（多发性硬化）被处罚款；仍在上诉中")], None,
   [("土耳其，2026年，指控：", "通过分案专利策略拖延仿制药竞争。"), ("第二项指控：", "就竞争产品向卫生主管部门提供误导性信息。"), ("欧洲，2024年，指控：", "通过专利策略拖延仿制药竞争。"), ("为何重要：", "这是竞争管理局2026年8月行业报告所描述的“分案专利”机制的第一个点名的具体案例。")],
   "同一家公司，同一类指控，两个不同的司法辖区。"),
 'hi': D("दवा नीति", "टेवा की जाँच", "विभाजित पेटेंट रणनीति और भ्रामक जानकारी के आरोप",
   [("6 अगस्त 2026", "तुर्की प्रतिस्पर्धा बोर्ड ने कानून संख्या 4054 के अनुच्छेद 6 के तहत टेवा के विरुद्ध जाँच शुरू की (निर्णय 26-28/804-M)"), ("50.3 करोड़ डॉलर", "2024 में यूरोप में कोपैक्सोन (मल्टिपल स्क्लेरोसिस) मामले में जुर्माना; अभी अपील में")], None,
   [("तुर्किये, 2026, आरोप:", "विभाजित पेटेंट रणनीति से जेनेरिक प्रतिस्पर्धा में देरी।"), ("दूसरा आरोप:", "प्रतिस्पर्धी उत्पादों के बारे में स्वास्थ्य प्राधिकरणों को भ्रामक जानकारी।"), ("यूरोप, 2024, आरोप:", "पेटेंट रणनीति से जेनेरिक प्रतिस्पर्धा में देरी।"), ("यह क्यों अहम है:", "प्रतिस्पर्धा प्राधिकरण की अगस्त 2026 की क्षेत्र रिपोर्ट में वर्णित “विभाजित पेटेंट” तंत्र का पहला नामित, ठोस मामला।")],
   "वही कंपनी, वही तरह का आरोप, दो अलग क्षेत्राधिकार।"),
 'ja': D("医薬品政策", "テバ社への調査", "分割特許戦略と誤解を招く情報提供の疑い",
   [("2026年8月6日", "トルコ競争委員会が法律第4054号第6条に基づきテバ社の調査を開始（決定26-28/804-M）"), ("5億300万ドル", "2024年に欧州でコパキソン（多発性硬化症）をめぐり科された制裁金。現在も係争中")], None,
   [("トルコ、2026年、疑い：", "分割特許戦略によるジェネリック競争の遅延。"), ("第2の疑い：", "競合製品について保健当局に誤解を招く情報を提供。"), ("欧州、2024年、疑い：", "特許戦略によるジェネリック競争の遅延。"), ("なぜ重要か：", "競争当局の2026年8月の業界報告書が示した「分割特許」の仕組みについて、社名の挙がった初の具体的事例。")],
   "同じ企業、同じ種類の疑い、二つの異なる法域。"),
})

# 15 — Keytruda
_KP = "USA $208,000 · Colombia $130,000 · Croatia $116,000 · Lebanon $93,000 · Germany $80,000 · South Africa $65,000 · Türkiye 3 million TL"
CARDS['keytruda'] = ('dark', {
 'en': D("ICIJ · CANCER CALCULUS", "The price of the cancer drug Keytruda", "How Merck protects the world's best-selling cancer drug through patents, pricing and lobbying",
   [("1,212", "patent applications in 53 countries and territories; 84% filed after 2014"), ("2042", "protection may last until 2042, 14 years beyond 2028"), ("$46 bn vs $1.9 bn", "Merck's claimed R&D cost versus the independent Public Eye estimate"), ("~$163 bn", "total sales revenue since 2014")], None,
   [("Prices by country:", _KP), ("Dosing debate:", "using a flat 200 mg dose instead of 2 mg/kg roughly doubles drug consumption in most patients."), ("Secrecy:", "public authorities in at least 6 countries withhold spending and patient numbers as 'trade secrets'."), ("Unequal access:", "in some countries a year's median income cannot buy even a single dose.")],
   None, "Source: ICIJ, Cancer Calculus (April 2026), icij.org"),
 'de': D("ICIJ · CANCER CALCULUS", "Der Preis des Krebsmedikaments Keytruda", "Wie Merck das meistverkaufte Krebsmedikament der Welt mit Patenten, Preisgestaltung und Lobbyarbeit schützt",
   [("1.212", "Patentanmeldungen in 53 Ländern und Gebieten; 84 % nach 2014 eingereicht"), ("2042", "Schutz möglicherweise bis 2042, 14 Jahre über 2028 hinaus"), ("46 vs. 1,9 Mrd. $", "Von Merck angegebene F&E-Kosten gegenüber der unabhängigen Schätzung von Public Eye"), ("~163 Mrd. $", "Gesamtumsatz seit 2014")], None,
   [("Preise nach Land:", "USA 208.000 $ · Kolumbien 130.000 $ · Kroatien 116.000 $ · Libanon 93.000 $ · Deutschland 80.000 $ · Südafrika 65.000 $ · Türkei 3 Mio. TL"), ("Dosierungsdebatte:", "Die Pauschaldosis von 200 mg statt 2 mg/kg verdoppelt bei den meisten Patienten etwa den Verbrauch."), ("Geheimhaltung:", "Behörden in mindestens 6 Ländern halten Ausgaben und Patientenzahlen als „Geschäftsgeheimnis“ zurück."), ("Ungleicher Zugang:", "In manchen Ländern reicht ein medianes Jahreseinkommen nicht einmal für eine Dosis.")],
   None, "Quelle: ICIJ, Cancer Calculus (April 2026), icij.org"),
 'es': D("ICIJ · CANCER CALCULUS", "El precio del fármaco oncológico Keytruda", "Cómo protege Merck el fármaco contra el cáncer más vendido del mundo con patentes, precios y cabildeo",
   [("1.212", "solicitudes de patente en 53 países y territorios; el 84 % presentadas después de 2014"), ("2042", "la protección podría durar hasta 2042, 14 años más allá de 2028"), ("46.000 vs 1.900 M$", "Coste de I+D declarado por Merck frente a la estimación independiente de Public Eye"), ("~163.000 M$", "ingresos totales por ventas desde 2014")], None,
   [("Precios por país:", "EE. UU. 208.000 $ · Colombia 130.000 $ · Croacia 116.000 $ · Líbano 93.000 $ · Alemania 80.000 $ · Sudáfrica 65.000 $ · Turquía 3 millones de TL"), ("Debate sobre la dosis:", "usar una dosis fija de 200 mg en lugar de 2 mg/kg duplica aproximadamente el consumo en la mayoría de los pacientes."), ("Secretismo:", "las autoridades de al menos 6 países no revelan el gasto ni el número de pacientes alegando «secreto comercial»."), ("Acceso desigual:", "en algunos países el ingreso mediano de un año no alcanza ni para una dosis.")],
   None, "Fuente: ICIJ, Cancer Calculus (abril de 2026), icij.org"),
 'ru': D("ICIJ · CANCER CALCULUS", "Цена противоопухолевого препарата Китруда", "Как Merck защищает самое продаваемое в мире лекарство от рака с помощью патентов, цен и лоббирования",
   [("1212", "патентных заявок в 53 странах и территориях; 84 % поданы после 2014 года"), ("2042", "защита может продлиться до 2042 года, на 14 лет дольше 2028-го"), ("46 против 1,9 млрд $", "Заявленные Merck расходы на НИОКР и независимая оценка Public Eye"), ("~163 млрд $", "общая выручка от продаж с 2014 года")], None,
   [("Цены по странам:", "США 208 000 $ · Колумбия 130 000 $ · Хорватия 116 000 $ · Ливан 93 000 $ · Германия 80 000 $ · ЮАР 65 000 $ · Турция 3 млн лир"), ("Спор о дозе:", "фиксированная доза 200 мг вместо 2 мг/кг примерно удваивает расход препарата у большинства пациентов."), ("Секретность:", "власти как минимум 6 стран не раскрывают расходы и число пациентов, ссылаясь на «коммерческую тайну»."), ("Неравный доступ:", "в некоторых странах медианного годового дохода не хватает даже на одну дозу.")],
   None, "Источник: ICIJ, Cancer Calculus (апрель 2026 г.), icij.org"),
 'zh': D("ICIJ · CANCER CALCULUS", "抗癌药可瑞达（Keytruda）的代价", "默沙东如何用专利、定价和游说保护全球最畅销的抗癌药",
   [("1,212项", "在53个国家和地区的专利申请；84%在2014年之后提交"), ("2042年", "保护期可能延续到2042年，比2028年多14年"), ("460亿对19亿美元", "默沙东声称的研发成本与Public Eye的独立估算"), ("约1630亿美元", "2014年以来的销售总收入")], None,
   [("各国价格：", "美国20.8万美元 · 哥伦比亚13万美元 · 克罗地亚11.6万美元 · 黎巴嫩9.3万美元 · 德国8万美元 · 南非6.5万美元 · 土耳其300万里拉"), ("剂量之争：", "采用200毫克固定剂量而不是2毫克/公斤，使多数患者的用药量约增加一倍。"), ("保密：", "至少6个国家的公共机构以“商业秘密”为由不公开支出和患者人数。"), ("可及性不平等：", "在一些国家，一年的收入中位数连一剂药都买不起。")],
   None, "来源：ICIJ，Cancer Calculus（2026年4月），icij.org"),
 'hi': D("ICIJ · CANCER CALCULUS", "कैंसर की दवा कीट्रूडा की कीमत", "मर्क दुनिया की सबसे अधिक बिकने वाली कैंसर दवा को पेटेंट, मूल्य निर्धारण और लॉबिंग से कैसे बचाता है",
   [("1,212", "53 देशों और क्षेत्रों में पेटेंट आवेदन; 84% वर्ष 2014 के बाद दाख़िल"), ("2042", "संरक्षण 2042 तक चल सकता है, यानी 2028 से 14 वर्ष आगे"), ("46 बनाम 1.9 अरब डॉलर", "मर्क का बताया अनुसंधान खर्च बनाम Public Eye का स्वतंत्र अनुमान"), ("~163 अरब डॉलर", "2014 से कुल बिक्री आय")], None,
   [("देशों के अनुसार कीमतें:", "अमेरिका 2,08,000 डॉलर · कोलंबिया 1,30,000 डॉलर · क्रोएशिया 1,16,000 डॉलर · लेबनान 93,000 डॉलर · जर्मनी 80,000 डॉलर · दक्षिण अफ्रीका 65,000 डॉलर · तुर्किये 30 लाख TL"), ("खुराक पर बहस:", "2 मि.ग्रा./कि.ग्रा. के बजाय 200 मि.ग्रा. की निश्चित खुराक अधिकांश मरीज़ों में दवा की खपत लगभग दोगुनी कर देती है।"), ("गोपनीयता:", "कम से कम 6 देशों के अधिकारी “व्यापारिक रहस्य” कहकर खर्च और मरीज़ों की संख्या नहीं बताते।"), ("असमान पहुँच:", "कुछ देशों में साल भर की माध्यिका आय से एक खुराक भी नहीं खरीदी जा सकती।")],
   None, "स्रोत: ICIJ, Cancer Calculus (अप्रैल 2026), icij.org"),
 'ja': D("ICIJ · CANCER CALCULUS", "抗がん剤キイトルーダの代償", "メルクは世界で最も売れている抗がん剤を、特許・価格設定・ロビー活動でどう守っているのか",
   [("1,212件", "53の国と地域での特許出願。84%は2014年以降に出願"), ("2042年", "保護は2042年まで続く可能性があり、2028年より14年長い"), ("460億対19億ドル", "メルクが主張する研究開発費と、Public Eyeによる独立した推計"), ("約1,630億ドル", "2014年以降の総売上高")], None,
   [("国別の価格：", "米国20万8千ドル · コロンビア13万ドル · クロアチア11万6千ドル · レバノン9万3千ドル · ドイツ8万ドル · 南アフリカ6万5千ドル · トルコ300万リラ"), ("用量をめぐる議論：", "2mg/kgではなく200mgの固定用量を使うと、多くの患者で薬の消費量がほぼ2倍になる。"), ("秘密主義：", "少なくとも6か国の公的機関が「営業秘密」を理由に支出と患者数を公表していない。"), ("アクセスの不平等：", "国によっては、年間所得の中央値でも1回分すら買えない。")],
   None, "出典：ICIJ「Cancer Calculus」（2026年4月）、icij.org"),
})
