from batch1 import D
CARDS = {}

# i22: Quality in medicines (EN image = twin from the paired English article)
CARDS['b15_kalite'] = ('dark', {
 'de': D("ARZNEIMITTELQUALITÄT", "Qualität bei Arzneimitteln", "Drei Stufen, die zusammengehören", None, None,
   [("Zerfall (Disintegration):", "Zerfällt die Tablette?"),
    ("Freisetzung (Dissolution):", "Löst sich der Wirkstoff? Ein Instrument der Qualitätskontrolle, kein Nachweis der Bioäquivalenz."),
    ("BV/BÄ:", "Bioverfügbarkeit und Bioäquivalenz. Wird der Wirkstoff im menschlichen Körper wirklich aufgenommen?"),
    ("Fixkombinationen:", "Freisetzungsdaten allein reichen für eine Zulassung nicht aus."),
    ("Vor und nach der Zulassung:", "Qualität muss vor der Zulassung belegt und danach durch ständige Überwachung bestätigt werden."),
    ("Leistungsprinzip verlangt:", "kompetente und ehrliche Beamte; Entscheidungen auf objektiver, wissenschaftlicher und ethischer Grundlage; Kommissionen und Experten, die Stellung nehmen.")],
   "Fehlt nur eine dieser drei Stufen, gilt die Arzneimittelqualität nicht als vollständig."),
 'es': D("CALIDAD DEL MEDICAMENTO", "Calidad en los medicamentos", "Tres etapas que van juntas", None, None,
   [("Disgregación:", "¿se deshace el comprimido?"),
    ("Disolución:", "¿se disuelve el principio activo? Es una herramienta de control de calidad, no una prueba de bioequivalencia."),
    ("BD/BE:", "biodisponibilidad y bioequivalencia. ¿Se absorbe realmente en el cuerpo humano?"),
    ("Combinaciones a dosis fijas:", "los datos de disolución por sí solos no bastan para autorizar."),
    ("Antes y después de la autorización:", "la calidad debe demostrarse antes y confirmarse después con vigilancia continua."),
    ("El mérito exige:", "burócratas competentes y honestos; decisiones basadas en elementos objetivos, científicos y éticos; comisiones y expertos que emiten opinión.")],
   "Si falta una sola de estas tres etapas, la calidad del medicamento no está completa."),
 'ru': D("КАЧЕСТВО ЛЕКАРСТВ", "Качество лекарственных средств", "Три этапа, неотделимые друг от друга", None, None,
   [("Распадаемость:", "распадается ли таблетка?"),
    ("Растворение:", "растворяется ли действующее вещество? Это инструмент контроля качества, а не доказательство биоэквивалентности."),
    ("БД/БЭ:", "биодоступность и биоэквивалентность. Действительно ли вещество всасывается в организме человека?"),
    ("Фиксированные комбинации:", "одних данных о растворении недостаточно для регистрации."),
    ("До и после регистрации:", "качество нужно доказать до регистрации и подтверждать постоянным надзором после неё."),
    ("Принцип заслуг требует:", "компетентных и честных чиновников; решений, основанных на объективных, научных и этических началах; комиссий и экспертов, дающих заключения.")],
   "Если отсутствует хотя бы один из трёх этапов, качество лекарства нельзя считать подтверждённым."),
 'zh': D("药品质量", "药品的质量", "三个环节，缺一不可", None, None,
   [("崩解：", "药片能否崩解？"),
    ("溶出：", "活性成分能否溶出？它是质量控制工具，不是生物等效性的证明。"),
    ("BA/BE：", "生物利用度与生物等效性。药物在人体内是否真正被吸收？"),
    ("固定剂量复方制剂：", "仅凭溶出数据不足以批准上市。"),
    ("上市前与上市后：", "质量须在批准前得到证明，并在批准后通过持续监督加以确认。"),
    ("任人唯贤要求：", "有能力且诚实的官员；基于客观、科学和伦理因素的决定；提出意见的委员会和专家。")],
   "这三个环节只要缺少一个，药品质量就不算完整。"),
 'hi': D("दवा की गुणवत्ता", "दवाओं में गुणवत्ता", "तीन चरण, जो एक साथ चलते हैं", None, None,
   [("विघटन (डिसइंटीग्रेशन):", "क्या गोली टूटकर बिखरती है?"),
    ("विलयन (डिसॉल्यूशन):", "क्या सक्रिय पदार्थ घुलता है? यह गुणवत्ता नियंत्रण का साधन है, जैव-समतुल्यता का प्रमाण नहीं।"),
    ("BA/BE:", "जैव-उपलब्धता और जैव-समतुल्यता। क्या दवा मानव शरीर में सचमुच अवशोषित होती है?"),
    ("निश्चित खुराक संयोजन:", "केवल विलयन के आँकड़े लाइसेंस के लिए पर्याप्त नहीं हैं।"),
    ("लाइसेंस से पहले और बाद में:", "गुणवत्ता पहले सिद्ध होनी चाहिए और बाद में निरंतर निगरानी से पुष्ट होनी चाहिए।"),
    ("योग्यता की माँग:", "सक्षम और ईमानदार अधिकारी; वस्तुनिष्ठ, वैज्ञानिक और नैतिक आधार पर निर्णय; राय देने वाले आयोग और विशेषज्ञ।")],
   "इन तीन चरणों में से एक भी कम हो, तो दवा की गुणवत्ता पूरी नहीं मानी जाती।"),
 'ja': D("医薬品の品質", "医薬品における品質", "切り離せない三つの段階", None, None,
   [("崩壊：", "錠剤は崩壊するか。"),
    ("溶出：", "有効成分は溶け出すか。品質管理の手段であり、生物学的同等性の証明ではない。"),
    ("BA/BE：", "バイオアベイラビリティと生物学的同等性。人体で実際に吸収されるか。"),
    ("固定用量配合剤：", "溶出データだけでは承認の根拠として不十分である。"),
    ("承認の前と後：", "品質は承認前に証明し、承認後も継続的な監視で確認しなければならない。"),
    ("能力主義に必要なもの：", "有能で誠実な行政官、客観的・科学的・倫理的要素に基づく決定、意見を述べる委員会と専門家。")],
   "この三段階のうち一つでも欠ければ、医薬品の品質は完成したとはいえない。"),
})

# i23: Gabapentin and gabapentinoids
CARDS['b15_gaba'] = ('burg', {
 'en': D("GABAPENTIN AND GABAPENTINOIDS", "The overlooked facts", "The myth of the \"safe alternative\": why are they prescribed so freely?",
   [(">2x", "dementia risk with 6 or more prescriptions"), (">3x", "risk of mild cognitive impairment"), ("5th", "most prescribed drug in the USA in 2024"), ("15.5 million", "users in the USA in 2024 (5.8 million in 2010)")], None,
   [("Rising adverse effects:", "cognitive decline and dementia, peripheral oedema, misuse and dependence, withdrawal syndromes."),
    ("Prescribing cascade:", "the oedema is labelled as heart failure or venous insufficiency and a loop diuretic is added."),
    ("Opioid crisis:", "not a substitute but a silent partner that strengthens the opioid effect."),
    ("Legal does not mean harmless:", "the green prescription in Türkiye has not reduced use.")],
   "To prevent more harm, let us use these drugs wisely and have them used wisely."),
 'de': D("GABAPENTIN UND GABAPENTINOIDE", "Die übersehenen Tatsachen", "Der Mythos der \"sicheren Alternative\": Warum wird so leichtfertig verordnet?",
   [(">2-fach", "Demenzrisiko bei 6 oder mehr Verordnungen"), (">3-fach", "Risiko einer leichten kognitiven Störung"), ("Platz 5", "der meistverordneten Arzneimittel in den USA 2024"), ("15,5 Mio.", "Anwender in den USA 2024 (2010: 5,8 Mio.)")], None,
   [("Zunehmende Nebenwirkungen:", "kognitiver Abbau und Demenz, periphere Ödeme, Missbrauch und Abhängigkeit, Entzugssyndrome."),
    ("Verordnungskaskade:", "das Ödem wird als Herz- oder Veneninsuffizienz eingestuft und ein Schleifendiuretikum kommt hinzu."),
    ("Opioidkrise:", "kein Ersatz, sondern ein stiller Partner, der die Opioidwirkung verstärkt."),
    ("Legal heißt nicht harmlos:", "das grüne Rezept in der Türkei hat den Gebrauch nicht gesenkt.")],
   "Um weiteren Schaden zu verhindern: Setzen wir diese Arzneimittel klug ein und sorgen wir für ihren klugen Einsatz."),
 'es': D("GABAPENTINA Y GABAPENTINOIDES", "Las verdades ignoradas", "El mito de la \"alternativa segura\": ¿por qué se recetan con tanta ligereza?",
   [(">2 veces", "riesgo de demencia con 6 o más recetas"), (">3 veces", "riesgo de deterioro cognitivo leve"), ("5.º", "fármaco más recetado en EE. UU. en 2024"), ("15,5 millones", "usuarios en EE. UU. en 2024 (5,8 millones en 2010)")], None,
   [("Efectos adversos en aumento:", "deterioro cognitivo y demencia, edema periférico, abuso y dependencia, síndromes de abstinencia."),
    ("Cascada de prescripción:", "el edema se etiqueta como insuficiencia cardíaca o venosa y se añade un diurético de asa."),
    ("Crisis de opioides:", "no un sustituto, sino un socio silencioso que potencia el efecto opioide."),
    ("Legal no significa inocuo:", "la receta verde en Turquía no ha reducido el uso.")],
   "Para evitar más daño, usemos estos fármacos con inteligencia y hagamos que se usen así."),
 'ru': D("ГАБАПЕНТИН И ГАБАПЕНТИНОИДЫ", "Факты, которые упускают из виду", "Миф о «безопасной альтернативе»: почему их назначают так легко?",
   [(">2 раз", "риск деменции при 6 и более рецептах"), (">3 раз", "риск лёгких когнитивных нарушений"), ("5-е место", "среди самых назначаемых лекарств в США в 2024 г."), ("15,5 млн", "принимавших в США в 2024 г. (в 2010 г.: 5,8 млн)")], None,
   [("Растущие побочные эффекты:", "когнитивное снижение и деменция, периферические отёки, злоупотребление и зависимость, синдром отмены."),
    ("Каскад назначений:", "отёк принимают за сердечную или венозную недостаточность и добавляют петлевой диуретик."),
    ("Опиоидный кризис:", "не замена, а молчаливый партнёр, усиливающий действие опиоидов."),
    ("Законно не значит безвредно:", "зелёный рецепт в Турции не сократил применение.")],
   "Чтобы предотвратить новый вред, будем применять эти препараты разумно и добиваться разумного применения."),
 'zh': D("加巴喷丁与加巴喷丁类药物", "被忽视的事实", "“安全替代品”的神话：为什么开得如此随意？",
   [(">2倍", "开具6张及以上处方者的痴呆风险"), (">3倍", "轻度认知障碍风险"), ("第5位", "2024年美国处方量最多的药物"), ("1550万", "2024年美国使用者（2010年为580万）")], None,
   [("不断增加的不良反应：", "认知减退和痴呆、外周水肿、滥用和依赖、戒断综合征。"),
    ("处方级联：", "水肿被当作心力衰竭或静脉功能不全，于是加用袢利尿剂。"),
    ("阿片类危机：", "它不是替代品，而是增强阿片类作用的沉默伙伴。"),
    ("合法不等于无害：", "土耳其的绿色处方并未减少使用。")],
   "为了避免更多伤害，让我们明智地使用这些药物，也让别人明智地使用。"),
 'hi': D("गैबापेंटिन और गैबापेंटिनॉइड", "अनदेखे किए गए तथ्य", "\"सुरक्षित विकल्प\" का मिथक: ये इतनी आसानी से क्यों लिखी जाती हैं?",
   [(">2 गुना", "6 या अधिक पर्चों पर डिमेंशिया का जोखिम"), (">3 गुना", "हल्की संज्ञानात्मक हानि का जोखिम"), ("5वीं", "2024 में अमेरिका में सबसे अधिक लिखी गई दवा"), ("1.55 करोड़", "2024 में अमेरिका में उपयोगकर्ता (2010 में 58 लाख)")], None,
   [("बढ़ते दुष्प्रभाव:", "संज्ञानात्मक गिरावट और डिमेंशिया, परिधीय शोथ, दुरुपयोग और निर्भरता, विदड्रॉल सिंड्रोम।"),
    ("पर्चों की शृंखला:", "सूजन को हृदय या शिरा की विफलता मान लिया जाता है और लूप डाइयूरेटिक जोड़ दी जाती है।"),
    ("ओपिओइड संकट:", "विकल्प नहीं, बल्कि ओपिओइड के असर को बढ़ाने वाला मौन साझेदार।"),
    ("कानूनी होने का अर्थ हानिरहित नहीं:", "तुर्किये में हरे पर्चे से उपयोग कम नहीं हुआ।")],
   "और अधिक नुकसान रोकने के लिए इन दवाओं का समझदारी से उपयोग करें और करवाएँ।"),
 'ja': D("ガバペンチンとガバペンチノイド", "見過ごされてきた事実", "「安全な代替薬」という神話：なぜこれほど気軽に処方されるのか",
   [("2倍超", "処方6回以上での認知症リスク"), ("3倍超", "軽度認知障害のリスク"), ("第5位", "2024年に米国で最も多く処方された薬"), ("1550万人", "2024年の米国の使用者（2010年は580万人）")], None,
   [("増える副作用：", "認知機能低下と認知症、末梢性浮腫、乱用と依存、離脱症候群。"),
    ("処方カスケード：", "浮腫が心不全や静脈不全とみなされ、ループ利尿薬が追加される。"),
    ("オピオイド危機：", "代替ではなく、オピオイドの作用を強める静かなパートナー。"),
    ("合法でも無害ではない：", "トルコのグリーン処方箋は使用を減らしていない。")],
   "これ以上の害を防ぐために、これらの薬を賢く使い、賢く使わせよう。"),
})

# i28: Do not kill older people with medicines (deprescribing)
CARDS['b15_yasli'] = ('teal', {
 'en': D("TURKISH RATIONAL DRUG USE PLATFORM", "Do not kill older people with medicines!", "Deprescribing: a clinical process",
   [("15%", "risk of a serious adverse event with 2 medicines"), ("58%", "with 5 medicines"), ("82%", "with 7 or more medicines")], None,
   [("1. Review:", "go through all current medicines."),
    ("2. Identify:", "decide which medicines should be stopped, substituted or reduced."),
    ("3. Plan:", "prepare a deprescribing regimen in partnership with the patient."),
    ("4. Follow up:", "review frequently and support the patient.")],
   "The aim is not to leave the patient without medicines, but to remove those that are unnecessary or do more harm than good."),
 'de': D("TÜRKISCHE PLATTFORM FÜR RATIONALEN ARZNEIMITTELGEBRAUCH", "Tötet ältere Menschen nicht mit Medikamenten!", "Deprescribing: ein klinischer Prozess",
   [("15 %", "Risiko eines schweren unerwünschten Ereignisses bei 2 Arzneimitteln"), ("58 %", "bei 5 Arzneimitteln"), ("82 %", "bei 7 oder mehr Arzneimitteln")], None,
   [("1. Überprüfen:", "alle aktuellen Arzneimittel durchgehen."),
    ("2. Bestimmen:", "welche Arzneimittel abgesetzt, ersetzt oder reduziert werden sollen."),
    ("3. Planen:", "ein Absetzschema gemeinsam mit dem Patienten erstellen."),
    ("4. Begleiten:", "häufig überprüfen und den Patienten unterstützen.")],
   "Ziel ist nicht, den Patienten ohne Arzneimittel zu lassen, sondern die unnötigen und die eher schädlichen als nützlichen abzusetzen."),
 'es': D("PLATAFORMA TURCA DE USO RACIONAL DE MEDICAMENTOS", "¡No maten a los mayores con medicamentos!", "Deprescripción: un proceso clínico",
   [("15 %", "riesgo de evento adverso grave con 2 medicamentos"), ("58 %", "con 5 medicamentos"), ("82 %", "con 7 o más medicamentos")], None,
   [("1. Revisar:", "repasar todos los medicamentos actuales."),
    ("2. Identificar:", "qué medicamentos deben suspenderse, sustituirse o reducirse."),
    ("3. Planificar:", "preparar una pauta de deprescripción junto con el paciente."),
    ("4. Seguir:", "revisar con frecuencia y apoyar al paciente.")],
   "El objetivo no es dejar al paciente sin medicamentos, sino retirar los innecesarios y los que hacen más daño que bien."),
 'ru': D("ТУРЕЦКАЯ ПЛАТФОРМА РАЦИОНАЛЬНОГО ПРИМЕНЕНИЯ ЛЕКАРСТВ", "Не убивайте пожилых лекарствами!", "Депрескрайбинг: клинический процесс",
   [("15 %", "риск серьёзного нежелательного явления при 2 препаратах"), ("58 %", "при 5 препаратах"), ("82 %", "при 7 и более препаратах")], None,
   [("1. Пересмотреть:", "все принимаемые сейчас препараты."),
    ("2. Определить:", "какие препараты отменить, заменить или уменьшить в дозе."),
    ("3. Спланировать:", "схему отмены вместе с пациентом."),
    ("4. Наблюдать:", "часто пересматривать и поддерживать пациента.")],
   "Цель не в том, чтобы оставить пациента без лекарств, а в том, чтобы убрать ненужные и приносящие больше вреда, чем пользы."),
 'zh': D("土耳其合理用药平台", "不要用药物害死老年人！", "精简处方（Deprescribing）：一个临床过程",
   [("15%", "使用2种药物时发生严重不良事件的风险"), ("58%", "使用5种药物时"), ("82%", "使用7种及以上药物时")], None,
   [("1. 审查：", "梳理目前使用的全部药物。"),
    ("2. 确定：", "哪些药物应当停用、替换或减量。"),
    ("3. 计划：", "与患者共同制定减药方案。"),
    ("4. 随访：", "经常复查并支持患者。")],
   "目的不是让患者无药可用，而是停掉不必要的、弊大于利的药物。"),
 'hi': D("तुर्किये तर्कसंगत दवा उपयोग मंच", "बुज़ुर्गों को दवाओं से मत मारिए!", "डीप्रिस्क्राइबिंग: एक नैदानिक प्रक्रिया",
   [("15%", "2 दवाओं पर गंभीर प्रतिकूल घटना का जोखिम"), ("58%", "5 दवाओं पर"), ("82%", "7 या अधिक दवाओं पर")], None,
   [("1. समीक्षा:", "वर्तमान की सभी दवाओं को देखें।"),
    ("2. पहचान:", "कौन सी दवाएँ बंद, बदली या कम की जानी चाहिए।"),
    ("3. योजना:", "रोगी के साथ मिलकर दवा घटाने की योजना बनाएँ।"),
    ("4. अनुवर्तन:", "बार-बार समीक्षा करें और रोगी का साथ दें।")],
   "उद्देश्य रोगी को बिना दवा के छोड़ना नहीं, बल्कि अनावश्यक और लाभ से अधिक हानि करने वाली दवाएँ हटाना है।"),
 'ja': D("トルコ合理的医薬品使用プラットフォーム", "高齢者を薬で死なせるな！", "デプレスクライビング（減薬）：臨床的なプロセス",
   [("15%", "2剤使用時の重篤な有害事象のリスク"), ("58%", "5剤使用時"), ("82%", "7剤以上使用時")], None,
   [("1. 見直す：", "現在使用しているすべての薬を確認する。"),
    ("2. 特定する：", "中止、変更、減量すべき薬を決める。"),
    ("3. 計画する：", "患者と協力して減薬計画を立てる。"),
    ("4. 経過をみる：", "頻繁に見直し、患者を支える。")],
   "目的は患者を薬なしにすることではなく、不要な薬や益より害の大きい薬をやめることである。"),
})
