from batch1 import D
CARDS = {}

# i=1: Migraine "vaccines" (EN image = twin from the English article)
CARDS['b13_migren'] = ('blue', {
 'de': D("MIGRÄNE", "Migräne-„Impfungen“: wissenschaftliche Revolution oder teure Hoffnung?", "Wie verlässlich sind die Angaben der Hersteller?",
   [("1–2 Tage", "Nettoeffekt der CGRP-Antikörper pro Monat"), ("650 $", "Kosten pro Monat"), ("7.800 $", "Kosten pro Jahr"), ("400–500 $", "pro vermiedenem Migränetag")], None,
   [("Klassische Mittel:", "Propranolol und Topiramat senken die monatlichen Migränetage um 2–3 Tage, CGRP-Antikörper um 1–2 Tage."),
    ("Markt:", "3,5 Milliarden $ pro Jahr."),
    ("Sicherheit:", "offene Fragen zu kardiovaskulären Risiken und Langzeitwirkungen."),
    ("Fazit:", "1–2 Tage Nutzen, hohe Kosten; klassische Medikamente sind wirksamer.")],
   "Migräne-„Impfungen“ sind keine Impfstoffe. Es sind monoklonale Antikörper."),
 'es': D("MIGRAÑA", "«Vacunas» contra la migraña: ¿revolución científica o esperanza cara?", "¿Qué fiabilidad tienen las afirmaciones de las compañías?",
   [("1–2 días", "efecto neto mensual de los anticuerpos anti-CGRP"), ("650 $", "coste mensual"), ("7.800 $", "coste anual"), ("400–500 $", "por cada día de migraña evitado")], None,
   [("Fármacos clásicos:", "propranolol y topiramato reducen los días de migraña al mes en 2–3 días; los anticuerpos anti-CGRP, en 1–2 días."),
    ("Mercado:", "3,5 mil millones de dólares al año."),
    ("Seguridad:", "dudas sobre los riesgos cardiovasculares y los efectos a largo plazo."),
    ("Conclusión:", "1–2 días de beneficio, coste elevado; los fármacos clásicos son más eficaces.")],
   "Las «vacunas» contra la migraña no son vacunas. Son anticuerpos monoclonales."),
 'ru': D("МИГРЕНЬ", "«Прививки» от мигрени: научная революция или дорогая надежда?", "Насколько надёжны заявления компаний?",
   [("1–2 дня", "чистый эффект антител к CGRP в месяц"), ("650 $", "стоимость в месяц"), ("7 800 $", "стоимость в год"), ("400–500 $", "за один предотвращённый день мигрени")], None,
   [("Классические препараты:", "пропранолол и топирамат сокращают число дней мигрени в месяц на 2–3 дня, антитела к CGRP на 1–2 дня."),
    ("Рынок:", "3,5 миллиарда долларов в год."),
    ("Безопасность:", "вопросы о сердечно-сосудистых рисках и отдалённых эффектах."),
    ("Итог:", "польза 1–2 дня, высокая стоимость; классические препараты эффективнее.")],
   "«Прививки» от мигрени не являются вакцинами. Это моноклональные антитела."),
 'zh': D("偏头痛", "偏头痛“疫苗”：科学革命，还是昂贵的希望？", "企业的说法有多可靠？",
   [("1–2天", "CGRP抗体每月的净效果"), ("650美元", "每月费用"), ("7,800美元", "每年费用"), ("400–500美元", "每减少一个偏头痛日的成本")], None,
   [("传统药物：", "普萘洛尔和托吡酯使每月偏头痛天数减少2–3天，CGRP抗体减少1–2天。"),
    ("市场：", "每年35亿美元。"),
    ("安全性：", "心血管风险和长期影响仍有疑问。"),
    ("结论：", "获益1–2天，费用高昂；传统药物更有效。")],
   "偏头痛“疫苗”不是疫苗，而是单克隆抗体。"),
 'hi': D("माइग्रेन", "माइग्रेन के “टीके”: वैज्ञानिक क्रांति या महंगी उम्मीद?", "कंपनियों के दावे कितने भरोसेमंद हैं?",
   [("1–2 दिन", "CGRP एंटीबॉडी का प्रति माह शुद्ध असर"), ("650 $", "मासिक खर्च"), ("7,800 $", "वार्षिक खर्च"), ("400–500 $", "माइग्रेन के हर टले दिन की लागत")], None,
   [("पारंपरिक दवाएं:", "प्रोप्रानोलोल और टोपिरामेट माइग्रेन के मासिक दिनों को 2–3 दिन घटाते हैं, CGRP एंटीबॉडी 1–2 दिन।"),
    ("बाज़ार:", "प्रति वर्ष 3.5 अरब डॉलर।"),
    ("सुरक्षा:", "हृदय और रक्तवाहिका संबंधी जोखिमों तथा दीर्घकालिक प्रभावों पर सवाल।"),
    ("निष्कर्ष:", "1–2 दिन का लाभ, ऊंची लागत; पारंपरिक दवाएं अधिक प्रभावी हैं।")],
   "माइग्रेन के “टीके” टीके नहीं हैं। ये मोनोक्लोनल एंटीबॉडी हैं।"),
 'ja': D("片頭痛", "片頭痛「ワクチン」：科学の革命か、高価な希望か", "企業の主張はどこまで信頼できるか",
   [("1–2日", "CGRP抗体の月あたり正味の効果"), ("650ドル", "月額費用"), ("7,800ドル", "年間費用"), ("400–500ドル", "片頭痛を1日減らすための費用")], None,
   [("従来薬：", "プロプラノロールとトピラマートは月間片頭痛日数を2–3日減らし、CGRP抗体は1–2日減らす。"),
    ("市場：", "年間35億ドル。"),
    ("安全性：", "心血管リスクと長期的影響に疑問が残る。"),
    ("結論：", "利益は1–2日、費用は高額。従来薬のほうが有効。")],
   "片頭痛「ワクチン」はワクチンではない。モノクローナル抗体である。"),
})

# i=2: Being a doctor in Turkey
CARDS['b13_doktor'] = ('dark', {
 'en': D("HEALTH SYSTEM", "Why is it getting harder to be a doctor in Turkey?", "The health system, the quality of training and the transformation of the profession",
   [("70–100", "patients a day in an outpatient clinic"), ("3–5 min", "per examination"), ("4000", "patients per family physician"), ("1 in 2", "doctors faced violence in the last year")], None,
   [("Inadequate training:", "the number of medical faculties has risen rapidly, many lack teaching staff, and some residents turn to YouTube to learn surgery."),
    ("Violence:", "physical and verbal, in hospitals and emergency departments."),
    ("Family medicine:", "performance pressure, workload and more than 10 bureaucratic tasks a day."),
    ("Economic pressure:", "pay is very low for the workload; young doctors go abroad.")],
   "The level of medical education is falling and young doctors are emigrating. The solution requires structural reform."),
 'de': D("GESUNDHEITSSYSTEM", "Warum wird es in der Türkei immer schwerer, Arzt zu sein?", "Gesundheitssystem, Qualität der Ausbildung und Wandel des Berufs",
   [("70–100", "Patienten pro Tag in der Ambulanz"), ("3–5 Min.", "pro Untersuchung"), ("4000", "Patienten pro Hausarzt"), ("1 von 2", "Ärzten erlebte im letzten Jahr Gewalt")], None,
   [("Unzureichende Ausbildung:", "die Zahl der medizinischen Fakultäten ist rasch gestiegen, vielen fehlt Lehrpersonal, und manche Assistenzärzte lernen Operationen über YouTube."),
    ("Gewalt:", "körperlich und verbal, in Krankenhäusern und Notaufnahmen."),
    ("Hausarztsystem:", "Leistungsdruck, Arbeitslast und mehr als 10 bürokratische Aufgaben pro Tag."),
    ("Wirtschaftlicher Druck:", "die Bezahlung ist gemessen an der Arbeitslast sehr niedrig; junge Ärzte gehen ins Ausland.")],
   "Das Niveau der medizinischen Ausbildung sinkt, junge Ärzte wandern aus. Die Lösung erfordert eine Strukturreform."),
 'es': D("SISTEMA SANITARIO", "¿Por qué es cada vez más difícil ser médico en Turquía?", "El sistema sanitario, la calidad de la formación y la transformación de la profesión",
   [("70–100", "pacientes al día en consulta externa"), ("3–5 min", "por consulta"), ("4000", "pacientes por médico de familia"), ("1 de 2", "médicos sufrió violencia en el último año")], None,
   [("Formación insuficiente:", "el número de facultades de medicina ha crecido con rapidez, en muchas falta profesorado y algunos residentes recurren a YouTube para aprender cirugía."),
    ("Violencia:", "física y verbal, en hospitales y urgencias."),
    ("Medicina de familia:", "presión por rendimiento, carga de trabajo y más de 10 tareas burocráticas al día."),
    ("Presión económica:", "los sueldos son muy bajos para la carga de trabajo; los médicos jóvenes se van al extranjero.")],
   "El nivel de la formación médica baja y los médicos jóvenes emigran. La solución exige una reforma estructural."),
 'ru': D("СИСТЕМА ЗДРАВООХРАНЕНИЯ", "Почему в Турции всё труднее быть врачом?", "Система здравоохранения, качество образования и трансформация профессии",
   [("70–100", "пациентов в день на поликлиническом приёме"), ("3–5 мин", "на один осмотр"), ("4000", "пациентов на одного семейного врача"), ("1 из 2", "врачей столкнулся с насилием за последний год")], None,
   [("Недостаточное образование:", "число медицинских факультетов быстро выросло, во многих не хватает преподавателей, а некоторые ординаторы учатся операциям по YouTube."),
    ("Насилие:", "физическое и словесное, в больницах и отделениях неотложной помощи."),
    ("Семейная медицина:", "давление показателей, нагрузка и более 10 бюрократических задач в день."),
    ("Экономическое давление:", "оплата очень низка для такой нагрузки; молодые врачи уезжают за границу.")],
   "Уровень медицинского образования падает, молодые врачи эмигрируют. Решение требует структурной реформы."),
 'zh': D("医疗体系", "在土耳其当医生为什么越来越难？", "医疗体系、教育质量与职业的转变",
   [("70–100", "门诊每天接诊患者数"), ("3–5分钟", "每次诊查时间"), ("4000", "每名家庭医生负责的患者数"), ("每2人中1人", "医生在过去一年遭遇暴力")], None,
   [("医学教育不足：", "医学院数量迅速增加，许多学院师资短缺，一些住院医师靠YouTube学习手术。"),
    ("暴力：", "身体暴力和言语暴力，发生在医院和急诊科。"),
    ("家庭医生制度：", "绩效压力、工作负担，每天10项以上行政事务。"),
    ("经济压力：", "相对于工作量，薪酬非常低；年轻医生前往国外。")],
   "医学教育水平在下降，年轻医生移居国外。解决之道在于结构性改革。"),
 'hi': D("स्वास्थ्य प्रणाली", "तुर्की में डॉक्टर होना कठिन क्यों होता जा रहा है?", "स्वास्थ्य प्रणाली, शिक्षा की गुणवत्ता और पेशे का बदलता रूप",
   [("70–100", "ओपीडी में प्रतिदिन मरीज"), ("3–5 मिनट", "प्रति जांच"), ("4000", "मरीज प्रति पारिवारिक चिकित्सक"), ("2 में से 1", "डॉक्टर ने पिछले एक वर्ष में हिंसा झेली")], None,
   [("अपर्याप्त शिक्षा:", "मेडिकल कॉलेजों की संख्या तेज़ी से बढ़ी है, कई में शिक्षकों की कमी है, और कुछ रेज़िडेंट सर्जरी सीखने के लिए YouTube का सहारा लेते हैं।"),
    ("हिंसा:", "शारीरिक और मौखिक, अस्पतालों और आपातकालीन विभागों में।"),
    ("पारिवारिक चिकित्सा:", "प्रदर्शन का दबाव, काम का बोझ और प्रतिदिन 10 से अधिक प्रशासनिक काम।"),
    ("आर्थिक दबाव:", "काम के बोझ की तुलना में वेतन बहुत कम है; युवा डॉक्टर विदेश जा रहे हैं।")],
   "चिकित्सा शिक्षा का स्तर गिर रहा है और युवा डॉक्टर विदेश जा रहे हैं। समाधान के लिए संरचनात्मक सुधार ज़रूरी है।"),
 'ja': D("医療制度", "トルコで医師であることはなぜ難しくなっているのか", "医療制度、教育の質、そして職業の変容",
   [("70–100人", "外来での1日の患者数"), ("3–5分", "1回の診察時間"), ("4000人", "家庭医1人あたりの患者数"), ("2人に1人", "の医師が過去1年に暴力を経験")], None,
   [("不十分な医学教育：", "医学部の数が急増し、多くで教員が不足。手術を学ぶためにYouTubeに頼る研修医もいる。"),
    ("暴力：", "身体的暴力と言葉の暴力が、病院や救急部門で起きている。"),
    ("家庭医制度：", "成果への圧力、業務負担、1日10件以上の事務作業。"),
    ("経済的圧力：", "仕事量に対して報酬は非常に低く、若い医師は国外へ出ていく。")],
   "医学教育の水準は下がり、若い医師は国外へ移住している。解決には構造改革が必要である。"),
})

# i=3: Semaglutide: the 3-dollar opportunity
CARDS['b13_sema'] = ('teal', {
 'en': D("OZEMPIC / WEGOVY", "Semaglutide: the 3-dollar opportunity", "What Ozempic and Wegovy prices mean for global health",
   [("~$3", "estimated production cost of the injection per month"), ("~$200", "price in the USA"), ("~£120", "price in the United Kingdom"), ("1 billion+", "people living with obesity")], None,
   [("End of patents:", "in 2026 key semaglutide patents are expected to expire in Brazil, China, India, South Africa, Turkey, Mexico and Canada. This opens the way for generics."),
    ("No patent filed:", "in more than 150 countries, most of them in Africa and low-income regions."),
    ("Global effect:", "treatment of obesity and diabetes could expand greatly."),
    ("Turkey:", "access to these drugs may increase.")],
   "If prices fall, the lives of millions of people may change.",
   "Source: analysis by Andrew Hill and colleagues (University of Liverpool), reported in The Guardian"),
 'de': D("OZEMPIC / WEGOVY", "Semaglutid: die 3-Dollar-Chance", "Was die Preise von Ozempic und Wegovy für die globale Gesundheit bedeuten",
   [("~3 $", "geschätzte Herstellungskosten der Injektion pro Monat"), ("~200 $", "Preis in den USA"), ("~120 £", "Preis im Vereinigten Königreich"), ("1 Mrd.+", "Menschen leben mit Adipositas")], None,
   [("Patentende:", "2026 laufen zentrale Semaglutid-Patente voraussichtlich in Brasilien, China, Indien, Südafrika, der Türkei, Mexiko und Kanada aus. Das öffnet den Weg für Generika."),
    ("Kein Patent angemeldet:", "in mehr als 150 Ländern, die meisten in Afrika und in einkommensschwachen Regionen."),
    ("Globale Wirkung:", "die Behandlung von Adipositas und Diabetes könnte sich stark ausweiten."),
    ("Türkei:", "der Zugang zu diesen Medikamenten kann zunehmen.")],
   "Wenn die Preise fallen, kann sich das Leben von Millionen Menschen ändern.",
   "Quelle: Analyse von Andrew Hill und Kollegen (Universität Liverpool), berichtet im Guardian"),
 'es': D("OZEMPIC / WEGOVY", "Semaglutida: la oportunidad de 3 dólares", "Qué significan los precios de Ozempic y Wegovy para la salud mundial",
   [("~3 $", "coste estimado de producción de la inyección al mes"), ("~200 $", "precio en EE. UU."), ("~120 £", "precio en el Reino Unido"), ("+1000 M", "de personas viven con obesidad")], None,
   [("Fin de las patentes:", "en 2026 se espera que expiren patentes clave de semaglutida en Brasil, China, India, Sudáfrica, Turquía, México y Canadá. Esto abre el camino a los genéricos."),
    ("Sin solicitud de patente:", "en más de 150 países, la mayoría en África y en regiones de ingresos bajos."),
    ("Efecto mundial:", "el tratamiento de la obesidad y la diabetes podría ampliarse mucho."),
    ("Turquía:", "el acceso a estos medicamentos puede aumentar.")],
   "Si los precios bajan, la vida de millones de personas puede cambiar.",
   "Fuente: análisis de Andrew Hill y colaboradores (Universidad de Liverpool), publicado en The Guardian"),
 'ru': D("OZEMPIC / WEGOVY", "Семаглутид: возможность за 3 доллара", "Что цены на Ozempic и Wegovy означают для мирового здравоохранения",
   [("~3 $", "оценка себестоимости инъекционной формы в месяц"), ("~200 $", "цена в США"), ("~120 £", "цена в Великобритании"), ("1 млрд+", "человек живут с ожирением")], None,
   [("Конец патентов:", "в 2026 году ключевые патенты на семаглутид, как ожидается, истекут в Бразилии, Китае, Индии, ЮАР, Турции, Мексике и Канаде. Это открывает путь дженерикам."),
    ("Патент не заявлен:", "более чем в 150 странах, большинство из них в Африке и регионах с низким доходом."),
    ("Мировой эффект:", "лечение ожирения и диабета может значительно расшириться."),
    ("Турция:", "доступность этих препаратов может вырасти.")],
   "Если цены упадут, жизнь миллионов людей может измениться.",
   "Источник: анализ Эндрю Хилла и коллег (Ливерпульский университет), опубликованный в The Guardian"),
 'zh': D("OZEMPIC / WEGOVY", "司美格鲁肽：3美元的机会", "Ozempic和Wegovy的价格对全球健康意味着什么",
   [("约3美元", "注射剂每月估算生产成本"), ("约200美元", "美国售价"), ("约120英镑", "英国售价"), ("10亿以上", "肥胖人口")], None,
   [("专利到期：", "2026年，司美格鲁肽的核心专利预计将在巴西、中国、印度、南非、土耳其、墨西哥和加拿大到期，为仿制药打开大门。"),
    ("未申请专利：", "超过150个国家，多数位于非洲和低收入地区。"),
    ("全球影响：", "肥胖和糖尿病的治疗可能大幅扩展。"),
    ("土耳其：", "这类药物的可及性可能提高。")],
   "如果价格下降，数百万人的生活可能改变。",
   "来源：Andrew Hill及其同事（利物浦大学）的分析，《卫报》报道"),
 'hi': D("OZEMPIC / WEGOVY", "सेमाग्लूटाइड: 3 डॉलर का अवसर", "Ozempic और Wegovy की कीमतों का वैश्विक स्वास्थ्य के लिए अर्थ",
   [("~3 $", "इंजेक्शन की अनुमानित मासिक उत्पादन लागत"), ("~200 $", "अमेरिका में कीमत"), ("~120 £", "ब्रिटेन में कीमत"), ("1 अरब+", "लोग मोटापे के साथ जी रहे हैं")], None,
   [("पेटेंट का अंत:", "2026 में सेमाग्लूटाइड के प्रमुख पेटेंट ब्राज़ील, चीन, भारत, दक्षिण अफ्रीका, तुर्की, मेक्सिको और कनाडा में समाप्त होने की उम्मीद है। इससे जेनेरिक दवाओं का रास्ता खुलता है।"),
    ("पेटेंट आवेदन नहीं:", "150 से अधिक देशों में, जिनमें अधिकांश अफ्रीका और कम आय वाले क्षेत्रों में हैं।"),
    ("वैश्विक असर:", "मोटापे और मधुमेह का उपचार बहुत बढ़ सकता है।"),
    ("तुर्की:", "इन दवाओं तक पहुंच बढ़ सकती है।")],
   "अगर कीमतें घटती हैं, तो लाखों लोगों का जीवन बदल सकता है।",
   "स्रोत: एंड्रयू हिल और सहयोगियों (लिवरपूल विश्वविद्यालय) का विश्लेषण, The Guardian में प्रकाशित"),
 'ja': D("OZEMPIC / WEGOVY", "セマグルチド：3ドルのチャンス", "OzempicとWegovyの価格が世界の健康に持つ意味",
   [("約3ドル", "注射剤の月あたり推定製造コスト"), ("約200ドル", "米国での価格"), ("約120ポンド", "英国での価格"), ("10億人超", "肥満とともに生きる人々")], None,
   [("特許の終了：", "2026年、セマグルチドの基本特許がブラジル、中国、インド、南アフリカ、トルコ、メキシコ、カナダで満了する見込み。ジェネリックへの道が開かれる。"),
    ("特許出願なし：", "150か国以上。その多くはアフリカと低所得地域にある。"),
    ("世界への影響：", "肥満と糖尿病の治療が大きく広がる可能性がある。"),
    ("トルコ：", "これらの薬へのアクセスが高まる可能性がある。")],
   "価格が下がれば、何百万人もの人生が変わるかもしれない。",
   "出典：Andrew Hillら（リバプール大学）の分析、The Guardian紙の報道"),
})

# i=4: Antidepressants in pregnancy
CARDS['b13_gebe'] = ('burg', {
 'en': D("PREGNANCY", "Antidepressants in pregnancy: real risks and exaggerations", "Scientific data and industry realities",
   [("7 → 10", "preterm births per 100 pregnancies: normally vs with antidepressants"), ("5 times", "higher risk of neonatal adaptation syndrome"), ("3 in 1000", "births: pulmonary hypertension of the newborn"), ("20–30%", "higher risk of postpartum bleeding")], None,
   [("Data-hiding scandal:", "negative results were not published and misleading reports were submitted to the FDA."),
    ("SSRIs and autism:", "a risk to neurodevelopment is under debate."),
    ("Courts and penalties:", "a 3 billion dollar settlement.")],
   "Antidepressant use in pregnancy is not entirely risk-free. An individual risk-benefit assessment is needed."),
 'de': D("SCHWANGERSCHAFT", "Antidepressiva in der Schwangerschaft: echte Risiken und Übertreibungen", "Wissenschaftliche Daten und die Realität der Industrie",
   [("7 → 10", "Frühgeburten je 100 Schwangerschaften: normal vs. mit Antidepressiva"), ("5-fach", "höheres Risiko für das neonatale Anpassungssyndrom"), ("3 von 1000", "Geburten: pulmonale Hypertonie des Neugeborenen"), ("20–30 %", "höheres Risiko für postpartale Blutungen")], None,
   [("Skandal um verborgene Daten:", "negative Ergebnisse wurden nicht veröffentlicht, der FDA wurden irreführende Berichte vorgelegt."),
    ("SSRI und Autismus:", "ein Risiko für die neurologische Entwicklung wird diskutiert."),
    ("Gerichte und Strafen:", "ein Vergleich über 3 Milliarden Dollar.")],
   "Die Einnahme von Antidepressiva in der Schwangerschaft ist nicht völlig risikofrei. Nötig ist eine individuelle Nutzen-Risiko-Abwägung."),
 'es': D("EMBARAZO", "Antidepresivos en el embarazo: riesgos reales y exageraciones", "Datos científicos y realidades de la industria",
   [("7 → 10", "partos prematuros por 100 embarazos: normal frente a antidepresivos"), ("5 veces", "más riesgo de síndrome de adaptación neonatal"), ("3 de 1000", "nacimientos: hipertensión pulmonar del recién nacido"), ("20–30 %", "más riesgo de hemorragia posparto")], None,
   [("Escándalo de ocultación de datos:", "no se publicaron resultados negativos y se presentaron informes engañosos a la FDA."),
    ("ISRS y autismo:", "se debate un riesgo para el neurodesarrollo."),
    ("Tribunales y sanciones:", "un acuerdo de 3 mil millones de dólares.")],
   "El uso de antidepresivos en el embarazo no está totalmente exento de riesgo. Hace falta una valoración individual de riesgo y beneficio."),
 'ru': D("БЕРЕМЕННОСТЬ", "Антидепрессанты при беременности: реальные риски и преувеличения", "Научные данные и реалии индустрии",
   [("7 → 10", "преждевременных родов на 100 беременностей: в норме и при антидепрессантах"), ("в 5 раз", "выше риск неонатального синдрома адаптации"), ("3 на 1000", "родов: лёгочная гипертензия новорождённых"), ("20–30 %", "выше риск послеродового кровотечения")], None,
   [("Скандал с сокрытием данных:", "отрицательные результаты не публиковались, в FDA подавались вводящие в заблуждение отчёты."),
    ("СИОЗС и аутизм:", "обсуждается риск для развития нервной системы."),
    ("Суды и штрафы:", "мировое соглашение на 3 миллиарда долларов.")],
   "Применение антидепрессантов при беременности не является полностью безопасным. Нужна индивидуальная оценка соотношения риска и пользы."),
 'zh': D("妊娠", "妊娠期抗抑郁药：真实风险与夸大之处", "科学数据与制药业的现实",
   [("7 → 10", "每100例妊娠的早产数：正常情况与使用抗抑郁药"), ("5倍", "新生儿适应综合征风险升高"), ("3/1000", "每1000例分娩：新生儿肺动脉高压"), ("20–30%", "产后出血风险升高")], None,
   [("隐瞒数据丑闻：", "阴性结果未被发表，并向FDA提交了误导性报告。"),
    ("SSRI与孤独症：", "对神经发育的风险尚在争论中。"),
    ("法庭与处罚：", "30亿美元和解。")],
   "妊娠期使用抗抑郁药并非完全没有风险。应进行个体化的风险获益评估。"),
 'hi': D("गर्भावस्था", "गर्भावस्था में अवसादरोधी दवाएं: वास्तविक जोखिम और अतिशयोक्ति", "वैज्ञानिक आंकड़े और उद्योग की सच्चाइयां",
   [("7 → 10", "प्रति 100 गर्भ में समय पूर्व प्रसव: सामान्यतः और दवा के साथ"), ("5 गुना", "नवजात अनुकूलन सिंड्रोम का अधिक जोखिम"), ("1000 में 3", "प्रसव: नवजात में पल्मोनरी हाइपरटेंशन"), ("20–30%", "प्रसव के बाद रक्तस्राव का अधिक जोखिम")], None,
   [("आंकड़े छिपाने का घोटाला:", "नकारात्मक परिणाम प्रकाशित नहीं किए गए और FDA को भ्रामक रिपोर्टें दी गईं।"),
    ("SSRI और ऑटिज़्म:", "तंत्रिका विकास पर जोखिम को लेकर बहस जारी है।"),
    ("अदालत और दंड:", "3 अरब डॉलर का समझौता।")],
   "गर्भावस्था में अवसादरोधी दवाओं का उपयोग पूरी तरह जोखिम रहित नहीं है। हर मरीज के लिए जोखिम और लाभ का आकलन ज़रूरी है।"),
 'ja': D("妊娠", "妊娠中の抗うつ薬：本当のリスクと誇張", "科学的データと製薬業界の現実",
   [("7 → 10", "妊娠100件あたりの早産：通常と抗うつ薬使用時"), ("5倍", "新生児不適応症候群のリスク上昇"), ("1000件に3件", "出生あたりの新生児肺高血圧症"), ("20–30%", "分娩後出血のリスク上昇")], None,
   [("データ隠蔽スキャンダル：", "否定的な結果は公表されず、FDAには誤解を招く報告が提出された。"),
    ("SSRIと自閉症：", "神経発達へのリスクが議論されている。"),
    ("裁判と制裁：", "30億ドルの和解。")],
   "妊娠中の抗うつ薬の使用は完全に無リスクではない。個別のリスクとベネフィットの評価が必要である。"),
})

# i=5: Licensed but low clinical value drugs
CARDS['b13_dusuk'] = ('navy', {
 'en': D("DRUG REGULATION", "Licensed but low clinical value drugs", "Health loss, economic burden and systemic problems", None, None,
   [("What they are:", "licensed drugs whose clinical effect is small while their cost and budget impact are high."),
    ("Accelerated approval:", "approval based on a surrogate endpoint. For aducanumab (Aduhelm), amyloid plaque reduction meant a benefit that was expected but not proven."),
    ("Failed confirmation:", "Makena was withdrawn by the FDA in 2023 after confirmatory trials showed no benefit."),
    ("Statistics versus the clinic:", "in oncology a small gain in progression-free survival can be enough for approval without a difference in overall survival."),
    ("Hidden data:", "publication bias, selective reporting, unpublished negative trials and ghostwriting.")],
   "The problem is not only pharmacology. It is also one of regulation, ethics and health policy."),
 'de': D("ARZNEIMITTELREGULIERUNG", "Zugelassen, aber von geringem klinischem Wert", "Gesundheitsverlust, wirtschaftliche Last und systemische Probleme", None, None,
   [("Worum es geht:", "zugelassene Arzneimittel mit geringer klinischer Wirkung, aber hohen Kosten und hoher Budgetbelastung."),
    ("Beschleunigte Zulassung:", "Zulassung anhand eines Surrogatendpunkts. Bei Aducanumab (Aduhelm) bedeutete die Abnahme der Amyloid-Plaques einen erwarteten, aber nicht belegten Nutzen."),
    ("Gescheiterte Bestätigung:", "Makena wurde 2023 von der FDA vom Markt genommen, nachdem Bestätigungsstudien keinen Nutzen zeigten."),
    ("Statistik gegen Klinik:", "in der Onkologie kann ein kleiner Gewinn beim progressionsfreien Überleben ohne Unterschied im Gesamtüberleben für die Zulassung genügen."),
    ("Verborgene Daten:", "Publikationsbias, selektive Berichterstattung, unveröffentlichte negative Studien und Ghostwriting.")],
   "Das Problem ist nicht nur Pharmakologie. Es geht auch um Regulierung, Ethik und Gesundheitspolitik."),
 'es': D("REGULACIÓN DE MEDICAMENTOS", "Medicamentos autorizados pero de bajo valor clínico", "Pérdida de salud, carga económica y problemas sistémicos", None, None,
   [("Qué son:", "medicamentos autorizados con un efecto clínico pequeño y un coste e impacto presupuestario elevados."),
    ("Aprobación acelerada:", "autorización basada en una variable subrogada. Con aducanumab (Aduhelm), la reducción de placas de amiloide suponía un beneficio esperado pero no demostrado."),
    ("Confirmación fallida:", "la FDA retiró Makena en 2023 después de que los ensayos confirmatorios no mostraran beneficio."),
    ("Estadística frente a clínica:", "en oncología, una pequeña mejora de la supervivencia libre de progresión puede bastar para la autorización sin diferencia en la supervivencia global."),
    ("Datos ocultos:", "sesgo de publicación, comunicación selectiva, ensayos negativos sin publicar y autoría fantasma.")],
   "El problema no es solo de farmacología. También es de regulación, ética y política sanitaria."),
 'ru': D("РЕГУЛИРОВАНИЕ ЛЕКАРСТВ", "Зарегистрированные препараты с низкой клинической ценностью", "Потери для здоровья, экономическое бремя и системные проблемы", None, None,
   [("Что это такое:", "зарегистрированные препараты с небольшим клиническим эффектом при высокой стоимости и нагрузке на бюджет."),
    ("Ускоренное одобрение:", "регистрация по суррогатной конечной точке. Для адуканумаба (Aduhelm) уменьшение амилоидных бляшек означало ожидаемую, но не доказанную пользу."),
    ("Неудачное подтверждение:", "в 2023 году FDA отозвало Makena, когда подтверждающие исследования не показали пользы."),
    ("Статистика и клиника:", "в онкологии небольшой прирост выживаемости без прогрессирования может быть достаточен для регистрации без разницы в общей выживаемости."),
    ("Скрытые данные:", "публикационное смещение, выборочное представление результатов, неопубликованные отрицательные исследования и гострайтинг.")],
   "Проблема не только в фармакологии. Это также вопрос регулирования, этики и политики здравоохранения."),
 'zh': D("药品监管", "已获批准但临床价值低的药物", "健康损失、经济负担与系统性问题", None, None,
   [("这是什么：", "已获批准的药物，临床效果很小，而成本和预算影响很高。"),
    ("加速批准：", "依据替代终点获批。以阿杜那单抗（Aduhelm）为例，淀粉样斑块减少所代表的获益是“预期的但未经证实的”。"),
    ("验证失败：", "验证性试验未显示获益后，FDA于2023年撤销了Makena的批准。"),
    ("统计学与临床：", "在肿瘤学中，无进展生存期的小幅延长即使总生存期没有差异，也可能足以获批。"),
    ("被隐瞒的数据：", "发表偏倚、选择性报告、未发表的阴性试验和代笔写作。")],
   "问题不只是药理学，也是监管、伦理和卫生政策的问题。"),
 'hi': D("दवा विनियमन", "स्वीकृत, पर कम नैदानिक मूल्य वाली दवाएं", "स्वास्थ्य की हानि, आर्थिक बोझ और व्यवस्थागत समस्याएं", None, None,
   [("ये क्या हैं:", "स्वीकृत दवाएं जिनका नैदानिक असर कम है, जबकि लागत और बजट पर बोझ अधिक है।"),
    ("त्वरित स्वीकृति:", "सरोगेट एंडपॉइंट के आधार पर मंज़ूरी। एडुकानुमैब (Aduhelm) में एमिलॉइड प्लाक की कमी का अर्थ ऐसा लाभ था जो अपेक्षित था पर प्रमाणित नहीं।"),
    ("विफल पुष्टि:", "पुष्टिकारक परीक्षणों में लाभ न दिखने पर FDA ने 2023 में Makena की स्वीकृति वापस ले ली।"),
    ("सांख्यिकी बनाम क्लिनिक:", "ऑन्कोलॉजी में प्रोग्रेशन-फ्री सर्वाइवल में थोड़ी बढ़त, समग्र उत्तरजीविता में अंतर के बिना भी, स्वीकृति के लिए काफी हो सकती है।"),
    ("छिपाए गए आंकड़े:", "प्रकाशन पूर्वाग्रह, चुनिंदा रिपोर्टिंग, अप्रकाशित नकारात्मक परीक्षण और घोस्टराइटिंग।")],
   "समस्या केवल औषध विज्ञान की नहीं है। यह विनियमन, नैतिकता और स्वास्थ्य नीति की भी है।"),
 'ja': D("医薬品規制", "承認されているが臨床的価値の低い薬", "健康の損失、経済的負担、そして制度的な問題", None, None,
   [("どのような薬か：", "承認済みだが臨床効果は小さく、費用と予算への影響は大きい薬。"),
    ("迅速承認：", "代替エンドポイントに基づく承認。アデュカヌマブ（Aduhelm）では、アミロイド斑の減少が意味する利益は「期待されるが証明されていない」ものだった。"),
    ("検証の失敗：", "検証試験で利益が示されず、FDAは2023年にMakenaの承認を取り消した。"),
    ("統計と臨床：", "腫瘍学では、全生存期間に差がなくても、無増悪生存期間のわずかな延長で承認に足りることがある。"),
    ("隠されたデータ：", "出版バイアス、選択的報告、公表されない否定的試験、ゴーストライティング。")],
   "問題は薬理学だけではない。規制、倫理、医療政策の問題でもある。"),
})

# i=6: Lecanemab
CARDS['b13_lecan'] = ('purple', {
 'en': D("ALZHEIMER'S DISEASE", "Lecanemab: the hope merchants' useless drug", "Statistically effective, clinically ineffective",
   [("0.45", "point difference on CDR-SB versus placebo at 18 months"), ("27%", "relative slowing (CLARITY-AD)"), ("12–13%", "ARIA-E on brain imaging"), ("~$40,000", "total cost per year")], None,
   [("High cost, empty promises:", "the US list price is about $26,500 a year; with infusion, MRI monitoring and neurology follow-up the total is around $40,000."),
    ("The clinical reality:", "the disease keeps progressing. The drug does not stop it and does not reverse it."),
    ("Safety:", "ARIA means brain oedema or microbleeds, so regular MRI monitoring is required."),
    ("Amyloid:", "lowering amyloid does not always mean clinical improvement.")],
   "Is lecanemab effective for Alzheimer's? Progression slows very slightly, with little benefit for the patient."),
 'de': D("ALZHEIMER-KRANKHEIT", "Lecanemab: das nutzlose Medikament der Hoffnungshändler", "Statistisch wirksam, klinisch unwirksam",
   [("0,45", "Punkte Unterschied im CDR-SB gegenüber Placebo nach 18 Monaten"), ("27 %", "relative Verlangsamung (CLARITY-AD)"), ("12–13 %", "ARIA-E in der Bildgebung"), ("~40.000 $", "Gesamtkosten pro Jahr")], None,
   [("Hohe Kosten, leere Versprechen:", "der US-Listenpreis liegt bei etwa 26.500 $ pro Jahr; mit Infusion, MRT-Kontrollen und neurologischer Betreuung sind es rund 40.000 $."),
    ("Die klinische Realität:", "die Krankheit schreitet weiter fort. Das Medikament stoppt sie nicht und kehrt sie nicht um."),
    ("Sicherheit:", "ARIA bedeutet Hirnödem oder Mikroblutungen, deshalb sind regelmäßige MRT-Kontrollen nötig."),
    ("Amyloid:", "weniger Amyloid bedeutet nicht immer eine klinische Besserung.")],
   "Wirkt Lecanemab bei Alzheimer? Das Fortschreiten verlangsamt sich nur minimal, mit wenig Nutzen für den Patienten."),
 'es': D("ENFERMEDAD DE ALZHEIMER", "Lecanemab: el fármaco inútil de los mercaderes de esperanza", "Estadísticamente eficaz, clínicamente ineficaz",
   [("0,45", "puntos de diferencia en CDR-SB frente a placebo a 18 meses"), ("27 %", "enlentecimiento relativo (CLARITY-AD)"), ("12–13 %", "ARIA-E en neuroimagen"), ("~40.000 $", "coste total al año")], None,
   [("Coste alto, promesas vacías:", "el precio de lista en EE. UU. es de unos 26.500 $ al año; con infusión, controles por RM y seguimiento neurológico el total ronda los 40.000 $."),
    ("La realidad clínica:", "la enfermedad sigue avanzando. El fármaco no la detiene ni la revierte."),
    ("Seguridad:", "ARIA significa edema cerebral o microhemorragias, por lo que se requiere control periódico por RM."),
    ("Amiloide:", "reducir el amiloide no siempre significa mejoría clínica.")],
   "¿Es eficaz lecanemab en el alzhéimer? La progresión se frena muy poco, con escaso beneficio para el paciente."),
 'ru': D("БОЛЕЗНЬ АЛЬЦГЕЙМЕРА", "Леканемаб: бесполезное лекарство торговцев надеждой", "Статистически эффективен, клинически неэффективен",
   [("0,45", "балла разницы по CDR-SB с плацебо за 18 месяцев"), ("27 %", "относительное замедление (CLARITY-AD)"), ("12–13 %", "ARIA-E при нейровизуализации"), ("~40 000 $", "общая стоимость в год")], None,
   [("Высокая цена, пустые обещания:", "прейскурантная цена в США около 26 500 $ в год; с инфузиями, МРТ-контролем и наблюдением невролога выходит около 40 000 $."),
    ("Клиническая реальность:", "болезнь продолжает прогрессировать. Препарат не останавливает её и не обращает вспять."),
    ("Безопасность:", "ARIA означает отёк мозга или микрокровоизлияния, поэтому нужен регулярный МРТ-контроль."),
    ("Амилоид:", "снижение амилоида не всегда означает клиническое улучшение.")],
   "Эффективен ли леканемаб при болезни Альцгеймера? Прогрессирование замедляется совсем немного, пользы для пациента мало."),
 'zh': D("阿尔茨海默病", "仑卡奈单抗：希望贩子的无用之药", "统计学上有效，临床上无效",
   [("0.45", "分：18个月时CDR-SB与安慰剂的差异"), ("27%", "相对减缓（CLARITY-AD）"), ("12–13%", "影像学ARIA-E发生率"), ("约4万美元", "每年总费用")], None,
   [("高成本，空承诺：", "美国标价约为每年26,500美元；加上输注、MRI监测和神经科随访，总费用约为40,000美元。"),
    ("临床现实：", "疾病仍在继续进展。药物既不能阻止，也不能逆转。"),
    ("安全性：", "ARIA指脑水肿或微出血，因此需要定期MRI监测。"),
    ("淀粉样蛋白：", "淀粉样蛋白减少并不总是意味着临床改善。")],
   "仑卡奈单抗对阿尔茨海默病有效吗？进展速度只略微减慢，对患者没有多少益处。"),
 'hi': D("अल्ज़ाइमर रोग", "लेकानेमैब: उम्मीद के सौदागरों की बेकार दवा", "सांख्यिकीय रूप से प्रभावी, नैदानिक रूप से अप्रभावी",
   [("0.45", "अंक का अंतर: 18 माह में CDR-SB पर प्लेसीबो से"), ("27%", "सापेक्ष धीमापन (CLARITY-AD)"), ("12–13%", "इमेजिंग में ARIA-E"), ("~40,000 $", "प्रति वर्ष कुल लागत")], None,
   [("ऊंची लागत, खोखले वादे:", "अमेरिका में सूची मूल्य लगभग 26,500 $ प्रति वर्ष है; इन्फ्यूज़न, MRI निगरानी और न्यूरोलॉजी फॉलो-अप जोड़ने पर कुल लगभग 40,000 $।"),
    ("नैदानिक सच्चाई:", "रोग बढ़ता रहता है। दवा उसे न रोकती है, न पलटती है।"),
    ("सुरक्षा:", "ARIA का अर्थ है मस्तिष्क में सूजन या सूक्ष्म रक्तस्राव, इसलिए नियमित MRI निगरानी ज़रूरी है।"),
    ("एमिलॉइड:", "एमिलॉइड का घटना हमेशा नैदानिक सुधार नहीं होता।")],
   "क्या लेकानेमैब अल्ज़ाइमर में प्रभावी है? रोग की गति बहुत थोड़ी धीमी होती है, मरीज को खास लाभ नहीं मिलता।"),
 'ja': D("アルツハイマー病", "レカネマブ：希望を売る商人たちの役に立たない薬", "統計的には有効、臨床的には無効",
   [("0.45", "点：18か月時点のCDR-SBでのプラセボとの差"), ("27%", "相対的な進行抑制（CLARITY-AD）"), ("12–13%", "画像上のARIA-E"), ("約4万ドル", "年間の総費用")], None,
   [("高い費用、空虚な約束：", "米国の定価は年間約26,500ドル。点滴、MRIによる監視、神経内科の経過観察を加えると総額は約40,000ドルになる。"),
    ("臨床の現実：", "病気は進行し続ける。薬は進行を止めず、元に戻すこともない。"),
    ("安全性：", "ARIAは脳浮腫または微小出血を意味し、定期的なMRI監視が必要となる。"),
    ("アミロイド：", "アミロイドの減少が必ずしも臨床的改善を意味するわけではない。")],
   "レカネマブはアルツハイマー病に有効か。進行はごくわずかに遅くなるだけで、患者への利益は乏しい。"),
})
