from batch1 import D
CARDS = {}

# 82 - US bill to ban prescription drug advertising
CARDS['b21_adban'] = ('navy', {
 'en': D("UNITED STATES", "Will drug advertising be banned in the USA?", "Senators Sanders and King introduced a bill to ban prescription drug advertising",
   [("$5 billion+", "spent by the drug industry on TV advertising last year"), ("30%+", "of advertising time on the major networks' evening news"), ("1 in 4", "Americans cannot afford the medicine their doctor prescribes")], None,
   [("The bill:", "the End Prescription Drug Ads Now Act would ban these ads on television, radio, print, digital platforms and social media."),
    ("An exception in the world:", "apart from New Zealand, the USA is the only country where drug companies may legally advertise on television."),
    ("Misleading:", "studies showed that more than half of prescription drug ads are misleading or false."),
    ("Prices:", "Ozempic costs about $1,000 a month in the USA and only $59 in Germany.")],
   "America has finally woken up!"),
 'de': D("USA", "Wird Arzneimittelwerbung in den USA verboten?", "Die Senatoren Sanders und King haben einen Gesetzentwurf zum Verbot der Werbung für verschreibungspflichtige Arzneimittel eingebracht",
   [("5 Mrd. $+", "gab die Pharmaindustrie im letzten Jahr für Fernsehwerbung aus"), ("30 %+", "der Werbezeit in den Abendnachrichten der großen Sender"), ("1 von 4", "Amerikanern kann sich das verordnete Medikament nicht leisten")], None,
   [("Der Entwurf:", "der End Prescription Drug Ads Now Act würde diese Werbung in Fernsehen, Radio, Printmedien, auf digitalen Plattformen und in sozialen Medien verbieten."),
    ("Eine Ausnahme weltweit:", "außer Neuseeland sind die USA das einzige Land, in dem Pharmafirmen legal im Fernsehen werben dürfen."),
    ("Irreführend:", "Studien zeigten, dass mehr als die Hälfte dieser Werbung irreführend oder falsch ist."),
    ("Preise:", "Ozempic kostet in den USA etwa 1.000 $ pro Monat, in Deutschland nur 59 $.")],
   "Amerika ist endlich aufgewacht!"),
 'es': D("ESTADOS UNIDOS", "¿Se prohibirá la publicidad de medicamentos en EE. UU.?", "Los senadores Sanders y King presentaron un proyecto de ley para prohibir la publicidad de medicamentos de venta con receta",
   [("5.000 mill. $+", "gastó la industria farmacéutica en anuncios de televisión el año pasado"), ("30 %+", "del tiempo publicitario en los informativos nocturnos de las grandes cadenas"), ("1 de cada 4", "estadounidenses no puede pagar el medicamento que le receta su médico")], None,
   [("El proyecto:", "la End Prescription Drug Ads Now Act prohibiría estos anuncios en televisión, radio, prensa, plataformas digitales y redes sociales."),
    ("Una excepción mundial:", "salvo Nueva Zelanda, EE. UU. es el único país donde las farmacéuticas pueden anunciarse legalmente en televisión."),
    ("Engañosa:", "los estudios mostraron que más de la mitad de estos anuncios son engañosos o falsos."),
    ("Precios:", "Ozempic cuesta unos 1.000 $ al mes en EE. UU. y solo 59 $ en Alemania.")],
   "¡Estados Unidos por fin ha despertado!"),
 'ru': D("США", "Запретят ли в США рекламу лекарств?", "Сенаторы Сандерс и Кинг внесли законопроект о запрете рекламы рецептурных лекарств",
   [("5 млрд $+", "потратила фарминдустрия на телерекламу в прошлом году"), ("30 %+", "рекламного времени в вечерних новостях крупных телесетей"), ("1 из 4", "американцев не может оплатить лекарство, назначенное врачом")], None,
   [("Законопроект:", "End Prescription Drug Ads Now Act запретит такую рекламу на телевидении, радио, в печати, на цифровых платформах и в социальных сетях."),
    ("Исключение в мире:", "кроме Новой Зеландии, США остаются единственной страной, где фармкомпании могут законно рекламировать лекарства по телевидению."),
    ("Вводит в заблуждение:", "исследования показали, что более половины такой рекламы вводит в заблуждение или неверна."),
    ("Цены:", "Ozempic стоит в США около 1000 $ в месяц, а в Германии всего 59 $.")],
   "Америка наконец проснулась!"),
 'zh': D("美国", "美国会禁止药品广告吗？", "参议员桑德斯和金提出法案，禁止处方药广告",
   [("50亿美元以上", "制药业去年用于电视广告的支出"), ("30%以上", "大型电视网晚间新闻广告时间中的占比"), ("四分之一", "的美国人负担不起医生开的药")], None,
   [("法案内容：", "《End Prescription Drug Ads Now Act》将禁止在电视、广播、印刷品、数字平台和社交媒体上投放此类广告。"),
    ("世界上的例外：", "除新西兰外，美国是唯一允许制药公司在电视上合法做药品广告的国家。"),
    ("具有误导性：", "研究表明，半数以上的处方药广告具有误导性或不属实。"),
    ("价格：", "Ozempic在美国每月约1,000美元，在德国仅59美元。")],
   "美国终于醒了！"),
 'hi': D("संयुक्त राज्य अमेरिका", "क्या अमेरिका में दवाओं के विज्ञापन पर रोक लगेगी?", "सीनेटर सैंडर्स और किंग ने प्रिस्क्रिप्शन दवाओं के विज्ञापन पर रोक के लिए विधेयक पेश किया",
   [("5 अरब डॉलर+", "दवा उद्योग ने पिछले वर्ष टीवी विज्ञापनों पर खर्च किए"), ("30%+", "बड़े नेटवर्कों के शाम के समाचारों के विज्ञापन समय का हिस्सा"), ("4 में से 1", "अमेरिकी डॉक्टर की लिखी दवा का खर्च नहीं उठा सकता")], None,
   [("विधेयक:", "End Prescription Drug Ads Now Act टीवी, रेडियो, प्रिंट, डिजिटल प्लेटफ़ॉर्म और सोशल मीडिया पर ऐसे विज्ञापनों पर रोक लगाएगा।"),
    ("दुनिया में अपवाद:", "न्यूज़ीलैंड को छोड़कर अमेरिका ही ऐसा देश है जहाँ दवा कंपनियाँ टीवी पर कानूनी रूप से विज्ञापन दे सकती हैं।"),
    ("भ्रामक:", "अध्ययनों ने दिखाया कि प्रिस्क्रिप्शन दवाओं के आधे से अधिक विज्ञापन भ्रामक या गलत हैं।"),
    ("कीमतें:", "Ozempic अमेरिका में लगभग 1,000 डॉलर प्रति माह की है, जर्मनी में केवल 59 डॉलर की।")],
   "अमेरिका आखिरकार जाग गया!"),
 'ja': D("アメリカ合衆国", "米国で医薬品広告は禁止されるのか", "サンダース、キング両上院議員が処方薬広告を禁止する法案を提出",
   [("50億ドル超", "製薬業界が昨年テレビ広告に費やした額"), ("30%超", "大手ネットワークの夜のニュースの広告時間に占める割合"), ("4人に1人", "の米国人は医師が処方した薬の費用を払えない")], None,
   [("法案:", "End Prescription Drug Ads Now Act は、テレビ、ラジオ、印刷媒体、デジタルプラットフォーム、SNSでの処方薬広告を禁止する。"),
    ("世界の例外:", "ニュージーランドを除けば、製薬会社がテレビで合法的に医薬品を広告できる国は米国だけである。"),
    ("誤解を招く:", "研究では、処方薬広告の半数以上が誤解を招く、または誤った内容であることが示された。"),
    ("価格:", "Ozempic は米国で月約1,000ドル、ドイツではわずか59ドル。")],
   "アメリカはようやく目を覚ました！"),
})

# 84 - Weight-loss drugs: side effects and cost
CARDS['b21_weight'] = ('teal', {
 'en': D("GLP-1 DRUGS", "Weight-loss drugs: side effects and costs", "Ozempic, Wegovy, Saxenda, Mounjaro, Zepbound and others", None, None,
   [("Cost:", "monthly treatment is around 20,000-30,000 TL and must be continued for months, sometimes for life."),
    ("Common side effects:", "nausea (the most frequent), vomiting, diarrhoea, constipation, abdominal pain, headache and fatigue."),
    ("Serious side effects:", "pancreatitis, gallbladder problems, kidney damage, severe allergic reactions and worsening of diabetic retinopathy."),
    ("Thyroid:", "C-cell tumours were seen in animal studies. Not recommended with a family history of medullary thyroid cancer or with MEN 2."),
    ("After stopping:", "in a 2022 clinical trial, semaglutide users regained about two thirds of the lost weight within one year.")],
   "Within 3-6 months of stopping the drugs, the lost weight is regained."),
 'de': D("GLP-1-MEDIKAMENTE", "Abnehmmedikamente: Nebenwirkungen und Kosten", "Ozempic, Wegovy, Saxenda, Mounjaro, Zepbound und andere", None, None,
   [("Kosten:", "die monatliche Behandlung kostet etwa 20.000-30.000 TL und muss über Monate, manchmal lebenslang fortgesetzt werden."),
    ("Häufige Nebenwirkungen:", "Übelkeit (am häufigsten), Erbrechen, Durchfall, Verstopfung, Bauchschmerzen, Kopfschmerzen und Müdigkeit."),
    ("Schwere Nebenwirkungen:", "Pankreatitis, Gallenblasenprobleme, Nierenschädigung, schwere allergische Reaktionen und Verschlechterung einer diabetischen Retinopathie."),
    ("Schilddrüse:", "in Tierstudien traten C-Zell-Tumoren auf. Nicht empfohlen bei medullärem Schilddrüsenkarzinom in der Familie oder bei MEN 2."),
    ("Nach dem Absetzen:", "in einer klinischen Studie von 2022 nahmen Semaglutid-Anwender innerhalb eines Jahres etwa zwei Drittel des verlorenen Gewichts wieder zu.")],
   "Innerhalb von 3-6 Monaten nach dem Absetzen kehrt das verlorene Gewicht zurück."),
 'es': D("FÁRMACOS GLP-1", "Fármacos para adelgazar: efectos adversos y costes", "Ozempic, Wegovy, Saxenda, Mounjaro, Zepbound y otros", None, None,
   [("Coste:", "el tratamiento mensual ronda las 20.000-30.000 TL y debe mantenerse durante meses, a veces de por vida."),
    ("Efectos adversos frecuentes:", "náuseas (el más frecuente), vómitos, diarrea, estreñimiento, dolor abdominal, cefalea y cansancio."),
    ("Efectos adversos graves:", "pancreatitis, problemas de la vesícula biliar, daño renal, reacciones alérgicas graves y empeoramiento de la retinopatía diabética."),
    ("Tiroides:", "en estudios con animales aparecieron tumores de células C. No se recomiendan con antecedentes familiares de cáncer medular de tiroides ni con MEN 2."),
    ("Tras suspenderlos:", "en un ensayo clínico de 2022, los usuarios de semaglutida recuperaron en un año unos dos tercios del peso perdido.")],
   "En los 3-6 meses tras suspender los fármacos se recupera el peso perdido."),
 'ru': D("ПРЕПАРАТЫ ГПП-1", "Препараты для похудения: побочные эффекты и стоимость", "Ozempic, Wegovy, Saxenda, Mounjaro, Zepbound и другие", None, None,
   [("Стоимость:", "месяц лечения стоит около 20 000-30 000 TL, а применять препарат нужно месяцами, иногда пожизненно."),
    ("Частые побочные эффекты:", "тошнота (чаще всего), рвота, диарея, запор, боль в животе, головная боль и утомляемость."),
    ("Серьёзные побочные эффекты:", "панкреатит, заболевания желчного пузыря, поражение почек, тяжёлые аллергические реакции и ухудшение диабетической ретинопатии."),
    ("Щитовидная железа:", "в исследованиях на животных возникали опухоли из С-клеток. Не рекомендуются при медуллярном раке щитовидной железы в семье и при МЭН 2."),
    ("После отмены:", "в клиническом исследовании 2022 года принимавшие семаглутид за год вернули около двух третей потерянного веса.")],
   "В течение 3-6 месяцев после отмены препаратов потерянный вес возвращается."),
 'zh': D("GLP-1类药物", "减肥药：副作用与费用", "Ozempic、Wegovy、Saxenda、Mounjaro、Zepbound等", None, None,
   [("费用：", "每月治疗费用约为20,000-30,000土耳其里拉，需要使用数月，有时需终身使用。"),
    ("常见副作用：", "恶心（最常见）、呕吐、腹泻、便秘、腹痛、头痛和乏力。"),
    ("严重副作用：", "胰腺炎、胆囊疾病、肾损伤、严重过敏反应以及糖尿病视网膜病变加重。"),
    ("甲状腺：", "动物研究中出现甲状腺C细胞肿瘤。有甲状腺髓样癌家族史或患MEN 2者不建议使用。"),
    ("停药之后：", "2022年的一项临床试验显示，使用司美格鲁肽者停药后一年内体重回升了所减体重的约三分之二。")],
   "停药后3-6个月内，减掉的体重会反弹。"),
 'hi': D("GLP-1 दवाएँ", "वज़न घटाने की दवाएँ: दुष्प्रभाव और खर्च", "Ozempic, Wegovy, Saxenda, Mounjaro, Zepbound और अन्य", None, None,
   [("खर्च:", "मासिक उपचार लगभग 20,000-30,000 TL का है और इसे महीनों तक, कभी-कभी जीवन भर लेना पड़ता है।"),
    ("सामान्य दुष्प्रभाव:", "मतली (सबसे आम), उल्टी, दस्त, कब्ज़, पेट दर्द, सिरदर्द और थकान।"),
    ("गंभीर दुष्प्रभाव:", "अग्नाशयशोथ, पित्ताशय की समस्याएँ, गुर्दे की क्षति, गंभीर एलर्जी प्रतिक्रियाएँ और डायबिटिक रेटिनोपैथी का बिगड़ना।"),
    ("थायरॉइड:", "पशु अध्ययनों में C-कोशिका ट्यूमर देखे गए। परिवार में मेडुलरी थायरॉइड कैंसर या MEN 2 होने पर इनकी सलाह नहीं दी जाती।"),
    ("दवा बंद करने के बाद:", "2022 के एक क्लिनिकल ट्रायल में सेमाग्लूटाइड लेने वालों ने एक वर्ष में घटाए गए वज़न का लगभग दो तिहाई वापस पा लिया।")],
   "दवा बंद करने के 3-6 महीनों के भीतर घटाया हुआ वज़न वापस आ जाता है।"),
 'ja': D("GLP-1製剤", "肥満症治療薬：副作用と費用", "Ozempic、Wegovy、Saxenda、Mounjaro、Zepbound など", None, None,
   [("費用:", "1か月の治療費は約20,000-30,000トルコリラで、数か月、ときには生涯にわたり使用が必要。"),
    ("よくある副作用:", "悪心（最も多い）、嘔吐、下痢、便秘、腹痛、頭痛、倦怠感。"),
    ("重篤な副作用:", "膵炎、胆嚢障害、腎障害、重度のアレルギー反応、糖尿病網膜症の悪化。"),
    ("甲状腺:", "動物実験でC細胞腫瘍が認められた。甲状腺髄様癌の家族歴がある人やMEN 2の人には推奨されない。"),
    ("中止後:", "2022年の臨床試験では、セマグルチド使用者は中止後1年以内に減った体重の約3分の2を取り戻した。")],
   "薬をやめると3-6か月以内に、減った体重は元に戻る。"),
})

# 88 - Finasteride and suicidal ideation (EMA)
CARDS['b21_finast'] = ('purple', {
 'en': D("EMA REVIEW", "Finasteride and suicidal thoughts", "The EMA confirmed suicidal ideation as a side effect of the prostate and hair-loss drug",
   [("325", "cases associated with suicidal ideation"), ("313", "cases with finasteride"), ("13", "cases with dutasteride")], None,
   [("Who:", "most cases were in patients treated for male-pattern hair loss, especially users of finasteride 1 mg."),
    ("Context:", "270 million patient-years of exposure to finasteride and 82 million to dutasteride. The frequency is not known."),
    ("Advice:", "in case of depressed mood, depression or suicidal thoughts, stop treatment and seek medical help."),
    ("Dutasteride:", "no direct link was found, but warnings will be added as a precaution."),
    ("New measures:", "warnings on mood changes and a patient card in finasteride 1 mg packs.")],
   "For both drugs the benefits outweigh the risks in their approved uses.",
   "Source: Medscape Medical News, 9 May 2025"),
 'de': D("EMA-BEWERTUNG", "Finasterid und Suizidgedanken", "Die EMA bestätigte Suizidgedanken als Nebenwirkung des Mittels gegen Prostatavergrößerung und Haarausfall",
   [("325", "Fälle im Zusammenhang mit Suizidgedanken"), ("313", "Fälle unter Finasterid"), ("13", "Fälle unter Dutasterid")], None,
   [("Wer:", "die meisten Fälle betrafen Patienten mit erblich bedingtem Haarausfall, vor allem Anwender von Finasterid 1 mg."),
    ("Einordnung:", "270 Millionen Patientenjahre Exposition bei Finasterid, 82 Millionen bei Dutasterid. Die Häufigkeit ist nicht bekannt."),
    ("Empfehlung:", "bei gedrückter Stimmung, Depression oder Suizidgedanken die Behandlung beenden und ärztliche Hilfe suchen."),
    ("Dutasterid:", "kein direkter Zusammenhang festgestellt, Warnhinweise werden aber vorsorglich ergänzt."),
    ("Neue Maßnahmen:", "Warnhinweise zu Stimmungsänderungen und eine Patientenkarte in Packungen mit Finasterid 1 mg.")],
   "Bei beiden Arzneimitteln überwiegt in den zugelassenen Anwendungen der Nutzen die Risiken.",
   "Quelle: Medscape Medical News, 9. Mai 2025"),
 'es': D("REVISIÓN DE LA EMA", "Finasterida e ideas suicidas", "La EMA confirmó la ideación suicida como efecto adverso del fármaco para la próstata y la calvicie",
   [("325", "casos asociados a ideación suicida"), ("313", "casos con finasterida"), ("13", "casos con dutasterida")], None,
   [("Quiénes:", "la mayoría de los casos fueron pacientes tratados por alopecia androgénica, sobre todo con finasterida 1 mg."),
    ("Contexto:", "270 millones de pacientes-año de exposición a finasterida y 82 millones a dutasterida. La frecuencia no se conoce."),
    ("Consejo:", "ante estado de ánimo deprimido, depresión o ideas suicidas, suspender el tratamiento y buscar ayuda médica."),
    ("Dutasterida:", "no se halló una relación directa, pero se añadirán advertencias por precaución."),
    ("Nuevas medidas:", "advertencias sobre cambios del estado de ánimo y una tarjeta para el paciente en los envases de finasterida 1 mg.")],
   "En ambos fármacos los beneficios superan a los riesgos en sus usos autorizados.",
   "Fuente: Medscape Medical News, 9 de mayo de 2025"),
 'ru': D("ОЦЕНКА EMA", "Финастерид и суицидальные мысли", "EMA подтвердило суицидальные мысли как побочный эффект препарата от аденомы простаты и облысения",
   [("325", "случаев, связанных с суицидальными мыслями"), ("313", "случаев при приёме финастерида"), ("13", "случаев при приёме дутастерида")], None,
   [("У кого:", "большинство случаев отмечено у пациентов, лечившихся от андрогенной алопеции, особенно при приёме финастерида 1 мг."),
    ("Контекст:", "экспозиция составила 270 миллионов пациенто-лет для финастерида и 82 миллиона для дутастерида. Частота неизвестна."),
    ("Рекомендация:", "при подавленном настроении, депрессии или суицидальных мыслях прекратить лечение и обратиться к врачу."),
    ("Дутастерид:", "прямой связи не выявлено, но предупреждения будут добавлены из предосторожности."),
    ("Новые меры:", "предупреждения об изменениях настроения и карточка пациента в упаковках финастерида 1 мг.")],
   "Для обоих препаратов польза превышает риски при одобренных показаниях.",
   "Источник: Medscape Medical News, 9 мая 2025 г."),
 'zh': D("EMA评估", "非那雄胺与自杀念头", "EMA确认自杀意念是这种前列腺和脱发药物的副作用",
   [("325", "例与自杀意念相关的病例"), ("313", "例与非那雄胺有关"), ("13", "例与度他雄胺有关")], None,
   [("人群：", "多数病例为接受男性型脱发治疗的患者，尤其是使用非那雄胺1 mg者。"),
    ("背景：", "非那雄胺的暴露量为2.7亿患者年，度他雄胺为8200万患者年。发生频率未知。"),
    ("建议：", "出现情绪低落、抑郁或自杀念头时，应停止治疗并就医。"),
    ("度他雄胺：", "未发现直接关联，但出于谨慎将增加警示。"),
    ("新措施：", "增加有关情绪变化的警示，并在非那雄胺1 mg包装中加入患者提示卡。")],
   "两种药物在获批用途中的获益均大于风险。",
   "来源：Medscape Medical News，2025年5月9日"),
 'hi': D("EMA की समीक्षा", "फ़िनास्टराइड और आत्महत्या के विचार", "EMA ने प्रोस्टेट और गंजेपन की इस दवा के दुष्प्रभाव के रूप में आत्महत्या के विचारों की पुष्टि की",
   [("325", "मामले आत्महत्या के विचारों से जुड़े"), ("313", "मामले फ़िनास्टराइड के साथ"), ("13", "मामले ड्यूटास्टराइड के साथ")], None,
   [("कौन:", "अधिकांश मामले पुरुषों के गंजेपन का इलाज करा रहे रोगियों में थे, विशेषकर फ़िनास्टराइड 1 mg लेने वालों में।"),
    ("संदर्भ:", "फ़िनास्टराइड का एक्सपोज़र 27 करोड़ रोगी-वर्ष और ड्यूटास्टराइड का 8.2 करोड़ रोगी-वर्ष है। आवृत्ति ज्ञात नहीं है।"),
    ("सलाह:", "उदास मनोदशा, अवसाद या आत्महत्या के विचार आने पर उपचार रोकें और चिकित्सकीय सहायता लें।"),
    ("ड्यूटास्टराइड:", "कोई सीधा संबंध नहीं मिला, पर सावधानी के तौर पर चेतावनियाँ जोड़ी जाएँगी।"),
    ("नए उपाय:", "मनोदशा में बदलाव की चेतावनियाँ और फ़िनास्टराइड 1 mg के पैक में रोगी कार्ड।")],
   "दोनों दवाओं के स्वीकृत उपयोगों में लाभ जोखिमों से अधिक हैं।",
   "स्रोत: Medscape Medical News, 9 मई 2025"),
 'ja': D("EMAの評価", "フィナステリドと自殺念慮", "EMAは前立腺肥大症・脱毛症治療薬の副作用として自殺念慮を確認した",
   [("325", "件が自殺念慮に関連する症例"), ("313", "件がフィナステリド"), ("13", "件がデュタステリド")], None,
   [("対象:", "症例の多くは男性型脱毛症の治療を受けていた患者で、特にフィナステリド1 mgの使用者であった。"),
    ("背景:", "曝露量はフィナステリドが2億7000万患者年、デュタステリドが8200万患者年。頻度は不明。"),
    ("助言:", "抑うつ気分、うつ病、自殺念慮が現れた場合は治療を中止し、医療機関を受診する。"),
    ("デュタステリド:", "直接の関連は認められなかったが、予防的に警告が追加される。"),
    ("新たな措置:", "気分変化に関する警告と、フィナステリド1 mgの包装への患者カードの追加。")],
   "いずれの薬も、承認された用途では有益性がリスクを上回る。",
   "出典: Medscape Medical News、2025年5月9日"),
})

# the originals are mostly English already: English visitors keep the original picture
for _c in ('b21_adban','b21_finast'): CARDS[_c][1].pop('en', None)
