from batch1 import D
CARDS = {}
BM = {'en': "BITTER MEDICINE", 'de': "BITTERE MEDIZIN", 'es': "MEDICINA AMARGA", 'ru': "ГОРЬКОЕ ЛЕКАРСТВО", 'zh': "苦口良药", 'hi': "कड़वी दवा", 'ja': "苦い薬"}

# 16 — Competition Authority report (poster)
CARDS['rekabet'] = ('navy', {
 'en': D("COMPETITION AUTHORITY · PHARMACEUTICAL SECTOR INQUIRY · PRELIMINARY REPORT · AUGUST 2026", "An independent inquiry, or the industry's own text?", None),
 'de': D("WETTBEWERBSBEHÖRDE · SEKTORUNTERSUCHUNG ARZNEIMITTEL · VORBERICHT · AUGUST 2026", "Unabhängige Untersuchung oder der eigene Text der Branche?", None),
 'es': D("AUTORIDAD DE COMPETENCIA · ESTUDIO DEL SECTOR FARMACÉUTICO · INFORME PRELIMINAR · AGOSTO DE 2026", "¿Un estudio independiente o el texto del propio sector?", None),
 'ru': D("УПРАВЛЕНИЕ ПО КОНКУРЕНЦИИ · ИССЛЕДОВАНИЕ ФАРМСЕКТОРА · ПРЕДВАРИТЕЛЬНЫЙ ОТЧЁТ · АВГУСТ 2026", "Независимое исследование или текст самой отрасли?", None),
 'zh': D("竞争管理局 · 医药行业调查 · 初步报告 · 2026年8月", "是独立调查，还是行业自己的文本？", None),
 'hi': D("प्रतिस्पर्धा प्राधिकरण · दवा क्षेत्र जाँच · प्रारंभिक रिपोर्ट · अगस्त 2026", "स्वतंत्र जाँच, या उद्योग का अपना पाठ?", None),
 'ja': D("競争当局 · 医薬品セクター調査 · 中間報告 · 2026年8月", "独立した調査か、それとも業界自身の文章か", None),
})

# 17 — Prescribing by generic name
CARDS['jenerik'] = ('blue', {
 'en': D(BM['en'], "Prescribing by generic (active substance) name", "Thesis: generic prescribing in Türkiye exists on paper, not in practice", None, None,
   [("Official position:", "the Ministry of Health says generics with proven bioequivalence give the same treatment as the original, and that claims they cannot replace each other have no scientific or legal basis."),
    ("At physician level:", "physicians think and prescribe by brand name. The 'generic' appearance comes from the system's automatic conversion, not from a conscious choice."),
    ("At institutional level:", "hospital formularies follow tender and purchasing logic, and medicines can be switched without knowing the physician's clinical reasoning."),
    ("Four concepts, not one:", "chemical, pharmaceutical, bio- and therapeutic equivalence are different things.")]),
 'de': D(BM['de'], "Verordnen nach Wirkstoffnamen (generisch)", "These: Die Wirkstoffverordnung existiert in der Türkei auf dem Papier, nicht in der Praxis", None, None,
   [("Offizielle Position:", "Laut Gesundheitsministerium bieten Generika mit nachgewiesener Bioäquivalenz dieselbe Behandlung wie das Original; Behauptungen, sie seien nicht austauschbar, haben keine wissenschaftliche oder rechtliche Grundlage."),
    ("Auf Ebene der Ärzte:", "Ärzte denken und verordnen nach Markennamen. Der „generische“ Anschein entsteht durch die automatische Umwandlung im System, nicht durch bewusste Wahl."),
    ("Auf institutioneller Ebene:", "Krankenhauslisten folgen der Logik von Ausschreibung und Einkauf; Medikamente können gewechselt werden, ohne die klinische Begründung des Arztes zu kennen."),
    ("Vier Begriffe, nicht einer:", "chemische, pharmazeutische, Bio- und therapeutische Äquivalenz sind verschiedene Dinge.")]),
 'es': D(BM['es'], "Recetar por nombre genérico (principio activo)", "Tesis: en Turquía la prescripción por principio activo existe sobre el papel, no en la práctica", None, None,
   [("Posición oficial:", "el Ministerio de Sanidad afirma que los genéricos con bioequivalencia demostrada ofrecen el mismo tratamiento que el original, y que negar su intercambiabilidad carece de base científica y legal."),
    ("En el médico:", "los médicos piensan y recetan por marca. La apariencia «genérica» procede de la conversión automática del sistema, no de una elección consciente."),
    ("En las instituciones:", "los formularios hospitalarios siguen la lógica de licitaciones y compras, y se cambian medicamentos sin conocer la justificación clínica del médico."),
    ("Cuatro conceptos, no uno:", "equivalencia química, farmacéutica, bioequivalencia y equivalencia terapéutica son cosas distintas.")]),
 'ru': D(BM['ru'], "Выписывать рецепт по действующему веществу (МНН)", "Тезис: в Турции назначение по МНН существует на бумаге, но не на практике", None, None,
   [("Официальная позиция:", "Минздрав заявляет, что дженерики с доказанной биоэквивалентностью обеспечивают то же лечение, что и оригинал, а утверждения об их невзаимозаменяемости не имеют научных и правовых оснований."),
    ("На уровне врача:", "врачи думают и выписывают по торговым названиям. «Дженерический» вид создаёт автоматическое преобразование в системе, а не осознанный выбор."),
    ("На уровне учреждений:", "больничные формуляры подчинены логике тендеров и закупок, и препарат могут заменить, не зная клинических соображений врача."),
    ("Четыре понятия, а не одно:", "химическая, фармацевтическая, био- и терапевтическая эквивалентность не одно и то же.")]),
 'zh': D(BM['zh'], "按通用名（有效成分）开处方", "论点：在土耳其，通用名处方只存在于纸面上，而不在实践中", None, None,
   [("官方立场：", "卫生部表示，经生物等效性证明的仿制药与原研药提供相同的治疗，称它们不能互相替代的说法没有科学和法律依据。"),
    ("在医生层面：", "医生按商品名思考和开处方。所谓“通用名”的表象来自系统的自动转换，而不是医生的自觉选择。"),
    ("在机构层面：", "医院处方集遵循招标和采购逻辑，可以在不了解医生临床理由的情况下换药。"),
    ("是四个概念，不是一个：", "化学等效、药学等效、生物等效和治疗等效并不相同。")]),
 'hi': D(BM['hi'], "जेनेरिक (सक्रिय पदार्थ) नाम से नुस्खा लिखना", "तर्क: तुर्किये में जेनेरिक नाम से नुस्खा काग़ज़ पर है, व्यवहार में नहीं", None, None,
   [("आधिकारिक रुख:", "स्वास्थ्य मंत्रालय के अनुसार जैव-समतुल्यता सिद्ध जेनेरिक दवाएँ मूल दवा जैसा ही उपचार देती हैं, और उन्हें अदला-बदली योग्य न मानने के दावों का कोई वैज्ञानिक या कानूनी आधार नहीं।"),
    ("चिकित्सक के स्तर पर:", "चिकित्सक ब्रांड नाम से सोचते और लिखते हैं। “जेनेरिक” रूप प्रणाली के स्वचालित रूपांतरण से आता है, सोच-समझकर किए गए चुनाव से नहीं।"),
    ("संस्थागत स्तर पर:", "अस्पतालों की दवा-सूचियाँ निविदा और खरीद के तर्क पर चलती हैं, और चिकित्सक का नैदानिक कारण जाने बिना दवा बदली जा सकती है।"),
    ("चार अवधारणाएँ, एक नहीं:", "रासायनिक, औषधीय, जैव- और चिकित्सीय समतुल्यता अलग-अलग चीज़ें हैं।")]),
 'ja': D(BM['ja'], "一般名（有効成分名）で処方する", "主張：トルコでは一般名処方は紙の上にあるだけで、実際には行われていない", None, None,
   [("公式見解：", "保健省は、生物学的同等性が証明された後発品は先発品と同じ治療を提供し、互いに代替できないという主張には科学的・法的根拠がないとしている。"),
    ("医師のレベルでは：", "医師は商品名で考え、処方している。「一般名」に見えるのはシステムの自動変換によるもので、意識的な選択ではない。"),
    ("機関のレベルでは：", "病院の採用薬は入札と購買の論理で決まり、医師の臨床上の理由を知らないまま薬が切り替えられることがある。"),
    ("概念は一つではなく四つ：", "化学的同等性、製剤学的同等性、生物学的同等性、治療学的同等性は別のものである。")]),
})

# 18 — mRNA vaccine in melanoma
_MS = "Merck/Moderna, SEC, STAT News, CNBC"
CARDS['mrna'] = ('burg', {
 'en': D("ONCOLOGY", "mRNA vaccine in melanoma: positive Phase 3 result", "Intismeran + Keytruda, INTerpath-001 trial (19 August 2026)",
   [("1,100+", "patients (resected melanoma)"), ("49%", "lower risk of recurrence or death (Phase 2b, 5 years)"), ("59%", "lower risk of distant metastasis (Phase 2b, 5 years)")], None,
   [("Mechanism:", "a synthetic mRNA molecule made to match the genetic profile of the patient's own tumour, targeting up to 34 tumour-specific neoantigens."),
    ("Phase 3 endpoint:", "a significant extension of recurrence-free survival and a lower risk of distant spread. Detailed data and statistics have not yet been opened to independent review.")],
   None, "Source: " + _MS + " (August 2026)"),
 'de': D("ONKOLOGIE", "mRNA-Impfstoff beim Melanom: positives Phase-3-Ergebnis", "Intismeran + Keytruda, Studie INTerpath-001 (19. August 2026)",
   [("1.100+", "Patienten (reseziertes Melanom)"), ("49 %", "geringeres Risiko für Rückfall oder Tod (Phase 2b, 5 Jahre)"), ("59 %", "geringeres Risiko für Fernmetastasen (Phase 2b, 5 Jahre)")], None,
   [("Mechanismus:", "ein synthetisches mRNA-Molekül, hergestellt nach dem genetischen Profil des eigenen Tumors, gerichtet gegen bis zu 34 tumorspezifische Neoantigene."),
    ("Phase-3-Endpunkt:", "signifikante Verlängerung des rezidivfreien Überlebens und geringeres Risiko der Fernausbreitung. Detaillierte Daten und Statistiken sind noch nicht unabhängig überprüfbar.")],
   None, "Quelle: " + _MS + " (August 2026)"),
 'es': D("ONCOLOGÍA", "Vacuna de ARNm en melanoma: resultado positivo en fase 3", "Intismeran + Keytruda, ensayo INTerpath-001 (19 de agosto de 2026)",
   [("1.100+", "pacientes (melanoma resecado)"), ("49 %", "menor riesgo de recaída o muerte (fase 2b, 5 años)"), ("59 %", "menor riesgo de metástasis a distancia (fase 2b, 5 años)")], None,
   [("Mecanismo:", "una molécula sintética de ARNm fabricada según el perfil genético del tumor del propio paciente, dirigida contra hasta 34 neoantígenos específicos del tumor."),
    ("Criterio de valoración de fase 3:", "prolongación significativa de la supervivencia libre de recaída y menor riesgo de diseminación a distancia. Los datos detallados aún no están abiertos a revisión independiente.")],
   None, "Fuente: " + _MS + " (agosto de 2026)"),
 'ru': D("ОНКОЛОГИЯ", "мРНК-вакцина при меланоме: положительный результат 3-й фазы", "Интисмеран + Китруда, исследование INTerpath-001 (19 августа 2026 г.)",
   [("1100+", "пациентов (резецированная меланома)"), ("49 %", "снижение риска рецидива или смерти (фаза 2b, 5 лет)"), ("59 %", "снижение риска отдалённых метастазов (фаза 2b, 5 лет)")], None,
   [("Механизм:", "синтетическая молекула мРНК, созданная по генетическому профилю опухоли самого пациента и нацеленная на до 34 опухолеспецифичных неоантигенов."),
    ("Конечная точка 3-й фазы:", "значимое увеличение безрецидивной выживаемости и снижение риска отдалённого распространения. Подробные данные пока не открыты для независимой проверки.")],
   None, "Источник: " + _MS + " (август 2026 г.)"),
 'zh': D("肿瘤学", "黑色素瘤mRNA疫苗：3期试验取得阳性结果", "Intismeran + 可瑞达，INTerpath-001研究（2026年8月19日）",
   [("1100多名", "患者（已切除的黑色素瘤）"), ("49%", "复发或死亡风险降低（2b期，5年）"), ("59%", "远处转移风险降低（2b期，5年）")], None,
   [("机制：", "根据患者自身肿瘤的基因特征制备的合成mRNA分子，靶向多达34种肿瘤特异性新抗原。"),
    ("3期终点：", "无复发生存期显著延长，远处扩散风险降低。详细数据和统计结果尚未开放供独立审查。")],
   None, "来源：" + _MS + "（2026年8月）"),
 'hi': D("ऑन्कोलॉजी", "मेलेनोमा में mRNA टीका: तीसरे चरण में सकारात्मक परिणाम", "इंटिस्मेरान + कीट्रूडा, INTerpath-001 अध्ययन (19 अगस्त 2026)",
   [("1,100+", "मरीज़ (शल्यक्रिया से निकाला गया मेलेनोमा)"), ("49%", "पुनरावृत्ति या मृत्यु के जोखिम में कमी (चरण 2b, 5 वर्ष)"), ("59%", "दूरस्थ मेटास्टेसिस के जोखिम में कमी (चरण 2b, 5 वर्ष)")], None,
   [("क्रियाविधि:", "मरीज़ के अपने ट्यूमर की आनुवंशिक रूपरेखा के अनुसार बना कृत्रिम mRNA अणु, जो ट्यूमर-विशिष्ट 34 तक नियोएंटीजन को लक्ष्य करता है।"),
    ("तीसरे चरण का अंतिम बिंदु:", "पुनरावृत्ति-मुक्त जीवनकाल में सार्थक वृद्धि और दूर तक फैलने के जोखिम में कमी। विस्तृत आँकड़े अभी स्वतंत्र समीक्षा के लिए उपलब्ध नहीं।")],
   None, "स्रोत: " + _MS + " (अगस्त 2026)"),
 'ja': D("腫瘍学", "悪性黒色腫のmRNAワクチン：第3相で良好な結果", "インティスメラン＋キイトルーダ、INTerpath-001試験（2026年8月19日）",
   [("1,100人以上", "の患者（切除後の悪性黒色腫）"), ("49%", "再発または死亡リスクの低下（第2b相、5年）"), ("59%", "遠隔転移リスクの低下（第2b相、5年）")], None,
   [("仕組み：", "患者自身の腫瘍の遺伝子プロファイルに合わせて作る合成mRNA分子で、最大34種類の腫瘍特異的ネオアンチゲンを標的とする。"),
    ("第3相の評価項目：", "無再発生存期間の有意な延長と遠隔転移リスクの低下。詳細なデータと統計はまだ独立した検証に供されていない。")],
   None, "出典：" + _MS + "（2026年8月）"),
})

# 19 — Copy-paste licences and TİTCK
CARDS['copypaste'] = ('burg', {
 'en': D("CİMER APPLICATION NO. 2603804196 · 28 JULY 2026", "Copy-paste licences and TİTCK's answer", None, None, "EIGHT QUESTIONS WERE ASKED, AMONG THEM:",
   [("1.", "In which category was the licence application assessed?"), ("2.", "Which bridging data were submitted under 'well-established use'?"), ("4.", "If no human study was submitted, what was the justification for the biowaiver?"), ("5.", "Is a public assessment report like the PAR (MHRA) or EPAR (EMA) planned?"), ("6.", "Was the overlap between the product information of Abdi İbrahim Melatonin 3 mg and Baymela 3 mg noticed during licensing?")],
   "The Agency's reply (18 August 2026): \"Information submitted to the Agency by the applicant is confidential.\" All eight questions were refused in a single sentence."),
 'de': D("CİMER-ANTRAG NR. 2603804196 · 28. JULI 2026", "Copy-Paste-Zulassungen und die Antwort der TİTCK", None, None, "ACHT FRAGEN WURDEN GESTELLT, DARUNTER:",
   [("1.", "In welcher Kategorie wurde der Zulassungsantrag bewertet?"), ("2.", "Welche Bridging-Daten wurden bei „allgemein medizinischer Verwendung“ vorgelegt?"), ("4.", "Wenn keine Humanstudie vorgelegt wurde: Wie wurde der Biowaiver begründet?"), ("5.", "Ist ein öffentlicher Bewertungsbericht wie PAR (MHRA) oder EPAR (EMA) geplant?"), ("6.", "Wurde die Überschneidung der Fachinformationen von Abdi İbrahim Melatonin 3 mg und Baymela 3 mg bei der Zulassung bemerkt?")],
   "Antwort der Behörde (18. August 2026): „Die vom Antragsteller vorgelegten Informationen sind vertraulich.“ Alle acht Fragen wurden mit einem einzigen Satz abgelehnt."),
 'es': D("SOLICITUD CİMER N.º 2603804196 · 28 DE JULIO DE 2026", "Autorizaciones «copia y pega» y la respuesta de la TİTCK", None, None, "SE HICIERON OCHO PREGUNTAS, ENTRE ELLAS:",
   [("1.", "¿En qué categoría se evaluó la solicitud de autorización?"), ("2.", "¿Qué datos puente se presentaron en «uso bien establecido»?"), ("4.", "Si no se presentó un estudio en humanos, ¿cuál fue la justificación de la bioexención?"), ("5.", "¿Se prevé un informe público de evaluación como el PAR (MHRA) o el EPAR (EMA)?"), ("6.", "¿Se advirtió durante la autorización la coincidencia entre las fichas técnicas de Abdi İbrahim Melatonin 3 mg y Baymela 3 mg?")],
   "Respuesta de la Agencia (18 de agosto de 2026): «La información presentada por el solicitante es confidencial». Las ocho preguntas se rechazaron con una sola frase."),
 'ru': D("ОБРАЩЕНИЕ В CİMER № 2603804196 · 28 ИЮЛЯ 2026", "Регистрации «копировать-вставить» и ответ TİTCK", None, None, "БЫЛО ЗАДАНО ВОСЕМЬ ВОПРОСОВ, СРЕДИ НИХ:",
   [("1.", "По какой категории оценивалась заявка на регистрацию?"), ("2.", "Какие связующие данные были представлены при «хорошо изученном применении»?"), ("4.", "Если исследование на людях не представлено, чем обоснован биовейвер?"), ("5.", "Планируется ли публичный отчёт об оценке, подобный PAR (MHRA) или EPAR (EMA)?"), ("6.", "Было ли замечено при регистрации совпадение инструкций Abdi İbrahim Melatonin 3 мг и Baymela 3 мг?")],
   "Ответ агентства (18 августа 2026 г.): «Сведения, представленные заявителем, являются конфиденциальными». Все восемь вопросов отклонены одной фразой."),
 'zh': D("CİMER申请编号2603804196 · 2026年7月28日", "“复制粘贴”式上市许可与TİTCK的答复", None, None, "共提出八个问题，其中包括：",
   [("1.", "上市许可申请是按哪一类别审评的？"), ("2.", "在“确立已久的应用”类别下提交了哪些桥接数据？"), ("4.", "如果没有提交人体研究，豁免生物等效性试验的理由是什么？"), ("5.", "是否计划发布类似PAR（MHRA）或EPAR（EMA）的公开审评报告？"), ("6.", "审批时是否注意到Abdi İbrahim Melatonin 3毫克与Baymela 3毫克产品信息的重合？")],
   "该机构的答复（2026年8月18日）：“申请人向本机构提交的信息属于保密信息。”八个问题被一句话全部拒绝。"),
 'hi': D("CİMER आवेदन सं. 2603804196 · 28 जुलाई 2026", "कॉपी-पेस्ट लाइसेंस और TİTCK का जवाब", None, None, "आठ प्रश्न पूछे गए, जिनमें:",
   [("1.", "लाइसेंस आवेदन का मूल्यांकन किस श्रेणी में हुआ?"), ("2.", "“स्थापित उपयोग” में कौन-सा ब्रिजिंग डेटा दिया गया?"), ("4.", "यदि मानव अध्ययन नहीं दिया गया, तो बायोवेवर का आधार क्या था?"), ("5.", "क्या PAR (MHRA) या EPAR (EMA) जैसी सार्वजनिक मूल्यांकन रिपोर्ट की योजना है?"), ("6.", "क्या लाइसेंस देते समय Abdi İbrahim Melatonin 3 mg और Baymela 3 mg की उत्पाद जानकारी की समानता पर ध्यान गया?")],
   "एजेंसी का जवाब (18 अगस्त 2026): “आवेदक द्वारा एजेंसी को दी गई जानकारी गोपनीय है।” आठों प्रश्न एक ही वाक्य में ठुकरा दिए गए।"),
 'ja': D("CİMER申請番号2603804196 · 2026年7月28日", "コピー＆ペースト承認とTİTCKの回答", None, None, "8つの質問をした。そのうち：",
   [("1.", "承認申請はどの区分で評価されたのか"), ("2.", "「確立された使用」ではどのブリッジングデータが提出されたのか"), ("4.", "ヒト試験が提出されていない場合、バイオウェーバーの根拠は何か"), ("5.", "PAR（MHRA）やEPAR（EMA）のような公開審査報告書の予定はあるか"), ("6.", "Abdi İbrahim Melatonin 3 mg と Baymela 3 mg の製品情報の重複は、承認時に認識されていたか")],
   "当局の回答（2026年8月18日）：「申請者が当局に提出した情報は機密である。」8つの質問すべてが一文で拒否された。"),
})

# 20 — Exercise-mimicking pill
CARDS['egzersiz'] = ('teal', {
 'en': D("NEWS", "A pill that mimics exercise", "ENV-308: a new era in obesity treatment? First Phase 1 results of an oral small molecule inspired by Lac-Phe, a metabolite that rises during exercise",
   [("88", "healthy volunteers in Phase 1"), ("Safe", "and well tolerated: no serious adverse events or treatment discontinuations"), ("Leptin ↓", "an early signal that leptin resistance may decrease")], None,
   [("Why it matters:", "weight can be lost with GLP-1 drugs but is regained when the drug is stopped. ENV-308 may be a new candidate for maintenance treatment."),
    ("Do not forget:", "Phase 1 results show only safety and biomarker signals. Efficacy for weight loss and weight maintenance is not yet proven."),
    ("Next:", "Phase 2 trials are due to start in late 2026.")]),
 'de': D("NACHRICHTEN", "Eine Pille, die Bewegung nachahmt", "ENV-308: eine neue Ära der Adipositastherapie? Erste Phase-1-Ergebnisse eines oralen kleinen Moleküls, inspiriert vom Metaboliten Lac-Phe, der bei Bewegung ansteigt",
   [("88", "gesunde Freiwillige in Phase 1"), ("Sicher", "und gut verträglich: keine schweren Nebenwirkungen, keine Therapieabbrüche"), ("Leptin ↓", "ein frühes Signal, dass die Leptinresistenz abnehmen könnte")], None,
   [("Warum es wichtig ist:", "Mit GLP-1-Medikamenten lässt sich abnehmen, doch nach dem Absetzen kehrt das Gewicht zurück. ENV-308 könnte ein neuer Kandidat für die Erhaltungstherapie sein."),
    ("Nicht vergessen:", "Phase-1-Ergebnisse zeigen nur Sicherheits- und Biomarkersignale. Die Wirksamkeit bei Gewichtsabnahme und Gewichtserhalt ist noch nicht belegt."),
    ("Wie es weitergeht:", "Phase-2-Studien sollen Ende 2026 beginnen.")]),
 'es': D("NOTICIAS", "Una píldora que imita el ejercicio", "ENV-308: ¿una nueva era en el tratamiento de la obesidad? Primeros resultados de fase 1 de una molécula pequeña oral inspirada en Lac-Phe, un metabolito que aumenta con el ejercicio",
   [("88", "voluntarios sanos en fase 1"), ("Seguro", "y bien tolerado: sin efectos adversos graves ni abandonos"), ("Leptina ↓", "una señal temprana de que la resistencia a la leptina podría disminuir")], None,
   [("Por qué importa:", "con los fármacos GLP-1 se pierde peso, pero se recupera al suspenderlos. ENV-308 podría ser un nuevo candidato para el tratamiento de mantenimiento."),
    ("No olvidemos:", "los resultados de fase 1 solo muestran seguridad y señales de biomarcadores. La eficacia para perder y mantener el peso aún no está demostrada."),
    ("Siguiente paso:", "los ensayos de fase 2 comenzarán a finales de 2026.")]),
 'ru': D("НОВОСТИ", "Таблетка, имитирующая физическую нагрузку", "ENV-308: новая эпоха в лечении ожирения? Первые результаты 1-й фазы для перорального низкомолекулярного препарата, созданного по образцу метаболита Lac-Phe, уровень которого растёт при нагрузке",
   [("88", "здоровых добровольцев в 1-й фазе"), ("Безопасен", "и хорошо переносится: без серьёзных побочных эффектов и отмен лечения"), ("Лептин ↓", "ранний сигнал возможного снижения резистентности к лептину")], None,
   [("Почему это важно:", "с препаратами ГПП-1 вес снижается, но после отмены возвращается. ENV-308 может стать новым кандидатом для поддерживающей терапии."),
    ("Не забудем:", "результаты 1-й фазы показывают только безопасность и сигналы биомаркеров. Эффективность для снижения и удержания веса пока не доказана."),
    ("Что дальше:", "исследования 2-й фазы начнутся в конце 2026 года.")]),
 'zh': D("新闻", "模拟运动的药片", "ENV-308：肥胖治疗的新时代？受运动时升高的代谢物Lac-Phe启发的口服小分子药物公布首批1期结果",
   [("88名", "健康志愿者参加1期试验"), ("安全", "且耐受性良好：没有严重不良反应，也无人中止治疗"), ("瘦素 ↓", "瘦素抵抗可能减轻的早期信号")], None,
   [("为什么重要：", "GLP-1类药物可以减重，但停药后体重会反弹。ENV-308可能成为新的维持治疗候选药物。"),
    ("不要忘记：", "1期结果只显示安全性和生物标志物信号。减重和维持体重的疗效尚未得到证实。"),
    ("下一步：", "2期试验将于2026年底启动。")]),
 'hi': D("समाचार", "व्यायाम की नकल करने वाली गोली", "ENV-308: मोटापे के इलाज में नया दौर? व्यायाम के दौरान बढ़ने वाले मेटाबोलाइट Lac-Phe से प्रेरित मौखिक छोटे अणु के पहले चरण-1 परिणाम",
   [("88", "स्वस्थ स्वयंसेवक, चरण 1"), ("सुरक्षित", "और अच्छी तरह सहन की गई: कोई गंभीर दुष्प्रभाव या उपचार छोड़ना नहीं"), ("लेप्टिन ↓", "लेप्टिन प्रतिरोध घट सकने का शुरुआती संकेत")], None,
   [("यह क्यों अहम है:", "GLP-1 दवाओं से वज़न घटता है, पर दवा बंद करने पर लौट आता है। ENV-308 वज़न बनाए रखने के उपचार का नया उम्मीदवार हो सकता है।"),
    ("याद रखें:", "चरण 1 के परिणाम केवल सुरक्षा और बायोमार्कर संकेत दिखाते हैं। वज़न घटाने और बनाए रखने की प्रभावकारिता अभी सिद्ध नहीं।"),
    ("आगे:", "चरण 2 के अध्ययन 2026 के अंत में शुरू होंगे।")]),
 'ja': D("ニュース", "運動をまねる薬", "ENV-308：肥満治療の新時代か。運動時に増える代謝物Lac-Pheに着想を得た経口低分子薬の第1相試験の最初の結果",
   [("88人", "の健康なボランティア（第1相）"), ("安全", "で忍容性も良好：重い副作用や治療中止なし"), ("レプチン ↓", "レプチン抵抗性が下がる可能性を示す初期のシグナル")], None,
   [("なぜ重要か：", "GLP-1受容体作動薬で体重は減るが、やめると元に戻る。ENV-308は体重維持療法の新たな候補になりうる。"),
    ("忘れてはならないこと：", "第1相の結果が示すのは安全性とバイオマーカーのシグナルだけ。減量と体重維持の有効性はまだ証明されていない。"),
    ("今後：", "第2相試験は2026年末に始まる予定。")]),
})

# 21 — Domestic drug or a promise (SMA)
CARDS['yerli'] = ('navy', {
 'en': D("SMA DRUGS", "A domestic drug, or a promise?", "The statements versus the realities of patents and cost",
   [("2030–34", "core patent expiry in the US (TÜSEB's own report)"), ("2032", "end of SPC protection in the EU"), ("0", "approved biosimilars"), ("300–3,000", "patient numbers differ up to 5-fold between sources")], None,
   [("26 Sep 2025:", "nusinersen synthesis completed; mass production promised for 'the first half of 2026'."),
    ("26 Nov 2025:", "TÜSEB–Polifarma protocol signed; 14 million dollars reported spent."),
    ("16 Aug 2026:", "the Minister again said 'we will produce'; the earlier timetable was not mentioned.")],
   "Repeating a statement does not make it true. A promise is not evidence."),
 'de': D("SMA-MEDIKAMENTE", "Heimisches Medikament oder Versprechen?", "Die Erklärungen und die Realität von Patenten und Kosten",
   [("2030–34", "Ablauf des Basispatents in den USA (TÜSEBs eigener Bericht)"), ("2032", "Ende des SPC-Schutzes in der EU"), ("0", "zugelassene Biosimilars"), ("300–3.000", "Patientenzahlen unterscheiden sich je nach Quelle bis zum 5-Fachen")], None,
   [("26. Sept. 2025:", "Nusinersen-Synthese abgeschlossen; Serienproduktion für „das erste Halbjahr 2026“ versprochen."),
    ("26. Nov. 2025:", "TÜSEB-Polifarma-Protokoll unterzeichnet; Ausgaben von 14 Millionen Dollar genannt."),
    ("16. Aug. 2026:", "Der Minister sagte erneut „wir werden produzieren“; der frühere Zeitplan blieb unerwähnt.")],
   "Eine Erklärung wird durch Wiederholung nicht wahr. Ein Versprechen ist kein Beweis."),
 'es': D("FÁRMACOS PARA LA AME", "¿Fármaco nacional o promesa?", "Las declaraciones frente a la realidad de las patentes y los costes",
   [("2030–34", "vencimiento de la patente básica en EE. UU. (informe del propio TÜSEB)"), ("2032", "fin de la protección por CCP en la UE"), ("0", "biosimilares aprobados"), ("300–3.000", "el número de pacientes varía hasta 5 veces según la fuente")], None,
   [("26 sep. 2025:", "síntesis de nusinersén completada; producción en serie prometida para «el primer semestre de 2026»."),
    ("26 nov. 2025:", "se firma el protocolo TÜSEB-Polifarma; se declara un gasto de 14 millones de dólares."),
    ("16 ago. 2026:", "el ministro volvió a decir «lo produciremos»; no se mencionó el calendario anterior.")],
   "Repetir una declaración no la convierte en verdad. Una promesa no es una prueba."),
 'ru': D("ПРЕПАРАТЫ ДЛЯ СМА", "Отечественное лекарство или обещание?", "Заявления и реальность патентов и затрат",
   [("2030–34", "истечение базового патента в США (собственный отчёт TÜSEB)"), ("2032", "окончание защиты SPC в ЕС"), ("0", "одобренных биоаналогов"), ("300–3000", "число пациентов различается до 5 раз в разных источниках")], None,
   [("26 сент. 2025:", "синтез нусинерсена завершён; серийное производство обещано в «первой половине 2026 года»."),
    ("26 нояб. 2025:", "подписан протокол TÜSEB–Polifarma; сообщено о расходах 14 млн долларов."),
    ("16 авг. 2026:", "министр вновь заявил «будем производить»; прежний срок не упоминался.")],
   "От повторения заявление не становится правдой. Обещание не доказательство."),
 'zh': D("脊髓性肌萎缩症药物", "国产药，还是一句承诺？", "官方表态与专利和成本的现实",
   [("2030–34年", "美国核心专利到期（TÜSEB自己的报告）"), ("2032年", "欧盟补充保护证书到期"), ("0", "已获批的同类仿制产品"), ("300–3000人", "不同来源的患者人数相差最多5倍")], None,
   [("2025年9月26日：", "诺西那生钠合成完成；承诺“2026年上半年”量产。"),
    ("2025年11月26日：", "TÜSEB与Polifarma签署协议；宣布已花费1400万美元。"),
    ("2026年8月16日：", "部长再次表示“我们会生产”；此前的时间表只字未提。")],
   "一句话重复多遍并不会成真。承诺不是证据。"),
 'hi': D("SMA की दवाएँ", "स्वदेशी दवा, या वादा?", "बयान बनाम पेटेंट और लागत की हकीकत",
   [("2030–34", "अमेरिका में मूल पेटेंट की समाप्ति (TÜSEB की अपनी रिपोर्ट)"), ("2032", "यूरोपीय संघ में SPC संरक्षण की समाप्ति"), ("0", "स्वीकृत बायोसिमिलर"), ("300–3,000", "स्रोतों के अनुसार मरीज़ों की संख्या में 5 गुना तक अंतर")], None,
   [("26 सितं. 2025:", "नुसिनर्सेन का संश्लेषण पूरा; “2026 की पहली छमाही” में बड़े पैमाने पर उत्पादन का वादा।"),
    ("26 नवं. 2025:", "TÜSEB–Polifarma प्रोटोकॉल पर हस्ताक्षर; 1.4 करोड़ डॉलर खर्च बताया गया।"),
    ("16 अग. 2026:", "मंत्री ने फिर कहा “हम उत्पादन करेंगे”; पिछली समय-सीमा का ज़िक्र नहीं।")],
   "बयान दोहराने से सच नहीं बनता। वादा प्रमाण नहीं है।"),
 'ja': D("SMA治療薬", "国産薬か、それとも約束か", "発言と、特許およびコストの現実",
   [("2030〜34年", "米国での基本特許満了（TÜSEB自身の報告書）"), ("2032年", "EUでのSPC保護の終了"), ("0", "承認された後続品"), ("300〜3,000人", "患者数は情報源によって最大5倍の開き")], None,
   [("2025年9月26日：", "ヌシネルセンの合成完了。量産は「2026年前半」と約束。"),
    ("2025年11月26日：", "TÜSEBとPolifarmaが議定書に署名。1,400万ドルを支出したと発表。"),
    ("2026年8月16日：", "大臣は再び「生産する」と述べたが、以前の日程には触れなかった。")],
   "発言は繰り返しても事実にはならない。約束は証拠ではない。"),
})
