from batch1 import D
from batch2 import BM
CARDS = {}

# 63 — TİTCK presidents change
CARDS['titckbaskan'] = ('navy', {
 'en': D("AN ASSESSMENT OF TÜRKİYE'S DRUG REGULATORY AUTHORITY", "TİTCK's presidents keep changing. But where is the agency heading?", "Eight presidencies between 2012 and 2026", None, None,
   [("Why it matters:", "TİTCK directly affects public health, from drug licensing and GMP inspections to bioequivalence, clinical trials, pharmacovigilance and medical devices."),
    ("How much power does the president really have?", "drug policy, pricing, reimbursement and local-production strategy are not decided by TİTCK alone; the Ministry of Health and other public bodies shape them."),
    ("The open question:", "is the president the leader of an independent regulator that makes policy, or a senior official who implements policies decided elsewhere?"),
    ("Elsewhere:", "the FDA Commissioner has wide autonomy in scientific decisions; the EMA Executive Director works within an institution independent of politics.")],
   "An agency's real strength is shown not by who its president is, but by whether it keeps the same scientific standards when the president changes."),
 'de': D("EINE BEWERTUNG DER TÜRKISCHEN ARZNEIMITTELBEHÖRDE", "Bei der TİTCK wechseln die Präsidenten. Aber wohin steuert die Behörde?", "Acht Präsidentschaften zwischen 2012 und 2026", None, None,
   [("Warum es wichtig ist:", "Die TİTCK betrifft die öffentliche Gesundheit unmittelbar, von Zulassung und GMP-Inspektionen bis zu Bioäquivalenz, klinischen Studien, Pharmakovigilanz und Medizinprodukten."),
    ("Wie viel Macht hat der Präsident wirklich?", "Arzneimittelpolitik, Preise, Erstattung und Strategien zur Inlandsproduktion werden nicht allein von der TİTCK bestimmt, sondern vom Gesundheitsministerium und anderen Stellen geprägt."),
    ("Die offene Frage:", "Ist der Präsident Leiter einer unabhängigen, politikgestaltenden Behörde oder ein hoher Beamter, der anderswo beschlossene Politik umsetzt?"),
    ("Andernorts:", "Der FDA-Commissioner hat große Autonomie bei wissenschaftlichen Entscheidungen; der EMA-Exekutivdirektor arbeitet in einer politisch unabhängigen Institution.")],
   "Die wahre Stärke einer Behörde zeigt sich nicht darin, wer sie leitet, sondern darin, ob sie nach einem Wechsel mit denselben wissenschaftlichen Standards weiterarbeitet."),
 'es': D("UNA VALORACIÓN DE LA AUTORIDAD REGULADORA DE MEDICAMENTOS DE TURQUÍA", "En la TİTCK cambian los presidentes. Pero ¿hacia dónde va la agencia?", "Ocho presidencias entre 2012 y 2026", None, None,
   [("Por qué importa:", "la TİTCK afecta directamente a la salud pública, desde la autorización y las inspecciones GMP hasta la bioequivalencia, los ensayos clínicos, la farmacovigilancia y los productos sanitarios."),
    ("¿Cuánto poder tiene realmente el presidente?", "la política farmacéutica, los precios, el reembolso y la producción local no los decide solo la TİTCK; los definen el Ministerio de Sanidad y otros organismos."),
    ("La pregunta abierta:", "¿es el presidente el líder de un regulador independiente que formula políticas, o un alto funcionario que aplica las decididas en otro lugar?"),
    ("En otros lugares:", "el comisionado de la FDA tiene amplia autonomía en las decisiones científicas; el director ejecutivo de la EMA trabaja en una institución independiente de la política.")],
   "La verdadera fuerza de una institución no se ve en quién la preside, sino en que siga trabajando con los mismos estándares científicos cuando cambia el presidente."),
 'ru': D("ОЦЕНКА ТУРЕЦКОГО РЕГУЛЯТОРА ЛЕКАРСТВ", "В TİTCK меняются руководители. А куда движется само агентство?", "Восемь руководителей с 2012 по 2026 год", None, None,
   [("Почему это важно:", "TİTCK напрямую влияет на здоровье населения: от регистрации лекарств и инспекций GMP до биоэквивалентности, клинических исследований, фармаконадзора и медицинских изделий."),
    ("Насколько реальна власть руководителя?", "лекарственную политику, цены, возмещение и стратегию локального производства определяет не только TİTCK; их формируют Минздрав и другие госорганы."),
    ("Открытый вопрос:", "руководитель это глава независимого регулятора, формирующего политику, или высокопоставленный чиновник, исполняющий решения, принятые в другом месте?"),
    ("В других странах:", "комиссар FDA обладает большой самостоятельностью в научных решениях; исполнительный директор EMA работает в институте, независимом от политики.")],
   "Настоящая сила учреждения видна не по тому, кто его возглавляет, а по тому, сохраняет ли оно прежние научные стандарты при смене руководителя."),
 'zh': D("对土耳其药品监管机构的评估", "TİTCK的主席换了又换，机构将走向何方？", "2012至2026年间的八任主席", None, None,
   [("为什么重要：", "从药品上市许可、GMP检查到生物等效性、临床试验、药物警戒和医疗器械，TİTCK直接关系公众健康。"),
    ("主席究竟有多大权力？", "药品政策、定价、报销和本土生产战略并非由TİTCK单独决定，而是由卫生部等公共机构共同塑造。"),
    ("悬而未决的问题：", "主席是制定政策的独立监管机构领导者，还是执行他处既定政策的高级官员？"),
    ("其他国家：", "FDA局长在科学决策上有高度自主权；EMA执行主任在独立于政治的机构框架内工作。")],
   "一个机构真正的实力，不在于主席是谁，而在于主席更换之后能否继续坚持同样的科学标准。"),
 'hi': D("तुर्किये के दवा नियामक प्राधिकरण का मूल्यांकन", "TİTCK में अध्यक्ष बदलते रहते हैं। पर संस्था किधर जा रही है?", "2012 से 2026 के बीच आठ अध्यक्ष", None, None,
   [("यह क्यों अहम है:", "दवाओं के लाइसेंस और GMP निरीक्षण से लेकर जैव-समतुल्यता, क्लिनिकल ट्रायल, फार्माकोविजिलेंस और चिकित्सा उपकरणों तक, TİTCK सीधे जनस्वास्थ्य से जुड़ा है।"),
    ("अध्यक्ष के पास वास्तव में कितना अधिकार है?", "दवा नीति, मूल्य, प्रतिपूर्ति और स्थानीय उत्पादन की रणनीति अकेले TİTCK तय नहीं करता; स्वास्थ्य मंत्रालय और अन्य संस्थाएँ उन्हें आकार देती हैं।"),
    ("खुला प्रश्न:", "क्या अध्यक्ष नीति बनाने वाले स्वतंत्र नियामक का नेता है, या कहीं और तय नीतियों को लागू करने वाला वरिष्ठ अधिकारी?"),
    ("अन्य जगह:", "FDA आयुक्त को वैज्ञानिक निर्णयों में व्यापक स्वायत्तता है; EMA के कार्यकारी निदेशक राजनीति से स्वतंत्र संस्था में काम करते हैं।")],
   "किसी संस्था की असली ताक़त इससे नहीं दिखती कि अध्यक्ष कौन है, बल्कि इससे कि अध्यक्ष बदलने पर भी वह वही वैज्ञानिक मानक बनाए रखती है या नहीं।"),
 'ja': D("トルコの医薬品規制当局についての評価", "TİTCKでは長官が次々に替わる。では、機関はどこへ向かうのか", "2012年から2026年までに8人の長官", None, None,
   [("なぜ重要か：", "TİTCKは、医薬品の承認やGMP査察から、生物学的同等性、臨床試験、安全性監視、医療機器まで、公衆衛生に直接かかわる。"),
    ("長官の権限は実際どの程度か：", "医薬品政策、価格、償還、国内生産戦略はTİTCKだけで決まるのではなく、保健省など他の公的機関によって形づくられる。"),
    ("未解決の問い：", "長官は政策をつくる独立規制機関のリーダーなのか、それとも他所で決まった政策を実行する高級官僚なのか。"),
    ("他国では：", "FDA長官は科学的判断に大きな自律性を持ち、EMA長官は政治から独立した機関の枠組みで働く。")],
   "機関の本当の強さは、長官が誰かではなく、長官が替わっても同じ科学的基準で仕事を続けられるかどうかに表れる。"),
})

# 64 — Fixed-dose combinations licensing
CARDS['sabitdoz'] = ('navy', {
 'en': D("THE QUESTION IS CLEAR: WHERE IS THE EVIDENCE?", "Drug licensing where the evidence ends", "Fixed-dose combinations without an originator, the pharmacokinetic evidence gap and the limits of regulatory science in Türkiye: Apranax Plus and CODEFEN", None, None,
   [("The problem:", "fixed-dose combinations such as Apranax Plus and CODEFEN have no international originator; they were licensed in Türkiye for the first time in the world."),
    ("One NSAID plus one prodrug in the same tablet:", "naproxen with codeine. No study in the literature measures the pharmacokinetics of the combination within a single tablet; only pharmacodynamic studies exist."),
    ("The regulatory gap:", "the EMA publishes a public scientific assessment (EPAR) for every licence. Türkiye has no equivalent, so licensing decisions cannot be verified from outside."),
    ("What follows:", "a combination with no international reference logically belongs in the full-application category, with combination-specific pharmacokinetic evidence.")],
   "Our principle: science, transparency, accountability and public health."),
 'de': D("DIE FRAGE IST KLAR: WO IST DIE EVIDENZ?", "Arzneimittelzulassung dort, wo die Evidenz endet", "Fixkombinationen ohne Originator, die Lücke bei der pharmakokinetischen Evidenz und die Grenzen der Regulierungswissenschaft in der Türkei: Apranax Plus und CODEFEN", None, None,
   [("Das Problem:", "Fixkombinationen wie Apranax Plus und CODEFEN haben keinen internationalen Originator; sie wurden weltweit erstmals in der Türkei zugelassen."),
    ("Ein NSAR plus ein Prodrug in derselben Tablette:", "Naproxen mit Codein. Keine Studie in der Literatur misst die Pharmakokinetik der Kombination in einer Tablette; es gibt nur pharmakodynamische Studien."),
    ("Die Regulierungslücke:", "Die EMA veröffentlicht zu jeder Zulassung einen öffentlichen Bewertungsbericht (EPAR). In der Türkei fehlt Vergleichbares, daher sind Zulassungsentscheidungen von außen nicht überprüfbar."),
    ("Die Folgerung:", "Eine Kombination ohne internationale Referenz gehört logisch in die Kategorie Vollantrag, mit kombinationsspezifischer pharmakokinetischer Evidenz.")],
   "Unser Grundsatz: Wissenschaft, Transparenz, Rechenschaft und öffentliche Gesundheit."),
 'es': D("LA PREGUNTA ES CLARA: ¿DÓNDE ESTÁ LA EVIDENCIA?", "Autorización de medicamentos donde se acaba la evidencia", "Combinaciones a dosis fijas sin originador, el vacío de evidencia farmacocinética y los límites de la ciencia reguladora en Turquía: Apranax Plus y CODEFEN", None, None,
   [("El problema:", "combinaciones a dosis fijas como Apranax Plus y CODEFEN no tienen originador internacional; se autorizaron en Turquía por primera vez en el mundo."),
    ("Un AINE más un profármaco en el mismo comprimido:", "naproxeno con codeína. Ningún estudio mide la farmacocinética de la combinación en un solo comprimido; solo existen estudios farmacodinámicos."),
    ("El vacío regulador:", "la EMA publica un informe público de evaluación (EPAR) para cada autorización. Turquía no tiene un sistema equivalente, por lo que las decisiones no pueden verificarse desde fuera."),
    ("La consecuencia:", "una combinación sin referencia internacional debería tramitarse como solicitud completa, con evidencia farmacocinética específica de la combinación.")],
   "Nuestro principio: ciencia, transparencia, rendición de cuentas y salud pública."),
 'ru': D("ВОПРОС ЯСЕН: ГДЕ ДОКАЗАТЕЛЬСТВА?", "Регистрация лекарств там, где заканчиваются доказательства", "Фиксированные комбинации без оригинатора, пробел в фармакокинетических данных и пределы регуляторной науки в Турции: Apranax Plus и CODEFEN", None, None,
   [("В чём проблема:", "у фиксированных комбинаций вроде Apranax Plus и CODEFEN нет международного оригинатора; они впервые в мире зарегистрированы в Турции."),
    ("НПВП и пролекарство в одной таблетке:", "напроксен с кодеином. В литературе нет ни одного исследования фармакокинетики комбинации в одной таблетке; есть только фармакодинамические работы."),
    ("Регуляторный пробел:", "EMA публикует открытый отчёт об оценке (EPAR) по каждой регистрации. В Турции аналога нет, поэтому решения нельзя проверить извне."),
    ("Вывод:", "комбинация без международного референта логически относится к категории полной заявки, с фармакокинетическими данными именно для комбинации.")],
   "Наш принцип: наука, прозрачность, подотчётность и общественное здоровье."),
 'zh': D("问题很清楚：证据在哪里？", "证据止步之处的药品审批", "没有原研药的固定剂量复方、药代动力学证据缺口与土耳其监管科学的边界：以Apranax Plus和CODEFEN为例", None, None,
   [("问题所在：", "Apranax Plus和CODEFEN这类固定剂量复方在国际上没有原研药，是在土耳其全球首次获批。"),
    ("一种非甾体抗炎药加一种前药同在一片：", "萘普生加可待因。文献中没有任何研究测定过单片复方的药代动力学，只有药效学研究。"),
    ("监管缺口：", "EMA为每项上市许可发布公开的科学评估报告（EPAR）。土耳其没有对应制度，外界无法核实审批决定。"),
    ("由此可见：", "没有国际参照的复方按理应归入完整申请类别，并提供针对复方本身的药代动力学证据。")],
   "我们的原则：科学、透明、问责与公共健康。"),
 'hi': D("सवाल साफ़ है: प्रमाण कहाँ है?", "जहाँ प्रमाण ख़त्म होते हैं, वहाँ दवा का लाइसेंस", "बिना मूल उत्पाद वाले निश्चित-खुराक संयोजन, फार्माकोकाइनेटिक प्रमाण की कमी और तुर्किये में नियामक विज्ञान की सीमाएँ: Apranax Plus और CODEFEN", None, None,
   [("समस्या:", "Apranax Plus और CODEFEN जैसे निश्चित-खुराक संयोजनों का कोई अंतरराष्ट्रीय मूल उत्पाद नहीं; दुनिया में पहली बार इन्हें तुर्किये में लाइसेंस मिला।"),
    ("एक ही गोली में एक NSAID और एक प्रो-ड्रग:", "नैप्रोक्सेन के साथ कोडीन। साहित्य में एक ही गोली में इस संयोजन की फार्माकोकाइनेटिक्स मापने वाला कोई अध्ययन नहीं; केवल फार्माकोडायनामिक अध्ययन हैं।"),
    ("नियामकीय कमी:", "EMA हर लाइसेंस के लिए सार्वजनिक वैज्ञानिक मूल्यांकन (EPAR) प्रकाशित करता है। तुर्किये में ऐसी व्यवस्था नहीं, इसलिए निर्णयों की बाहर से पुष्टि नहीं हो सकती।"),
    ("निष्कर्ष:", "जिस संयोजन का अंतरराष्ट्रीय संदर्भ नहीं, उसे तर्कसंगत रूप से पूर्ण आवेदन की श्रेणी में, संयोजन-विशिष्ट फार्माकोकाइनेटिक प्रमाण के साथ आना चाहिए।")],
   "हमारा सिद्धांत: विज्ञान, पारदर्शिता, जवाबदेही और जनस्वास्थ्य।"),
 'ja': D("問いは明快だ。エビデンスはどこにあるのか", "エビデンスが尽きるところでの医薬品承認", "先発品のない配合剤、薬物動態エビデンスの空白、トルコの規制科学の限界：Apranax PlusとCODEFENを例に", None, None,
   [("問題：", "Apranax PlusやCODEFENのような配合剤には国際的な先発品がなく、世界で初めてトルコで承認された。"),
    ("NSAIDとプロドラッグを同じ錠剤に：", "ナプロキセンとコデイン。1錠中の配合剤の薬物動態を測定した研究は文献になく、薬力学的研究しかない。"),
    ("規制上の空白：", "EMAは承認ごとに公開の審査報告書（EPAR）を公表する。トルコには同等の仕組みがなく、承認判断を外部から検証できない。"),
    ("そこから言えること：", "国際的な参照品のない配合剤は、論理的には完全申請の区分に入り、配合剤固有の薬物動態エビデンスが求められるべきである。")],
   "私たちの原則：科学、透明性、説明責任、公衆衛生。"),
})

# 65 — What quality of drugs do we use
CARDS['kalite2'] = ('navy', {
 'en': D("DRUG QUALITY · THE ACTIVE SUBSTANCE SUPPLY CHAIN", "What quality of drugs are we using in Türkiye?", "The same active substance is sold in three qualities and at three prices, depending on how tightly the destination market is inspected",
   [("Highest price", "1. Regulated, pharmacopoeia quality: GMP plus USP/EP, certified. Target: EU and US"), ("−35%", "2. Local standard: local norms, slightly lower purity. Target: domestic, middle-income markets"), ("−40–60%", "3. Unregulated: uncertified, uninspected impurities. Target: weakly regulated countries")], None,
   [("The tablet still says '500 mg'.", "What changes is not the amount of active substance but its purity, impurity profile and the assurance of inspection."),
    ("How does it enter Türkiye?", "the system rests largely on documents: a GMP certificate, an import document and the batch certificate of analysis. Independent state analysis of every batch is not routine."),
    ("The weak point:", "all three documents rest on declarations. Forged certificates of analysis and GMP records are a documented phenomenon worldwide.")]),
 'de': D("ARZNEIMITTELQUALITÄT · LIEFERKETTE DER WIRKSTOFFE", "Welche Arzneimittelqualität verwenden wir in der Türkei?", "Derselbe Wirkstoff wird je nach Kontrolldichte des Zielmarkts in drei Qualitäten und zu drei Preisen verkauft",
   [("Höchster Preis", "1. Reguliert, Arzneibuchqualität: GMP plus USP/EP, zertifiziert. Ziel: EU und USA"), ("−35 %", "2. Lokaler Standard: lokale Normen, etwas geringere Reinheit. Ziel: Inlandsmärkte mit mittlerem Einkommen"), ("−40–60 %", "3. Unreguliert: unzertifiziert, ungeprüfte Verunreinigungen. Ziel: schwach regulierte Länder")], None,
   [("Auf der Tablette steht weiter „500 mg“.", "Es ändert sich nicht die Wirkstoffmenge, sondern Reinheit, Verunreinigungsprofil und die Sicherheit durch Kontrolle."),
    ("Wie gelangt es in die Türkei?", "Das System beruht weitgehend auf Dokumenten: GMP-Zertifikat, Einfuhrdokument und Analysenzertifikat der Charge. Eine unabhängige staatliche Analyse jeder Charge ist nicht Routine."),
    ("Die Schwachstelle:", "Alle drei Dokumente beruhen auf Erklärungen. Gefälschte Analysenzertifikate und GMP-Unterlagen sind weltweit belegt.")]),
 'es': D("CALIDAD DE LOS MEDICAMENTOS · CADENA DE SUMINISTRO DE PRINCIPIOS ACTIVOS", "¿Qué calidad de medicamentos usamos en Turquía?", "El mismo principio activo se vende en tres calidades y a tres precios según el grado de control del mercado de destino",
   [("Precio más alto", "1. Regulado, calidad de farmacopea: GMP más USP/EP, certificado. Destino: UE y EE. UU."), ("−35 %", "2. Estándar local: normas locales, pureza algo menor. Destino: mercado interno, renta media"), ("−40–60 %", "3. No regulado: sin certificar, impurezas sin controlar. Destino: países con regulación débil")], None,
   [("En el comprimido sigue poniendo «500 mg».", "Lo que cambia no es la cantidad de principio activo, sino la pureza, el perfil de impurezas y la garantía de inspección."),
    ("¿Cómo entra en Turquía?", "el sistema se basa sobre todo en documentos: certificado GMP, documento de importación y certificado de análisis del lote. El análisis estatal independiente de cada lote no es rutinario."),
    ("El punto débil:", "los tres documentos se basan en declaraciones. Los certificados de análisis y registros GMP falsos son un fenómeno documentado en el mundo.")]),
 'ru': D("КАЧЕСТВО ЛЕКАРСТВ · ЦЕПОЧКА ПОСТАВОК СУБСТАНЦИЙ", "Лекарства какого качества мы применяем в Турции?", "Одно и то же действующее вещество продаётся в трёх вариантах качества и по трём ценам в зависимости от строгости контроля на целевом рынке",
   [("Самая высокая цена", "1. Регулируемое, фармакопейное качество: GMP плюс USP/EP, сертифицировано. Рынки: ЕС и США"), ("−35 %", "2. Местный стандарт: местные нормы, чуть ниже чистота. Рынки: внутренние, со средним доходом"), ("−40–60 %", "3. Нерегулируемое: без сертификатов, неконтролируемые примеси. Рынки: страны со слабым регулированием")], None,
   [("На таблетке по-прежнему написано «500 мг».", "Меняется не количество действующего вещества, а его чистота, профиль примесей и гарантия контроля."),
    ("Как это попадает в Турцию?", "система в основном опирается на документы: сертификат GMP, импортный документ и сертификат анализа серии. Независимый государственный анализ каждой серии не является рутиной."),
    ("Слабое место:", "все три документа основаны на заявлениях. Поддельные сертификаты анализа и записи GMP являются задокументированным в мире явлением.")]),
 'zh': D("药品质量 · 原料药供应链", "我们在土耳其用的是什么质量的药？", "同一种有效成分，按目标市场监管的严格程度，以三种质量、三种价格出售",
   [("价格最高", "1. 受监管的药典级：GMP加USP/EP，有认证。目标市场：欧盟和美国"), ("−35%", "2. 本地标准：按本地规范，纯度略低。目标市场：国内、中等收入市场"), ("−40–60%", "3. 不受监管：无认证，杂质未经检查。目标市场：监管薄弱的国家")], None,
   [("药片上仍然写着“500毫克”。", "改变的不是有效成分的含量，而是纯度、杂质谱和监管保障。"),
    ("它是怎样进入土耳其的？", "这套体系主要依靠文件：GMP证书、进口文件和批次检验报告。国家对每一批次进行独立检验并非常规做法。"),
    ("薄弱环节：", "这三份文件都以申报为依据。伪造检验报告和GMP记录在全球都有据可查。")]),
 'hi': D("दवा की गुणवत्ता · सक्रिय पदार्थ की आपूर्ति शृंखला", "तुर्किये में हम किस गुणवत्ता की दवाएँ ले रहे हैं?", "वही सक्रिय पदार्थ, जिस बाज़ार में जाना है वहाँ की निगरानी के अनुसार, तीन गुणवत्ताओं और तीन कीमतों पर बिकता है",
   [("सबसे ऊँची कीमत", "1. विनियमित, फार्माकोपिया गुणवत्ता: GMP और USP/EP, प्रमाणित। लक्ष्य: यूरोपीय संघ और अमेरिका"), ("−35%", "2. स्थानीय मानक: स्थानीय मानदंड, शुद्धता कुछ कम। लक्ष्य: घरेलू, मध्यम आय वाले बाज़ार"), ("−40–60%", "3. अविनियमित: बिना प्रमाणपत्र, बिना जाँची अशुद्धियाँ। लक्ष्य: कमज़ोर विनियमन वाले देश")], None,
   [("गोली पर अब भी “500 मि.ग्रा.” ही लिखा है।", "बदलती है सक्रिय पदार्थ की मात्रा नहीं, बल्कि शुद्धता, अशुद्धियों की रूपरेखा और निरीक्षण का भरोसा।"),
    ("यह तुर्किये में कैसे आती है?", "व्यवस्था मोटे तौर पर दस्तावेज़ों पर टिकी है: GMP प्रमाणपत्र, आयात दस्तावेज़ और बैच का विश्लेषण प्रमाणपत्र। हर बैच का स्वतंत्र सरकारी विश्लेषण नियमित नहीं है।"),
    ("कमज़ोर कड़ी:", "तीनों दस्तावेज़ घोषणा पर आधारित हैं। जाली विश्लेषण प्रमाणपत्र और GMP अभिलेख दुनिया में दर्ज तथ्य हैं।")]),
 'ja': D("医薬品の品質 · 原薬のサプライチェーン", "トルコではどの品質の薬が使われているのか", "同じ有効成分が、出荷先市場の監督の厳しさに応じて、3つの品質と3つの価格で売られている",
   [("最も高い価格", "1. 規制市場向けの薬局方品質：GMPとUSP/EP、認証あり。対象はEUと米国"), ("−35%", "2. 現地規格：現地の基準で、純度はやや低い。対象は国内・中所得市場"), ("−40〜60%", "3. 規制対象外：認証なし、不純物は未検査。対象は規制の弱い国")], None,
   [("錠剤には相変わらず「500mg」と書かれている。", "変わるのは有効成分の量ではなく、純度、不純物プロファイル、そして監督による保証である。"),
    ("どうやってトルコに入るのか：", "制度は主に書類に基づく。GMP証明書、輸入書類、ロットの試験成績書である。ロットごとの国による独立した分析は日常的には行われていない。"),
    ("弱点：", "3つの書類はいずれも申告に基づく。偽造された試験成績書やGMP記録は世界で記録されている現象である。")]),
})

# 66 — Emergency contraception
CARDS['ertesigun'] = ('purple', {
 'en': D("HEALTH INFORMATION", "What is emergency contraception (the morning-after pill)?", "Methods that help prevent pregnancy after unprotected intercourse, a torn condom, a missed contraceptive pill or sexual assault",
   [("Up to 98%", "ulipristal acetate 30 mg: within the first 120 hours (5 days)"), ("Up to 85%", "levonorgestrel 1.5 mg: within the first 72 hours, most effective in the first 24"), (">99%", "the copper IUD, if fitted within 5 days: the most effective method is not a pill")], None,
   [("The earlier, the better:", "effectiveness is higher the sooner the pill is taken."),
    ("These pills do not end a pregnancy;", "they only work to prevent one from occurring."),
    ("Not a regular method:", "they should not replace regular contraception and do not protect against sexually transmitted infections."),
    ("Interactions:", "some drugs, such as antiepileptics, rifampicin and St John's wort, can reduce effectiveness. Levonorgestrel may be less effective in obesity.")],
   "Value yourself, be informed, stay safe."),
 'de': D("GESUNDHEITSINFORMATION", "Was ist Notfallverhütung (die „Pille danach“)?", "Methoden, die nach ungeschütztem Verkehr, gerissenem Kondom, vergessener Pille oder sexueller Gewalt eine Schwangerschaft verhindern helfen",
   [("Bis zu 98 %", "Ulipristalacetat 30 mg: in den ersten 120 Stunden (5 Tage)"), ("Bis zu 85 %", "Levonorgestrel 1,5 mg: in den ersten 72 Stunden, am wirksamsten in den ersten 24"), (">99 %", "die Kupferspirale, wenn sie binnen 5 Tagen eingesetzt wird: Die wirksamste Methode ist keine Pille")], None,
   [("Je früher, desto besser:", "Die Wirksamkeit ist umso höher, je eher die Pille eingenommen wird."),
    ("Diese Pillen beenden keine Schwangerschaft;", "sie wirken nur, indem sie ihr Entstehen verhindern."),
    ("Keine reguläre Methode:", "Sie sollen die regelmäßige Verhütung nicht ersetzen und schützen nicht vor sexuell übertragbaren Infektionen."),
    ("Wechselwirkungen:", "Einige Mittel wie Antiepileptika, Rifampicin und Johanniskraut können die Wirkung verringern. Levonorgestrel kann bei Adipositas weniger wirksam sein.")],
   "Achte auf dich, sei informiert, bleib sicher."),
 'es': D("INFORMACIÓN DE SALUD", "¿Qué es la anticoncepción de urgencia (la píldora del día después)?", "Métodos que ayudan a evitar el embarazo tras una relación sin protección, la rotura del preservativo, el olvido de la píldora o una agresión sexual",
   [("Hasta 98 %", "acetato de ulipristal 30 mg: en las primeras 120 horas (5 días)"), ("Hasta 85 %", "levonorgestrel 1,5 mg: en las primeras 72 horas, más eficaz en las primeras 24"), (">99 %", "el DIU de cobre, colocado en 5 días: el método más eficaz no es una píldora")], None,
   [("Cuanto antes, mejor:", "la eficacia es mayor cuanto antes se tome."),
    ("Estas píldoras no interrumpen un embarazo;", "solo actúan para evitar que se produzca."),
    ("No es un método habitual:", "no deben sustituir a la anticoncepción regular y no protegen frente a las infecciones de transmisión sexual."),
    ("Interacciones:", "algunos fármacos, como antiepilépticos, rifampicina o hipérico, pueden reducir la eficacia. El levonorgestrel puede ser menos eficaz en la obesidad.")],
   "Valórate, infórmate, mantente segura."),
 'ru': D("ИНФОРМАЦИЯ О ЗДОРОВЬЕ", "Что такое экстренная контрацепция (таблетка «на следующий день»)?", "Методы, помогающие предотвратить беременность после незащищённого контакта, разрыва презерватива, пропуска противозачаточной таблетки или сексуального насилия",
   [("До 98 %", "улипристала ацетат 30 мг: в первые 120 часов (5 дней)"), ("До 85 %", "левоноргестрел 1,5 мг: в первые 72 часа, максимально в первые 24"), (">99 %", "медная спираль, установленная в течение 5 дней: самый эффективный метод не таблетка")], None,
   [("Чем раньше, тем лучше:", "эффективность тем выше, чем раньше принят препарат."),
    ("Эти таблетки не прерывают беременность;", "они лишь предотвращают её наступление."),
    ("Не метод на каждый день:", "они не должны заменять регулярную контрацепцию и не защищают от инфекций, передающихся половым путём."),
    ("Взаимодействия:", "некоторые средства (противоэпилептические, рифампицин, зверобой) могут снизить эффективность. При ожирении левоноргестрел может действовать слабее.")],
   "Цени себя, будь информирована, будь в безопасности."),
 'zh': D("健康知识", "什么是紧急避孕（事后避孕药）？", "在无保护性行为、避孕套破裂、漏服避孕药或遭受性侵之后，帮助预防怀孕的方法",
   [("最高98%", "醋酸乌利司他30毫克：最初120小时（5天）内"), ("最高85%", "左炔诺孕酮1.5毫克：最初72小时内，头24小时效果最好"), (">99%", "5天内放置含铜宫内节育器：最有效的方法并不是药片")], None,
   [("越早越好：", "服药越早，效果越好。"),
    ("这类药物不能终止妊娠，", "只能阻止妊娠的发生。"),
    ("不是常规避孕方法：", "不应代替常规避孕，也不能预防性传播感染。"),
    ("药物相互作用：", "抗癫痫药、利福平、圣约翰草等可降低药效。左炔诺孕酮在肥胖者中效果可能下降。")],
   "珍视自己，了解知识，保障安全。"),
 'hi': D("स्वास्थ्य जानकारी", "आपातकालीन गर्भनिरोध (अगली सुबह की गोली) क्या है?", "असुरक्षित संबंध, कंडोम फटने, गर्भनिरोधक गोली भूलने या यौन हमले के बाद गर्भ रोकने में मदद करने वाले तरीक़े",
   [("98% तक", "यूलिप्रिस्टल एसीटेट 30 मि.ग्रा.: पहले 120 घंटों (5 दिन) में"), ("85% तक", "लेवोनॉर्जेस्ट्रेल 1.5 मि.ग्रा.: पहले 72 घंटों में, पहले 24 घंटों में सबसे प्रभावी"), (">99%", "कॉपर IUD, 5 दिनों के भीतर लगाने पर: सबसे प्रभावी तरीक़ा गोली नहीं है")], None,
   [("जितनी जल्दी, उतना बेहतर:", "गोली जितनी जल्दी ली जाए, प्रभाव उतना अधिक।"),
    ("ये गोलियाँ गर्भ समाप्त नहीं करतीं;", "ये केवल गर्भ ठहरने से रोकती हैं।"),
    ("नियमित तरीक़ा नहीं:", "इन्हें नियमित गर्भनिरोध की जगह नहीं लेना चाहिए और ये यौन संचारित संक्रमणों से नहीं बचातीं।"),
    ("अंतःक्रियाएँ:", "कुछ दवाएँ (मिर्गीरोधी, रिफ़ैम्पिसिन, सेंट जॉन्स वॉर्ट) प्रभाव घटा सकती हैं। मोटापे में लेवोनॉर्जेस्ट्रेल का असर कम हो सकता है।")],
   "ख़ुद को महत्व दें, जानकार रहें, सुरक्षित रहें।"),
 'ja': D("健康情報", "緊急避妊（アフターピル）とは", "避妊をしなかった性交、コンドームの破損、経口避妊薬の飲み忘れ、性暴力の後に、妊娠を防ぐ助けとなる方法",
   [("最大98%", "ウリプリスタル酢酸エステル30mg：最初の120時間（5日）以内"), ("最大85%", "レボノルゲストレル1.5mg：最初の72時間以内。24時間以内が最も有効"), ("99%超", "5日以内に装着する銅付加IUD。最も有効な方法は錠剤ではない")], None,
   [("早いほどよい：", "服用が早いほど効果は高い。"),
    ("これらの薬は妊娠を終わらせるものではなく、", "妊娠の成立を防ぐだけである。"),
    ("日常的な避妊法ではない：", "通常の避妊の代わりにすべきではなく、性感染症も防げない。"),
    ("相互作用：", "抗てんかん薬、リファンピシン、セントジョーンズワートなどで効果が弱まることがある。レボノルゲストレルは肥満の場合に効果が下がる可能性がある。")],
   "自分を大切に。正しく知って、安全に。"),
})

# 67 — EU pharma reform
CARDS['abreform'] = ('blue', {
 'en': D("EUROPEAN UNION 2026", "The great reform of pharmaceutical legislation", "A fundamental overhaul after 20 years",
   [("27 countries", "Accessibility: simultaneous market launch across the EU is the aim"), ("10 → 6 years", "Data protection, plus conditional extensions of up to 4 years"), ("210 → 180 days", "Faster approval: EMA procedures are shortened")], None,
   [("AMR voucher:", "a transferable data-exclusivity voucher for a company that develops a new antibiotic."),
    ("Environmental protection:", "a licence can be suspended if the environmental risk assessment fails."),
    ("Security of supply:", "supply-chain transparency to prevent shortages, especially of antibiotics and cancer drugs.")],
   "Global effect: it affects every country that follows EU legislation, including Türkiye."),
 'de': D("EUROPÄISCHE UNION 2026", "Die große Reform des Arzneimittelrechts", "Eine grundlegende Erneuerung nach 20 Jahren",
   [("27 Länder", "Zugänglichkeit: Ziel ist die gleichzeitige Markteinführung in der ganzen EU"), ("10 → 6 Jahre", "Unterlagenschutz, plus bedingte Verlängerungen bis zu 4 Jahren"), ("210 → 180 Tage", "Schnellere Zulassung: Die EMA-Verfahren werden verkürzt")], None,
   [("AMR-Gutschein:", "ein übertragbarer Gutschein für Datenexklusivität für Unternehmen, die ein neues Antibiotikum entwickeln."),
    ("Umweltschutz:", "Bei unzureichender Umweltrisikobewertung kann die Zulassung ausgesetzt werden."),
    ("Versorgungssicherheit:", "Transparenz der Lieferkette, um Engpässe zu verhindern, besonders bei Antibiotika und Krebsmedikamenten.")],
   "Globale Wirkung: betrifft alle Länder, die dem EU-Recht folgen, auch die Türkei."),
 'es': D("UNIÓN EUROPEA 2026", "La gran reforma de la legislación farmacéutica", "Una renovación de fondo tras 20 años",
   [("27 países", "Accesibilidad: se busca el lanzamiento simultáneo en toda la UE"), ("10 → 6 años", "Protección de datos, más prórrogas condicionadas de hasta 4 años"), ("210 → 180 días", "Aprobación más rápida: se acortan los procedimientos de la EMA")], None,
   [("Bono AMR:", "un bono transferible de exclusividad de datos para la empresa que desarrolle un nuevo antibiótico."),
    ("Protección ambiental:", "la autorización puede suspenderse si falla la evaluación del riesgo ambiental."),
    ("Seguridad del suministro:", "transparencia de la cadena de suministro para evitar desabastecimientos, sobre todo de antibióticos y oncológicos.")],
   "Efecto global: afecta a todos los países que siguen la legislación de la UE, incluida Turquía."),
 'ru': D("ЕВРОПЕЙСКИЙ СОЮЗ 2026", "Большая реформа фармацевтического законодательства", "Коренное обновление спустя 20 лет",
   [("27 стран", "Доступность: цель одновременный вывод на рынок по всему ЕС"), ("10 → 6 лет", "Защита данных плюс условные продления до 4 лет"), ("210 → 180 дней", "Ускоренное одобрение: процедуры EMA сокращаются")], None,
   [("Ваучер для антибиотиков:", "передаваемый ваучер эксклюзивности данных для компании, разработавшей новый антибиотик."),
    ("Охрана окружающей среды:", "регистрация может быть приостановлена, если оценка экологического риска неудовлетворительна."),
    ("Безопасность поставок:", "прозрачность цепочки поставок для предотвращения дефицита, особенно антибиотиков и противоопухолевых препаратов.")],
   "Глобальный эффект: затрагивает все страны, ориентирующиеся на право ЕС, включая Турцию."),
 'zh': D("欧盟 2026", "药品立法大改革", "时隔20年的根本性更新",
   [("27个国家", "可及性：目标是在欧盟各国同步上市"), ("10年 → 6年", "数据保护期，另有最长4年的附条件延长"), ("210天 → 180天", "加快审批：EMA程序缩短")], None,
   [("抗菌药凭证：", "向开发新抗生素的企业发放可转让的数据独占凭证。"),
    ("环境保护：", "环境风险评估不达标时可暂停上市许可。"),
    ("供应安全：", "提高供应链透明度以防短缺，尤其是抗生素和抗癌药。")],
   "全球影响：波及所有参照欧盟法规的国家，包括土耳其。"),
 'hi': D("यूरोपीय संघ 2026", "दवा कानून का बड़ा सुधार", "20 वर्ष बाद बुनियादी नवीनीकरण",
   [("27 देश", "सुलभता: पूरे यूरोपीय संघ में एक साथ बाज़ार में उतारने का लक्ष्य"), ("10 → 6 वर्ष", "डेटा संरक्षण, साथ में 4 वर्ष तक के सशर्त विस्तार"), ("210 → 180 दिन", "तेज़ मंज़ूरी: EMA की प्रक्रियाएँ छोटी हुईं")], None,
   [("AMR वाउचर:", "नया एंटीबायोटिक विकसित करने वाली कंपनी को हस्तांतरणीय डेटा-विशिष्टता वाउचर।"),
    ("पर्यावरण संरक्षण:", "पर्यावरणीय जोखिम मूल्यांकन विफल होने पर लाइसेंस निलंबित हो सकता है।"),
    ("आपूर्ति सुरक्षा:", "कमी रोकने के लिए आपूर्ति शृंखला में पारदर्शिता, ख़ासकर एंटीबायोटिक और कैंसर की दवाओं में।")],
   "वैश्विक प्रभाव: तुर्किये सहित उन सभी देशों पर असर, जो यूरोपीय संघ के कानून का अनुसरण करते हैं।"),
 'ja': D("欧州連合 2026", "医薬品法制の大改革", "20年ぶりの抜本的な見直し",
   [("27か国", "アクセス：EU全域での同時発売を目指す"), ("10年 → 6年", "データ保護期間。条件付きで最長4年の延長あり"), ("210日 → 180日", "承認の迅速化：EMAの手続きを短縮")], None,
   [("AMRバウチャー：", "新しい抗菌薬を開発した企業に、譲渡可能なデータ独占権バウチャーを付与。"),
    ("環境保護：", "環境リスク評価が不十分な場合、承認を停止できる。"),
    ("供給の安定：", "抗菌薬やがん治療薬を中心に、不足を防ぐためサプライチェーンの透明性を高める。")],
   "世界への影響：トルコを含め、EU法制を参照するすべての国に及ぶ。"),
})

# 69 — Value-based pricing (English image from English article)
CARDS['degerbazli'] = ('navy', {
 'de': D(BM['de'], "Wertbasierte Preisbildung bei Arzneimitteln", "Das Gleichgewicht von Wissenschaft, Ökonomie, Ethik und Nachhaltigkeit. Wert = Ergebnis / Kosten"),
 'es': D(BM['es'], "Precios de los medicamentos basados en el valor", "El equilibrio entre ciencia, economía, ética y sostenibilidad. Valor = resultado / coste"),
 'ru': D(BM['ru'], "Ценообразование на лекарства на основе ценности", "Баланс науки, экономики, этики и устойчивости. Ценность = результат / затраты"),
 'zh': D(BM['zh'], "药品的基于价值定价", "科学、经济、伦理与可持续性的平衡。价值 = 结果 / 成本"),
 'hi': D(BM['hi'], "दवाओं में मूल्य-आधारित मूल्य निर्धारण", "विज्ञान, अर्थशास्त्र, नैतिकता और टिकाऊपन का संतुलन। मूल्य = परिणाम / लागत"),
 'ja': D(BM['ja'], "医薬品の価値に基づく価格設定", "科学、経済、倫理、持続可能性のバランス。価値 = 成果 / 費用"),
})

# 70 — Vitamin D
CARDS['dvit'] = ('navy', {
 'en': D("VITAMIN D", "Vitamin D deficiency, or a vitamin D testing epidemic?", "Not every low vitamin D result means deficiency",
   [("57%", "of tests are unnecessary (outside the guidelines)"), ("£38 m+", "annual loss to the NHS"), ("£28 m → £92 m", "prescription spending in England over 10 years")], None,
   [("Real risk groups:", "the very old, vegans and vegetarians, people who get no sun, malabsorption (Crohn's, coeliac disease, bypass surgery), dark-skinned people, premature babies and kidney disease."),
    ("What you should know:", "there is no universal 'sufficiency' threshold; a low result is not always disease; supplements are not a miracle and high doses can be harmful."),
    ("Testing:", "routine screening outside risk groups is not recommended. If there are no symptoms, do not order the test."),
    ("Trials:", "VITAL and D-HEALTH showed no miracle effect.")],
   "The first question should not be 'What is the vitamin D level?' but 'Is this patient really deficient?'"),
 'de': D("VITAMIN D", "Vitamin-D-Mangel oder eine Epidemie der Vitamin-D-Tests?", "Nicht jeder niedrige Vitamin-D-Wert bedeutet einen Mangel",
   [("57 %", "der Tests sind unnötig (außerhalb der Leitlinien)"), ("38 Mio. £+", "jährlicher Verlust für den NHS"), ("28 → 92 Mio. £", "Verordnungsausgaben in England binnen 10 Jahren")], None,
   [("Echte Risikogruppen:", "Hochbetagte, Veganer und Vegetarier, Menschen ohne Sonnenexposition, Malabsorption (Crohn, Zöliakie, Bypass), dunkelhäutige Menschen, Frühgeborene und Nierenkranke."),
    ("Was man wissen sollte:", "Es gibt keinen universellen Schwellenwert; ein niedriger Wert ist nicht immer Krankheit; Supplemente sind kein Wundermittel, hohe Dosen können schaden."),
    ("Tests:", "Routine-Screening außerhalb von Risikogruppen wird nicht empfohlen. Ohne Symptome keinen Test anfordern."),
    ("Studien:", "VITAL und D-HEALTH zeigten keinen Wundereffekt.")],
   "Die erste Frage sollte nicht lauten „Wie hoch ist der Vitamin-D-Spiegel?“, sondern „Hat dieser Patient wirklich einen Mangel?“"),
 'es': D("VITAMINA D", "¿Déficit de vitamina D o epidemia de análisis de vitamina D?", "No todo resultado bajo de vitamina D significa déficit",
   [("57 %", "de las pruebas son innecesarias (fuera de las guías)"), ("38 M£+", "pérdida anual para el NHS"), ("28 → 92 M£", "gasto en recetas en Inglaterra en 10 años")], None,
   [("Grupos de riesgo reales:", "personas muy mayores, veganos y vegetarianos, quienes no toman el sol, malabsorción (Crohn, celiaquía, bypass), personas de piel oscura, prematuros y enfermedad renal."),
    ("Lo que conviene saber:", "no existe un umbral universal de «suficiencia»; un resultado bajo no siempre es enfermedad; el suplemento no es un milagro y las dosis altas pueden dañar."),
    ("Pruebas:", "no se recomienda el cribado rutinario fuera de los grupos de riesgo. Si no hay síntomas, no pida la prueba."),
    ("Ensayos:", "VITAL y D-HEALTH no mostraron un efecto milagroso.")],
   "La primera pregunta no debería ser «¿cuál es el nivel de vitamina D?», sino «¿tiene este paciente realmente un déficit?»"),
 'ru': D("ВИТАМИН D", "Дефицит витамина D или эпидемия анализов на витамин D?", "Не каждый низкий результат означает дефицит",
   [("57 %", "анализов не нужны (вне рекомендаций)"), ("38 млн £+", "ежегодные потери NHS"), ("28 → 92 млн £", "расходы на рецепты в Англии за 10 лет")], None,
   [("Настоящие группы риска:", "люди преклонного возраста, веганы и вегетарианцы, те, кто не бывает на солнце, мальабсорбция (болезнь Крона, целиакия, шунтирование), люди с тёмной кожей, недоношенные дети, болезни почек."),
    ("Что нужно знать:", "универсального порога «достаточности» нет; низкий результат не всегда болезнь; добавки не чудо, а высокие дозы могут навредить."),
    ("Анализы:", "рутинный скрининг вне групп риска не рекомендуется. Нет симптомов, не назначайте анализ."),
    ("Исследования:", "VITAL и D-HEALTH не показали чудесного эффекта.")],
   "Первый вопрос должен быть не «какой уровень витамина D?», а «есть ли у этого пациента действительно дефицит?»"),
 'zh': D("维生素D", "是维生素D缺乏，还是维生素D检测泛滥？", "并非每个偏低的维生素D结果都意味着缺乏",
   [("57%", "的检测没有必要（不符合指南）"), ("3800万英镑以上", "英国国家医疗服务体系每年的损失"), ("2800万 → 9200万英镑", "英格兰10年间的处方支出")], None,
   [("真正的高危人群：", "高龄老人、纯素和素食者、不晒太阳的人、吸收不良（克罗恩病、乳糜泻、胃旁路手术）、深肤色人群、早产儿和肾病患者。"),
    ("需要知道：", "没有通用的“充足”阈值；结果偏低不一定是疾病；补充剂不是灵丹妙药，大剂量可能有害。"),
    ("检测：", "不建议对高危人群以外的人常规筛查。没有症状就不要开检测。"),
    ("试验：", "VITAL和D-HEALTH研究没有显示神奇效果。")],
   "首先该问的不是“维生素D水平是多少”，而是“这位患者真的缺乏吗”。"),
 'hi': D("विटामिन D", "विटामिन D की कमी, या विटामिन D जाँच की महामारी?", "हर कम विटामिन D परिणाम का मतलब कमी नहीं होता",
   [("57%", "जाँचें अनावश्यक हैं (दिशानिर्देशों के बाहर)"), ("3.8 करोड़ पाउंड+", "NHS को वार्षिक नुकसान"), ("2.8 → 9.2 करोड़ पाउंड", "इंग्लैंड में 10 वर्षों में नुस्खों पर खर्च")], None,
   [("असली जोखिम समूह:", "बहुत बुज़ुर्ग, वीगन और शाकाहारी, धूप में न निकलने वाले, अवशोषण की गड़बड़ी (क्रोन, सीलिएक, बाइपास), गहरी त्वचा वाले, समय-पूर्व जन्मे शिशु और गुर्दे के रोगी।"),
    ("जानने योग्य:", "“पर्याप्तता” की कोई सार्वभौमिक सीमा नहीं; कम परिणाम हमेशा रोग नहीं; पूरक चमत्कार नहीं और ऊँची खुराक हानिकारक हो सकती है।"),
    ("जाँच:", "जोखिम समूहों के बाहर नियमित जाँच की सलाह नहीं। लक्षण न हों तो जाँच न लिखें।"),
    ("अध्ययन:", "VITAL और D-HEALTH में कोई चमत्कारी असर नहीं दिखा।")],
   "पहला सवाल “विटामिन D का स्तर कितना है?” नहीं, बल्कि “क्या इस मरीज़ में वाक़ई कमी है?” होना चाहिए।"),
 'ja': D("ビタミンD", "ビタミンD不足か、それともビタミンD検査の流行か", "ビタミンDの値が低いからといって、必ずしも欠乏ではない",
   [("57%", "の検査は不要（ガイドライン外）"), ("3,800万ポンド超", "NHSの年間損失"), ("2,800万 → 9,200万ポンド", "イングランドの処方支出（10年間）")], None,
   [("本当のリスク群：", "超高齢者、ヴィーガン・菜食の人、日光に当たらない人、吸収不良（クローン病、セリアック病、バイパス術後）、肌の色が濃い人、早産児、腎臓病の人。"),
    ("知っておくべきこと：", "「充足」の普遍的な基準値はない。低値が常に病気とは限らない。サプリメントは奇跡の薬ではなく、高用量は害になりうる。"),
    ("検査：", "リスク群以外での定期的なスクリーニングは推奨されない。症状がなければ検査を依頼しない。"),
    ("臨床試験：", "VITAL試験とD-HEALTH試験で劇的な効果は示されなかった。")],
   "最初に問うべきは「ビタミンDの値はいくつか」ではなく、「この患者に本当に欠乏があるのか」である。"),
})

# 71 — Pharmacology education
CARDS['egitim'] = ('blue', {
 'en': D("FROM ROTE LEARNING TO ARTIFICIAL INTELLIGENCE", "Pharmacology education in the 21st century", "Science, technology, clinical practice, ethics and sustainability", None, "WHAT IT SHOULD COVER",
   [("Pharmacogenetics and personalised medicine:", "predicting a drug's efficacy and safety from a person's genetic make-up."),
    ("Big data and real-world evidence:", "strengthening evidence-based decisions with real-life data."),
    ("Artificial intelligence:", "AI-supported approaches from drug discovery to clinical decisions."),
    ("Clinical pharmacology and rational drug use:", "the right drug, for the right patient, at the right dose, for the right time."),
    ("Pharmacovigilance:", "monitoring drug safety and protecting public health."),
    ("The pharmacologist of the future:", "scientific, digitally competent, a clinical thinker, ethically responsible and a lifelong learner.")],
   "Pharmacology is no longer a course; it is the foundation of the health system of the future."),
 'de': D("VOM AUSWENDIGLERNEN ZUR KÜNSTLICHEN INTELLIGENZ", "Pharmakologie-Ausbildung im 21. Jahrhundert", "Wissenschaft, Technologie, klinische Praxis, Ethik und Nachhaltigkeit", None, "WAS SIE UMFASSEN SOLLTE",
   [("Pharmakogenetik und personalisierte Medizin:", "Wirksamkeit und Sicherheit eines Arzneimittels aus der genetischen Ausstattung vorhersagen."),
    ("Big Data und Real-World-Evidenz:", "evidenzbasierte Entscheidungen mit Daten aus dem Versorgungsalltag stärken."),
    ("Künstliche Intelligenz:", "KI-gestützte Ansätze von der Wirkstoffsuche bis zur klinischen Entscheidung."),
    ("Klinische Pharmakologie und rationaler Arzneimitteleinsatz:", "das richtige Mittel für den richtigen Patienten, in richtiger Dosis und Dauer."),
    ("Pharmakovigilanz:", "Arzneimittelsicherheit überwachen und die öffentliche Gesundheit schützen."),
    ("Der Pharmakologe der Zukunft:", "wissenschaftlich, digital kompetent, klinisch denkend, ethisch verantwortlich und lebenslang lernend.")],
   "Pharmakologie ist kein Unterrichtsfach mehr; sie ist das Fundament des Gesundheitssystems der Zukunft."),
 'es': D("DE LA MEMORIZACIÓN A LA INTELIGENCIA ARTIFICIAL", "La enseñanza de la farmacología en el siglo XXI", "Ciencia, tecnología, práctica clínica, ética y sostenibilidad", None, "LO QUE DEBE ABARCAR",
   [("Farmacogenética y medicina personalizada:", "predecir la eficacia y seguridad de un fármaco según la genética de cada persona."),
    ("Big data y evidencia del mundo real:", "reforzar las decisiones basadas en la evidencia con datos de la vida real."),
    ("Inteligencia artificial:", "enfoques apoyados en IA, desde el descubrimiento de fármacos hasta las decisiones clínicas."),
    ("Farmacología clínica y uso racional:", "el fármaco adecuado, al paciente adecuado, a la dosis y durante el tiempo adecuados."),
    ("Farmacovigilancia:", "vigilar la seguridad de los medicamentos y proteger la salud pública."),
    ("El farmacólogo del futuro:", "científico, competente en lo digital, con pensamiento clínico, responsable en lo ético y en aprendizaje continuo.")],
   "La farmacología ya no es una asignatura; es la base del sistema sanitario del futuro."),
 'ru': D("ОТ ЗУБРЁЖКИ К ИСКУССТВЕННОМУ ИНТЕЛЛЕКТУ", "Преподавание фармакологии в XXI веке", "Наука, технологии, клиническая практика, этика и устойчивость", None, "ЧТО ОНО ДОЛЖНО ВКЛЮЧАТЬ",
   [("Фармакогенетика и персонализированная медицина:", "прогноз эффективности и безопасности лекарства по генетическим особенностям человека."),
    ("Большие данные и данные реальной практики:", "подкрепление доказательных решений данными из жизни."),
    ("Искусственный интеллект:", "подходы с поддержкой ИИ от поиска лекарств до клинических решений."),
    ("Клиническая фармакология и рациональное применение:", "нужное лекарство нужному пациенту в нужной дозе и в нужный срок."),
    ("Фармаконадзор:", "наблюдение за безопасностью лекарств и защита здоровья населения."),
    ("Фармаколог будущего:", "учёный, владеющий цифровыми инструментами, клинически мыслящий, этически ответственный и постоянно учащийся.")],
   "Фармакология уже не учебный предмет; это фундамент системы здравоохранения будущего."),
 'zh': D("从死记硬背到人工智能", "21世纪的药理学教育", "科学、技术、临床实践、伦理与可持续性", None, "应当涵盖的内容",
   [("药物遗传学与个体化医疗：", "根据个人的基因构成预测药物的疗效和安全性。"),
    ("大数据与真实世界证据：", "用真实世界数据强化循证决策。"),
    ("人工智能：", "从药物发现到临床决策的人工智能辅助方法。"),
    ("临床药理学与合理用药：", "把合适的药，以合适的剂量和疗程，用于合适的患者。"),
    ("药物警戒：", "监测药品安全，保护公众健康。"),
    ("未来的药理学家：", "有科学素养、精通数字工具、具备临床思维、恪守伦理并终身学习。")],
   "药理学不再只是一门课程，而是未来卫生体系的基石。"),
 'hi': D("रटने से कृत्रिम बुद्धिमत्ता तक", "21वीं सदी में फार्माकोलॉजी शिक्षा", "विज्ञान, प्रौद्योगिकी, नैदानिक व्यवहार, नैतिकता और टिकाऊपन", None, "इसमें क्या शामिल हो",
   [("फार्माकोजेनेटिक्स और व्यक्ति-विशेष चिकित्सा:", "व्यक्ति की आनुवंशिक बनावट से दवा की प्रभावकारिता और सुरक्षा का अनुमान।"),
    ("बिग डेटा और वास्तविक-जीवन प्रमाण:", "वास्तविक जीवन के आँकड़ों से प्रमाण-आधारित निर्णयों को मज़बूत करना।"),
    ("कृत्रिम बुद्धिमत्ता:", "दवा की खोज से नैदानिक निर्णयों तक AI-समर्थित तरीक़े।"),
    ("क्लिनिकल फार्माकोलॉजी और तर्कसंगत दवा उपयोग:", "सही दवा, सही मरीज़ को, सही खुराक में, सही अवधि तक।"),
    ("फार्माकोविजिलेंस:", "दवा सुरक्षा की निगरानी और जनस्वास्थ्य की रक्षा।"),
    ("भविष्य का फार्माकोलॉजिस्ट:", "वैज्ञानिक, डिजिटल रूप से सक्षम, नैदानिक सोच वाला, नैतिक रूप से ज़िम्मेदार और आजीवन सीखने वाला।")],
   "फार्माकोलॉजी अब केवल एक विषय नहीं; यह भविष्य की स्वास्थ्य प्रणाली की नींव है।"),
 'ja': D("暗記から人工知能へ", "21世紀の薬理学教育", "科学、技術、臨床実践、倫理、持続可能性", None, "扱うべき内容",
   [("薬理遺伝学と個別化医療：", "個人の遺伝的特徴から薬の有効性と安全性を予測する。"),
    ("ビッグデータとリアルワールドエビデンス：", "実臨床のデータで、エビデンスに基づく判断を強化する。"),
    ("人工知能：", "創薬から臨床判断まで、AIを活用した新しいアプローチ。"),
    ("臨床薬理学と合理的な薬物使用：", "正しい薬を、正しい患者に、正しい用量と期間で。"),
    ("ファーマコビジランス：", "医薬品の安全性を監視し、公衆衛生を守る。"),
    ("これからの薬理学者：", "科学的で、デジタルに強く、臨床的に考え、倫理に責任を持ち、学び続ける人。")],
   "薬理学はもはや一つの科目ではない。未来の医療制度の土台である。"),
})
