from batch1 import D
from batch2 import BM
CARDS = {}

# 36 — Inside story of innovative Alzheimer drugs
CARDS['alz2'] = ('dark', {
 'en': D("COCHRANE REVIEW · CD016297 · 2026", "The inside story of innovative Alzheimer's drugs", "What was promised, and what was proven",
   [("36.8%", "ARIA (brain oedema or bleeding)"), ("Not met", "the threshold of clinical importance (MCID)"), ("$32,000", "annual cost of treatment")]),
 'de': D("COCHRANE-REVIEW · CD016297 · 2026", "Die Wahrheit über innovative Alzheimer-Medikamente", "Was versprochen und was bewiesen wurde",
   [("36,8 %", "ARIA (Hirnödem oder Hirnblutung)"), ("Nicht erreicht", "die Schwelle klinischer Relevanz (MCID)"), ("32.000 $", "jährliche Behandlungskosten")]),
 'es': D("REVISIÓN COCHRANE · CD016297 · 2026", "La verdad sobre los fármacos innovadores para el Alzheimer", "Lo prometido y lo demostrado",
   [("36,8 %", "ARIA (edema o hemorragia cerebral)"), ("No alcanzado", "el umbral de relevancia clínica (MCID)"), ("32.000 $", "coste anual del tratamiento")]),
 'ru': D("КОКРЕЙНОВСКИЙ ОБЗОР · CD016297 · 2026", "Изнанка инновационных лекарств от болезни Альцгеймера", "Что обещали и что доказано",
   [("36,8 %", "ARIA (отёк мозга или кровоизлияние)"), ("Не достигнут", "порог клинической значимости (MCID)"), ("32 000 $", "годовая стоимость лечения")]),
 'zh': D("COCHRANE系统综述 · CD016297 · 2026", "创新型阿尔茨海默病药物的内幕", "承诺的与被证实的",
   [("36.8%", "ARIA（脑水肿或脑出血）"), ("未达到", "最小临床重要差异（MCID）阈值"), ("3.2万美元", "每年治疗费用")]),
 'hi': D("कोक्रेन समीक्षा · CD016297 · 2026", "नवोन्मेषी अल्ज़ाइमर दवाओं की असलियत", "जो वादा किया गया, और जो सिद्ध हुआ",
   [("36.8%", "ARIA (मस्तिष्क शोथ या रक्तस्राव)"), ("पूरी नहीं हुई", "नैदानिक महत्व की सीमा (MCID)"), ("32,000 डॉलर", "उपचार की वार्षिक लागत")]),
 'ja': D("コクランレビュー · CD016297 · 2026", "革新的アルツハイマー病治療薬の内実", "約束されたことと、証明されたこと",
   [("36.8%", "ARIA（脳浮腫または脳出血）"), ("未達", "臨床的に意味のある最小差（MCID）の基準"), ("3万2千ドル", "年間治療費")]),
})

# 37 — AIFD "we cannot access innovative drugs" discourse (English image exists from the English article)
CARDS['aifd'] = ('purple', {
 'de': D(BM['de'], "AIFDs Erzählung „Wir haben keinen Zugang zu innovativen Medikamenten“", "Wie die Botschaft des Branchenverbands verbreitet wird", None, None,
   [("Pressemitteilungen:", "wortgleich in 7 Medien."), ("Symposium:", "mit Gästen aus Behörden und Wissenschaft."), ("DETESADER-Netzwerk:", "ein verbundener Interessenverband."), ("Ziel: TİTCK und SGK.", "Druck auf Preise und Erstattung.")]),
 'es': D(BM['es'], "El discurso de AIFD: «no podemos acceder a los medicamentos innovadores»", "Cómo se difunde el mensaje de la asociación del sector", None, None,
   [("Notas de prensa:", "idénticas en 7 medios."), ("Simposio:", "con invitados de la administración y la academia."), ("Red DETESADER:", "una asociación de defensa vinculada."), ("Objetivo: TİTCK y SGK.", "Presión sobre precios y reembolso.")]),
 'ru': D(BM['ru'], "Тезис AIFD: «у нас нет доступа к инновационным лекарствам»", "Как распространяется послание отраслевой ассоциации", None, None,
   [("Пресс-релизы:", "слово в слово в 7 изданиях."), ("Симпозиум:", "с приглашёнными из госорганов и академической среды."), ("Сеть DETESADER:", "связанная пациентская ассоциация."), ("Цель: TİTCK и SGK.", "Давление по ценам и возмещению.")]),
 'zh': D(BM['zh'], "AIFD的说法：“我们得不到创新药”", "行业协会的信息是如何传播的", None, None,
   [("新闻稿：", "在7家媒体上一字不差地刊出。"), ("研讨会：", "邀请政府部门和学术界人士参加。"), ("DETESADER网络：", "一个有关联的倡导团体。"), ("目标：TİTCK和SGK。", "在价格和报销上施压。")]),
 'hi': D(BM['hi'], "AIFD का कथन: “हमें नवोन्मेषी दवाएँ नहीं मिल पा रहीं”", "उद्योग संघ का संदेश कैसे फैलाया जाता है", None, None,
   [("प्रेस विज्ञप्तियाँ:", "7 माध्यमों में शब्दशः एक जैसी।"), ("संगोष्ठी:", "सरकारी और अकादमिक अतिथियों के साथ।"), ("DETESADER नेटवर्क:", "एक जुड़ी हुई पैरोकार संस्था।"), ("लक्ष्य: TİTCK और SGK।", "कीमत और प्रतिपूर्ति पर दबाव।")]),
 'ja': D(BM['ja'], "AIFDの主張「革新的医薬品にアクセスできない」", "業界団体のメッセージはどう広められるのか", None, None,
   [("プレスリリース：", "7つの媒体に一字一句同じ内容で掲載。"), ("シンポジウム：", "行政と学界から招待。"), ("DETESADERのネットワーク：", "関係のある擁護団体。"), ("標的はTİTCKとSGK。", "価格と償還への圧力。")]),
})

# 38 — COVID corruption: USA and Türkiye
CARDS['fauci'] = ('navy', {
 'en': D("THE FAUCI FILE", "COVID corruption: the US and Türkiye", "A comparison of transparency and oversight",
   [("100+", "USA: times the Fifth Amendment was invoked; no question was answered"), ("$12.5 m", "USA: additional income earned after public office"), ("240 m → 30.5 m", "Türkiye: doses agreed versus doses actually delivered"), ("150,000–600,000", "Türkiye: conflicting, unverifiable usage figures for TURKOVAC")], None,
   [("USA:", "a 141-page official financial disclosure was analysed by an independent body (Open The Books); a contempt-of-Congress vote was set for 5 August."),
    ("Türkiye:", "the total production cost of TURKOVAC has never been disclosed to the public."),
    ("The difference:", "in Türkiye no public body independently audits the cost of TURKOVAC.")]),
 'de': D("DIE AKTE FAUCI", "COVID-Korruption: USA und Türkei", "Ein Vergleich von Transparenz und Kontrolle",
   [("100+", "USA: so oft wurde die Aussage unter Berufung auf den 5. Verfassungszusatz verweigert"), ("12,5 Mio. $", "USA: zusätzliches Einkommen nach dem öffentlichen Amt"), ("240 Mio. → 30,5 Mio.", "Türkei: vereinbarte gegenüber tatsächlich gelieferten Dosen"), ("150.000–600.000", "Türkei: widersprüchliche, nicht überprüfbare Anwendungszahlen für TURKOVAC")], None,
   [("USA:", "Eine 141-seitige offizielle Finanzerklärung wurde von einer unabhängigen Organisation (Open The Books) analysiert; für den 5. August war eine Abstimmung über Missachtung des Kongresses angesetzt."),
    ("Türkei:", "Die gesamten Produktionskosten von TURKOVAC wurden der Öffentlichkeit nie vorgelegt."),
    ("Der Unterschied:", "In der Türkei prüft keine öffentliche Stelle die Kosten von TURKOVAC unabhängig.")]),
 'es': D("EL EXPEDIENTE FAUCI", "Corrupción en la COVID: EE. UU. y Turquía", "Una comparación de transparencia y control",
   [("100+", "EE. UU.: veces que se acogió a la Quinta Enmienda sin responder a ninguna pregunta"), ("12,5 M$", "EE. UU.: ingresos adicionales obtenidos tras el cargo público"), ("240 M → 30,5 M", "Turquía: dosis acordadas frente a dosis realmente recibidas"), ("150.000–600.000", "Turquía: cifras de uso de TURKOVAC contradictorias e imposibles de verificar")], None,
   [("EE. UU.:", "una declaración financiera oficial de 141 páginas fue analizada por un organismo independiente (Open The Books); se fijó para el 5 de agosto una votación por desacato al Congreso."),
    ("Turquía:", "el coste total de producción de TURKOVAC nunca se ha hecho público."),
    ("La diferencia:", "en Turquía ningún organismo público audita de forma independiente el coste de TURKOVAC.")]),
 'ru': D("ДОСЬЕ ФАУЧИ", "Коррупция времён COVID: США и Турция", "Сравнение прозрачности и контроля",
   [("100+", "США: столько раз он сослался на Пятую поправку и не ответил ни на один вопрос"), ("12,5 млн $", "США: дополнительный доход после государственной службы"), ("240 млн → 30,5 млн", "Турция: согласованное число доз и фактически полученное"), ("150–600 тыс.", "Турция: противоречивые, непроверяемые данные о применении TURKOVAC")], None,
   [("США:", "141-страничную официальную финансовую декларацию проанализировала независимая организация (Open The Books); на 5 августа назначено голосование о неуважении к Конгрессу."),
    ("Турция:", "общая стоимость производства TURKOVAC так и не была обнародована."),
    ("Разница:", "в Турции нет государственного органа, независимо проверяющего затраты на TURKOVAC.")]),
 'zh': D("福奇档案", "新冠时期的腐败：美国与土耳其", "透明度与监督的对比",
   [("100多次", "美国：援引宪法第五修正案，未回答任何问题"), ("1250万美元", "美国：离开公职后获得的额外收入"), ("2.4亿 → 3050万", "土耳其：约定剂量与实际交付剂量"), ("15万–60万", "土耳其：TURKOVAC接种数字相互矛盾且无法核实")], None,
   [("美国：", "一份141页的官方财务申报被独立机构（Open The Books）分析；国会定于8月5日就藐视国会进行表决。"),
    ("土耳其：", "TURKOVAC的总生产成本从未向公众公布。"),
    ("差别：", "土耳其没有任何公共机构对TURKOVAC的成本进行独立审计。")]),
 'hi': D("फ़ाउची फ़ाइल", "कोविड भ्रष्टाचार: अमेरिका और तुर्किये", "पारदर्शिता और निगरानी की तुलना",
   [("100+", "अमेरिका: इतनी बार पाँचवें संशोधन का सहारा लिया, किसी सवाल का जवाब नहीं"), ("1.25 करोड़ डॉलर", "अमेरिका: सार्वजनिक पद के बाद अर्जित अतिरिक्त आय"), ("24 करोड़ → 3.05 करोड़", "तुर्किये: तय खुराकें बनाम वास्तव में मिली खुराकें"), ("1.5–6 लाख", "तुर्किये: TURKOVAC के उपयोग के परस्पर-विरोधी, असत्यापनीय आँकड़े")], None,
   [("अमेरिका:", "141 पृष्ठों के आधिकारिक वित्तीय विवरण का विश्लेषण एक स्वतंत्र संस्था (Open The Books) ने किया; 5 अगस्त को कांग्रेस की अवमानना पर मतदान तय था।"),
    ("तुर्किये:", "TURKOVAC की कुल उत्पादन लागत कभी जनता के सामने नहीं रखी गई।"),
    ("अंतर:", "तुर्किये में कोई सार्वजनिक संस्था TURKOVAC की लागत का स्वतंत्र ऑडिट नहीं करती।")]),
 'ja': D("ファウチ・ファイル", "COVIDをめぐる不正：米国とトルコ", "透明性と監督の比較",
   [("100回以上", "米国：憲法修正第5条を援用し、質問に一切答えなかった回数"), ("1,250万ドル", "米国：公職を離れた後に得た追加収入"), ("2.4億 → 3,050万", "トルコ：契約した接種回数分と実際に納入された分"), ("15万〜60万", "トルコ：TURKOVACの使用実績は食い違い、検証できない")], None,
   [("米国：", "141ページの公式資産報告書を独立団体（Open The Books）が分析。8月5日に議会侮辱の採決が予定された。"),
    ("トルコ：", "TURKOVACの総生産コストは一度も公表されていない。"),
    ("違い：", "トルコにはTURKOVACのコストを独立して監査する公的機関がない。")]),
})

# 40 — WHO guidance / non-compliant trials
CARDS['ihlal'] = ('burg', {
 'en': D("CLINICAL TRIAL TRANSPARENCY", "The share of non-compliant clinical trials", "30–50% of trials breach the obligation to report results",
   [("29.6%", "FDA / USA"), ("50.4%", "EU / CTIS"), ("60–80%", "not reported on time"), ("26%", "protocol or methodology violations")], None,
   [("FDA (USA):", "a fine of 10,000 dollars a day. First formal action in 2021; rarely applied."),
    ("WHO:", "funding cuts or refusal to publish, indirectly, through funders and journals (ICMJE).")]),
 'de': D("TRANSPARENZ KLINISCHER STUDIEN", "Der Anteil regelwidriger klinischer Studien", "30–50 % der Studien verletzen die Pflicht zur Ergebnisberichterstattung",
   [("29,6 %", "FDA / USA"), ("50,4 %", "EU / CTIS"), ("60–80 %", "nicht fristgerecht berichtet"), ("26 %", "Verstöße gegen Protokoll oder Methodik")], None,
   [("FDA (USA):", "Geldbuße von 10.000 Dollar pro Tag. Erste formelle Maßnahme 2021; selten angewandt."),
    ("WHO:", "Mittelkürzung oder Ablehnung der Publikation, indirekt über Geldgeber und Zeitschriften (ICMJE).")]),
 'es': D("TRANSPARENCIA DE LOS ENSAYOS CLÍNICOS", "La proporción de ensayos clínicos que incumplen", "Entre el 30 y el 50 % de los ensayos incumple la obligación de comunicar resultados",
   [("29,6 %", "FDA / EE. UU."), ("50,4 %", "UE / CTIS"), ("60–80 %", "no comunicados a tiempo"), ("26 %", "infracciones de protocolo o metodología")], None,
   [("FDA (EE. UU.):", "multa de 10.000 dólares al día. Primera actuación formal en 2021; rara vez se aplica."),
    ("OMS:", "retirada de fondos o rechazo de publicación, de forma indirecta, a través de financiadores y revistas (ICMJE).")]),
 'ru': D("ПРОЗРАЧНОСТЬ КЛИНИЧЕСКИХ ИССЛЕДОВАНИЙ", "Доля клинических исследований с нарушениями", "30–50 % исследований нарушают обязанность сообщать результаты",
   [("29,6 %", "FDA / США"), ("50,4 %", "ЕС / CTIS"), ("60–80 %", "не представлены в срок"), ("26 %", "нарушения протокола или методологии")], None,
   [("FDA (США):", "штраф 10 000 долларов в день. Первое официальное действие в 2021 г.; применяется редко."),
    ("ВОЗ:", "прекращение финансирования или отказ в публикации, косвенно, через спонсоров и журналы (ICMJE).")]),
 'zh': D("临床试验透明度", "不合规临床试验的比例", "30%–50%的试验违反了报告结果的义务",
   [("29.6%", "FDA / 美国"), ("50.4%", "欧盟 / CTIS"), ("60–80%", "未按时报告"), ("26%", "违反方案或方法学要求")], None,
   [("FDA（美国）：", "每天1万美元罚款。2021年首次正式执法；很少动用。"),
    ("世卫组织：", "通过资助方和期刊（ICMJE）间接实施：削减经费或拒绝发表。")]),
 'hi': D("क्लिनिकल ट्रायल पारदर्शिता", "नियमों का पालन न करने वाले क्लिनिकल ट्रायलों का अनुपात", "30–50% अध्ययन परिणाम रिपोर्ट करने के दायित्व का उल्लंघन करते हैं",
   [("29.6%", "FDA / अमेरिका"), ("50.4%", "यूरोपीय संघ / CTIS"), ("60–80%", "समय पर रिपोर्ट नहीं"), ("26%", "प्रोटोकॉल या कार्यप्रणाली के उल्लंघन")], None,
   [("FDA (अमेरिका):", "10,000 डॉलर प्रतिदिन का जुर्माना। पहली औपचारिक कार्रवाई 2021 में; शायद ही कभी लागू।"),
    ("WHO:", "अनुदान में कटौती या प्रकाशन से इनकार, परोक्ष रूप से, अनुदानदाताओं और पत्रिकाओं (ICMJE) के ज़रिये।")]),
 'ja': D("臨床試験の透明性", "規則を守らない臨床試験の割合", "30〜50%の試験が結果報告の義務に違反している",
   [("29.6%", "FDA／米国"), ("50.4%", "EU／CTIS"), ("60〜80%", "期限内に報告されていない"), ("26%", "プロトコルまたは方法論の違反")], None,
   [("FDA（米国）：", "1日1万ドルの制裁金。初の正式措置は2021年で、適用はまれ。"),
    ("WHO：", "資金提供者や学術誌（ICMJE）を通じた間接的な対応として、資金の打ち切りや掲載拒否。")]),
})

# 41 — FDA's historic transparency move
CARDS['fdaseffaf'] = ('burg', {
 'en': D("CLINICAL TRIALS", "A historic transparency move by the FDA", "More than 2,200 clinical trial sponsors are being forced to disclose results",
   [("3,000+", "trials under review because results were not reported"), ("2,200+", "sponsors warned: formal notices sent to companies and universities"), ("12 months", "legal deadline for posting results on ClinicalTrials.gov after a trial ends"), ("$15,107 a day", "administrative fine that can be applied to those who do not disclose")], None, None,
   "Hiding results is harder now."),
 'de': D("KLINISCHE STUDIEN", "Ein historischer Transparenzvorstoß der FDA", "Über 2.200 Sponsoren klinischer Studien werden gezwungen, Ergebnisse offenzulegen",
   [("3.000+", "Studien in Prüfung, weil Ergebnisse nicht gemeldet wurden"), ("2.200+", "Sponsoren verwarnt: offizielle Schreiben an Firmen und Universitäten"), ("12 Monate", "gesetzliche Frist für das Einstellen der Ergebnisse auf ClinicalTrials.gov nach Studienende"), ("15.107 $ pro Tag", "Verwaltungsstrafe, die bei Nichtoffenlegung verhängt werden kann")], None, None,
   "Ergebnisse zu verbergen ist jetzt schwieriger."),
 'es': D("ENSAYOS CLÍNICOS", "Un paso histórico de la FDA hacia la transparencia", "Más de 2.200 promotores de ensayos clínicos, obligados a publicar resultados",
   [("3.000+", "ensayos bajo revisión por no comunicar resultados"), ("2.200+", "promotores advertidos: avisos formales a empresas y universidades"), ("12 meses", "plazo legal para publicar los resultados en ClinicalTrials.gov tras finalizar el ensayo"), ("15.107 $ al día", "multa administrativa aplicable a quienes no publican")], None, None,
   "Ocultar resultados ya es más difícil."),
 'ru': D("КЛИНИЧЕСКИЕ ИССЛЕДОВАНИЯ", "Исторический шаг FDA к прозрачности", "Более 2200 спонсоров клинических исследований вынуждают раскрыть результаты",
   [("3000+", "исследований на проверке из-за непредставления результатов"), ("2200+", "спонсоров предупреждены: официальные письма компаниям и университетам"), ("12 месяцев", "законный срок размещения результатов на ClinicalTrials.gov после завершения исследования"), ("15 107 $ в день", "административный штраф для тех, кто не раскрывает результаты")], None, None,
   "Скрывать результаты теперь труднее."),
 'zh': D("临床试验", "FDA具有历史意义的透明度行动", "2200多家临床试验申办方被要求公开结果",
   [("3000多项", "试验因未报告结果而接受审查"), ("2200多家", "申办方收到警告：已向企业和大学发出正式通知"), ("12个月", "试验结束后在ClinicalTrials.gov公布结果的法定期限"), ("每天15,107美元", "可对不公开结果者处以的行政罚款")], None, None,
   "隐瞒结果，如今更难了。"),
 'hi': D("क्लिनिकल ट्रायल", "पारदर्शिता की ओर FDA का ऐतिहासिक क़दम", "2,200 से अधिक क्लिनिकल ट्रायल प्रायोजकों को परिणाम बताने पर मजबूर किया जा रहा है",
   [("3,000+", "अध्ययन जाँच के दायरे में, क्योंकि परिणाम रिपोर्ट नहीं किए गए"), ("2,200+", "प्रायोजकों को चेतावनी: कंपनियों और विश्वविद्यालयों को औपचारिक नोटिस"), ("12 महीने", "अध्ययन पूरा होने के बाद ClinicalTrials.gov पर परिणाम डालने की कानूनी समय-सीमा"), ("15,107 डॉलर प्रतिदिन", "परिणाम न बताने वालों पर लगाया जा सकने वाला प्रशासनिक जुर्माना")], None, None,
   "परिणाम छिपाना अब और कठिन है।"),
 'ja': D("臨床試験", "FDAの歴史的な透明化の動き", "2,200を超える臨床試験スポンサーが結果の公表を迫られている",
   [("3,000件以上", "結果未報告のため調査対象となった試験"), ("2,200以上", "のスポンサーに警告：企業と大学に正式な通知を送付"), ("12か月", "試験終了後、ClinicalTrials.govに結果を掲載する法定期限"), ("1日15,107ドル", "結果を公表しない者に科すことができる制裁金")], None, None,
   "結果を隠すことは、もう難しくなった。"),
})

# 42 — CTIS
_CS = "TranspariMED et al., medRxiv"
CARDS['ctis'] = ('teal', {
 'en': D("CTIS · CLINICAL TRIAL TRANSPARENCY · EUROPEAN UNION", "A revolution in transparency, or a digital shop window?", "Only half of the 234 clinical trials legally required to report results in CTIS shared them in full within the deadline",
   [("49.6%", "reported on time and in full"), ("8.5%", "reported late"), ("41.9%", "not reported")], None, None, None, "Source: " + _CS + ", April 2026 (preprint)"),
 'de': D("CTIS · TRANSPARENZ KLINISCHER STUDIEN · EUROPÄISCHE UNION", "Revolution der Transparenz oder digitales Schaufenster?", "Nur die Hälfte der 234 klinischen Studien, die im CTIS gesetzlich Ergebnisse melden müssen, hat sie fristgerecht und vollständig geteilt",
   [("49,6 %", "fristgerecht und vollständig gemeldet"), ("8,5 %", "verspätet gemeldet"), ("41,9 %", "nicht gemeldet")], None, None, None, "Quelle: " + _CS + ", April 2026 (Preprint)"),
 'es': D("CTIS · TRANSPARENCIA DE LOS ENSAYOS CLÍNICOS · UNIÓN EUROPEA", "¿Revolución en la transparencia o escaparate digital?", "Solo la mitad de los 234 ensayos clínicos obligados por ley a comunicar resultados en CTIS los compartió completos dentro de plazo",
   [("49,6 %", "comunicados a tiempo y completos"), ("8,5 %", "comunicados con retraso"), ("41,9 %", "no comunicados")], None, None, None, "Fuente: " + _CS + ", abril de 2026 (preprint)"),
 'ru': D("CTIS · ПРОЗРАЧНОСТЬ КЛИНИЧЕСКИХ ИССЛЕДОВАНИЙ · ЕВРОПЕЙСКИЙ СОЮЗ", "Революция прозрачности или цифровая витрина?", "Лишь половина из 234 клинических исследований, обязанных по закону сообщить результаты в CTIS, сделала это полностью и в срок",
   [("49,6 %", "сообщили вовремя и полностью"), ("8,5 %", "сообщили с опозданием"), ("41,9 %", "не сообщили")], None, None, None, "Источник: " + _CS + ", апрель 2026 г. (препринт)"),
 'zh': D("CTIS · 临床试验透明度 · 欧盟", "透明度的革命，还是数字橱窗？", "依法必须在CTIS报告结果的234项临床试验中，只有一半在规定期限内完整公布了结果",
   [("49.6%", "按时并完整报告"), ("8.5%", "延迟报告"), ("41.9%", "未报告")], None, None, None, "来源：" + _CS + "，2026年4月（预印本）"),
 'hi': D("CTIS · क्लिनिकल ट्रायल पारदर्शिता · यूरोपीय संघ", "पारदर्शिता में क्रांति, या डिजिटल शो-केस?", "CTIS में परिणाम बताना जिन 234 क्लिनिकल ट्रायलों के लिए कानूनन अनिवार्य था, उनमें से केवल आधों ने तय समय में पूरे परिणाम साझा किए",
   [("49.6%", "समय पर और पूरे रिपोर्ट किए"), ("8.5%", "देर से रिपोर्ट किए"), ("41.9%", "रिपोर्ट नहीं किए")], None, None, None, "स्रोत: " + _CS + ", अप्रैल 2026 (प्रीप्रिंट)"),
 'ja': D("CTIS · 臨床試験の透明性 · 欧州連合", "透明性の革命か、デジタルのショーウィンドウか", "CTISで結果報告が法的に義務づけられた234件の臨床試験のうち、期限内に完全な結果を公表したのは半数にすぎない",
   [("49.6%", "期限内に完全に報告"), ("8.5%", "遅れて報告"), ("41.9%", "未報告")], None, None, None, "出典：" + _CS + "、2026年4月（プレプリント）"),
})
