from batch1 import D
from batch2 import BM
CARDS = {}

# 43 — Cannabis drinks in US supermarkets
CARDS['esrar'] = ('dark', {
 'en': D("MARKET RESEARCH · JULY 2026", "Cannabis is now sold in US supermarkets", "Hemp-derived THC drinks have reached the shelves, next to soda and iced tea",
   [("$1.4 billion", "estimated size of the US market in 2026"), ("95%", "share of products that will become illegal in November 2026"), ("×15", "increase in child poisonings, 2017–2021"), ("19%", "of drinks deliver the dose stated on the label")], None, None,
   "Türkiye's new hemp regulation (January 2026) adopted the same 0.3% THC threshold."),
 'de': D("MARKTFORSCHUNG · JULI 2026", "Cannabis steht in den USA jetzt im Supermarkt", "THC-haltige Getränke aus Hanf stehen im Regal, neben Limonade und Eistee",
   [("1,4 Mrd. $", "geschätzte Größe des US-Marktes 2026"), ("95 %", "Anteil der Produkte, die im November 2026 illegal werden"), ("×15", "Anstieg der Vergiftungen bei Kindern, 2017–2021"), ("19 %", "der Getränke liefern die auf dem Etikett angegebene Dosis")], None, None,
   "Auch die neue türkische Hanfverordnung (Januar 2026) übernimmt die Schwelle von 0,3 % THC."),
 'es': D("ESTUDIO DE MERCADO · JULIO DE 2026", "El cannabis ya se vende en los supermercados de EE. UU.", "Las bebidas con THC derivado del cáñamo han llegado a los estantes, junto a los refrescos y el té helado",
   [("1.400 M$", "tamaño estimado del mercado de EE. UU. en 2026"), ("95 %", "de los productos será ilegal en noviembre de 2026"), ("×15", "aumento de las intoxicaciones infantiles, 2017–2021"), ("19 %", "de las bebidas aporta la dosis indicada en la etiqueta")], None, None,
   "La nueva normativa turca sobre el cáñamo (enero de 2026) adoptó el mismo umbral del 0,3 % de THC."),
 'ru': D("ИССЛЕДОВАНИЕ РЫНКА · ИЮЛЬ 2026", "В США каннабис начали продавать в супермаркетах", "Напитки с ТГК из конопли появились на полках рядом с газировкой и холодным чаем",
   [("1,4 млрд $", "оценка объёма рынка США в 2026 году"), ("95 %", "продуктов станут незаконными в ноябре 2026 года"), ("×15", "рост отравлений у детей, 2017–2021 гг."), ("19 %", "напитков содержат дозу, указанную на этикетке")], None, None,
   "Новое турецкое положение о конопле (январь 2026 г.) приняло тот же порог 0,3 % ТГК."),
 'zh': D("市场调查 · 2026年7月", "大麻饮料进了美国超市", "含工业大麻提取THC的饮料摆上货架，与汽水和冰茶并列",
   [("14亿美元", "2026年美国市场规模估计"), ("95%", "的产品将在2026年11月变为非法"), ("15倍", "2017–2021年儿童中毒增幅"), ("19%", "的饮料实际剂量与标签相符")], None, None,
   "土耳其新的工业大麻法规（2026年1月）也采用了同样的0.3% THC阈值。"),
 'hi': D("बाज़ार अध्ययन · जुलाई 2026", "अमेरिका में भांग अब सुपरमार्केट में बिक रही है", "भांग से बने THC युक्त पेय सोडा और आइस-टी के साथ अलमारियों पर आ गए हैं",
   [("1.4 अरब डॉलर", "2026 में अमेरिकी बाज़ार का अनुमानित आकार"), ("95%", "उत्पाद नवंबर 2026 में ग़ैरक़ानूनी हो जाएँगे"), ("15 गुना", "बच्चों में विषाक्तता में वृद्धि, 2017–2021"), ("19%", "पेय ही लेबल पर लिखी खुराक देते हैं")], None, None,
   "तुर्किये के नए भांग विनियमन (जनवरी 2026) ने भी वही 0.3% THC सीमा अपनाई।"),
 'ja': D("市場調査 · 2026年7月", "米国で大麻がスーパーの棚に並び始めた", "ヘンプ由来のTHC入り飲料が、炭酸飲料やアイスティーの隣に置かれている",
   [("14億ドル", "2026年の米国市場規模の推計"), ("95%", "の製品は2026年11月に違法となる"), ("15倍", "子どもの中毒の増加（2017〜2021年）"), ("19%", "の飲料だけが表示どおりの用量を含む")], None, None,
   "トルコの新しいヘンプ規則（2026年1月）も、同じTHC 0.3%の基準を採用した。"),
})

# 44 — Acetaminophen + naproxen OTC approval
CARDS['tylenol'] = ('blue', {
 'en': D("FDA · 24 JULY 2026", "First over-the-counter painkiller combining acetaminophen and naproxen sodium in one tablet", "Tylenol with Naproxen (Kenvue), for adults and children aged 12 and over",
   [("325 mg + 110 mg", "acetaminophen and naproxen sodium per tablet"), ("2 tablets", "recommended dose: 650 mg + 220 mg, every 12 hours"), ("3 years", "of market exclusivity granted by the FDA")], None,
   [("Evidence:", "the manufacturer cites eight clinical studies, not yet published in a peer-reviewed journal; presentation is expected at PAINWeek 2026."),
    ("Liver:", "must not be used together with other products containing acetaminophen."),
    ("NSAID risks:", "stomach bleeding and a higher risk of heart attack, heart failure and stroke."),
    ("Pregnancy:", "naproxen sodium should not be used from week 20 of pregnancy without a doctor's approval.")]),
 'de': D("FDA · 24. JULI 2026", "Erstes rezeptfreies Schmerzmittel, das Paracetamol und Naproxen-Natrium in einer Tablette kombiniert", "Tylenol with Naproxen (Kenvue), für Erwachsene und Kinder ab 12 Jahren",
   [("325 mg + 110 mg", "Paracetamol und Naproxen-Natrium pro Tablette"), ("2 Tabletten", "empfohlene Dosis: 650 mg + 220 mg, alle 12 Stunden"), ("3 Jahre", "von der FDA gewährte Marktexklusivität")], None,
   [("Evidenz:", "Der Hersteller nennt acht klinische Studien, noch nicht in einer Fachzeitschrift mit Peer-Review veröffentlicht; Präsentation auf der PAINWeek 2026 erwartet."),
    ("Leber:", "darf nicht zusammen mit anderen paracetamolhaltigen Produkten angewendet werden."),
    ("NSAR-Risiken:", "Magenblutungen sowie erhöhtes Risiko für Herzinfarkt, Herzinsuffizienz und Schlaganfall."),
    ("Schwangerschaft:", "Naproxen-Natrium ab der 20. Schwangerschaftswoche nicht ohne ärztliche Zustimmung anwenden.")]),
 'es': D("FDA · 24 DE JULIO DE 2026", "Primer analgésico sin receta que combina paracetamol y naproxeno sódico en un comprimido", "Tylenol with Naproxen (Kenvue), para adultos y niños a partir de 12 años",
   [("325 mg + 110 mg", "paracetamol y naproxeno sódico por comprimido"), ("2 comprimidos", "dosis recomendada: 650 mg + 220 mg, cada 12 horas"), ("3 años", "de exclusividad de mercado concedida por la FDA")], None,
   [("Evidencia:", "el fabricante cita ocho estudios clínicos aún no publicados en una revista con revisión por pares; se espera su presentación en PAINWeek 2026."),
    ("Hígado:", "no debe usarse junto con otros productos que contengan paracetamol."),
    ("Riesgos de los AINE:", "hemorragia gástrica y mayor riesgo de infarto, insuficiencia cardiaca e ictus."),
    ("Embarazo:", "el naproxeno sódico no debe usarse a partir de la semana 20 sin aprobación médica.")]),
 'ru': D("FDA · 24 ИЮЛЯ 2026", "Первое безрецептурное обезболивающее, объединяющее парацетамол и напроксен натрия в одной таблетке", "Tylenol with Naproxen (Kenvue), для взрослых и детей с 12 лет",
   [("325 мг + 110 мг", "парацетамол и напроксен натрия в одной таблетке"), ("2 таблетки", "рекомендуемая доза: 650 мг + 220 мг каждые 12 часов"), ("3 года", "рыночной эксклюзивности, предоставленной FDA")], None,
   [("Доказательства:", "производитель ссылается на восемь клинических исследований, пока не опубликованных в рецензируемом журнале; доклад ожидается на PAINWeek 2026."),
    ("Печень:", "нельзя применять вместе с другими препаратами, содержащими парацетамол."),
    ("Риски НПВП:", "желудочное кровотечение и повышенный риск инфаркта, сердечной недостаточности и инсульта."),
    ("Беременность:", "напроксен натрия нельзя применять с 20-й недели беременности без одобрения врача.")]),
 'zh': D("FDA · 2026年7月24日", "首个把对乙酰氨基酚与萘普生钠合为一片的非处方止痛药", "Tylenol with Naproxen（Kenvue），适用于成人和12岁及以上儿童",
   [("325毫克 + 110毫克", "每片所含的对乙酰氨基酚和萘普生钠"), ("2片", "推荐剂量：650毫克 + 220毫克，每12小时一次"), ("3年", "FDA授予的市场独占期")], None,
   [("证据：", "生产商称有八项临床研究，但尚未在同行评议期刊发表；预计将在PAINWeek 2026上报告。"),
    ("肝脏：", "不得与其他含对乙酰氨基酚的产品同时使用。"),
    ("非甾体抗炎药风险：", "胃出血，以及心肌梗死、心力衰竭和脑卒中风险升高。"),
    ("妊娠：", "妊娠20周起，未经医生同意不应使用萘普生钠。")]),
 'hi': D("FDA · 24 जुलाई 2026", "एक ही गोली में पैरासिटामोल और नैप्रोक्सेन सोडियम वाली पहली बिना-पर्चे की दर्द-निवारक", "Tylenol with Naproxen (Kenvue), वयस्कों और 12 वर्ष से ऊपर के बच्चों के लिए",
   [("325 मि.ग्रा. + 110 मि.ग्रा.", "प्रति गोली पैरासिटामोल और नैप्रोक्सेन सोडियम"), ("2 गोलियाँ", "अनुशंसित खुराक: 650 मि.ग्रा. + 220 मि.ग्रा., हर 12 घंटे"), ("3 वर्ष", "FDA द्वारा दी गई बाज़ार विशिष्टता")], None,
   [("प्रमाण:", "निर्माता आठ क्लिनिकल अध्ययनों का हवाला देता है, जो अभी समकक्ष-समीक्षित पत्रिका में प्रकाशित नहीं; PAINWeek 2026 में प्रस्तुति अपेक्षित।"),
    ("यकृत:", "पैरासिटामोल युक्त अन्य उत्पादों के साथ नहीं लेनी चाहिए।"),
    ("NSAID के जोखिम:", "पेट में रक्तस्राव तथा दिल के दौरे, हृदय विफलता और स्ट्रोक का बढ़ा जोखिम।"),
    ("गर्भावस्था:", "गर्भ के 20वें सप्ताह से डॉक्टर की अनुमति के बिना नैप्रोक्सेन सोडियम न लें।")]),
 'ja': D("FDA · 2026年7月24日", "アセトアミノフェンとナプロキセンナトリウムを1錠に配合した初の市販鎮痛薬", "Tylenol with Naproxen（Kenvue）。成人と12歳以上の小児向け",
   [("325mg + 110mg", "1錠中のアセトアミノフェンとナプロキセンナトリウム"), ("2錠", "推奨用量：650mg + 220mgを12時間ごと"), ("3年", "FDAが認めた市場独占期間")], None,
   [("エビデンス：", "製造元は8件の臨床試験を挙げるが、査読誌には未掲載。PAINWeek 2026での発表が見込まれる。"),
    ("肝臓：", "アセトアミノフェンを含む他の製品と併用してはならない。"),
    ("NSAIDsのリスク：", "胃出血のほか、心筋梗塞、心不全、脳卒中のリスクが高まる。"),
    ("妊娠：", "妊娠20週以降は、医師の了承なくナプロキセンナトリウムを使用しない。")]),
})

# 45 — Drugs to avoid (poster)
CARDS['kacin'] = ('teal', {
 'en': D("PRESCRIRE · 2026 UPDATE", "2026: drugs to avoid", "Prescrire's annual review of drugs that are more dangerous than beneficial"),
 'de': D("PRESCRIRE · AKTUALISIERUNG 2026", "2026: Medikamente, die man meiden sollte", "Die jährliche Prescrire-Übersicht der Arzneimittel, die mehr schaden als nützen"),
 'es': D("PRESCRIRE · ACTUALIZACIÓN 2026", "2026: medicamentos que conviene evitar", "La revisión anual de Prescrire sobre los fármacos más peligrosos que beneficiosos"),
 'ru': D("PRESCRIRE · ОБНОВЛЕНИЕ 2026", "2026: лекарства, которых следует избегать", "Ежегодный обзор Prescrire: препараты, которые приносят больше вреда, чем пользы"),
 'zh': D("PRESCRIRE · 2026年更新", "2026年：应当避免使用的药物", "Prescrire年度评估：弊大于利的药物"),
 'hi': D("PRESCRIRE · 2026 अद्यतन", "2026: जिन दवाओं से बचना चाहिए", "Prescrire की वार्षिक समीक्षा: वे दवाएँ जो लाभ से अधिक हानि करती हैं"),
 'ja': D("PRESCRIRE · 2026年版", "2026年：避けるべき薬", "Prescrire誌の年次レビュー：有益性より危険性が大きい薬"),
})

# 46 — Foundation medical schools
CARDS['vakif'] = ('burg', {
 'en': D("EDITORIAL", "Türkiye's foundation medical schools are printing money", "Annual tuition fees have overtaken those of the world's most prestigious medical schools. What about quality and education?",
   [("3,740,000 TL", "İstanbul Nişantaşı University, medicine, per year"), ("3,300,000 TL", "Acıbadem Mehmet Ali Aydınlar University, medicine"), ("3,249,000 TL", "Koç University, medicine")], None, None,
   "Were foundation medical schools set up for education, or for expensive hospital services?"),
 'de': D("LEITARTIKEL", "Die Stiftungs-Medizinfakultäten der Türkei drucken Geld", "Die jährlichen Studiengebühren übertreffen die der renommiertesten medizinischen Fakultäten der Welt. Und Qualität und Lehre?",
   [("3.740.000 TL", "Universität İstanbul Nişantaşı, Medizin, pro Jahr"), ("3.300.000 TL", "Universität Acıbadem Mehmet Ali Aydınlar, Medizin"), ("3.249.000 TL", "Koç-Universität, Medizin")], None, None,
   "Wurden die Stiftungs-Medizinfakultäten für die Lehre gegründet oder für teure Krankenhausleistungen?"),
 'es': D("EDITORIAL", "Las facultades de medicina de fundación en Turquía fabrican dinero", "Las matrículas anuales superan a las de las facultades de medicina más prestigiosas del mundo. ¿Y la calidad y la enseñanza?",
   [("3.740.000 TL", "Universidad İstanbul Nişantaşı, medicina, al año"), ("3.300.000 TL", "Universidad Acıbadem Mehmet Ali Aydınlar, medicina"), ("3.249.000 TL", "Universidad Koç, medicina")], None, None,
   "¿Se crearon las facultades de medicina de fundación para enseñar o para prestar servicios hospitalarios caros?"),
 'ru': D("ОТ РЕДАКТОРА", "Частные (фондовые) медицинские факультеты Турции печатают деньги", "Годовая плата за обучение превысила плату на самых престижных медицинских факультетах мира. А что с качеством и образованием?",
   [("3 740 000 лир", "Университет Стамбул Нишанташи, медицина, в год"), ("3 300 000 лир", "Университет Аджибадем Мехмет Али Айдынлар, медицина"), ("3 249 000 лир", "Университет Коч, медицина")], None, None,
   "Фондовые медицинские факультеты созданы ради образования или ради дорогих больничных услуг?"),
 'zh': D("编者的话", "土耳其的基金会医学院在“印钞”", "每年学费已超过世界上最负盛名的医学院。质量和教育呢？",
   [("374万里拉", "伊斯坦布尔尼尚塔什大学医学院，每年"), ("330万里拉", "阿杰巴德姆大学医学院"), ("324.9万里拉", "科奇大学医学院")], None, None,
   "基金会医学院是为教育而设，还是为昂贵的医院服务而设？"),
 'hi': D("संपादकीय", "तुर्किये के फ़ाउंडेशन मेडिकल कॉलेज पैसा छाप रहे हैं", "वार्षिक शुल्क दुनिया के सबसे प्रतिष्ठित मेडिकल कॉलेजों से आगे निकल गया है। गुणवत्ता और शिक्षा का क्या?",
   [("37,40,000 TL", "इस्तांबुल निशानताशी विश्वविद्यालय, चिकित्सा, प्रति वर्ष"), ("33,00,000 TL", "अजीबादेम मेहमत अली आयदिनलार विश्वविद्यालय, चिकित्सा"), ("32,49,000 TL", "कोच विश्वविद्यालय, चिकित्सा")], None, None,
   "फ़ाउंडेशन मेडिकल कॉलेज शिक्षा के लिए बने थे, या महँगी अस्पताल सेवाओं के लिए?"),
 'ja': D("編集長から", "トルコの財団立医学部は金を刷っている", "年間授業料は世界で最も名高い医学部を上回った。では、質と教育はどうか",
   [("374万リラ", "イスタンブール・ニシャンタシュ大学医学部、年額"), ("330万リラ", "アジュバデム大学医学部"), ("324万9千リラ", "コチ大学医学部")], None, None,
   "財団立医学部は教育のために作られたのか、それとも高額な病院サービスのためか。"),
})

# 47 — Clinical trial transparency: where is Türkiye
_S = "TranspariMED / Bruckner et al., medRxiv 2026; STAT Pharmalot, 23.07.2026; TİTCK"
CARDS['ctis2'] = ('teal', {
 'en': D("EMA · JULY 2026", "More than half of clinical trial results are not disclosed, despite the law", "234 overdue trials in CTIS, Europe's clinical trial register, were examined. Under pressure from civil society, the EMA acted within weeks",
   [("116", "reported on time"), ("20", "reported late"), ("98", "never reported (42%)")], "AND IN TÜRKİYE?",
   [("A register exists, but it is incomplete:", "TİTCK's KAP portal leaves out bioavailability and bioequivalence studies."),
    ("Not binding:", "portal data are for information only; in case of conflict the Agency's closed records prevail."),
    ("Results transparency is unclear:", "the results report is submitted to the Agency, but public posting cannot be verified as it can in CTIS.")],
   None, "Source: " + _S),
 'de': D("EMA · JULI 2026", "Mehr als die Hälfte der Studienergebnisse wird trotz Gesetz nicht offengelegt", "Untersucht wurden 234 überfällige Studien im europäischen Register CTIS. Unter dem Druck der Zivilgesellschaft handelte die EMA binnen Wochen",
   [("116", "fristgerecht gemeldet"), ("20", "verspätet gemeldet"), ("98", "gar nicht gemeldet (42 %)")], "UND IN DER TÜRKEI?",
   [("Ein Register gibt es, aber es ist lückenhaft:", "Das KAP-Portal der TİTCK lässt Bioverfügbarkeits- und Bioäquivalenzstudien aus."),
    ("Nicht verbindlich:", "Die Portaldaten dienen nur der Information; bei Abweichungen gelten die nicht öffentlichen Unterlagen der Behörde."),
    ("Ergebnistransparenz unklar:", "Der Ergebnisbericht geht an die Behörde, doch die öffentliche Bereitstellung lässt sich nicht wie im CTIS überprüfen.")],
   None, "Quelle: " + _S),
 'es': D("EMA · JULIO DE 2026", "Más de la mitad de los resultados de ensayos clínicos no se publica, pese a la ley", "Se examinaron 234 ensayos con plazo vencido en CTIS, el registro europeo. Bajo la presión de la sociedad civil, la EMA actuó en semanas",
   [("116", "comunicados a tiempo"), ("20", "comunicados con retraso"), ("98", "nunca comunicados (42 %)")], "¿Y EN TURQUÍA?",
   [("Hay registro, pero incompleto:", "el portal KAP de la TİTCK deja fuera los estudios de biodisponibilidad y bioequivalencia."),
    ("No es vinculante:", "los datos del portal son solo informativos; en caso de discrepancia prevalecen los registros cerrados de la Agencia."),
    ("Transparencia de resultados incierta:", "el informe de resultados se presenta a la Agencia, pero su publicación no puede verificarse como en CTIS.")],
   None, "Fuente: " + _S),
 'ru': D("EMA · ИЮЛЬ 2026", "Более половины результатов клинических исследований не раскрывается вопреки закону", "Изучены 234 исследования с истёкшим сроком в европейском реестре CTIS. Под давлением гражданского общества EMA приняло меры за несколько недель",
   [("116", "представлены в срок"), ("20", "представлены с опозданием"), ("98", "не представлены вовсе (42 %)")], "А В ТУРЦИИ?",
   [("Реестр есть, но неполный:", "портал KAP агентства TİTCK не включает исследования биодоступности и биоэквивалентности."),
    ("Не имеет обязательной силы:", "данные портала носят справочный характер; при расхождениях действуют закрытые записи агентства."),
    ("Прозрачность результатов неясна:", "отчёт о результатах подаётся в агентство, но его публикацию нельзя проверить так, как в CTIS.")],
   None, "Источник: " + _S),
 'zh': D("EMA · 2026年7月", "尽管有法律规定，超过一半的临床试验结果仍未公开", "对欧洲临床试验登记系统CTIS中234项已到期的试验进行了审查。在民间组织的压力下，EMA在数周内采取了行动",
   [("116项", "按时报告"), ("20项", "延迟报告"), ("98项", "从未报告（42%）")], "那么土耳其呢？",
   [("有登记，但不完整：", "TİTCK的KAP门户网站不包括生物利用度和生物等效性研究。"),
    ("没有约束力：", "门户数据仅供参考；出现不一致时以该机构不公开的记录为准。"),
    ("结果透明度不明：", "结果报告提交给该机构，但无法像CTIS那样核实是否公开发布。")],
   None, "来源：" + _S),
 'hi': D("EMA · जुलाई 2026", "कानून के बावजूद आधे से अधिक क्लिनिकल ट्रायल परिणाम सार्वजनिक नहीं किए जाते", "यूरोप के क्लिनिकल ट्रायल रजिस्टर CTIS में समय-सीमा पार कर चुके 234 अध्ययनों की जाँच हुई। नागरिक समाज के दबाव में EMA ने कुछ ही हफ़्तों में कार्रवाई की",
   [("116", "समय पर रिपोर्ट किए गए"), ("20", "देर से रिपोर्ट किए गए"), ("98", "कभी रिपोर्ट नहीं किए गए (42%)")], "और तुर्किये में?",
   [("रजिस्टर है, पर अधूरा:", "TİTCK का KAP पोर्टल जैव-उपलब्धता और जैव-समतुल्यता अध्ययनों को बाहर रखता है।"),
    ("बाध्यकारी नहीं:", "पोर्टल का डेटा केवल जानकारी के लिए है; असंगति होने पर एजेंसी के बंद अभिलेख मान्य होते हैं।"),
    ("परिणामों की पारदर्शिता अस्पष्ट:", "परिणाम रिपोर्ट एजेंसी को दी जाती है, पर CTIS की तरह उसके सार्वजनिक प्रकाशन की पुष्टि नहीं हो सकती।")],
   None, "स्रोत: " + _S),
 'ja': D("EMA · 2026年7月", "法律があっても、臨床試験結果の半数以上は公表されていない", "欧州の臨床試験登録システムCTISで期限を過ぎた234試験を調査。市民社会の圧力を受け、EMAは数週間で対応に動いた",
   [("116件", "期限内に報告"), ("20件", "遅れて報告"), ("98件", "一度も報告されていない（42%）")], "では、トルコでは？",
   [("登録はあるが不完全：", "TİTCKのKAPポータルは、バイオアベイラビリティ試験と生物学的同等性試験を対象外としている。"),
    ("拘束力がない：", "ポータルのデータは情報提供のみが目的で、食い違いがあれば当局の非公開記録が優先される。"),
    ("結果の透明性は不明確：", "結果報告書は当局に提出されるが、CTISのように公開されているかは確認できない。")],
   None, "出典：" + _S),
})
