from batch1 import D
from batch2 import BM
CARDS = {}

# 81 — Migraine prophylaxis (EN image copied from the paired English article)
CARDS['migren'] = ('navy', {
 'de': D("MIGRÄNEPROPHYLAXE", "Vorbeugende Behandlung der Migräne: der aktuelle Ansatz", "Ziel ist nicht nur, den Schmerz zu stoppen, sondern Attacken zu verhindern und Lebensqualität zurückzugeben", None, None,
   [("Wann daran denken:", "ab 4 Migränetagen im Monat, bei schweren oder langen Attacken, unzureichender Akuttherapie, Risiko des Medikamentenübergebrauchs oder chronischer Migräne."),
    ("Klassische Mittel:", "Betablocker, Antiepileptika (Topiramat, Valproat), Antidepressiva, Kalziumkanalblocker, Candesartan."),
    ("CGRP-gerichtete Therapien:", "monoklonale Antikörper (Erenumab, Fremanezumab, Galcanezumab, Eptinezumab) und Gepante (Atogepant, Rimegepant)."),
    ("OnabotulinumtoxinA:", "wirksam bei chronischer Migräne, Injektionen alle 12 Wochen."),
    ("Ohne Medikamente:", "Lebensstil, Bewegung, Schlafhygiene, Stressbewältigung, Biofeedback."),
    ("Beurteilung:", "nach 8 bis 12 Wochen; Ansprechen bedeutet mindestens 50 % weniger Attacken.")],
   "Das Ziel der Migränetherapie: nicht nur weniger Schmerz, sondern ein besseres Leben."),
 'es': D("PROFILAXIS DE LA MIGRAÑA", "Tratamiento preventivo de la migraña: el enfoque actual", "El objetivo no es solo cortar el dolor, sino prevenir las crisis y devolver la calidad de vida", None, None,
   [("Cuándo plantearlo:", "4 o más días de migraña al mes, crisis intensas o prolongadas, tratamiento agudo insuficiente, riesgo de abuso de medicación o migraña crónica."),
    ("Fármacos clásicos:", "betabloqueantes, antiepilépticos (topiramato, valproato), antidepresivos, antagonistas del calcio, candesartán."),
    ("Terapias dirigidas a CGRP:", "anticuerpos monoclonales (erenumab, fremanezumab, galcanezumab, eptinezumab) y gepantes (atogepant, rimegepant)."),
    ("OnabotulinumtoxinA:", "eficaz en la migraña crónica, inyecciones cada 12 semanas."),
    ("Sin fármacos:", "estilo de vida, ejercicio, higiene del sueño, manejo del estrés, biofeedback."),
    ("Evaluación:", "a las 8-12 semanas; respuesta es una reducción de al menos el 50 % de las crisis.")],
   "El objetivo en la migraña: no solo menos dolor, sino vivir mejor."),
 'ru': D("ПРОФИЛАКТИКА МИГРЕНИ", "Профилактическое лечение мигрени: современный подход", "Цель не только снять боль, но и предотвратить приступы и вернуть качество жизни", None, None,
   [("Когда думать о профилактике:", "4 и более дней мигрени в месяц, тяжёлые или длительные приступы, недостаточный эффект купирования, риск лекарственного абузуса, хроническая мигрень."),
    ("Классические средства:", "бета-блокаторы, противоэпилептические (топирамат, вальпроат), антидепрессанты, блокаторы кальциевых каналов, кандесартан."),
    ("Терапия, направленная на CGRP:", "моноклональные антитела (эренумаб, фреманезумаб, галканезумаб, эптинезумаб) и гепанты (атогепант, римегепант)."),
    ("Онаботулотоксин А:", "эффективен при хронической мигрени, инъекции каждые 12 недель."),
    ("Немедикаментозные методы:", "образ жизни, физическая активность, гигиена сна, управление стрессом, биологическая обратная связь."),
    ("Оценка:", "через 8-12 недель; ответ означает снижение числа приступов не менее чем на 50 %.")],
   "Цель лечения мигрени: не просто меньше боли, а лучшая жизнь."),
 'zh': D("偏头痛预防", "偏头痛的预防性治疗：当前思路", "目标不仅是止痛，更是预防发作、恢复生活质量", None, None,
   [("何时考虑：", "每月偏头痛达4天及以上、发作严重或持续时间长、急性期治疗效果不足、存在药物过度使用风险或慢性偏头痛。"),
    ("经典药物：", "β受体阻滞剂、抗癫痫药（托吡酯、丙戊酸）、抗抑郁药、钙通道阻滞剂、坎地沙坦。"),
    ("CGRP靶向治疗：", "单克隆抗体（依瑞奈尤单抗、瑞玛奈珠单抗、加卡奈珠单抗、艾普奈珠单抗）和吉泮类（阿托吉泮、瑞美吉泮）。"),
    ("A型肉毒毒素：", "对慢性偏头痛有效，每12周注射一次。"),
    ("非药物方法：", "生活方式调整、运动、睡眠卫生、压力管理、生物反馈。"),
    ("评估：", "8至12周后评估；发作减少至少50%视为有效。")],
   "偏头痛治疗的目标：不只是少痛，而是更好地生活。"),
 'hi': D("माइग्रेन की रोकथाम", "माइग्रेन का निवारक उपचार: वर्तमान दृष्टिकोण", "लक्ष्य केवल दर्द रोकना नहीं, बल्कि दौरे रोकना और जीवन की गुणवत्ता लौटाना है", None, None,
   [("कब सोचें:", "महीने में 4 या अधिक माइग्रेन दिन, तीव्र या लंबे दौरे, तात्कालिक उपचार अपर्याप्त, दवा के अति प्रयोग का जोखिम या क्रॉनिक माइग्रेन।"),
    ("पारंपरिक दवाएँ:", "बीटा ब्लॉकर, मिर्गी-रोधी (टोपिरामेट, वैल्प्रोएट), अवसादरोधी, कैल्शियम चैनल ब्लॉकर, कैंडेसार्टन।"),
    ("CGRP-लक्षित उपचार:", "मोनोक्लोनल एंटीबॉडी (एरेनुमैब, फ्रेमानेज़ुमैब, गैल्कानेज़ुमैब, एप्टिनेज़ुमैब) और गेपैंट (एटोगेपैंट, रिमेगेपैंट)।"),
    ("ओनाबोटुलिनमटॉक्सिन ए:", "क्रॉनिक माइग्रेन में प्रभावी, हर 12 सप्ताह में इंजेक्शन।"),
    ("बिना दवा के उपाय:", "जीवनशैली, व्यायाम, नींद की स्वच्छता, तनाव प्रबंधन, बायोफीडबैक।"),
    ("मूल्यांकन:", "8 से 12 सप्ताह बाद; दौरों में कम से कम 50% कमी को प्रतिक्रिया माना जाता है।")],
   "माइग्रेन उपचार का लक्ष्य: केवल कम दर्द नहीं, बेहतर जीवन।"),
 'ja': D("片頭痛の予防", "片頭痛の予防療法：現在の考え方", "目的は痛みを止めるだけでなく、発作を防ぎ生活の質を取り戻すこと", None, None,
   [("検討する時期：", "月4日以上の片頭痛、重度または長時間の発作、急性期治療が不十分、薬剤の使用過多のリスク、慢性片頭痛。"),
    ("従来の薬：", "β遮断薬、抗てんかん薬（トピラマート、バルプロ酸）、抗うつ薬、カルシウム拮抗薬、カンデサルタン。"),
    ("CGRP標的療法：", "モノクローナル抗体（エレヌマブ、フレマネズマブ、ガルカネズマブ、エプチネズマブ）とゲパント（アトゲパント、リメゲパント）。"),
    ("オナボツリヌムトキシンA：", "慢性片頭痛に有効、12週ごとに注射。"),
    ("薬以外の方法：", "生活習慣、運動、睡眠衛生、ストレス管理、バイオフィードバック。"),
    ("評価：", "8～12週後に判定。発作が50%以上減れば有効。")],
   "片頭痛治療の目標は、痛みを減らすだけでなく、より良く生きること。"),
})

# 83 — Phase 1 trials
CARDS['faz1'] = ('purple', {
 'en': D("HOPE, SCIENCE, INDUSTRY AND THE GLOBAL RESEARCH ECONOMY", "Phase 1 and Phase 1-2 trials in cancer and rare diseases", "The ethical, economic and global dimensions", None, None,
   [("How Phase 1 has changed:", "once small studies seeking toxicity and the maximum tolerated dose; today they also look for early signs of efficacy, with expansion cohorts and biomarker-based selection."),
    ("Core ethical problems:", "therapeutic misconception (patients assume the drug will treat them), incomplete information and consent, high risk with uncertain benefit, exploitation of despair and hope."),
    ("The global research economy:", "trials move to countries with lower cost, fast recruitment, easier regulation and a high patient burden."),
    ("Risk of ethical dumping:", "are high-risk, uncertain studies shifted to countries that are less protected economically?"),
    ("Turkey:", "low operating costs and a large patient pool attract Phase 1 work; publication rates and transparency remain an open question.")],
   "Phase 1 trials matter for the future of science, but they must be run with scientific and ethical transparency."),
 'de': D("HOFFNUNG, WISSENSCHAFT, INDUSTRIE UND DIE GLOBALE FORSCHUNGSÖKONOMIE", "Phase-1- und Phase-1/2-Studien bei Krebs und seltenen Erkrankungen", "Die ethische, wirtschaftliche und globale Dimension", None, None,
   [("Wie sich Phase 1 verändert hat:", "früher kleine Studien zu Toxizität und maximal verträglicher Dosis; heute suchen sie auch frühe Wirksamkeitssignale, mit Expansionskohorten und biomarkerbasierter Auswahl."),
    ("Ethische Kernprobleme:", "therapeutisches Missverständnis (Patienten glauben, das Mittel werde sie heilen), unvollständige Aufklärung und Einwilligung, hohes Risiko bei unsicherem Nutzen, Ausnutzung von Verzweiflung und Hoffnung."),
    ("Die globale Forschungsökonomie:", "Studien wandern in Länder mit niedrigen Kosten, schneller Rekrutierung, einfacherer Regulierung und hoher Krankheitslast."),
    ("Risiko des Ethik-Dumpings:", "Werden riskante, unsichere Studien in wirtschaftlich weniger geschützte Länder verlagert?"),
    ("Türkei:", "niedrige Betriebskosten und ein großer Patientenpool ziehen Phase-1-Studien an; Publikationsraten und Transparenz bleiben eine offene Frage.")],
   "Phase-1-Studien sind wichtig für die Zukunft der Wissenschaft, müssen aber wissenschaftlich und ethisch transparent geführt werden."),
 'es': D("ESPERANZA, CIENCIA, INDUSTRIA Y LA ECONOMÍA GLOBAL DE LA INVESTIGACIÓN", "Ensayos de fase 1 y fase 1-2 en cáncer y enfermedades raras", "La dimensión ética, económica y global", None, None,
   [("Cómo ha cambiado la fase 1:", "antes eran estudios pequeños para buscar toxicidad y dosis máxima tolerada; hoy también buscan señales tempranas de eficacia, con cohortes de expansión y selección por biomarcadores."),
    ("Problemas éticos de fondo:", "equívoco terapéutico (el paciente cree que el fármaco lo tratará), información y consentimiento insuficientes, riesgo alto con beneficio incierto, explotación de la desesperación y la esperanza."),
    ("La economía global de la investigación:", "los ensayos se trasladan a países con menor coste, reclutamiento rápido, regulación más fácil y alta carga de pacientes."),
    ("Riesgo de dumping ético:", "¿se desplazan los estudios de alto riesgo e inciertos a países económicamente menos protegidos?"),
    ("Turquía:", "los bajos costes operativos y una gran reserva de pacientes atraen la fase 1; las tasas de publicación y la transparencia siguen en cuestión.")],
   "Los ensayos de fase 1 importan para el futuro de la ciencia, pero deben realizarse con transparencia científica y ética."),
 'ru': D("НАДЕЖДА, НАУКА, ИНДУСТРИЯ И ГЛОБАЛЬНАЯ ЭКОНОМИКА ИССЛЕДОВАНИЙ", "Исследования фазы 1 и 1-2 при раке и редких болезнях", "Этическое, экономическое и глобальное измерение", None, None,
   [("Как изменилась фаза 1:", "раньше это были небольшие исследования токсичности и максимальной переносимой дозы; сегодня в них ищут и ранние признаки эффективности, с когортами расширения и отбором по биомаркерам."),
    ("Главные этические проблемы:", "терапевтическое заблуждение (пациент считает, что препарат его вылечит), неполное информирование и согласие, высокий риск при неясной пользе, эксплуатация отчаяния и надежды."),
    ("Глобальная экономика исследований:", "исследования уходят в страны с низкими затратами, быстрым набором, более простой регуляцией и большим числом пациентов."),
    ("Риск этического демпинга:", "не переносятся ли рискованные и неопределённые исследования в экономически менее защищённые страны?"),
    ("Турция:", "низкие операционные расходы и большой пул пациентов привлекают фазу 1; доля публикаций и прозрачность остаются под вопросом.")],
   "Исследования фазы 1 важны для будущего науки, но должны вестись с научной и этической прозрачностью."),
 'zh': D("希望、科学、产业与全球研究经济", "癌症与罕见病的1期及1-2期试验", "伦理、经济与全球层面", None, None,
   [("1期试验的演变：", "过去是寻找毒性和最大耐受剂量的小型研究；如今还要寻找早期疗效信号，采用扩展队列和基于生物标志物的入组。"),
    ("核心伦理问题：", "治疗性误解（患者以为药物一定能治病）、知情告知与同意不充分、高风险而获益不确定、利用绝望与希望。"),
    ("全球研究经济：", "试验流向成本更低、入组更快、监管更宽松、患者负担更重的国家。"),
    ("伦理倾销风险：", "高风险、不确定的研究是否被转移到经济上保护较弱的国家？"),
    ("土耳其：", "运营成本低、患者库大，吸引了1期研究；发表率与透明度仍是悬而未决的问题。")],
   "1期试验对科学的未来很重要，但必须在科学和伦理上保持透明。"),
 'hi': D("आशा, विज्ञान, उद्योग और वैश्विक शोध अर्थव्यवस्था", "कैंसर और दुर्लभ रोगों में फेज़ 1 और फेज़ 1-2 परीक्षण", "नैतिक, आर्थिक और वैश्विक आयाम", None, None,
   [("फेज़ 1 कैसे बदला:", "पहले ये विषाक्तता और अधिकतम सहनीय खुराक खोजने वाले छोटे अध्ययन थे; आज इनमें प्रभावकारिता के शुरुआती संकेत भी खोजे जाते हैं।"),
    ("मूल नैतिक समस्याएँ:", "उपचार का भ्रम (रोगी मानता है कि दवा उसे ठीक करेगी), अधूरी जानकारी और सहमति, अनिश्चित लाभ के साथ ऊँचा जोखिम, निराशा और आशा का शोषण।"),
    ("वैश्विक शोध अर्थव्यवस्था:", "परीक्षण उन देशों में जाते हैं जहाँ लागत कम, भर्ती तेज़, नियमन आसान और रोगी अधिक हैं।"),
    ("नैतिक डंपिंग का जोखिम:", "क्या अधिक जोखिम वाले अनिश्चित अध्ययन आर्थिक रूप से कम सुरक्षित देशों में भेजे जा रहे हैं?"),
    ("तुर्की:", "कम परिचालन लागत और बड़ा रोगी समूह फेज़ 1 को आकर्षित करते हैं; प्रकाशन दर और पारदर्शिता अब भी प्रश्न हैं।")],
   "फेज़ 1 परीक्षण विज्ञान के भविष्य के लिए अहम हैं, पर उन्हें वैज्ञानिक और नैतिक पारदर्शिता से चलाया जाना चाहिए।"),
 'ja': D("希望、科学、産業、そして世界の研究経済", "がんと希少疾患における第1相・第1/2相試験", "倫理的・経済的・国際的な側面", None, None,
   [("第1相の変化：", "かつては毒性と最大耐用量を探る小規模試験。現在は拡大コホートやバイオマーカーによる選択を用い、早期の有効性も探る。"),
    ("中心となる倫理問題：", "治療との誤解（患者は薬が効くと思い込む）、説明と同意の不足、利益が不確かな高リスク、絶望と希望の利用。"),
    ("世界の研究経済：", "試験は、費用が低く、登録が速く、規制が緩く、患者の多い国へ移っていく。"),
    ("倫理ダンピングの危険：", "高リスクで不確かな研究が、経済的に守られていない国へ移されていないか。"),
    ("トルコ：", "低い運営費と大きな患者プールが第1相試験を引き寄せる。公表率と透明性はなお課題。")],
   "第1相試験は科学の未来に重要だが、科学的・倫理的な透明性のもとで行われなければならない。"),
})

# 84 — Turkish universities (poster)
CARDS['univ'] = ('navy', {
 'en': D("TURKISH UNIVERSITIES", "From scientific erosion to institutional collapse", "Real independence is won by producing science. And science grows through merit, not loyalty. Universities grow through science and people, not buildings."),
 'de': D("TÜRKISCHE UNIVERSITÄTEN", "Von der wissenschaftlichen Erosion zum institutionellen Zusammenbruch", "Echte Unabhängigkeit gewinnt man, indem man Wissenschaft hervorbringt. Und Wissenschaft wächst durch Leistung, nicht durch Loyalität. Universitäten wachsen durch Wissenschaft und Menschen, nicht durch Gebäude."),
 'es': D("UNIVERSIDADES TURCAS", "De la erosión científica al colapso institucional", "La verdadera independencia se gana produciendo ciencia. Y la ciencia crece con el mérito, no con la lealtad. Las universidades crecen con ciencia y personas, no con edificios."),
 'ru': D("ТУРЕЦКИЕ УНИВЕРСИТЕТЫ", "От научной эрозии к институциональному краху", "Подлинная независимость достигается созданием науки. А наука растёт благодаря заслугам, а не лояльности. Университеты растут наукой и людьми, а не зданиями."),
 'zh': D("土耳其的大学", "从科学侵蚀到制度崩塌", "真正的独立靠产出科学赢得。科学靠才能成长，而不是靠忠诚。大学靠科学与人才壮大，而不是靠楼房。"),
 'hi': D("तुर्की के विश्वविद्यालय", "वैज्ञानिक क्षरण से संस्थागत पतन तक", "सच्ची स्वतंत्रता विज्ञान रचकर मिलती है। और विज्ञान निष्ठा से नहीं, योग्यता से बढ़ता है। विश्वविद्यालय इमारतों से नहीं, विज्ञान और इंसानों से बढ़ते हैं।"),
 'ja': D("トルコの大学", "科学の浸食から制度の崩壊へ", "真の独立は科学を生み出すことで得られる。科学は忠誠ではなく実力によって育つ。大学は建物ではなく、科学と人によって育つ。"),
})

# 85 — USTR Special 301
CARDS['ustr301'] = ('teal', {
 'en': D("GLOBAL PATENT WARS", "The USTR Special 301 Report and Turkey", "An analysis of the pharmaceutical industry and pharmaceutical independence", None, None,
   [("What it is:", "an annual report by the US Trade Representative on countries' protection of intellectual property (patents, copyright, trade secrets), widely used as a political tool for large drug companies' interests."),
    ("Turkey, 1989-2026:", "on the Watch List in most years, sometimes under closer review; never at the heaviest level, Priority Foreign Country."),
    ("Why Turkey is listed:", "drug price pressure and the fixed euro rate, data exclusivity, patent practice, biosimilars, copyright, and unpredictable regulation."),
    ("The core debate:", "patents and innovation on one side, public health and access to medicines on the other."),
    ("Turkey's dilemma:", "cheap generic supply in the short term, high-technology production and R&D in the long term.")],
   "Real independence comes not from building factories but from training scientists."),
 'de': D("GLOBALE PATENTKRIEGE", "Der USTR Special 301 Report und die Türkei", "Eine Analyse zu Pharmaindustrie und pharmazeutischer Unabhängigkeit", None, None,
   [("Was er ist:", "ein jährlicher Bericht des US-Handelsbeauftragten zum Schutz geistigen Eigentums (Patente, Urheberrecht, Geschäftsgeheimnisse) in anderen Ländern, oft ein politisches Instrument für die Interessen großer Pharmafirmen."),
    ("Türkei, 1989-2026:", "in den meisten Jahren auf der Watch List, zeitweise unter engerer Beobachtung; nie auf der schwersten Stufe, Priority Foreign Country."),
    ("Warum die Türkei gelistet ist:", "Preisdruck und fester Eurokurs, Unterlagenschutz, Patentpraxis, Biosimilars, Urheberrecht und unberechenbare Regulierung."),
    ("Die Kerndebatte:", "Patente und Innovation auf der einen, öffentliche Gesundheit und Zugang zu Arzneimitteln auf der anderen Seite."),
    ("Das Dilemma der Türkei:", "kurzfristig günstige Generikaversorgung, langfristig Hochtechnologie-Produktion sowie Forschung und Entwicklung.")],
   "Echte Unabhängigkeit entsteht nicht durch den Bau von Fabriken, sondern durch die Ausbildung von Wissenschaftlern."),
 'es': D("GUERRAS GLOBALES DE PATENTES", "El informe Special 301 de la USTR y Turquía", "Un análisis sobre la industria farmacéutica y la independencia farmacéutica", None, None,
   [("Qué es:", "un informe anual del Representante de Comercio de EE. UU. sobre la protección de la propiedad intelectual (patentes, derechos de autor, secretos comerciales) en otros países, usado a menudo como herramienta política de las grandes farmacéuticas."),
    ("Turquía, 1989-2026:", "en la Watch List la mayoría de los años, a veces bajo examen más estrecho; nunca en el nivel más grave, Priority Foreign Country."),
    ("Por qué figura Turquía:", "presión sobre los precios y tipo de cambio fijo del euro, exclusividad de datos, práctica de patentes, biosimilares, derechos de autor y regulación imprevisible."),
    ("El debate de fondo:", "patentes e innovación por un lado, salud pública y acceso a los medicamentos por otro."),
    ("El dilema de Turquía:", "a corto plazo, suministro barato de genéricos; a largo plazo, producción de alta tecnología e I+D.")],
   "La independencia real no llega construyendo fábricas, sino formando científicos."),
 'ru': D("ГЛОБАЛЬНЫЕ ПАТЕНТНЫЕ ВОЙНЫ", "Доклад USTR Special 301 и Турция", "Анализ фармацевтической отрасли и фармацевтической независимости", None, None,
   [("Что это такое:", "ежегодный доклад Торгового представителя США о защите интеллектуальной собственности (патенты, авторское право, коммерческая тайна) в других странах; часто служит политическим инструментом интересов крупных фармкомпаний."),
    ("Турция, 1989-2026:", "в большинстве лет в списке Watch List, иногда под более пристальным наблюдением; ни разу на самом тяжёлом уровне, Priority Foreign Country."),
    ("Почему Турция в списке:", "давление на цены и фиксированный курс евро, эксклюзивность данных, патентная практика, биоаналоги, авторское право и непредсказуемое регулирование."),
    ("Суть спора:", "патенты и инновации с одной стороны, общественное здоровье и доступ к лекарствам с другой."),
    ("Дилемма Турции:", "в краткосрочной перспективе дешёвые дженерики, в долгосрочной высокотехнологичное производство и НИОКР.")],
   "Настоящая независимость достигается не строительством заводов, а подготовкой учёных."),
 'zh': D("全球专利战", "美国贸易代表办公室《特别301报告》与土耳其", "关于制药产业与医药自主的分析", None, None,
   [("这是什么：", "美国贸易代表每年发布的报告，评估各国对知识产权（专利、版权、商业秘密）的保护，常被用作维护大型药企利益的政治工具。"),
    ("土耳其，1989至2026年：", "多数年份在观察名单上，有时受到更严密审查；从未被列入最严重的“重点外国”一级。"),
    ("土耳其为何上榜：", "药价压力与固定欧元汇率、数据独占、专利实践、生物类似药、版权以及监管的不可预测性。"),
    ("核心争论：", "一边是专利与创新，另一边是公共卫生与药品可及性。"),
    ("土耳其的两难：", "短期是廉价仿制药供应，长期是高技术生产与研发。")],
   "真正的独立不是靠建工厂，而是靠培养科学家。"),
 'hi': D("वैश्विक पेटेंट युद्ध", "USTR स्पेशल 301 रिपोर्ट और तुर्की", "दवा उद्योग और औषधीय स्वतंत्रता पर एक विश्लेषण", None, None,
   [("यह क्या है:", "अमेरिकी व्यापार प्रतिनिधि की वार्षिक रिपोर्ट, जो देशों में बौद्धिक संपदा (पेटेंट, कॉपीराइट, व्यापार रहस्य) की सुरक्षा को आँकती है; अक्सर बड़ी दवा कंपनियों के हितों का राजनीतिक औज़ार।"),
    ("तुर्की, 1989-2026:", "अधिकतर वर्षों में वॉच लिस्ट में, कभी-कभी कड़ी निगरानी में; सबसे गंभीर स्तर, प्रायोरिटी फ़ॉरेन कंट्री, पर कभी नहीं।"),
    ("तुर्की सूची में क्यों:", "दवा कीमतों पर दबाव और स्थिर यूरो दर, डेटा विशिष्टता, पेटेंट व्यवहार, बायोसिमिलर, कॉपीराइट और अनिश्चित नियमन।"),
    ("मूल बहस:", "एक ओर पेटेंट और नवाचार, दूसरी ओर जन स्वास्थ्य और दवाओं तक पहुँच।"),
    ("तुर्की की दुविधा:", "अल्पकाल में सस्ती जेनेरिक आपूर्ति, दीर्घकाल में उच्च तकनीक उत्पादन और अनुसंधान।")],
   "सच्ची स्वतंत्रता कारखाने बनाने से नहीं, वैज्ञानिक तैयार करने से आती है।"),
 'ja': D("世界の特許戦争", "USTRスペシャル301条報告書とトルコ", "製薬産業と医薬品の自立に関する分析", None, None,
   [("これは何か：", "米国通商代表部が毎年出す報告書。各国の知的財産（特許、著作権、営業秘密）保護を評価し、大手製薬企業の利益のための政治的手段としてもよく使われる。"),
    ("トルコ、1989～2026年：", "ほとんどの年で監視国リスト入り、時により厳しい審査対象。最も重い「優先国」には一度もなっていない。"),
    ("トルコが載る理由：", "薬価への圧力と固定ユーロレート、データ保護、特許運用、バイオシミラー、著作権、予測しにくい規制。"),
    ("中心的な論点：", "一方に特許とイノベーション、他方に公衆衛生と医薬品アクセス。"),
    ("トルコのジレンマ：", "短期的には安価なジェネリック供給、長期的には高度技術生産と研究開発。")],
   "真の自立は工場を建てることではなく、科学者を育てることから生まれる。"),
})

# 86 — Where is Turkish medicine going
CARDS['turktibbi'] = ('burg', {
 'en': D("AN ANALYSIS OF TUS DATA, 2016-2026", "Where is Turkish medicine going?", "Loss of merit, mass expansion and a collapsing medical education", None, None,
   [("Quota inflation:", "the number of medical schools and student places rose without control; average exam scores fell as places grew by about 10,000."),
    ("A 'defensive' shift in specialty choice:", "dermatology, plastic surgery and radiology now top the list; general surgery, obstetrics, paediatrics and neurosurgery places go unfilled, driven by fear of malpractice suits and violence."),
    ("The gap between schools:", "established faculties and new ones differ by close to 100 points in average exam results."),
    ("Loss of clinical quality:", "too few teachers and patients per student; learning shifts to exam courses and videos."),
    ("Proposed fixes:", "close or merge inadequate schools, exam reform, fair academic pay, a national qualifying exam, zero tolerance for violence in health care.")],
   "A country that starts losing its scientists loses not only its academia but its future."),
 'de': D("EINE ANALYSE DER TUS-DATEN 2016-2026", "Wohin steuert die türkische Medizin?", "Verlust des Leistungsprinzips, Vermassung und eine zusammenbrechende Medizinerausbildung", None, None,
   [("Inflation der Studienplätze:", "Zahl der Fakultäten und Studienplätze stieg unkontrolliert; die durchschnittlichen Prüfungsergebnisse sanken, während rund 10.000 Plätze hinzukamen."),
    ("«Defensive» Fachwahl:", "Dermatologie, plastische Chirurgie und Radiologie stehen an der Spitze; Stellen in Allgemeinchirurgie, Gynäkologie, Pädiatrie und Neurochirurgie bleiben unbesetzt, aus Angst vor Klagen und Gewalt."),
    ("Die Kluft zwischen den Fakultäten:", "etablierte und neue Fakultäten liegen im Prüfungsdurchschnitt fast 100 Punkte auseinander."),
    ("Verlust klinischer Qualität:", "zu wenige Lehrende und Patienten pro Studierendem; gelernt wird mit Repetitorien und Videos."),
    ("Lösungsvorschläge:", "unzureichende Fakultäten schließen oder zusammenlegen, Prüfungsreform, faire akademische Bezahlung, nationale Approbationsprüfung, null Toleranz bei Gewalt im Gesundheitswesen.")],
   "Ein Land, das seine Wissenschaftler verliert, verliert nicht nur seine Akademie, sondern seine Zukunft."),
 'es': D("UN ANÁLISIS DE LOS DATOS DEL TUS, 2016-2026", "¿Hacia dónde va la medicina turca?", "Pérdida del mérito, masificación y una formación médica que se derrumba", None, None,
   [("Inflación de plazas:", "el número de facultades y de plazas creció sin control; las notas medias del examen bajaron mientras las plazas aumentaban en unas 10.000."),
    ("Giro «defensivo» en la elección de especialidad:", "dermatología, cirugía plástica y radiología encabezan la lista; quedan vacantes en cirugía general, ginecología, pediatría y neurocirugía por miedo a demandas y a la violencia."),
    ("La brecha entre facultades:", "las facultades consolidadas y las nuevas difieren en casi 100 puntos de media en el examen."),
    ("Pérdida de calidad clínica:", "pocos docentes y pacientes por estudiante; se aprende con academias y vídeos."),
    ("Soluciones propuestas:", "cerrar o fusionar facultades insuficientes, reforma del examen, salarios académicos justos, examen nacional de habilitación y tolerancia cero con la violencia sanitaria.")],
   "Un país que empieza a perder a sus científicos pierde no solo su academia, sino su futuro."),
 'ru': D("АНАЛИЗ ДАННЫХ TUS ЗА 2016-2026 ГОДЫ", "Куда идёт турецкая медицина?", "Утрата меритократии, массовость и разрушающееся медицинское образование", None, None,
   [("Инфляция квот:", "число медицинских факультетов и мест росло бесконтрольно; средние баллы экзамена падали, а число мест выросло примерно на 10 000."),
    ("«Оборонительный» выбор специальности:", "лидируют дерматология, пластическая хирургия и радиология; места в общей хирургии, акушерстве, педиатрии и нейрохирургии пустуют из-за страха исков и насилия."),
    ("Разрыв между факультетами:", "старые и новые факультеты различаются почти на 100 баллов по среднему результату экзамена."),
    ("Потеря клинического качества:", "мало преподавателей и пациентов на студента; учатся по курсам подготовки и видео."),
    ("Предлагаемые решения:", "закрыть или объединить слабые факультеты, реформа экзамена, справедливая оплата труда преподавателей, национальный квалификационный экзамен, нулевая терпимость к насилию в медицине.")],
   "Страна, теряющая своих учёных, теряет не только академию, но и будущее."),
 'zh': D("2016至2026年TUS数据分析", "土耳其医学走向何方？", "任人唯贤的丧失、盲目扩招与正在崩塌的医学教育", None, None,
   [("招生名额膨胀：", "医学院和招生名额无序增长；名额增加约1万个的同时，考试平均分下降。"),
    ("专业选择的“防御性”转向：", "皮肤科、整形外科和放射科名列前茅；普外科、妇产科、儿科和神经外科名额招不满，原因是害怕医疗诉讼和暴力。"),
    ("院校之间的鸿沟：", "老牌医学院与新建医学院的考试平均分相差近100分。"),
    ("临床质量下降：", "每名学生对应的教师和患者太少；学习转向考试培训班和视频。"),
    ("解决建议：", "关闭或合并不合格院校、考试改革、公平的学术薪酬、全国执业资格考试、对医疗暴力零容忍。")],
   "一个开始失去科学家的国家，失去的不只是学术界，而是未来。"),
 'hi': D("TUS आँकड़ों का विश्लेषण, 2016-2026", "तुर्की की चिकित्सा किस ओर जा रही है?", "योग्यता का ह्रास, भीड़ीकरण और ढहती चिकित्सा शिक्षा", None, None,
   [("सीटों की बाढ़:", "मेडिकल कॉलेजों और सीटों की संख्या बेलगाम बढ़ी; सीटें लगभग 10,000 बढ़ीं और परीक्षा के औसत अंक गिरे।"),
    ("विशेषज्ञता चुनने में 'रक्षात्मक' मोड़:", "त्वचा रोग, प्लास्टिक सर्जरी और रेडियोलॉजी सबसे ऊपर; सामान्य सर्जरी, प्रसूति, बाल रोग और न्यूरोसर्जरी की सीटें खाली, मुक़दमों और हिंसा के डर से।"),
    ("कॉलेजों के बीच खाई:", "पुराने और नए कॉलेजों के औसत अंकों में लगभग 100 अंकों का अंतर।"),
    ("नैदानिक गुणवत्ता की हानि:", "प्रति छात्र शिक्षक और रोगी बहुत कम; पढ़ाई कोचिंग और वीडियो से।"),
    ("सुझाए गए उपाय:", "अपर्याप्त कॉलेज बंद या विलय, परीक्षा सुधार, उचित शैक्षणिक वेतन, राष्ट्रीय योग्यता परीक्षा, स्वास्थ्य क्षेत्र में हिंसा पर शून्य सहनशीलता।")],
   "जो देश अपने वैज्ञानिक खोने लगता है, वह केवल अपनी अकादमी नहीं, अपना भविष्य खोता है।"),
 'ja': D("TUSデータの分析、2016～2026年", "トルコの医学はどこへ向かうのか", "実力主義の喪失、大衆化、そして崩れゆく医学教育", None, None,
   [("定員のインフレ：", "医学部と定員が無秩序に増加。定員が約1万人増える一方で、試験の平均点は低下した。"),
    ("専門選択の「防衛的」転換：", "皮膚科、形成外科、放射線科が上位に。一般外科、産婦人科、小児科、脳神経外科は定員割れ。訴訟と暴力への恐れが背景。"),
    ("学部間の格差：", "伝統校と新設校では試験の平均点に100点近い差がある。"),
    ("臨床の質の低下：", "学生あたりの教員と患者が不足。学習は予備校と動画に移っている。"),
    ("提案される対策：", "不十分な学部の閉鎖・統合、試験改革、公正な教員給与、全国資格試験、医療現場の暴力に対するゼロ・トレランス。")],
   "科学者を失い始めた国は、学術界だけでなく未来を失う。"),
})

# 87 — Homeopathy (EN image copied from the paired English article)
CARDS['homeopati'] = ('navy', {
 'de': D("PSEUDOWISSENSCHAFT", "Homöopathie: kein wissenschaftlicher Beleg", "Placebo ja. Risiko ja. Kosten ja.", None, None,
   [("Was sie ist:", "im 18. Jahrhundert von Samuel Hahnemann entwickelt: «Ähnliches heilt Ähnliches» und «je verdünnter, desto stärker». Bei 30C (10⁻⁶⁰) bleibt kein einziges Molekül der Ausgangssubstanz."),
    ("Was die Wissenschaft sagt:", "NHMRC, Cochrane, WHO, EASAC und Metaanalysen im Lancet: nicht von Placebo zu unterscheiden."),
    ("Warum sie zu «wirken» scheint:", "Placeboeffekt: Erwartung, Arzt-Patient-Beziehung und Behandlungsritual."),
    ("Reale Risiken:", "Verzögerung wirksamer Therapie, vor allem bei Krebs und schweren Erkrankungen; in manchen Produkten Schwermetalle und pharmakologisch aktive Stoffe; finanzieller Schaden."),
    ("In der Welt:", "Frankreich hat die Erstattung beendet, der englische NHS empfiehlt sie nicht, in Deutschland wurde sie aus dem Versicherungsschutz genommen. In der Türkei seit 2014 offiziell zugelassen: legal heißt nicht wissenschaftlich.")],
   "Placebo kann den Patienten beruhigen. Homöopathie täuscht Patient und Arzt."),
 'es': D("PSEUDOCIENCIA", "Homeopatía: sin pruebas científicas", "Hay placebo. Hay riesgo. Hay coste.", None, None,
   [("Qué es:", "creada en el siglo XVIII por Samuel Hahnemann: «lo similar cura lo similar» y «cuanto más diluido, más potente». A 30C (10⁻⁶⁰) no queda ni una molécula de la sustancia original."),
    ("Qué dice la ciencia:", "NHMRC, Cochrane, OMS, EASAC y metaanálisis en The Lancet: no se distingue del placebo."),
    ("Por qué parece «funcionar»:", "efecto placebo: expectativa, relación médico-paciente y ritual del tratamiento."),
    ("Riesgos reales:", "retraso del tratamiento eficaz, sobre todo en cáncer y enfermedades graves; metales pesados y sustancias activas en algunos productos; perjuicio económico."),
    ("En el mundo:", "Francia retiró el reembolso, el NHS inglés no la recomienda y en Alemania se excluyó de la cobertura. En Turquía es oficial desde 2014: que sea legal no significa que sea científica.")],
   "El placebo puede aliviar al paciente. La homeopatía engaña al paciente y al médico."),
 'ru': D("ЛЖЕНАУКА", "Гомеопатия: научных доказательств нет", "Плацебо есть. Риск есть. Расходы есть.", None, None,
   [("Что это:", "создана в XVIII веке Самуэлем Ганеманом: «подобное лечится подобным» и «чем сильнее разведение, тем сильнее действие». При разведении 30C (10⁻⁶⁰) не остаётся ни одной молекулы исходного вещества."),
    ("Что говорит наука:", "NHMRC, Кокрейн, ВОЗ, EASAC и метаанализы в The Lancet: не отличается от плацебо."),
    ("Почему кажется, что «работает»:", "эффект плацебо: ожидание, отношения врача и пациента, ритуал лечения."),
    ("Реальные риски:", "задержка эффективного лечения, особенно при раке и тяжёлых болезнях; в некоторых средствах находят тяжёлые металлы и активные вещества; финансовый ущерб."),
    ("В мире:", "Франция отменила возмещение, английская NHS не рекомендует, в Германии исключили из страхового покрытия. В Турции разрешена с 2014 года: законно не значит научно.")],
   "Плацебо может успокоить пациента. Гомеопатия обманывает и пациента, и врача."),
 'zh': D("伪科学", "顺势疗法：没有科学证据", "有安慰剂效应。有风险。有成本。", None, None,
   [("它是什么：", "18世纪由塞缪尔·哈内曼提出：“以同治同”“越稀释越有效”。稀释到30C（10⁻⁶⁰）时，原始物质连一个分子都不剩。"),
    ("科学怎么说：", "澳大利亚NHMRC、Cochrane、世卫组织、EASAC以及《柳叶刀》荟萃分析：与安慰剂没有区别。"),
    ("为什么看似“有效”：", "安慰剂效应：期待、医患关系和治疗仪式。"),
    ("真实风险：", "延误有效治疗，尤其是癌症和重症；部分产品检出重金属和药理活性物质；经济损失。"),
    ("世界各国：", "法国取消报销，英国NHS不推荐，德国将其移出保险范围。土耳其自2014年起正式允许：合法不等于科学。")],
   "安慰剂可以让患者感到舒服。顺势疗法欺骗的是患者，也是医生。"),
 'hi': D("छद्म विज्ञान", "होम्योपैथी: कोई वैज्ञानिक प्रमाण नहीं", "प्लेसीबो है। जोखिम है। लागत है।", None, None,
   [("यह क्या है:", "18वीं सदी में सैमुअल हैनिमैन ने विकसित की: 'समान से समान का उपचार' और 'जितना पतला, उतना शक्तिशाली'। 30C (10⁻⁶⁰) पर मूल पदार्थ का एक भी अणु नहीं बचता।"),
    ("विज्ञान क्या कहता है:", "NHMRC, कॉक्रेन, WHO, EASAC और द लैंसेट के मेटा-विश्लेषण: प्लेसीबो से कोई अंतर नहीं।"),
    ("यह 'काम करती' क्यों लगती है:", "प्लेसीबो प्रभाव: अपेक्षा, डॉक्टर-रोगी संबंध और उपचार की रस्म।"),
    ("वास्तविक जोखिम:", "प्रभावी उपचार में देरी, ख़ासकर कैंसर और गंभीर रोगों में; कुछ उत्पादों में भारी धातुएँ और सक्रिय पदार्थ; आर्थिक नुकसान।"),
    ("दुनिया में:", "फ्रांस ने भुगतान बंद किया, इंग्लैंड का NHS इसकी सिफ़ारिश नहीं करता, जर्मनी में इसे बीमा से हटाया गया। तुर्की में 2014 से आधिकारिक: क़ानूनी होना वैज्ञानिक होना नहीं है।")],
   "प्लेसीबो रोगी को राहत दे सकता है। होम्योपैथी रोगी और डॉक्टर दोनों को धोखा देती है।"),
 'ja': D("疑似科学", "ホメオパシー：科学的根拠なし", "プラセボはある。リスクもある。費用もかかる。", None, None,
   [("ホメオパシーとは：", "18世紀にサミュエル・ハーネマンが考案。「似たものが似たものを治す」「薄めるほど強くなる」と主張。30C（10⁻⁶⁰）では元の物質は1分子も残らない。"),
    ("科学の見解：", "NHMRC、コクラン、WHO、EASAC、ランセットのメタ解析：プラセボと差がない。"),
    ("なぜ「効く」ように見えるのか：", "プラセボ効果：期待、医師と患者の関係、治療の儀式。"),
    ("現実のリスク：", "有効な治療の遅れ（特にがんや重い病気）、一部製品から重金属や薬理活性物質の検出、経済的損失。"),
    ("世界の状況：", "フランスは保険償還を廃止、英国NHSは推奨せず、ドイツでは保険適用から除外。トルコでは2014年から公認：合法は科学的という意味ではない。")],
   "プラセボは患者を楽にできる。ホメオパシーは患者も医師も欺く。"),
})

# 89 — Rescheduling cannabis and psychedelics in the US
CARDS['uyusturucu'] = ('dark', {
 'en': D("SCIENCE, OR A NEW ILLUSION?", "A 'medical' label for drugs", "Moving cannabis from Schedule I to Schedule III in the US and a softer line on psychedelics may open the way for research, but carry serious social risks", None, None,
   [("What changes technically:", "Schedule I means no accepted medical use and very high abuse potential; Schedule III means accepted medical use and lower dependence potential. This does not legalise cannabis, but it eases federal pressure, tax rules and research barriers."),
    ("Psychedelics:", "psilocybin and MDMA show promise in PTSD and depression, but the evidence is still limited."),
    ("Risks:", "dependence and misuse, especially among the young; psychosis and other psychiatric and physical harm; traffic and workplace safety; misleading marketing; weak oversight; social normalisation."),
    ("The politics:", "a populist, 'personal freedom' turn among conservatives helps drive the change.")],
   "Calling a substance 'medical' does not make it safe. A scientific opportunity is also a risk of abuse."),
 'de': D("WISSENSCHAFT ODER EINE NEUE ILLUSION?", "Ein «medizinisches» Etikett für Drogen", "Die Umstufung von Cannabis von Schedule I nach Schedule III in den USA und ein weicherer Kurs bei Psychedelika können Forschung ermöglichen, bergen aber ernste gesellschaftliche Risiken", None, None,
   [("Was sich technisch ändert:", "Schedule I heißt kein anerkannter medizinischer Nutzen und sehr hohes Missbrauchspotenzial; Schedule III heißt anerkannter medizinischer Nutzen und geringeres Abhängigkeitspotenzial. Cannabis wird dadurch nicht legal, aber Bundesdruck, Steuerregeln und Forschungshürden werden gelockert."),
    ("Psychedelika:", "Psilocybin und MDMA zeigen Potenzial bei PTBS und Depression, die Evidenz ist aber noch begrenzt."),
    ("Risiken:", "Abhängigkeit und Missbrauch, besonders bei Jugendlichen; Psychosen und andere psychische und körperliche Schäden; Verkehrs- und Arbeitssicherheit; irreführendes Marketing; schwache Aufsicht; gesellschaftliche Normalisierung."),
    ("Die Politik:", "eine populistische Wende zur «persönlichen Freiheit» unter Konservativen treibt den Wandel mit an.")],
   "Eine Substanz «medizinisch» zu nennen macht sie nicht sicher. Die wissenschaftliche Chance ist zugleich ein Missbrauchsrisiko."),
 'es': D("¿CIENCIA O UNA NUEVA ILUSIÓN?", "La etiqueta «médica» para las drogas", "Pasar el cannabis de la Lista I a la Lista III en EE. UU. y suavizar la postura sobre los psicodélicos puede abrir la investigación, pero conlleva riesgos sociales serios", None, None,
   [("Qué cambia técnicamente:", "la Lista I supone ningún uso médico aceptado y muy alto potencial de abuso; la Lista III, uso médico aceptado y menor potencial de dependencia. No legaliza el cannabis, pero alivia la presión federal, las normas fiscales y las barreras a la investigación."),
    ("Psicodélicos:", "la psilocibina y la MDMA son prometedoras en el TEPT y la depresión, pero la evidencia aún es limitada."),
    ("Riesgos:", "dependencia y abuso, sobre todo en jóvenes; psicosis y otros daños psiquiátricos y físicos; seguridad vial y laboral; marketing engañoso; supervisión débil; normalización social."),
    ("La política:", "un giro populista de «libertad personal» entre los conservadores impulsa el cambio.")],
   "Llamar «médica» a una sustancia no la hace segura. La oportunidad científica es también un riesgo de abuso."),
 'ru': D("НАУКА ИЛИ НОВАЯ ИЛЛЮЗИЯ?", "«Медицинский» ярлык для наркотиков", "Перевод каннабиса из Списка I в Список III в США и смягчение подхода к психоделикам могут открыть путь исследованиям, но несут серьёзные общественные риски", None, None,
   [("Что меняется технически:", "Список I означает отсутствие признанного медицинского применения и очень высокий потенциал злоупотребления; Список III означает признанное применение и меньший потенциал зависимости. Это не легализует каннабис, но ослабляет федеральное давление, налоговые правила и барьеры для исследований."),
    ("Психоделики:", "псилоцибин и МДМА перспективны при ПТСР и депрессии, но доказательств пока мало."),
    ("Риски:", "зависимость и злоупотребление, особенно у молодёжи; психозы и другой психический и физический вред; безопасность на дорогах и на работе; вводящий в заблуждение маркетинг; слабый надзор; нормализация в обществе."),
    ("Политика:", "популистский поворот консерваторов к «личной свободе» подталкивает перемены.")],
   "Назвать вещество «медицинским» не значит сделать его безопасным. Научная возможность одновременно является риском злоупотребления."),
 'zh': D("是科学，还是新的幻象？", "给毒品贴上“医用”标签", "美国将大麻从第一类管制物质调为第三类，并放宽对致幻剂的态度，可能为研究开路，也带来严重的社会风险", None, None,
   [("技术层面的变化：", "第一类意味着没有公认的医疗用途、滥用潜力极高；第三类意味着有公认的医疗用途、依赖潜力较低。这并未使大麻合法化，但减轻了联邦压力、税务限制和研究障碍。"),
    ("致幻剂：", "裸盖菇素和MDMA在创伤后应激障碍和抑郁症方面显示出潜力，但证据仍然有限。"),
    ("风险：", "成瘾与滥用，尤其是年轻人；精神病及其他身心损害；交通与职场安全；误导性营销；监管薄弱；社会正常化。"),
    ("政治因素：", "保守派中一种民粹的“个人自由”转向推动了这一变化。")],
   "把一种物质称为“医用”并不会让它变得安全。科学机遇同时也是滥用风险。"),
 'hi': D("विज्ञान, या एक नया भ्रम?", "नशीले पदार्थों पर 'चिकित्सीय' लेबल", "अमेरिका में भांग को अनुसूची I से अनुसूची III में लाना और साइकेडेलिक पदार्थों पर नरम रुख़ शोध का रास्ता खोल सकता है, पर गंभीर सामाजिक जोखिम भी लाता है", None, None,
   [("तकनीकी रूप से क्या बदलता है:", "अनुसूची I का अर्थ है कोई मान्य चिकित्सीय उपयोग नहीं और दुरुपयोग की बहुत ऊँची संभावना; अनुसूची III का अर्थ है मान्य चिकित्सीय उपयोग और कम निर्भरता। इससे भांग वैध नहीं होती, पर संघीय दबाव, कर नियम और शोध की बाधाएँ घटती हैं।"),
    ("साइकेडेलिक पदार्थ:", "सिलोसाइबिन और MDMA, PTSD और अवसाद में संभावना दिखाते हैं, पर प्रमाण अभी सीमित हैं।"),
    ("जोखिम:", "लत और दुरुपयोग, ख़ासकर युवाओं में; मनोविकृति और अन्य मानसिक व शारीरिक हानि; सड़क और कार्यस्थल सुरक्षा; भ्रामक विपणन; कमज़ोर निगरानी; सामाजिक सामान्यीकरण।"),
    ("राजनीति:", "रूढ़िवादियों में 'व्यक्तिगत स्वतंत्रता' की लोकलुभावन करवट इस बदलाव को आगे बढ़ाती है।")],
   "किसी पदार्थ को 'चिकित्सीय' कह देने से वह सुरक्षित नहीं हो जाता। वैज्ञानिक अवसर साथ ही दुरुपयोग का जोखिम भी है।"),
 'ja': D("科学か、新たな幻想か", "薬物に貼られる「医療用」のラベル", "米国で大麻をスケジュールIからIIIへ移し、サイケデリックスへの姿勢を緩める動きは研究の道を開く一方、深刻な社会的リスクを伴う", None, None,
   [("技術的に何が変わるか：", "スケジュールIは医療用途が認められず乱用の危険が極めて高い分類、IIIは医療用途が認められ依存性がより低い分類。大麻が合法化されるわけではないが、連邦の圧力、税制、研究の障壁が緩む。"),
    ("サイケデリックス：", "シロシビンとMDMAはPTSDやうつ病で有望だが、根拠はまだ限られている。"),
    ("リスク：", "依存と乱用（特に若者）、精神病などの精神的・身体的害、交通と職場の安全、誤解を招く宣伝、不十分な監督、社会的な常態化。"),
    ("政治的背景：", "保守層における「個人の自由」を掲げるポピュリズム的転換が変化を後押ししている。")],
   "物質を「医療用」と呼んでも安全にはならない。科学的な機会は、同時に乱用のリスクでもある。"),
})

# 91 — Scientific misconduct and zombie papers in Turkey
CARDS['zombi'] = ('burg', {
 'en': D("THE BIGGEST DANGER IN SCIENCE: THE WRONG LIVING ON AS IF IT WERE RIGHT", "Scientific misconduct in Turkey and 'zombie papers'", "A paper that has been scientifically refuted but is still cited is a zombie", None, None,
   [("Why papers are retracted:", "plagiarism, duplicate publication, data manipulation, data fabrication, fake peer review, missing ethics approval."),
    ("Specific to Turkey:", "ghost writing, guest authorship, papers and theses written for money, predatory journals, and fake output produced for academic promotion."),
    ("The zombie paper:", "even after retraction it is read, cited and can shape clinical decisions. Example: Paxil and the well-known Study 329."),
    ("Where it happens:", "most retracted papers come from universities and teaching hospitals: the problem is at the centre of the system, not its edge."),
    ("The fix:", "transparency, ethics, oversight and scientific honesty.")],
   "This is not a crisis of papers; it is a crisis of trust."),
 'de': D("DIE GRÖSSTE GEFAHR DER WISSENSCHAFT: DAS FALSCHE LEBT WEITER, ALS WÄRE ES RICHTIG", "Wissenschaftliches Fehlverhalten in der Türkei und «Zombie-Artikel»", "Ein wissenschaftlich widerlegter Artikel, der weiter zitiert wird, ist ein Zombie", None, None,
   [("Gründe für Rückzüge:", "Plagiat, Doppelpublikation, Datenmanipulation, Datenfälschung, gefälschtes Peer-Review, fehlendes Ethikvotum."),
    ("Türkeispezifisch:", "Ghostwriting, Gastautorschaft, gegen Geld geschriebene Artikel und Dissertationen, Raubjournale und Scheinproduktion für die akademische Beförderung."),
    ("Der Zombie-Artikel:", "auch nach dem Rückzug wird er gelesen, zitiert und kann klinische Entscheidungen prägen. Beispiel: Paxil und die bekannte Studie 329."),
    ("Wo es geschieht:", "die meisten zurückgezogenen Arbeiten stammen aus Universitäten und Lehrkrankenhäusern: das Problem sitzt im Zentrum des Systems, nicht am Rand."),
    ("Die Lösung:", "Transparenz, Ethik, Kontrolle und wissenschaftliche Redlichkeit.")],
   "Das ist keine Krise der Artikel, sondern eine Krise des Vertrauens."),
 'es': D("EL MAYOR PELIGRO DE LA CIENCIA: QUE LO FALSO SIGA VIVO COMO SI FUERA CIERTO", "Mala conducta científica en Turquía y los «artículos zombi»", "Un artículo refutado científicamente que sigue citándose es un zombi", None, None,
   [("Motivos de retractación:", "plagio, publicación duplicada, manipulación de datos, invención de datos, revisión por pares falsa, falta de aprobación ética."),
    ("Propio de Turquía:", "escritura fantasma, autoría invitada, artículos y tesis por encargo, revistas depredadoras y producción falsa para ascender en la academia."),
    ("El artículo zombi:", "aun retirado, se lee, se cita y puede influir en decisiones clínicas. Ejemplo: Paxil y el conocido Estudio 329."),
    ("Dónde ocurre:", "la mayoría de los artículos retirados procede de universidades y hospitales docentes: el problema está en el centro del sistema, no en la periferia."),
    ("La solución:", "transparencia, ética, control y honestidad científica.")],
   "No es una crisis de artículos; es una crisis de confianza."),
 'ru': D("ГЛАВНАЯ ОПАСНОСТЬ В НАУКЕ: ЛОЖНОЕ ПРОДОЛЖАЕТ ЖИТЬ КАК ИСТИННОЕ", "Научная недобросовестность в Турции и «статьи-зомби»", "Научно опровергнутая, но по-прежнему цитируемая статья и есть зомби", None, None,
   [("Причины отзыва статей:", "плагиат, дублирование публикаций, манипуляция данными, фабрикация данных, поддельное рецензирование, отсутствие этического одобрения."),
    ("Особенности Турции:", "гострайтинг, гостевое авторство, статьи и диссертации на заказ, хищнические журналы и фиктивные публикации ради академического продвижения."),
    ("Статья-зомби:", "даже после отзыва её читают, цитируют, и она может влиять на клинические решения. Пример: Паксил и известное Исследование 329."),
    ("Где это происходит:", "большинство отозванных работ вышло из университетов и учебных больниц: проблема в центре системы, а не на периферии."),
    ("Решение:", "прозрачность, этика, контроль и научная честность.")],
   "Это не кризис статей, а кризис доверия."),
 'zh': D("科学最大的危险：错误像真理一样继续活着", "土耳其的科研不端与“僵尸论文”", "在科学上已被推翻却仍被引用的论文，就是僵尸", None, None,
   [("撤稿原因：", "抄袭、重复发表、数据操纵、数据捏造、虚假同行评审、缺少伦理批准。"),
    ("土耳其特有的问题：", "代写、挂名作者、花钱代写论文和学位论文、掠夺性期刊，以及为职称晋升而制造的虚假成果。"),
    ("僵尸论文：", "即使被撤回，仍被阅读、引用，并可能影响临床决策。例子：帕罗西汀（Paxil）与著名的329号研究。"),
    ("发生在哪里：", "被撤论文多数来自大学和教学医院：问题在体系的中心，而不是边缘。"),
    ("解决之道：", "透明、伦理、监督与科学诚信。")],
   "这不是论文危机，而是信任危机。"),
 'hi': D("विज्ञान का सबसे बड़ा ख़तरा: ग़लत का सही की तरह जीते रहना", "तुर्की में वैज्ञानिक कदाचार और 'ज़ॉम्बी शोधपत्र'", "वैज्ञानिक रूप से खंडित होने के बाद भी उद्धृत होता शोधपत्र ज़ॉम्बी है", None, None,
   [("शोधपत्र वापस लेने के कारण:", "साहित्यिक चोरी, दोहरा प्रकाशन, आँकड़ों में हेरफेर, आँकड़े गढ़ना, फ़र्ज़ी समीक्षा, नैतिक अनुमति का अभाव।"),
    ("तुर्की की विशेष समस्याएँ:", "घोस्ट राइटिंग, अतिथि लेखकत्व, पैसे लेकर लिखे गए शोधपत्र और शोधप्रबंध, शिकारी पत्रिकाएँ और पदोन्नति के लिए नकली प्रकाशन।"),
    ("ज़ॉम्बी शोधपत्र:", "वापस लिए जाने के बाद भी पढ़ा और उद्धृत किया जाता है और नैदानिक निर्णयों को प्रभावित कर सकता है। उदाहरण: पैक्सिल और प्रसिद्ध स्टडी 329।"),
    ("कहाँ होता है:", "वापस लिए गए अधिकतर शोधपत्र विश्वविद्यालयों और शिक्षण अस्पतालों से हैं: समस्या व्यवस्था के केंद्र में है, किनारे पर नहीं।"),
    ("समाधान:", "पारदर्शिता, नैतिकता, निगरानी और वैज्ञानिक ईमानदारी।")],
   "यह शोधपत्रों का संकट नहीं, भरोसे का संकट है।"),
 'ja': D("科学における最大の危険：誤りが正しいものとして生き続けること", "トルコの研究不正と「ゾンビ論文」", "科学的に否定されたのに引用され続ける論文、それがゾンビである", None, None,
   [("撤回の理由：", "盗用、二重投稿、データ改ざん、データ捏造、偽の査読、倫理承認の欠如。"),
    ("トルコ特有の問題：", "ゴーストライティング、ゲストオーサーシップ、金銭で書かれる論文や学位論文、ハゲタカジャーナル、昇進のための偽の業績。"),
    ("ゾンビ論文：", "撤回後も読まれ、引用され、臨床判断に影響しうる。例：パキシルと有名なスタディ329。"),
    ("どこで起きているか：", "撤回論文の多くは大学と教育病院から出ている。問題は制度の周縁ではなく中心にある。"),
    ("解決策：", "透明性、倫理、監督、そして科学的誠実さ。")],
   "これは論文の危機ではなく、信頼の危機である。"),
})
