from batch1 import D
CARDS = {}

# 63 - Kennedy Jr and vaccines
CARDS['b19_kennedy'] = ('teal', {
 'en': D("USA · VACCINES", "The US Health Secretary hits a hard rock: censorship of science!", "Kennedy Jr dismissed the vaccine advisers and asked for a study to be withdrawn",
   [("43% → 6.2%", "ACIP: reported conflicts of interest, early 2000s vs. since 2016"), ("27% → 1.9%", "VRBPAC: the same comparison"), ("<1%", "Personal income from vaccine makers, both committees, since 2016"), ("1.2 million", "Children in the aluminium vaccine study")], None,
   [("June 2025:", "HHS Secretary Robert F. Kennedy Jr. removed all members of ACIP, citing conflict-of-interest concerns."),
    ("Censorship attempt:", "he asked Annals of Internal Medicine to withdraw the study showing no harm from aluminium in vaccines. The journal keeps it online."),
    ("The response:", "AAP, ACP, APHA, IDSA, MPHA and SMFM sued HHS and Kennedy to stop the attacks on public health.")],
   "National Immunization Awareness Month: vaccines are safe and effective.", "Sources: JAMA; Annals of Internal Medicine; ACP"),
 'de': D("USA · IMPFSTOFFE", "US-Gesundheitsminister beißt auf Granit: Zensur der Wissenschaft!", "Kennedy Jr. entließ die Impfberater und verlangte die Rücknahme einer Studie",
   [("43% → 6,2%", "ACIP: gemeldete Interessenkonflikte, frühe 2000er vs. seit 2016"), ("27% → 1,9%", "VRBPAC: derselbe Vergleich"), ("<1%", "Persönliche Einkünfte von Impfstoffherstellern, beide Ausschüsse, seit 2016"), ("1,2 Millionen", "Kinder in der Studie zu Aluminium in Impfstoffen")], None,
   [("Juni 2025:", "HHS-Minister Robert F. Kennedy Jr. entließ alle Mitglieder des ACIP und begründete dies mit Interessenkonflikten."),
    ("Zensurversuch:", "Er verlangte von Annals of Internal Medicine, die Studie zurückzuziehen, die keinen Schaden durch Aluminium in Impfstoffen zeigt. Die Zeitschrift hält sie online."),
    ("Die Antwort:", "AAP, ACP, APHA, IDSA, MPHA und SMFM verklagten HHS und Kennedy, um die Angriffe auf die öffentliche Gesundheit zu stoppen.")],
   "Nationaler Monat der Impfaufklärung: Impfstoffe sind sicher und wirksam.", "Quellen: JAMA; Annals of Internal Medicine; ACP"),
 'es': D("EE. UU. · VACUNAS", "El secretario de Salud de EE. UU. choca contra un muro: ¡censura a la ciencia!", "Kennedy Jr. destituyó a los asesores de vacunas y pidió retirar un estudio",
   [("43% → 6,2%", "ACIP: conflictos de intereses declarados, inicios de los 2000 vs. desde 2016"), ("27% → 1,9%", "VRBPAC: la misma comparación"), ("<1%", "Ingresos personales de fabricantes de vacunas, ambos comités, desde 2016"), ("1,2 millones", "Niños en el estudio sobre aluminio en vacunas")], None,
   [("Junio de 2025:", "el secretario del HHS, Robert F. Kennedy Jr., destituyó a todos los miembros del ACIP alegando conflictos de intereses."),
    ("Intento de censura:", "pidió a Annals of Internal Medicine retirar el estudio que no halló daño por el aluminio de las vacunas. La revista lo mantiene publicado."),
    ("La respuesta:", "AAP, ACP, APHA, IDSA, MPHA y SMFM demandaron al HHS y a Kennedy para frenar los ataques a la salud pública.")],
   "Mes Nacional de Concienciación sobre la Vacunación: las vacunas son seguras y eficaces.", "Fuentes: JAMA; Annals of Internal Medicine; ACP"),
 'ru': D("США · ВАКЦИНЫ", "Министр здравоохранения США: нашла коса на камень. Цензура науки!", "Кеннеди-младший уволил советников по вакцинам и потребовал отозвать исследование",
   [("43% → 6,2%", "ACIP: заявленные конфликты интересов, начало 2000-х и с 2016 г."), ("27% → 1,9%", "VRBPAC: то же сравнение"), ("<1%", "Личные доходы от производителей вакцин, оба комитета, с 2016 г."), ("1,2 млн", "Детей в исследовании алюминия в вакцинах")], None,
   [("Июнь 2025 г.:", "министр HHS Роберт Ф. Кеннеди-младший уволил всех членов ACIP, сославшись на конфликт интересов."),
    ("Попытка цензуры:", "он потребовал от Annals of Internal Medicine отозвать исследование, не выявившее вреда от алюминия в вакцинах. Журнал статью не снял."),
    ("Ответ:", "AAP, ACP, APHA, IDSA, MPHA и SMFM подали иск против HHS и Кеннеди, чтобы остановить атаки на общественное здоровье.")],
   "Национальный месяц осведомлённости об иммунизации: вакцины безопасны и эффективны.", "Источники: JAMA; Annals of Internal Medicine; ACP"),
 'zh': D("美国 · 疫苗", "美国卫生部长碰了硬钉子：对科学的审查！", "小肯尼迪解除了疫苗顾问的职务，并要求撤下一项研究",
   [("43% → 6.2%", "ACIP：申报的利益冲突，2000年代初与2016年以来"), ("27% → 1.9%", "VRBPAC：同样的比较"), ("<1%", "来自疫苗厂商的个人收入，两个委员会，2016年以来"), ("120万", "疫苗铝佐剂研究中的儿童人数")], None,
   [("2025年6月：", "美国卫生与公众服务部（HHS）部长小罗伯特·F·肯尼迪以利益冲突为由，解除了ACIP全体成员的职务。"),
    ("审查企图：", "他要求 Annals of Internal Medicine 撤下一项显示疫苗中的铝无害的研究。该期刊继续刊载此文。"),
    ("回应：", "AAP、ACP、APHA、IDSA、MPHA和SMFM联合起诉HHS和肯尼迪，要求停止对公共卫生的攻击。")],
   "全国免疫宣传月：疫苗安全有效。", "来源：JAMA；Annals of Internal Medicine；ACP"),
 'hi': D("अमेरिका · टीके", "अमेरिकी स्वास्थ्य मंत्री कठोर चट्टान से टकराए: विज्ञान पर सेंसरशिप!", "कैनेडी जूनियर ने टीका सलाहकारों को हटाया और एक अध्ययन वापस लेने की मांग की",
   [("43% → 6.2%", "ACIP: घोषित हितों के टकराव, 2000 के शुरुआती वर्ष बनाम 2016 से"), ("27% → 1.9%", "VRBPAC: वही तुलना"), ("<1%", "टीका निर्माताओं से निजी आय, दोनों समितियाँ, 2016 से"), ("12 लाख", "टीकों में एल्युमिनियम के अध्ययन में बच्चे")], None,
   [("जून 2025:", "HHS मंत्री रॉबर्ट एफ. कैनेडी जूनियर ने हितों के टकराव का हवाला देकर ACIP के सभी सदस्यों को हटा दिया।"),
    ("सेंसरशिप की कोशिश:", "उन्होंने Annals of Internal Medicine से वह अध्ययन हटाने को कहा जिसमें टीकों के एल्युमिनियम से कोई हानि नहीं मिली। पत्रिका ने उसे नहीं हटाया।"),
    ("जवाब:", "AAP, ACP, APHA, IDSA, MPHA और SMFM ने जन स्वास्थ्य पर हमले रोकने के लिए HHS और कैनेडी पर मुकदमा किया।")],
   "राष्ट्रीय टीकाकरण जागरूकता माह: टीके सुरक्षित और प्रभावी हैं।", "स्रोत: JAMA; Annals of Internal Medicine; ACP"),
 'ja': D("米国 · ワクチン", "米保健長官、固い岩にぶつかる：科学への検閲！", "ケネディ・ジュニア氏はワクチン諮問委員を解任し、研究論文の撤回を求めた",
   [("43% → 6.2%", "ACIP：申告された利益相反、2000年代初頭と2016年以降"), ("27% → 1.9%", "VRBPAC：同じ比較"), ("<1%", "ワクチン製造企業からの個人収入、両委員会、2016年以降"), ("120万人", "ワクチン中のアルミニウム研究の対象小児")], None,
   [("2025年6月：", "HHS長官ロバート・F・ケネディ・ジュニア氏は、利益相反の懸念を理由にACIPの全委員を解任した。"),
    ("検閲の試み：", "ワクチン中のアルミニウムに害がないことを示した研究の撤回を Annals of Internal Medicine に求めた。同誌は掲載を続けている。"),
    ("対抗措置：", "AAP、ACP、APHA、IDSA、MPHA、SMFMは、公衆衛生への攻撃を止めるためHHSとケネディ氏を提訴した。")],
   "全米予防接種啓発月間：ワクチンは安全で有効である。", "出典：JAMA、Annals of Internal Medicine、ACP"),
})

# 68 - Should SGK pay for every drug
CARDS['b19_sgk'] = ('burg', {
 'en': D("REIMBURSEMENT", "How many drugs are left that you do not reimburse?", "Should SGK, Turkey's social security institution, pay for every drug?",
   [("47", "more drugs added to the reimbursement list"), ("81", "more drugs added to the reimbursement list"), ("18", "more drugs covered by reimbursement"), ("61", "more drugs covered by reimbursement")], "SGK ANNOUNCEMENTS AND THE ARTICLE",
   [("Court of Cassation:", "a drug cannot be paid for by SGK just because it gives a short-term benefit or improves quality of life. The physician's opinion alone is not enough."),
    ("What must be weighed:", "scientific evidence, vital necessity and the legal limits of SGK, together."),
    ("The problem:", "pharmacoeconomics exists only on paper at SGK and TİTCK, so reimbursement is decided through lawsuits."),
    ("No country", "in the world reimburses all drugs.")],
   "The SGK budget is the budget of 81 million people."),
 'de': D("ERSTATTUNG", "Wie viele Arzneimittel bleiben noch, die Sie nicht erstatten?", "Soll die türkische Sozialversicherung SGK jedes Arzneimittel bezahlen?",
   [("47", "weitere Arzneimittel in die Erstattungsliste aufgenommen"), ("81", "weitere Arzneimittel in die Erstattungsliste aufgenommen"), ("18", "weitere Arzneimittel in der Erstattung"), ("61", "weitere Arzneimittel in der Erstattung")], "MELDUNGEN DER SGK UND DER ARTIKEL",
   [("Kassationshof:", "Ein Arzneimittel kann nicht allein deshalb von der SGK bezahlt werden, weil es kurzfristig nützt oder die Lebensqualität verbessert. Die ärztliche Meinung allein genügt nicht."),
    ("Abzuwägen sind:", "wissenschaftliche Evidenz, vitale Notwendigkeit und die gesetzlichen Grenzen der SGK, gemeinsam."),
    ("Das Problem:", "Pharmakoökonomie existiert bei SGK und TİTCK nur auf dem Papier, daher wird über Erstattung vor Gericht entschieden."),
    ("Kein Land", "der Welt erstattet alle Arzneimittel.")],
   "Das Budget der SGK ist das Budget von 81 Millionen Menschen."),
 'es': D("REEMBOLSO", "¿Cuántos medicamentos quedan que ustedes no reembolsen?", "¿Debe la SGK, la seguridad social de Turquía, pagar todos los medicamentos?",
   [("47", "medicamentos más añadidos a la lista de reembolso"), ("81", "medicamentos más añadidos a la lista de reembolso"), ("18", "medicamentos más con reembolso"), ("61", "medicamentos más con reembolso")], "ANUNCIOS DE LA SGK Y EL ARTÍCULO",
   [("Tribunal de Casación:", "la SGK no puede pagar un medicamento solo porque aporte un beneficio breve o mejore la calidad de vida. La opinión del médico por sí sola no basta."),
    ("Qué debe valorarse:", "la evidencia científica, la necesidad vital y los límites legales de la SGK, en conjunto."),
    ("El problema:", "la farmacoeconomía existe solo sobre el papel en la SGK y la TİTCK, y el reembolso se decide mediante demandas."),
    ("Ningún país", "del mundo reembolsa todos los medicamentos.")],
   "El presupuesto de la SGK es el presupuesto de 81 millones de personas."),
 'ru': D("ВОЗМЕЩЕНИЕ", "Сколько осталось лекарств, которые вы не возмещаете?", "Должна ли SGK, служба социального страхования Турции, оплачивать каждое лекарство?",
   [("47", "препаратов ещё включено в список возмещения"), ("81", "препарат ещё включён в список возмещения"), ("18", "препаратов ещё с возмещением"), ("61", "препарат ещё с возмещением")], "ОБЪЯВЛЕНИЯ SGK И СТАТЬЯ",
   [("Кассационный суд:", "SGK не может оплачивать препарат только потому, что он даёт кратковременную пользу или улучшает качество жизни. Одного мнения врача недостаточно."),
    ("Что нужно учитывать:", "научные доказательства, жизненную необходимость и законные пределы SGK, в совокупности."),
    ("Проблема:", "фармакоэкономика в SGK и TİTCK существует лишь на бумаге, поэтому вопрос возмещения решается через суды."),
    ("Ни одна страна", "в мире не возмещает все лекарства.")],
   "Бюджет SGK это бюджет 81 миллиона человек."),
 'zh': D("药品报销", "你们不报销的药还剩多少？", "土耳其社会保障机构（SGK）应该为每一种药付费吗？",
   [("47", "种药品新增列入报销目录"), ("81", "种药品新增列入报销目录"), ("18", "种药品新纳入报销范围"), ("61", "种药品新纳入报销范围")], "SGK的公告与本文要点",
   [("最高上诉法院：", "不能仅因一种药带来短期获益或改善生活质量，就由SGK支付。仅凭医生的意见是不够的。"),
    ("必须综合考量：", "科学证据、生命攸关的必要性以及SGK的法定界限。"),
    ("问题所在：", "药物经济学在SGK和TITCK只停留在纸面上，报销问题因此靠诉讼来决定。"),
    ("世界上没有一个国家", "报销所有药品。")],
   "SGK的预算是8100万人的预算。"),
 'hi': D("प्रतिपूर्ति", "ऐसी कितनी दवाएँ बची हैं जिनकी आप प्रतिपूर्ति नहीं करते?", "क्या तुर्की की सामाजिक सुरक्षा संस्था SGK को हर दवा का भुगतान करना चाहिए?",
   [("47", "और दवाएँ प्रतिपूर्ति सूची में जोड़ी गईं"), ("81", "और दवाएँ प्रतिपूर्ति सूची में जोड़ी गईं"), ("18", "और दवाएँ प्रतिपूर्ति के दायरे में"), ("61", "और दवाएँ प्रतिपूर्ति के दायरे में")], "SGK की घोषणाएँ और लेख",
   [("सर्वोच्च अपीलीय न्यायालय:", "केवल अल्पकालिक लाभ या जीवन की गुणवत्ता में सुधार के आधार पर SGK किसी दवा का भुगतान नहीं कर सकता। अकेले चिकित्सक की राय पर्याप्त नहीं है।"),
    ("क्या तौलना ज़रूरी है:", "वैज्ञानिक प्रमाण, जीवन के लिए अनिवार्यता और SGK की कानूनी सीमाएँ, एक साथ।"),
    ("समस्या:", "SGK और TİTCK में फार्माकोइकोनॉमिक्स केवल कागज़ पर है, इसलिए प्रतिपूर्ति मुकदमों से तय होती है।"),
    ("दुनिया का कोई देश", "सभी दवाओं की प्रतिपूर्ति नहीं करता।")],
   "SGK का बजट 8 करोड़ 10 लाख लोगों का बजट है।"),
 'ja': D("保険償還", "償還していない薬は、あといくつ残っているのか？", "トルコの社会保障機構（SGK）は、すべての薬の費用を支払うべきか",
   [("47", "品目を新たに償還リストに追加"), ("81", "品目を新たに償還リストに追加"), ("18", "品目が新たに償還対象に"), ("61", "品目が新たに償還対象に")], "SGKの発表と記事の要点",
   [("破毀院：", "短期的な利益がある、または生活の質を改善するというだけでは、SGKはその薬の費用を支払えない。医師の見解だけでは不十分である。"),
    ("併せて考慮すべきもの：", "科学的根拠、生命維持上の必要性、SGKの法的な限界。"),
    ("問題点：", "SGKとTITCKでは薬剤経済学が紙の上にしか存在せず、償還は訴訟によって決められている。"),
    ("世界には、", "すべての薬を償還している国は一つもない。")],
   "SGKの予算は8100万人の予算である。"),
})
