from batch1 import D
CARDS = {}

# History of clinical pharmacology in Turkey: cover (poster) and infographic (card)
CARDS['b23_kftarih_kapak'] = ('burg', {
 'en': D("HISTORY", "The history of clinical pharmacology in Turkey", "From Akil Muhtar Özden to a document dated 1975"),
 'de': D("GESCHICHTE", "Die Geschichte der klinischen Pharmakologie in der Türkei", "Von Akil Muhtar Özden zu einem Dokument aus dem Jahr 1975"),
 'es': D("HISTORIA", "La historia de la farmacología clínica en Turquía", "De Akil Muhtar Özden a un documento de 1975"),
 'ru': D("ИСТОРИЯ", "История клинической фармакологии в Турции", "От Акиля Мухтара Оздена к документу 1975 года"),
 'zh': D("历史", "土耳其临床药理学的历史", "从阿基尔·穆赫塔尔·厄兹登到1975年的一份文献"),
 'hi': D("इतिहास", "तुर्की में क्लिनिकल फ़ार्माकोलॉजी का इतिहास", "अकिल मुहतार ओज़देन से 1975 के एक दस्तावेज़ तक"),
 'ja': D("歴史", "トルコにおける臨床薬理学の歴史", "アキル・ムフタル・オズデンから1975年の文書まで"),
})

CARDS['b23_kftarih_info'] = ('burg', {
 'en': D("HISTORY", "The history of clinical pharmacology in Turkey", "Ord. Prof. Dr. Akil Muhtar Özden (1877-1949), Turkey's first clinical pharmacologist, and what followed", None, None,
   [("1909:", "Akil Muhtar Özden sets up the first clinic and institute for experimental drug therapy at the Darülfünun Faculty of Medicine in Istanbul."),
    ("1975:", "\"Clinical Pharmacology: What Is It and How It Works\", the first known definition of the modern discipline in Turkish, is published in Ankara."),
    ("1977:", "the first Clinical Pharmacology Society is founded; closed in 1980, founded again in 1983."),
    ("1978:", "clinical pharmacology lectures begin at Ankara University Faculty of Medicine; the WHO essential drugs list is translated into Turkish."),
    ("2003:", "the 6th Congress of the European Association for Clinical Pharmacology and Therapeutics (EACPT) meets in Istanbul.")],
   "History is written in the order of the documents."),
 'de': D("GESCHICHTE", "Die Geschichte der klinischen Pharmakologie in der Türkei", "Ord. Prof. Dr. Akil Muhtar Özden (1877-1949), der erste klinische Pharmakologe der Türkei, und was folgte", None, None,
   [("1909:", "Akil Muhtar Özden gründet an der Medizinischen Fakultät des Darülfünun in Istanbul die erste Klinik und das erste Institut für experimentelle Arzneitherapie."),
    ("1975:", "\"Klinische Pharmakologie: Was ist sie und wie arbeitet sie?\", die erste bekannte türkische Definition des modernen Fachs, erscheint in Ankara."),
    ("1977:", "Gründung der ersten Gesellschaft für Klinische Pharmakologie; 1980 geschlossen, 1983 neu gegründet."),
    ("1978:", "Beginn der Vorlesungen in klinischer Pharmakologie an der Medizinischen Fakultät der Universität Ankara; die WHO-Liste der unentbehrlichen Arzneimittel wird ins Türkische übersetzt."),
    ("2003:", "Der 6. Kongress der European Association for Clinical Pharmacology and Therapeutics (EACPT) tagt in Istanbul.")],
   "Geschichte wird in der Reihenfolge der Dokumente geschrieben."),
 'es': D("HISTORIA", "La historia de la farmacología clínica en Turquía", "Ord. Prof. Dr. Akil Muhtar Özden (1877-1949), primer farmacólogo clínico de Turquía, y lo que vino después", None, None,
   [("1909:", "Akil Muhtar Özden crea en la Facultad de Medicina del Darülfünun de Estambul la primera clínica y el primer instituto de terapéutica farmacológica experimental."),
    ("1975:", "se publica en Ankara \"Farmacología clínica: qué es y cómo funciona\", la primera definición conocida en turco de la disciplina moderna."),
    ("1977:", "se funda la primera Sociedad de Farmacología Clínica; cerrada en 1980, fundada de nuevo en 1983."),
    ("1978:", "comienzan las clases de farmacología clínica en la Facultad de Medicina de la Universidad de Ankara; se traduce al turco la lista de medicamentos esenciales de la OMS."),
    ("2003:", "el 6.º Congreso de la European Association for Clinical Pharmacology and Therapeutics (EACPT) se celebra en Estambul.")],
   "La historia se escribe en el orden de los documentos."),
 'ru': D("ИСТОРИЯ", "История клинической фармакологии в Турции", "Орд. проф. д-р Акиль Мухтар Озден (1877-1949), первый клинический фармаколог Турции, и то, что было после", None, None,
   [("1909:", "Акиль Мухтар Озден создаёт на медицинском факультете Дарюльфюнуна в Стамбуле первую клинику и институт экспериментальной лекарственной терапии."),
    ("1975:", "в Анкаре выходит статья \"Клиническая фармакология: что это и как она работает\", первое известное определение современной дисциплины на турецком языке."),
    ("1977:", "основано первое Общество клинической фармакологии; закрыто в 1980 году, воссоздано в 1983 году."),
    ("1978:", "на медицинском факультете Анкарского университета начинаются лекции по клинической фармакологии; на турецкий язык переведён перечень основных лекарственных средств ВОЗ."),
    ("2003:", "в Стамбуле проходит 6-й конгресс Европейской ассоциации клинической фармакологии и терапии (EACPT).")],
   "История пишется в порядке документов."),
 'zh': D("历史", "土耳其临床药理学的历史", "阿基尔·穆赫塔尔·厄兹登教授（1877-1949），土耳其第一位临床药理学家，以及此后的历程", None, None,
   [("1909年：", "阿基尔·穆赫塔尔·厄兹登在伊斯坦布尔达吕尔菲农医学院创办第一个实验性药物治疗诊所和研究所。"),
    ("1975年：", "《临床药理学：它是什么，如何运作》在安卡拉发表，是已知最早用土耳其语界定这一现代学科的文章。"),
    ("1977年：", "第一个临床药理学学会成立；1980年被关闭，1983年重新成立。"),
    ("1978年：", "安卡拉大学医学院开始讲授临床药理学课程；世界卫生组织基本药物目录被译成土耳其语。"),
    ("2003年：", "欧洲临床药理学与治疗学协会（EACPT）第六届大会在伊斯坦布尔举行。")],
   "历史是按文献的先后顺序书写的。"),
 'hi': D("इतिहास", "तुर्की में क्लिनिकल फ़ार्माकोलॉजी का इतिहास", "ऑर्ड. प्रो. डॉ. अकिल मुहतार ओज़देन (1877-1949), तुर्की के पहले क्लिनिकल फ़ार्माकोलॉजिस्ट, और उसके बाद का सफ़र", None, None,
   [("1909:", "अकिल मुहतार ओज़देन इस्तांबुल के दारुलफ़ुनून चिकित्सा संकाय में प्रायोगिक औषधि उपचार का पहला क्लिनिक और संस्थान स्थापित करते हैं।"),
    ("1975:", "\"क्लिनिकल फ़ार्माकोलॉजी: यह क्या है और कैसे काम करती है\" अंकारा में प्रकाशित होता है; यह आधुनिक विषय की तुर्की भाषा में पहली ज्ञात परिभाषा है।"),
    ("1977:", "पहली क्लिनिकल फ़ार्माकोलॉजी सोसाइटी की स्थापना; 1980 में बंद, 1983 में फिर स्थापित।"),
    ("1978:", "अंकारा विश्वविद्यालय चिकित्सा संकाय में क्लिनिकल फ़ार्माकोलॉजी के व्याख्यान शुरू; WHO की आवश्यक दवाओं की सूची का तुर्की में अनुवाद।"),
    ("2003:", "यूरोपीय क्लिनिकल फ़ार्माकोलॉजी एवं थेरैप्यूटिक्स संघ (EACPT) की छठी कांग्रेस इस्तांबुल में होती है।")],
   "इतिहास दस्तावेज़ों के क्रम में लिखा जाता है।"),
 'ja': D("歴史", "トルコにおける臨床薬理学の歴史", "アキル・ムフタル・オズデン教授（1877-1949）、トルコ初の臨床薬理学者とその後の歩み", None, None,
   [("1909年：", "アキル・ムフタル・オズデンがイスタンブールのダーリュルフュヌーン医学部に、実験的薬物治療のための最初の診療科と研究所を設立。"),
    ("1975年：", "「臨床薬理学：それは何か、どう機能するか」がアンカラで発表される。現代的な臨床薬理学をトルコ語で定義した、知られている最初の論文。"),
    ("1977年：", "最初の臨床薬理学会が設立される。1980年に閉鎖、1983年に再設立。"),
    ("1978年：", "アンカラ大学医学部で臨床薬理学の講義が始まる。WHO必須医薬品リストがトルコ語に翻訳される。"),
    ("2003年：", "欧州臨床薬理学・治療学会（EACPT）第6回大会がイスタンブールで開催される。")],
   "歴史は文書の順序で書かれる。"),
})
