from batch1 import D
from batch2 import BM
CARDS = {}

# 54 — First oral PCSK9 inhibitor
CARDS['pcsk9'] = ('navy', {
 'en': D("A NEW ERA IN CHOLESTEROL TREATMENT · 16 JULY 2026", "The first oral PCSK9 inhibitor", "Lipfendra (enlicitide) approved by the FDA: one tablet a day",
   [("59%", "LDL reduction in familial hypercholesterolaemia (CORALreef Phase III)"), ("56%", "LDL reduction in other patients with hypercholesterolaemia"), ("$10.50 a day", "US list price, about 315 dollars a month")], None,
   [("What to know:", "the approval rests on LDL lowering, a surrogate endpoint. The outcomes trial on heart attack, stroke and death is still running; results are expected in 2029."),
    ("Place in therapy:", "an add-on to statins, not a replacement, or an option when statins cannot be used."),
    ("Safety:", "diarrhoea, mild gastrointestinal complaints and dizziness, at rates similar to placebo. Long-term data will come from post-marketing follow-up.")],
   "Lowering LDL is a target; what matters is protecting the patient from events."),
 'de': D("EINE NEUE ÄRA DER CHOLESTERINTHERAPIE · 16. JULI 2026", "Der erste orale PCSK9-Hemmer", "Lipfendra (Enlicitid) von der FDA zugelassen: eine Tablette täglich",
   [("59 %", "LDL-Senkung bei familiärer Hypercholesterinämie (CORALreef, Phase III)"), ("56 %", "LDL-Senkung bei anderen Patienten mit Hypercholesterinämie"), ("10,50 $ pro Tag", "US-Listenpreis, rund 315 Dollar im Monat")], None,
   [("Wichtig zu wissen:", "Die Zulassung beruht auf der LDL-Senkung, einem Surrogatendpunkt. Die Endpunktstudie zu Herzinfarkt, Schlaganfall und Tod läuft noch; Ergebnisse werden 2029 erwartet."),
    ("Stellenwert:", "Ergänzung zu Statinen, kein Ersatz, oder Option, wenn Statine nicht eingesetzt werden können."),
    ("Sicherheit:", "Durchfall, leichte Magen-Darm-Beschwerden und Schwindel, ähnlich häufig wie unter Placebo. Langzeitdaten folgen aus der Beobachtung nach Markteinführung.")],
   "LDL zu senken ist ein Ziel; entscheidend ist, den Patienten vor Ereignissen zu schützen."),
 'es': D("UNA NUEVA ERA EN EL TRATAMIENTO DEL COLESTEROL · 16 DE JULIO DE 2026", "El primer inhibidor oral de PCSK9", "Lipfendra (enlicitida), aprobado por la FDA: un comprimido al día",
   [("59 %", "reducción de LDL en hipercolesterolemia familiar (CORALreef, fase III)"), ("56 %", "reducción de LDL en otros pacientes con hipercolesterolemia"), ("10,50 $ al día", "precio de lista en EE. UU., unos 315 dólares al mes")], None,
   [("Lo que hay que saber:", "la aprobación se basa en la reducción de LDL, un criterio indirecto. El ensayo de resultados sobre infarto, ictus y muerte sigue en curso; se esperan datos en 2029."),
    ("Lugar en la terapia:", "complemento de las estatinas, no sustituto, u opción cuando no pueden usarse."),
    ("Seguridad:", "diarrea, molestias gastrointestinales leves y mareo, con frecuencia similar a placebo. Los datos a largo plazo llegarán con el seguimiento poscomercialización.")],
   "Bajar el LDL es un objetivo; lo importante es proteger al paciente de los eventos."),
 'ru': D("НОВАЯ ЭПОХА В ЛЕЧЕНИИ ХОЛЕСТЕРИНА · 16 ИЮЛЯ 2026", "Первый пероральный ингибитор PCSK9", "Lipfendra (энлицитид) одобрен FDA: одна таблетка в день",
   [("59 %", "снижение ЛПНП при семейной гиперхолестеринемии (CORALreef, фаза III)"), ("56 %", "снижение ЛПНП у других пациентов с гиперхолестеринемией"), ("10,50 $ в день", "прейскурантная цена в США, около 315 долларов в месяц")], None,
   [("Что важно знать:", "одобрение основано на снижении ЛПНП, суррогатной конечной точке. Исследование исходов (инфаркт, инсульт, смерть) продолжается; результаты ожидаются в 2029 году."),
    ("Место в терапии:", "дополнение к статинам, а не замена, либо вариант при невозможности их применения."),
    ("Безопасность:", "диарея, лёгкие желудочно-кишечные жалобы и головокружение с частотой, близкой к плацебо. Долгосрочные данные даст пострегистрационное наблюдение.")],
   "Снижение ЛПНП это цель; главное защитить пациента от событий."),
 'zh': D("胆固醇治疗的新时代 · 2026年7月16日", "首个口服PCSK9抑制剂", "Lipfendra（enlicitide）获FDA批准：每日一片",
   [("59%", "家族性高胆固醇血症患者的LDL降幅（CORALreef 3期）"), ("56%", "其他高胆固醇血症患者的LDL降幅"), ("每天10.50美元", "美国标价，每月约315美元")], None,
   [("需要了解：", "批准依据是LDL下降这一替代终点。针对心肌梗死、脑卒中和死亡的结局研究仍在进行，预计2029年出结果。"),
    ("治疗定位：", "作为他汀类的补充而非替代，或用于不能使用他汀的患者。"),
    ("安全性：", "腹泻、轻度胃肠道不适和头晕，发生率与安慰剂相近。长期数据有待上市后监测。")],
   "降低LDL只是目标；重要的是保护患者免于发生事件。"),
 'hi': D("कोलेस्ट्रॉल उपचार में नया दौर · 16 जुलाई 2026", "पहला मौखिक PCSK9 अवरोधक", "Lipfendra (एनलिसिटाइड) को FDA की मंज़ूरी: दिन में एक गोली",
   [("59%", "पारिवारिक हाइपरकोलेस्ट्रॉलेमिया में LDL में कमी (CORALreef, चरण III)"), ("56%", "हाइपरकोलेस्ट्रॉलेमिया के अन्य मरीज़ों में LDL में कमी"), ("10.50 डॉलर प्रतिदिन", "अमेरिकी सूची मूल्य, लगभग 315 डॉलर प्रति माह")], None,
   [("जानने योग्य:", "मंज़ूरी LDL घटने पर आधारित है, जो सरोगेट अंतिम बिंदु है। दिल के दौरे, स्ट्रोक और मृत्यु पर परिणाम अध्ययन जारी है; नतीजे 2029 में अपेक्षित।"),
    ("उपचार में स्थान:", "स्टैटिन का पूरक, विकल्प नहीं; या जब स्टैटिन न दिए जा सकें।"),
    ("सुरक्षा:", "दस्त, हल्की पाचन संबंधी शिकायतें और चक्कर, प्लेसीबो जैसी दर पर। दीर्घकालिक डेटा बाज़ार में आने के बाद की निगरानी से मिलेगा।")],
   "LDL घटाना एक लक्ष्य है; असल बात मरीज़ को घटनाओं से बचाना है।"),
 'ja': D("コレステロール治療の新時代 · 2026年7月16日", "初の経口PCSK9阻害薬", "Lipfendra（エンリシチド）をFDAが承認：1日1錠",
   [("59%", "家族性高コレステロール血症でのLDL低下（CORALreef第III相）"), ("56%", "その他の高コレステロール血症患者でのLDL低下"), ("1日10.50ドル", "米国の定価。月約315ドル")], None,
   [("知っておくべきこと：", "承認の根拠はLDL低下という代替評価項目。心筋梗塞、脳卒中、死亡に関するアウトカム試験は継続中で、結果は2029年の見込み。"),
    ("治療上の位置づけ：", "スタチンの代わりではなく上乗せ、またはスタチンが使えない場合の選択肢。"),
    ("安全性：", "下痢、軽い胃腸症状、めまい。頻度はプラセボと同程度。長期データは市販後の追跡で明らかになる。")],
   "LDLを下げることは目標にすぎない。大切なのは患者をイベントから守ること。"),
})

# 55 — Food supplements
CARDS['takviye'] = ('teal', {
 'en': D("REGULATORY CRITIQUE · FOOD SUPPLEMENTS", "Remedy, or robbery?", "The same product. Its status is decided by its label, not its nature", None, None,
   [("Sold as a 'medicine':", "the state sets the price, so there is one price; the content is verified (GMP); it is sold only in pharmacies; SGK reimburses it."),
    ("Sold as a 'supplement':", "the price is free, with about a 2-fold difference; the content is not verified; it is sold everywhere, without a pharmacist; usually there is no inspection."),
    ("What should be done, 1:", "every product containing an active drug substance should be licensed by TİTCK."),
    ("What should be done, 2:", "every supplement with medicine status should be sold only in pharmacies.")],
   "The state should also set the price of a product it approves: one price across Türkiye."),
 'de': D("REGULIERUNGSKRITIK · NAHRUNGSERGÄNZUNGSMITTEL", "Heilmittel oder Abzocke?", "Dasselbe Produkt. Über seinen Status entscheidet das Etikett, nicht die Beschaffenheit", None, None,
   [("Als „Arzneimittel“ verkauft:", "Der Staat legt den Preis fest, also ein Preis; der Inhalt wird geprüft (GMP); Verkauf nur in Apotheken; die SGK erstattet."),
    ("Als „Ergänzungsmittel“ verkauft:", "freier Preis mit etwa 2-fachem Unterschied; der Inhalt wird nicht geprüft; Verkauf überall, ohne Apotheker; meist keine Kontrolle."),
    ("Was zu tun ist, 1:", "Alle Produkte mit einem Arzneiwirkstoff sollten von der TİTCK zugelassen werden."),
    ("Was zu tun ist, 2:", "Alle Ergänzungsmittel mit Arzneimittelstatus sollten nur in Apotheken verkauft werden.")],
   "Der Staat sollte auch den Preis eines Produkts festlegen, das er genehmigt: ein Preis in der ganzen Türkei."),
 'es': D("CRÍTICA REGULATORIA · COMPLEMENTOS ALIMENTICIOS", "¿Remedio o atraco?", "El mismo producto. Su estatus lo decide la etiqueta, no su naturaleza", None, None,
   [("Vendido como «medicamento»:", "el Estado fija el precio, así que hay un solo precio; el contenido se verifica (GMP); solo se vende en farmacias; la SGK lo reembolsa."),
    ("Vendido como «complemento»:", "precio libre, con una diferencia de unas 2 veces; el contenido no se verifica; se vende en cualquier parte, sin farmacéutico; por lo general no hay inspección."),
    ("Qué hacer, 1:", "todo producto que contenga un principio activo farmacológico debería ser autorizado por la TİTCK."),
    ("Qué hacer, 2:", "todo complemento con estatus de medicamento debería venderse solo en farmacias.")],
   "El Estado debería fijar también el precio del producto que aprueba: un solo precio en toda Turquía."),
 'ru': D("КРИТИКА РЕГУЛИРОВАНИЯ · БИОДОБАВКИ", "Лекарство или грабёж?", "Один и тот же продукт. Его статус определяет этикетка, а не свойства", None, None,
   [("Продаётся как «лекарство»:", "цену устанавливает государство, значит цена одна; состав проверяется (GMP); продаётся только в аптеках; SGK возмещает."),
    ("Продаётся как «добавка»:", "цена свободная, разница примерно вдвое; состав не проверяется; продаётся везде, без фармацевта; контроля обычно нет."),
    ("Что нужно сделать, 1:", "все продукты с лекарственным действующим веществом должны регистрироваться в TİTCK."),
    ("Что нужно сделать, 2:", "все добавки со статусом лекарства должны продаваться только в аптеках.")],
   "Государство должно устанавливать и цену продукта, который оно одобряет: одна цена по всей Турции."),
 'zh': D("监管批评 · 膳食补充剂", "是良药，还是抢劫？", "同一种产品，决定其身份的是标签，而不是其本质", None, None,
   [("作为“药品”销售：", "国家定价，全国一个价；成分经过核实（GMP）；只在药店销售；可由社保报销。"),
    ("作为“补充剂”销售：", "自由定价，价差约2倍；成分无人核实；到处可卖，没有药师；通常没有监管。"),
    ("应该怎么做（一）：", "所有含药物活性成分的产品都应由TİTCK批准上市。"),
    ("应该怎么做（二）：", "所有具有药品属性的补充剂都应只在药店销售。")],
   "国家既然批准了产品，也应为其定价：全土耳其统一价格。"),
 'hi': D("नियामकीय आलोचना · खाद्य पूरक", "इलाज, या लूट?", "वही उत्पाद। उसका दर्जा उसकी गुणवत्ता नहीं, उसका लेबल तय करता है", None, None,
   [("“दवा” के रूप में बिक्री:", "कीमत सरकार तय करती है, यानी एक ही कीमत; सामग्री सत्यापित होती है (GMP); केवल फ़ार्मेसी में बिकती है; SGK प्रतिपूर्ति करता है।"),
    ("“पूरक” के रूप में बिक्री:", "कीमत खुली, लगभग 2 गुना का अंतर; सामग्री सत्यापित नहीं; हर जगह, बिना फार्मासिस्ट के; आम तौर पर कोई निरीक्षण नहीं।"),
    ("क्या किया जाए, 1:", "दवा का सक्रिय पदार्थ रखने वाले सभी उत्पादों को TİTCK से लाइसेंस मिलना चाहिए।"),
    ("क्या किया जाए, 2:", "दवा के दर्जे वाले सभी पूरक केवल फ़ार्मेसियों में बिकने चाहिए।")],
   "जिस उत्पाद को सरकार मंज़ूरी देती है, उसकी कीमत भी वही तय करे: पूरे तुर्किये में एक कीमत।"),
 'ja': D("規制への批判 · サプリメント", "薬か、それとも搾取か", "同じ製品なのに、その扱いを決めるのは中身ではなくラベルである", None, None,
   [("「医薬品」として販売：", "価格は国が決めるので全国一律。内容は検証される（GMP）。薬局でのみ販売。SGKの償還あり。"),
    ("「サプリメント」として販売：", "価格は自由で約2倍の差。内容は検証されない。薬剤師なしでどこでも販売。たいてい監督なし。"),
    ("すべきこと1：", "医薬品の有効成分を含む製品はすべてTİTCKの承認を受けるべき。"),
    ("すべきこと2：", "医薬品扱いのサプリメントはすべて薬局でのみ販売すべき。")],
   "国は承認した製品の価格も決めるべきだ。トルコ全土で一つの価格に。"),
})

# 56 — Medical charlatans
CARDS['sarlatan'] = ('burg', {
 'en': D("OPINION", "Charlatans", "The anatomy of medical charlatanism in Türkiye", None, None,
   [("01", "Ignorant charlatans"), ("02", "Half-ignorant charlatans"), ("03", "Educated charlatans from the health professions"), ("04", "Charlatans with titles: the most dangerous"),
    ("The point:", "the most dangerous is not the ignorant one, but the one who appears best equipped.")],
   "Not trust that is claimed, but trust that can be demonstrated."),
 'de': D("MEINUNG", "Scharlatane", "Anatomie der medizinischen Scharlatanerie in der Türkei", None, None,
   [("01", "Unwissende Scharlatane"), ("02", "Halbwissende Scharlatane"), ("03", "Gebildete Scharlatane aus den Gesundheitsberufen"), ("04", "Scharlatane mit Titel: die gefährlichsten"),
    ("Der Punkt:", "Am gefährlichsten ist nicht der Unwissende, sondern der, der am besten gerüstet erscheint.")],
   "Nicht behauptetes Vertrauen, sondern nachweisbares Vertrauen."),
 'es': D("OPINIÓN", "Charlatanes", "Anatomía de la charlatanería médica en Turquía", None, None,
   [("01", "Charlatanes ignorantes"), ("02", "Charlatanes semiignorantes"), ("03", "Charlatanes instruidos, profesionales sanitarios"), ("04", "Charlatanes con título: los más peligrosos"),
    ("La idea:", "el más peligroso no es el ignorante, sino el que parece mejor preparado.")],
   "No la confianza que se proclama, sino la que puede demostrarse."),
 'ru': D("МНЕНИЕ", "Шарлатаны", "Анатомия медицинского шарлатанства в Турции", None, None,
   [("01", "Невежественные шарлатаны"), ("02", "Полуневежественные шарлатаны"), ("03", "Образованные шарлатаны из числа медиков"), ("04", "Шарлатаны со званиями: самые опасные"),
    ("Суть:", "опаснее всех не невежда, а тот, кто выглядит наиболее подготовленным.")],
   "Не доверие на словах, а доверие, которое можно доказать."),
 'zh': D("观点", "江湖骗子", "土耳其医疗骗术解剖", None, None,
   [("01", "无知的骗子"), ("02", "半懂不懂的骗子"), ("03", "受过教育的、医疗行业出身的骗子"), ("04", "有头衔的骗子：最危险"),
    ("要点：", "最危险的不是无知的人，而是看起来最有资历的人。")],
   "不是口头宣称的信任，而是可以被证明的信任。"),
 'hi': D("मत", "ढोंगी", "तुर्किये में चिकित्सा-ढोंग की शारीरिकी", None, None,
   [("01", "अज्ञानी ढोंगी"), ("02", "अधकचरे ज्ञान वाले ढोंगी"), ("03", "पढ़े-लिखे, स्वास्थ्य पेशे के ढोंगी"), ("04", "पदवीधारी ढोंगी: सबसे ख़तरनाक"),
    ("मूल बात:", "सबसे ख़तरनाक वह नहीं जो अज्ञानी है, बल्कि वह जो सबसे योग्य दिखता है।")],
   "कहा हुआ भरोसा नहीं, दिखाया जा सकने वाला भरोसा।"),
 'ja': D("オピニオン", "ペテン師たち", "トルコにおける医療ペテンの解剖", None, None,
   [("01", "無知なペテン師"), ("02", "半可通のペテン師"), ("03", "教育を受けた医療従事者のペテン師"), ("04", "肩書を持つペテン師：最も危険"),
    ("要点：", "最も危険なのは無知な者ではなく、最も資格がありそうに見える者である。")],
   "語られる信頼ではなく、示すことのできる信頼を。"),
})

# 57 — Future of GLP-1 drugs
CARDS['glp1gelecek'] = ('teal', {
 'en': D("WHERE ARE WEIGHT-LOSS DRUGS HEADING?", "The future of GLP-1 drugs", "A revolution from obesity to neurodegeneration, and a silent earthquake in Türkiye's drug spending",
   [("+102%", "spending on antidiabetic drugs almost doubled in one year (IEIS, IQVIA, SGK; January–May 2026)"), ("28–30%", "weight loss with retatrutide"), ("Orforglipron", "the first GLP-1 pill")], None,
   [("Spending:", "reimbursing obesity treatment could strain the budget.")]),
 'de': D("WOHIN GEHEN DIE ABNEHMMEDIKAMENTE?", "Die Zukunft der GLP-1-Medikamente", "Eine Revolution von der Adipositas bis zur Neurodegeneration und ein stilles Beben bei den türkischen Arzneimittelausgaben",
   [("+102 %", "die Ausgaben für Antidiabetika haben sich in einem Jahr fast verdoppelt (IEIS, IQVIA, SGK; Januar–Mai 2026)"), ("28–30 %", "Gewichtsverlust mit Retatrutid"), ("Orforglipron", "die erste GLP-1-Tablette")], None,
   [("Ausgaben:", "Die Erstattung der Adipositastherapie könnte das Budget stark belasten.")]),
 'es': D("¿HACIA DÓNDE VAN LOS FÁRMACOS PARA ADELGAZAR?", "El futuro de los fármacos GLP-1", "Una revolución de la obesidad a la neurodegeneración y un terremoto silencioso en el gasto farmacéutico de Turquía",
   [("+102 %", "el gasto en antidiabéticos casi se duplicó en un año (IEIS, IQVIA, SGK; enero–mayo de 2026)"), ("28–30 %", "de pérdida de peso con retatrutida"), ("Orforglipron", "la primera pastilla GLP-1")], None,
   [("Gasto:", "reembolsar el tratamiento de la obesidad podría tensionar el presupuesto.")]),
 'ru': D("КУДА ДВИЖУТСЯ ПРЕПАРАТЫ ДЛЯ ПОХУДЕНИЯ?", "Будущее препаратов ГПП-1", "Революция от ожирения до нейродегенерации и тихое землетрясение в лекарственных расходах Турции",
   [("+102 %", "расходы на противодиабетические препараты за год почти удвоились (IEIS, IQVIA, SGK; январь–май 2026 г.)"), ("28–30 %", "потеря веса на ретатрутиде"), ("Орфорглипрон", "первая таблетка ГПП-1")], None,
   [("Расходы:", "возмещение лечения ожирения может создать серьёзную нагрузку на бюджет.")]),
 'zh': D("减重药物将走向何方？", "GLP-1类药物的未来", "从肥胖到神经退行性疾病的一场革命，以及土耳其药品支出中的无声地震",
   [("+102%", "降糖药支出一年内几乎翻倍（IEIS、IQVIA、SGK；2026年1–5月）"), ("28–30%", "瑞他鲁肽的减重幅度"), ("Orforglipron", "首个GLP-1口服药")], None,
   [("支出：", "把肥胖治疗纳入报销可能使预算吃紧。")]),
 'hi': D("वज़न घटाने की दवाएँ किधर जा रही हैं?", "GLP-1 दवाओं का भविष्य", "मोटापे से तंत्रिका-अपक्षय तक एक क्रांति, और तुर्किये के दवा-खर्च में एक मौन भूचाल",
   [("+102%", "मधुमेहरोधी दवाओं पर खर्च एक वर्ष में लगभग दोगुना (IEIS, IQVIA, SGK; जनवरी–मई 2026)"), ("28–30%", "रेटाट्रूटाइड से वज़न में कमी"), ("ऑरफ़ॉरग्लिप्रॉन", "पहली GLP-1 गोली")], None,
   [("खर्च:", "मोटापे के उपचार की प्रतिपूर्ति बजट पर भारी पड़ सकती है।")]),
 'ja': D("肥満治療薬はどこへ向かうのか", "GLP-1受容体作動薬の未来", "肥満から神経変性疾患に及ぶ革命と、トルコの薬剤費に起きている静かな激震",
   [("+102%", "糖尿病治療薬の支出は1年でほぼ倍増（IEIS、IQVIA、SGK。2026年1〜5月）"), ("28〜30%", "レタトルチドによる体重減少"), ("オルフォルグリプロン", "初のGLP-1経口薬")], None,
   [("支出：", "肥満治療の償還は予算を圧迫しかねない。")]),
})

# 58 — Drug spending records
CARDS['harcama'] = ('blue', {
 'en': D("IEIS MARKET ANALYSIS · MAY 2026", "Türkiye's drug market is growing, but with fewer drugs and a bigger bill", "Fewer boxes are sold; more expensive drugs are used",
   [("−2%", "boxes, January–May: 1,072 million → 1,051 million"), ("+38.4%", "value, January–May: 168,195 → 232,828 million TL"), ("+50.9%", "money paid for imported drugs, January–May"), ("+102%", "antidiabetics, the fastest-growing group")], None,
   [("What is driving it:", "oncology (+47%), GLP-1 drugs for diabetes and obesity, and imported biotechnology products."),
    ("Antibiotics:", "boxes fell by 8% while value rose by 21%."),
    ("Expert view:", "IEIS is an industry body and its data reflect the commercial picture. They are not enough to judge access to medicines or the public cost.")]),
 'de': D("IEIS-MARKTANALYSE · MAI 2026", "Der türkische Arzneimittelmarkt wächst, aber mit weniger Medikamenten und höherer Rechnung", "Es werden weniger Packungen verkauft; teurere Medikamente werden eingesetzt",
   [("−2 %", "Packungen, Januar–Mai: 1.072 Mio. → 1.051 Mio."), ("+38,4 %", "Wert, Januar–Mai: 168.195 → 232.828 Mio. TL"), ("+50,9 %", "Ausgaben für importierte Medikamente, Januar–Mai"), ("+102 %", "Antidiabetika, die am schnellsten wachsende Gruppe")], None,
   [("Die Treiber:", "Onkologie (+47 %), GLP-1-Medikamente bei Diabetes und Adipositas sowie importierte Biotech-Produkte."),
    ("Antibiotika:", "Packungen −8 %, Wert +21 %."),
    ("Expertensicht:", "Die IEIS ist ein Branchenverband, ihre Daten zeigen das kommerzielle Bild. Sie reichen nicht aus, um Zugang oder öffentliche Kosten zu beurteilen.")]),
 'es': D("ANÁLISIS DE MERCADO DE IEIS · MAYO DE 2026", "El mercado farmacéutico turco crece, pero con menos medicamentos y una factura mayor", "Se venden menos envases; se usan fármacos más caros",
   [("−2 %", "envases, enero–mayo: 1.072 millones → 1.051 millones"), ("+38,4 %", "valor, enero–mayo: 168.195 → 232.828 millones de TL"), ("+50,9 %", "dinero pagado por fármacos importados, enero–mayo"), ("+102 %", "antidiabéticos, el grupo que más crece")], None,
   [("Qué lo impulsa:", "oncología (+47 %), los GLP-1 para diabetes y obesidad y los productos biotecnológicos importados."),
    ("Antibióticos:", "los envases bajaron un 8 % y el valor subió un 21 %."),
    ("Opinión experta:", "IEIS es una organización del sector y sus datos reflejan el panorama comercial. No bastan para valorar el acceso ni el coste público.")]),
 'ru': D("АНАЛИЗ РЫНКА IEIS · МАЙ 2026", "Фармрынок Турции растёт, но лекарств меньше, а счёт больше", "Продаётся меньше упаковок; применяются более дорогие препараты",
   [("−2 %", "упаковки, январь–май: 1072 млн → 1051 млн"), ("+38,4 %", "стоимость, январь–май: 168 195 → 232 828 млн лир"), ("+50,9 %", "расходы на импортные лекарства, январь–май"), ("+102 %", "противодиабетические средства, самая быстрорастущая группа")], None,
   [("Что движет ростом:", "онкология (+47 %), препараты ГПП-1 при диабете и ожирении и импортные биотехнологические продукты."),
    ("Антибиотики:", "упаковок на 8 % меньше, стоимость на 21 % больше."),
    ("Мнение эксперта:", "IEIS отраслевая организация, её данные отражают коммерческую картину. Их недостаточно для оценки доступности лекарств и нагрузки на бюджет.")]),
 'zh': D("IEIS市场分析 · 2026年5月", "土耳其药品市场在增长，但药更少、账单更高", "售出的盒数减少，使用的药品更贵",
   [("−2%", "盒数，1–5月：10.72亿 → 10.51亿"), ("+38.4%", "金额，1–5月：1681.95亿 → 2328.28亿里拉"), ("+50.9%", "1–5月进口药支出"), ("+102%", "降糖药，增长最快的类别")], None,
   [("增长动力：", "肿瘤药（+47%）、用于糖尿病和肥胖的GLP-1类药物以及进口生物技术产品。"),
    ("抗生素：", "盒数下降8%，金额上升21%。"),
    ("专家看法：", "IEIS是行业组织，其数据反映的是商业面貌，不足以评估药品可及性或公共支出。")]),
 'hi': D("IEIS बाज़ार विश्लेषण · मई 2026", "तुर्किये का दवा बाज़ार बढ़ रहा है, पर कम दवाओं और बड़े बिल के साथ", "कम डिब्बे बिक रहे हैं; महँगी दवाएँ इस्तेमाल हो रही हैं",
   [("−2%", "डिब्बे, जनवरी–मई: 107.2 करोड़ → 105.1 करोड़"), ("+38.4%", "मूल्य, जनवरी–मई: 1,68,195 → 2,32,828 मिलियन TL"), ("+50.9%", "आयातित दवाओं पर भुगतान, जनवरी–मई"), ("+102%", "मधुमेहरोधी दवाएँ, सबसे तेज़ी से बढ़ता समूह")], None,
   [("वृद्धि के कारण:", "ऑन्कोलॉजी (+47%), मधुमेह और मोटापे की GLP-1 दवाएँ और आयातित जैव-प्रौद्योगिकी उत्पाद।"),
    ("एंटीबायोटिक:", "डिब्बे 8% घटे, मूल्य 21% बढ़ा।"),
    ("विशेषज्ञ की राय:", "IEIS उद्योग का संगठन है और उसका डेटा व्यावसायिक तस्वीर दिखाता है। दवाओं तक पहुँच या सार्वजनिक लागत आँकने के लिए यह पर्याप्त नहीं।")]),
 'ja': D("IEIS市場分析 · 2026年5月", "トルコの医薬品市場は拡大している。ただし薬は減り、請求額は増えた", "販売箱数は減り、より高価な薬が使われている",
   [("−2%", "箱数（1〜5月）：10億7,200万 → 10億5,100万"), ("+38.4%", "金額（1〜5月）：1,681億9,500万 → 2,328億2,800万リラ"), ("+50.9%", "輸入医薬品への支払い（1〜5月）"), ("+102%", "糖尿病治療薬。最も伸びが大きい")], None,
   [("押し上げ要因：", "がん領域（+47%）、糖尿病・肥満向けGLP-1製剤、輸入バイオ医薬品。"),
    ("抗菌薬：", "箱数は8%減、金額は21%増。"),
    ("専門家の見方：", "IEISは業界団体で、そのデータは商業面の姿を示す。医薬品アクセスや公的負担を評価するには不十分である。")]),
})

# 59 — COVID spending
CARDS['covid'] = ('navy', {
 'en': D("PANDEMIC SPENDING", "What COVID-19 cost Türkiye", "Pandemic spending, vaccine purchases and the questions still awaiting an answer",
   [("£10.9 bn", "UK: losses in pandemic programmes from fraud and administrative error; only about £1.8 bn recoverable"), ("~78 m TL", "TÜBİTAK funding for vaccine and drug projects; about 80% went to vaccine projects"), ("17 projects", "49 institutions, 436 researchers; 3 of 7 vaccine projects were in the clinical phase in October 2021")], "THE MOST DEBATED ISSUE IN TÜRKİYE: THE SINOVAC PURCHASES",
   [("Unanswered:", "the price per dose, the contract details, the legal and commercial role of Keymen İlaç, and the fate of undelivered or unused doses."),
    ("TURKOVAC:", "how much public money went into it, how many doses were made, used, expired or destroyed?"),
    ("What is missing:", "an independent, comprehensive pandemic account, with a special audit by the Court of Accounts or an independent commission.")],
   "Public money is society's common resource. Every penny should be accounted for."),
 'de': D("PANDEMIEAUSGABEN", "Was COVID-19 die Türkei gekostet hat", "Pandemieausgaben, Impfstoffkäufe und die Fragen, die noch auf Antwort warten",
   [("10,9 Mrd. £", "Großbritannien: Verluste in Pandemieprogrammen durch Betrug und Verwaltungsfehler; nur rund 1,8 Mrd. £ rückholbar"), ("~78 Mio. TL", "TÜBİTAK-Mittel für Impfstoff- und Arzneimittelprojekte; etwa 80 % für Impfstoffprojekte"), ("17 Projekte", "49 Einrichtungen, 436 Forschende; 3 von 7 Impfstoffprojekten waren im Oktober 2021 in der klinischen Phase")], "DAS MEISTDISKUTIERTE THEMA IN DER TÜRKEI: DIE SINOVAC-KÄUFE",
   [("Unbeantwortet:", "Preis pro Dosis, Vertragsdetails, rechtliche und kommerzielle Rolle von Keymen İlaç sowie Verbleib nicht gelieferter oder ungenutzter Dosen."),
    ("TURKOVAC:", "Wie viel öffentliches Geld floss hinein, wie viele Dosen wurden hergestellt, verwendet, verfielen oder wurden vernichtet?"),
    ("Was fehlt:", "eine unabhängige, umfassende Pandemiebilanz, mit Sonderprüfung durch den Rechnungshof oder eine unabhängige Kommission.")],
   "Öffentliches Geld ist die gemeinsame Ressource der Gesellschaft. Über jeden Kuruş muss Rechenschaft abgelegt werden."),
 'es': D("GASTO DE LA PANDEMIA", "Lo que la COVID-19 le costó a Turquía", "Gasto pandémico, compras de vacunas y las preguntas que siguen sin respuesta",
   [("10.900 M£", "Reino Unido: pérdidas en programas de la pandemia por fraude y errores administrativos; solo unos 1.800 M£ recuperables"), ("~78 M TL", "financiación de TÜBİTAK para proyectos de vacunas y fármacos; cerca del 80 % para vacunas"), ("17 proyectos", "49 instituciones, 436 investigadores; 3 de 7 proyectos de vacunas estaban en fase clínica en octubre de 2021")], "EL ASUNTO MÁS DEBATIDO EN TURQUÍA: LAS COMPRAS DE SINOVAC",
   [("Sin respuesta:", "el precio por dosis, los detalles del contrato, el papel legal y comercial de Keymen İlaç y el destino de las dosis no entregadas o no utilizadas."),
    ("TURKOVAC:", "¿cuánto dinero público recibió, cuántas dosis se fabricaron, se usaron, caducaron o se destruyeron?"),
    ("Lo que falta:", "una rendición de cuentas independiente y completa de la pandemia, con una auditoría especial del Tribunal de Cuentas o de una comisión independiente.")],
   "El dinero público es el recurso común de la sociedad. Debe rendirse cuentas de cada céntimo."),
 'ru': D("РАСХОДЫ НА ПАНДЕМИЮ", "Во что COVID-19 обошёлся Турции", "Расходы на пандемию, закупки вакцин и вопросы, ожидающие ответа",
   [("10,9 млрд £", "Великобритания: потери в пандемических программах из-за мошенничества и ошибок; вернуть можно лишь около 1,8 млрд £"), ("~78 млн лир", "средства TÜBİTAK на проекты вакцин и лекарств; около 80 % ушло на вакцины"), ("17 проектов", "49 учреждений, 436 исследователей; 3 из 7 вакцинных проектов были на клинической стадии в октябре 2021 г.")], "САМАЯ ОБСУЖДАЕМАЯ ТЕМА В ТУРЦИИ: ЗАКУПКИ SINOVAC",
   [("Без ответа:", "цена за дозу, детали контракта, юридическая и коммерческая роль Keymen İlaç и судьба недопоставленных или неиспользованных доз."),
    ("TURKOVAC:", "сколько государственных денег вложено, сколько доз произведено, использовано, просрочено или уничтожено?"),
    ("Чего не хватает:", "независимого и полного отчёта о пандемии со специальной проверкой Счётной палаты или независимой комиссии.")],
   "Государственные деньги общий ресурс общества. Отчитаться нужно за каждую копейку."),
 'zh': D("疫情支出", "新冠疫情让土耳其付出了多少", "疫情支出、疫苗采购和仍待回答的问题",
   [("109亿英镑", "英国：疫情项目因欺诈和行政失误造成的损失；只有约18亿英镑可追回"), ("约7800万里拉", "TÜBİTAK用于疫苗和药物项目的经费；约80%用于疫苗项目"), ("17个项目", "49家机构、436名研究人员；截至2021年10月，7个疫苗项目中有3个进入临床阶段")], "土耳其争议最大的问题：科兴疫苗采购",
   [("尚无答案：", "每剂价格、合同细节、Keymen İlaç公司的法律和商业角色，以及未交付或未使用剂量的去向。"),
    ("TURKOVAC：", "投入了多少公共资金？生产、使用、过期和销毁了多少剂？"),
    ("缺少的是：", "一份独立而完整的疫情账目，由审计法院或独立委员会进行专项审计。")],
   "公共资金是全社会的共同资源，每一分钱都应当交代清楚。"),
 'hi': D("महामारी का खर्च", "कोविड-19 की तुर्किये को क्या कीमत चुकानी पड़ी", "महामारी का खर्च, टीकों की ख़रीद और जवाब का इंतज़ार करते सवाल",
   [("10.9 अरब पाउंड", "ब्रिटेन: धोखाधड़ी और प्रशासनिक त्रुटियों से महामारी कार्यक्रमों में नुकसान; केवल लगभग 1.8 अरब पाउंड की वसूली संभव"), ("~7.8 करोड़ TL", "टीका और दवा परियोजनाओं के लिए TÜBİTAK की राशि; लगभग 80% टीका परियोजनाओं पर"), ("17 परियोजनाएँ", "49 संस्थान, 436 शोधकर्ता; अक्टूबर 2021 तक 7 में से 3 टीका परियोजनाएँ क्लिनिकल चरण में")], "तुर्किये में सबसे विवादित मुद्दा: सिनोवैक की ख़रीद",
   [("अनुत्तरित:", "प्रति खुराक कीमत, अनुबंध का ब्योरा, Keymen İlaç की कानूनी और व्यावसायिक भूमिका, और न मिली या न इस्तेमाल हुई खुराकों का क्या हुआ।"),
    ("TURKOVAC:", "इसमें कितना सार्वजनिक धन लगा; कितनी खुराकें बनीं, इस्तेमाल हुईं, अवधि-पार हुईं या नष्ट की गईं?"),
    ("जो कमी है:", "महामारी का स्वतंत्र और समग्र हिसाब, लेखा न्यायालय या स्वतंत्र आयोग के विशेष ऑडिट के साथ।")],
   "सार्वजनिक धन समाज का साझा संसाधन है। हर पैसे का हिसाब दिया जाना चाहिए।"),
 'ja': D("パンデミック支出", "COVID-19がトルコにもたらした費用", "パンデミック支出、ワクチン購入、そして答えを待つ問い",
   [("109億ポンド", "英国：不正と事務上の誤りによるパンデミック事業の損失。回収できるのは約18億ポンドのみ"), ("約7,800万リラ", "TÜBİTAKによるワクチン・医薬品プロジェクトへの資金。約80%がワクチン向け"), ("17件", "49機関、研究者436人。2021年10月時点でワクチン7件のうち3件が臨床段階")], "トルコで最も議論された問題：シノバック製ワクチンの購入",
   [("答えのない問い：", "1回分の価格、契約の詳細、Keymen İlaç社の法的・商業的な役割、未納入や未使用の接種分の行方。"),
    ("TURKOVAC：", "公的資金はいくら投じられ、何回分が製造、使用、期限切れ、廃棄されたのか。"),
    ("欠けているもの：", "独立した包括的なパンデミックの収支報告と、会計検査院または独立委員会による特別監査。")],
   "公金は社会の共有資源である。その一円一円について説明がなされなければならない。"),
})

# 60 — Quality assurance in generics
CARDS['kalite'] = ('blue', {
 'en': D("A CRITICAL ASSESSMENT OF CHEAPNESS, QUALITY AND REGULATORY SYSTEMS", "Quality assurance in generic drugs", "The right question: does a country's regulatory system have the scientific and institutional capacity to assure the quality of every drug on its market throughout its life cycle?", None, None,
   [("What is a generic?", "the same active substance, dose and pharmaceutical form; different excipients and manufacturing processes. A bioequivalence study is required for licensing."),
    ("What affects quality:", "raw material quality, the manufacturing process and its control, excipients, pharmaceutical design, bioequivalence studies and regulatory inspection."),
    ("Major quality crises:", "contaminated heparin (2008), nitrosamine contamination (2018–2020), ranitidine and valsartan (NDMA), and data fraud cases."),
    ("Why assurance must be continuous:", "manufacturing changes can affect quality; post-marketing surveillance is essential."),
    ("A strong regulatory system means safe generics:", "an independent, strong authority, scientific guidelines, effective inspection and enforcement, transparency and data integrity.")]),
 'de': D("KRITISCHE BEWERTUNG VON BILLIGKEIT, QUALITÄT UND REGULIERUNGSSYSTEMEN", "Qualitätssicherung bei Generika", "Die richtige Frage: Hat das Regulierungssystem eines Landes die wissenschaftliche und institutionelle Kapazität, die Qualität jedes Medikaments auf seinem Markt über den gesamten Lebenszyklus zu sichern?", None, None,
   [("Was ist ein Generikum?", "gleicher Wirkstoff, gleiche Dosis und Darreichungsform; andere Hilfsstoffe und Herstellungsverfahren. Für die Zulassung ist eine Bioäquivalenzstudie Pflicht."),
    ("Was die Qualität beeinflusst:", "Rohstoffqualität, Herstellungsprozess und Kontrolle, Hilfsstoffe, pharmazeutisches Design, Bioäquivalenzstudien und behördliche Inspektion."),
    ("Große Qualitätskrisen:", "kontaminiertes Heparin (2008), Nitrosamin-Verunreinigungen (2018–2020), Ranitidin und Valsartan (NDMA) sowie Fälle von Datenfälschung."),
    ("Warum die Sicherung fortlaufend sein muss:", "Herstellungsänderungen können die Qualität beeinflussen; Überwachung nach Markteinführung ist unerlässlich."),
    ("Starkes Regulierungssystem heißt sichere Generika:", "unabhängige, starke Behörde, wissenschaftliche Leitlinien, wirksame Inspektion und Durchsetzung, Transparenz und Datenintegrität.")]),
 'es': D("VALORACIÓN CRÍTICA DEL BAJO PRECIO, LA CALIDAD Y LOS SISTEMAS REGULADORES", "Garantía de calidad en los medicamentos genéricos", "La pregunta correcta: ¿tiene el sistema regulador de un país la capacidad científica e institucional para garantizar la calidad de cada fármaco de su mercado durante todo su ciclo de vida?", None, None,
   [("¿Qué es un genérico?", "mismo principio activo, dosis y forma farmacéutica; excipientes y procesos de fabricación distintos. Para autorizarlo se exige un estudio de bioequivalencia."),
    ("Qué influye en la calidad:", "la calidad de la materia prima, el proceso de fabricación y su control, los excipientes, el diseño farmacéutico, los estudios de bioequivalencia y la inspección reguladora."),
    ("Grandes crisis de calidad:", "heparina contaminada (2008), contaminación por nitrosaminas (2018–2020), ranitidina y valsartán (NDMA) y casos de fraude de datos."),
    ("Por qué la garantía debe ser continua:", "los cambios de fabricación pueden afectar a la calidad; la vigilancia poscomercialización es imprescindible."),
    ("Sistema regulador fuerte, genéricos seguros:", "autoridad independiente y fuerte, guías científicas, inspección y sanción eficaces, transparencia e integridad de los datos.")]),
 'ru': D("КРИТИЧЕСКАЯ ОЦЕНКА ДЕШЕВИЗНЫ, КАЧЕСТВА И РЕГУЛЯТОРНЫХ СИСТЕМ", "Обеспечение качества дженериков", "Правильный вопрос: обладает ли регуляторная система страны научным и институциональным потенциалом, чтобы гарантировать качество каждого лекарства на рынке на протяжении всего его жизненного цикла?", None, None,
   [("Что такое дженерик?", "то же действующее вещество, доза и лекарственная форма; другие вспомогательные вещества и технологии производства. Для регистрации обязательно исследование биоэквивалентности."),
    ("Что влияет на качество:", "качество сырья, производственный процесс и его контроль, вспомогательные вещества, фармацевтическая разработка, исследования биоэквивалентности и инспекции."),
    ("Крупные кризисы качества:", "загрязнённый гепарин (2008), нитрозамины (2018–2020), ранитидин и валсартан (NDMA), случаи фальсификации данных."),
    ("Почему контроль должен быть непрерывным:", "изменения в производстве могут повлиять на качество; пострегистрационный надзор обязателен."),
    ("Сильная регуляторная система означает безопасные дженерики:", "независимый и сильный орган, научные руководства, действенные инспекции и санкции, прозрачность и целостность данных.")]),
 'zh': D("对低价、质量与监管体系的批判性评估", "仿制药的质量保证", "正确的问题是：一个国家的监管体系是否具备科学和制度能力，在整个生命周期内保证市场上每一种药品的质量？", None, None,
   [("什么是仿制药？", "相同的有效成分、剂量和剂型；辅料和生产工艺不同。上市必须做生物等效性研究。"),
    ("影响质量的因素：", "原料质量、生产工艺及其控制、辅料、制剂设计、生物等效性研究和监管检查。"),
    ("重大质量危机：", "受污染的肝素（2008年）、亚硝胺污染（2018–2020年）、雷尼替丁和缬沙坦（NDMA）以及数据造假案件。"),
    ("为什么质量保证必须持续：", "生产变更可能影响质量；上市后监测必不可少。"),
    ("强有力的监管体系才有安全的仿制药：", "独立而有力的监管机构、科学指南、有效的检查与执法、透明度和数据完整性。")]),
 'hi': D("सस्तेपन, गुणवत्ता और नियामक प्रणालियों का आलोचनात्मक मूल्यांकन", "जेनेरिक दवाओं में गुणवत्ता आश्वासन", "सही प्रश्न: क्या किसी देश की नियामक प्रणाली में वह वैज्ञानिक और संस्थागत क्षमता है कि वह बाज़ार की हर दवा की गुणवत्ता उसके पूरे जीवन-चक्र में सुनिश्चित कर सके?", None, None,
   [("जेनेरिक दवा क्या है?", "वही सक्रिय पदार्थ, वही खुराक और वही रूप; सहायक पदार्थ और निर्माण प्रक्रियाएँ अलग। लाइसेंस के लिए जैव-समतुल्यता अध्ययन अनिवार्य।"),
    ("गुणवत्ता को क्या प्रभावित करता है:", "कच्चे माल की गुणवत्ता, निर्माण प्रक्रिया और उसका नियंत्रण, सहायक पदार्थ, औषधीय डिज़ाइन, जैव-समतुल्यता अध्ययन और नियामकीय निरीक्षण।"),
    ("बड़े गुणवत्ता संकट:", "दूषित हेपरिन (2008), नाइट्रोसामीन संदूषण (2018–2020), रैनिटिडीन और वाल्सार्टन (NDMA), और डेटा धोखाधड़ी के मामले।"),
    ("आश्वासन निरंतर क्यों हो:", "निर्माण में बदलाव गुणवत्ता को प्रभावित कर सकते हैं; बाज़ार में आने के बाद निगरानी अनिवार्य है।"),
    ("मज़बूत नियामक प्रणाली यानी सुरक्षित जेनेरिक:", "स्वतंत्र और मज़बूत प्राधिकरण, वैज्ञानिक दिशानिर्देश, प्रभावी निरीक्षण और कार्रवाई, पारदर्शिता और डेटा की अखंडता।")]),
 'ja': D("安さ、品質、規制制度の批判的評価", "ジェネリック医薬品の品質保証", "正しい問いはこうだ。その国の規制制度は、市場に出すすべての医薬品の品質をライフサイクル全体にわたって保証できる科学的・制度的な能力を備えているか", None, None,
   [("ジェネリック医薬品とは：", "有効成分、用量、剤形は同じで、添加剤と製造工程が異なる。承認には生物学的同等性試験が必須。"),
    ("品質に影響する要因：", "原薬の品質、製造工程とその管理、添加剤、製剤設計、生物学的同等性試験、規制当局の査察。"),
    ("大きな品質問題：", "汚染ヘパリン（2008年）、ニトロソアミン混入（2018〜2020年）、ラニチジンとバルサルタン（NDMA）、データ不正事件。"),
    ("品質保証を継続すべき理由：", "製造上の変更は品質に影響しうる。市販後の監視が不可欠。"),
    ("強い規制制度があってこそ安全なジェネリック：", "独立した強い当局、科学的ガイドライン、実効性のある査察と執行、透明性とデータの完全性。")]),
})

# 61 — Bioequivalence in Türkiye (English image exists)
CARDS['biyoesdeger'] = ('navy', {
 'de': D("KLINISCHE PHARMAKOLOGIE", "Bioäquivalenz", "Wissenschaftliche Garantie oder Verwaltungsformalität? Ein System, das von der Verordnung in den Leitfaden abgestiegen ist, nicht überprüft wird und nicht transparent ist",
   [("~700", "Generika wurden in Europa (EMA) ausgesetzt, weil ein einziges Auftragsforschungsinstitut (CRO) Bioäquivalenzdaten gefälscht hatte")], None, None,
   "Und dieser Betrug kam nicht durch Aktenprüfung ans Licht, sondern nur durch eine Inspektion vor Ort."),
 'es': D("FARMACOLOGÍA CLÍNICA", "Bioequivalencia", "¿Garantía científica o formalidad administrativa? Un sistema rebajado del reglamento a la guía, que no se verifica y no es transparente",
   [("~700", "genéricos fueron suspendidos en Europa (EMA) por datos de bioequivalencia inventados en un solo centro de investigación (CRO)")], None, None,
   "Y este fraude no salió a la luz revisando expedientes, sino solo con una inspección in situ."),
 'ru': D("КЛИНИЧЕСКАЯ ФАРМАКОЛОГИЯ", "Биоэквивалентность", "Научная гарантия или административная формальность? Система, опустившаяся с уровня постановления до руководства, непроверяемая и непрозрачная",
   [("~700", "дженериков приостановлены в Европе (EMA) из-за данных о биоэквивалентности, сфабрикованных в одной контрактной исследовательской организации (CRO)")], None, None,
   "И этот подлог вскрылся не при проверке досье, а только при инспекции на месте."),
 'zh': D("临床药理学", "生物等效性", "是科学保证，还是行政手续？一个从法规降格为指南、无法核实且不透明的体系",
   [("约700种", "仿制药因同一家合同研究机构（CRO）伪造生物等效性数据而在欧洲（EMA）被暂停上市许可")], None, None,
   "而这起造假不是靠审查申报资料发现的，只是靠现场检查才被揭露。"),
 'hi': D("क्लिनिकल फार्माकोलॉजी", "जैव-समतुल्यता", "वैज्ञानिक गारंटी, या प्रशासनिक औपचारिकता? एक ऐसी प्रणाली जो विनियम से गिरकर दिशानिर्देश बन गई, जिसकी पुष्टि नहीं होती और जो पारदर्शी नहीं",
   [("~700", "जेनेरिक दवाओं का लाइसेंस यूरोप (EMA) में निलंबित हुआ, क्योंकि एक ही अनुबंध शोध संस्था (CRO) में जैव-समतुल्यता के आँकड़े गढ़े गए थे")], None, None,
   "और यह जालसाज़ी फ़ाइलों की जाँच से नहीं, केवल मौक़े पर निरीक्षण से सामने आई।"),
 'ja': D("臨床薬理学", "生物学的同等性", "科学的な保証か、行政上の形式か。規則から指針へ格下げされ、検証されず、透明性もない制度",
   [("約700品目", "のジェネリック医薬品が、1つの受託研究機関（CRO）による生物学的同等性データの捏造を理由に、欧州（EMA）で承認停止となった")], None, None,
   "しかもこの不正は書類審査ではなく、実地査察によって初めて明らかになった。"),
})
