from batch1 import D
from batch2 import BM
CARDS = {}

# 48 — Lecanemab real-world data + 10 warning signs
CARDS['lecanemab'] = ('navy', {
 'en': D("LECANEMAB · REAL-WORLD DATA", "A new hope in Alzheimer's disease?", "Ten warning signs of Alzheimer's disease that make early diagnosis easier", None, None,
   [("Memory loss:", "forgetting daily events or recently learned information."), ("Difficulty solving problems:", "trouble planning, calculating and following steps."), ("Difficulty with familiar tasks:", "being unable to complete a known job or route."), ("Confusion about time or place:", "mixing up dates, seasons or where one is."), ("Misplacing things:", "putting objects in unusual places and not finding them."),
    ("Also:", "trouble finding words, visual and spatial problems, poor judgement, mood changes and social withdrawal.")]),
 'de': D("LECANEMAB · DATEN AUS DEM VERSORGUNGSALLTAG", "Eine neue Hoffnung bei Alzheimer?", "Zehn Warnzeichen der Alzheimer-Krankheit, die die Früherkennung erleichtern", None, None,
   [("Gedächtnisverlust:", "Vergessen alltäglicher Ereignisse oder kürzlich Gelerntem."), ("Schwierigkeiten beim Problemlösen:", "Probleme beim Planen, Rechnen und Nachverfolgen."), ("Schwierigkeiten bei gewohnten Aufgaben:", "eine bekannte Tätigkeit oder Strecke nicht bewältigen."), ("Zeitliche oder örtliche Verwirrung:", "Datum, Jahreszeit oder Aufenthaltsort verwechseln."), ("Dinge verlegen:", "Gegenstände an ungewöhnliche Orte legen und nicht wiederfinden."),
    ("Außerdem:", "Wortfindungsstörungen, visuell-räumliche Probleme, schlechtes Urteilsvermögen, Stimmungsänderungen und sozialer Rückzug.")]),
 'es': D("LECANEMAB · DATOS DE LA VIDA REAL", "¿Una nueva esperanza en el Alzheimer?", "Diez señales de alerta de la enfermedad de Alzheimer que facilitan el diagnóstico precoz", None, None,
   [("Pérdida de memoria:", "olvidar hechos cotidianos o lo aprendido recientemente."), ("Dificultad para resolver problemas:", "problemas para planificar, calcular y seguir pasos."), ("Dificultad con tareas habituales:", "no poder completar un trabajo o un trayecto conocido."), ("Confusión de tiempo o lugar:", "confundir fechas, estaciones o dónde se está."), ("Colocar objetos fuera de sitio:", "dejarlos en lugares inusuales y no encontrarlos."),
    ("Además:", "dificultad para encontrar palabras, problemas visuoespaciales, juicio deficiente, cambios de ánimo y retraimiento social.")]),
 'ru': D("ЛЕКАНЕМАБ · ДАННЫЕ РЕАЛЬНОЙ ПРАКТИКИ", "Новая надежда при болезни Альцгеймера?", "Десять тревожных признаков болезни Альцгеймера, облегчающих раннюю диагностику", None, None,
   [("Потеря памяти:", "человек забывает повседневные события или недавно усвоенное."), ("Трудности с решением задач:", "сложно планировать, считать и следить за ходом дела."), ("Трудности с привычными делами:", "не удаётся выполнить знакомую работу или маршрут."), ("Путаница во времени и месте:", "человек путает даты, времена года или своё местонахождение."), ("Вещи не на своих местах:", "предметы кладутся в необычные места и не находятся."),
    ("Кроме того:", "трудности с подбором слов, зрительно-пространственные нарушения, снижение критики, перемены настроения и социальная изоляция.")]),
 'zh': D("仑卡奈单抗 · 真实世界数据", "阿尔茨海默病的新希望？", "有助于早期诊断的阿尔茨海默病十大警示信号", None, None,
   [("记忆减退：", "忘记日常事情或刚学到的内容。"), ("解决问题有困难：", "难以计划、计算和按步骤做事。"), ("熟悉的事情做不好：", "无法完成熟悉的工作或走熟悉的路线。"), ("时间或地点混乱：", "弄不清日期、季节或自己身在何处。"), ("把东西放错地方：", "把物品放到不寻常的地方后找不到。"),
    ("此外：", "找词困难、视觉空间障碍、判断力下降、情绪变化和回避社交。")]),
 'hi': D("लेकानेमैब · वास्तविक जीवन के आँकड़े", "अल्ज़ाइमर में नई उम्मीद?", "अल्ज़ाइमर रोग के दस चेतावनी संकेत, जो शीघ्र निदान को आसान बनाते हैं", None, None,
   [("याददाश्त घटना:", "रोज़मर्रा की घटनाएँ या हाल में सीखी बातें भूल जाना।"), ("समस्या सुलझाने में कठिनाई:", "योजना बनाने, हिसाब लगाने और क्रम निभाने में दिक़्क़त।"), ("परिचित कामों में कठिनाई:", "जाना-पहचाना काम या रास्ता पूरा न कर पाना।"), ("समय या स्थान का भ्रम:", "तारीख़, मौसम या अपनी जगह को लेकर उलझन।"), ("चीज़ें ग़लत जगह रखना:", "वस्तुएँ असामान्य जगह रखकर ढूँढ़ न पाना।"),
    ("साथ ही:", "शब्द ढूँढ़ने में कठिनाई, दृश्य-स्थानिक समस्याएँ, निर्णय में कमज़ोरी, मनोदशा में बदलाव और सामाजिक दूरी।")]),
 'ja': D("レカネマブ · 実臨床データ", "アルツハイマー病に新たな希望か", "早期診断に役立つアルツハイマー病の10の警告サイン", None, None,
   [("記憶の障害：", "日々の出来事や最近覚えたことを忘れる。"), ("問題解決が難しい：", "計画、計算、手順を追うことが難しくなる。"), ("慣れた作業が難しい：", "よく知っている仕事や道順をやり遂げられない。"), ("時間や場所の混乱：", "日付、季節、自分のいる場所がわからなくなる。"), ("物の置き忘れ：", "物をいつもと違う場所に置き、見つけられない。"),
    ("ほかにも：", "言葉が出てこない、視空間認知の問題、判断力の低下、気分の変化、社会的な引きこもり。")]),
})

# 49 — News from the USA
CARDS['abdhaber'] = ('teal', {
 'en': D("23 JULY 2026", "News from the USA", None, None, None,
   [("1. Bipartisan Senate support for an Office of Men's Health.", "Sen. Gallego (D) and Sen. Marshall (R) introduce a bill to create an Office of Men's Health within HHS. A status report will first be requested from the GAO."),
    ("2. The 'global code' era in maternity care is ending.", "The AMA and ACOG are dropping the bundled payment code for maternity services and moving to service-based codes. Debate continues over higher costs and transparency."),
    ("3. An FDA panel debates peptide compounding in pharmacies.", "The panel is considering whether 7 peptides regarded as unsafe may be compounded in pharmacies. Some panellists are criticised for conflicts of interest.")]),
 'de': D("23. JULI 2026", "Nachrichten aus den USA", None, None, None,
   [("1. Überparteiliche Unterstützung im Senat für ein Büro für Männergesundheit.", "Sen. Gallego (D) und Sen. Marshall (R) bringen einen Entwurf zur Einrichtung eines Büros für Männergesundheit im HHS ein. Zunächst wird ein Lagebericht des GAO angefordert."),
    ("2. Die Ära des „Global Code“ in der Geburtshilfe endet.", "AMA und ACOG schaffen den Pauschalcode für Geburtsleistungen ab und gehen zu leistungsbezogenen Codes über. Die Debatte über Mehrkosten und Transparenz dauert an."),
    ("3. FDA-Gremium berät über Peptidherstellung in Apotheken.", "Das Gremium erörtert, ob 7 als unsicher geltende Peptide in Apotheken hergestellt werden dürfen. Einigen Mitgliedern werden Interessenkonflikte vorgeworfen.")]),
 'es': D("23 DE JULIO DE 2026", "Noticias de EE. UU.", None, None, None,
   [("1. Apoyo bipartidista en el Senado a una Oficina de Salud Masculina.", "Los senadores Gallego (D) y Marshall (R) presentan un proyecto para crear una Oficina de Salud del Hombre en el HHS. Primero se pedirá un informe a la GAO."),
    ("2. Se acaba la era del «código global» en la atención al parto.", "La AMA y el ACOG eliminan el código de pago agrupado de los servicios de maternidad y pasan a códigos por servicio. Sigue el debate sobre el aumento de costes y la transparencia."),
    ("3. Un panel de la FDA debate la elaboración de péptidos en farmacias.", "El panel estudia si 7 péptidos considerados inseguros pueden elaborarse en farmacias. Se critica a algunos panelistas por conflictos de intereses.")]),
 'ru': D("23 ИЮЛЯ 2026", "Новости из США", None, None, None,
   [("1. Двухпартийная поддержка в Сенате Управления по мужскому здоровью.", "Сенаторы Гальего (демократ) и Маршалл (республиканец) вносят законопроект о создании такого управления в HHS. Сначала запросят доклад у GAO."),
    ("2. Эпоха «глобального кода» в акушерской помощи заканчивается.", "AMA и ACOG отменяют пакетный код оплаты родовспоможения и переходят к кодам за отдельные услуги. Споры о росте расходов и прозрачности продолжаются."),
    ("3. Комиссия FDA обсуждает изготовление пептидов в аптеках.", "Комиссия рассматривает, можно ли изготавливать в аптеках 7 пептидов, считающихся небезопасными. Некоторых членов критикуют за конфликт интересов.")]),
 'zh': D("2026年7月23日", "美国消息", None, None, None,
   [("1. 参议院两党支持设立男性健康办公室。", "民主党参议员Gallego和共和党参议员Marshall提出法案，拟在卫生与公众服务部内设立男性健康办公室。将先请政府问责局提交现状报告。"),
    ("2. 产科护理的“全球代码”时代即将结束。", "美国医学会和美国妇产科医师学会取消产科服务的打包付费代码，改用按服务计费的代码。关于成本上升和透明度的争论仍在继续。"),
    ("3. FDA专家组讨论药房配制多肽。", "专家组讨论7种被认为不安全的多肽能否在药房配制。部分专家被批评存在利益冲突。")]),
 'hi': D("23 जुलाई 2026", "अमेरिका से समाचार", None, None, None,
   [("1. पुरुष स्वास्थ्य कार्यालय को सीनेट में दोनों दलों का समर्थन।", "सीनेटर गैलेगो (डेमोक्रेट) और मार्शल (रिपब्लिकन) ने HHS में पुरुष स्वास्थ्य कार्यालय बनाने का विधेयक पेश किया। पहले GAO से स्थिति-रिपोर्ट माँगी जाएगी।"),
    ("2. प्रसूति देखभाल में “ग्लोबल कोड” का दौर ख़त्म हो रहा है।", "AMA और ACOG प्रसूति सेवाओं का एकमुश्त भुगतान कोड हटाकर सेवा-आधारित कोड अपना रहे हैं। लागत बढ़ने और पारदर्शिता पर बहस जारी है।"),
    ("3. FDA पैनल फ़ार्मेसियों में पेप्टाइड निर्माण पर विचार कर रहा है।", "पैनल इस पर चर्चा कर रहा है कि असुरक्षित माने गए 7 पेप्टाइड फ़ार्मेसियों में बनाए जा सकते हैं या नहीं। कुछ सदस्यों पर हितों के टकराव की आलोचना है।")]),
 'ja': D("2026年7月23日", "米国からのニュース", None, None, None,
   [("1. 男性の健康を担当する部局の新設に、上院で超党派の支持。", "ガジェゴ議員（民主）とマーシャル議員（共和）が、HHS内に男性健康局を設ける法案を提出。まずGAOに現状報告を求める。"),
    ("2. 産科医療の「グローバルコード」の時代が終わる。", "AMAとACOGは出産関連サービスの包括払いコードを廃止し、サービスごとのコードに移行する。費用の増加と透明性をめぐる議論が続いている。"),
    ("3. FDAの委員会が薬局でのペプチド調製を議論。", "安全でないとされる7種類のペプチドを薬局で調製できるかを検討している。一部の委員には利益相反の批判がある。")]),
})

# 50 — 100-200% tariff on imported generics (poster)
CARDS['tarife'] = ('navy', {
 'en': D("AN EARTHQUAKE IN THE DRUG TRADE", "Trump puts a 100–200% tariff on imported generic drugs", "An opportunity for the Turkish pharmaceutical industry?"),
 'de': D("ERDBEBEN IM ARZNEIMITTELHANDEL", "Trump belegt importierte Generika mit Zöllen von 100–200 %", "Eine Chance für die türkische Pharmaindustrie?"),
 'es': D("TERREMOTO EN EL COMERCIO DE MEDICAMENTOS", "Trump impone aranceles del 100–200 % a los genéricos importados", "¿Una oportunidad para la industria farmacéutica turca?"),
 'ru': D("ЗЕМЛЕТРЯСЕНИЕ В ТОРГОВЛЕ ЛЕКАРСТВАМИ", "Трамп вводит пошлины 100–200 % на импортные дженерики", "Шанс для турецкой фармацевтической промышленности?"),
 'zh': D("药品贸易大地震", "特朗普对进口仿制药征收100%–200%关税", "土耳其制药业的机会？"),
 'hi': D("दवा व्यापार में भूचाल", "ट्रंप आयातित जेनेरिक दवाओं पर 100–200% शुल्क लगा रहे हैं", "क्या यह तुर्की दवा उद्योग के लिए अवसर है?"),
 'ja': D("医薬品貿易に激震", "トランプ氏、輸入ジェネリック医薬品に100〜200%の関税", "トルコの製薬産業にとって好機か"),
})

# 51 — Menstrual migraine
CARDS['migren'] = ('burg', {
 'en': D("DIAGNOSIS AND TREATMENT", "Menstrual migraine", "Hormonal changes linked to the menstrual cycle can trigger migraine attacks. With the right diagnosis and individual treatment it can be controlled", None, None,
   [("Diagnosis:", "detailed history, migraine criteria (ICHD-3), the link with the menstrual cycle, exclusion of other causes and a headache diary."),
    ("Triggers:", "hormone fluctuations (the fall in oestrogen), stress, irregular sleep, intense exercise and eating habits."),
    ("Acute treatment:", "painkillers (NSAIDs), triptans and antiemetics."),
    ("Perimenstrual prevention:", "short-term use of triptans, NSAIDs or hormone modulation."),
    ("Long-term prevention:", "beta blockers, antidepressants, anticonvulsants and CGRP antibodies.")],
   "Knowing yourself is the strongest step in managing migraine."),
 'de': D("DIAGNOSE UND THERAPIE", "Menstruelle Migräne", "Hormonelle Veränderungen im Zyklus können Migräneattacken auslösen. Mit richtiger Diagnose und individueller Therapie lässt sie sich kontrollieren", None, None,
   [("Diagnose:", "ausführliche Anamnese, Migränekriterien (ICHD-3), Zusammenhang mit dem Zyklus, Ausschluss anderer Ursachen und ein Kopfschmerztagebuch."),
    ("Auslöser:", "Hormonschwankungen (Östrogenabfall), Stress, unregelmäßiger Schlaf, intensive Bewegung und Essgewohnheiten."),
    ("Akuttherapie:", "Schmerzmittel (NSAR), Triptane und Antiemetika."),
    ("Perimenstruelle Prophylaxe:", "kurzzeitige Anwendung von Triptanen, NSAR oder Hormonmodulation."),
    ("Langzeitprophylaxe:", "Betablocker, Antidepressiva, Antikonvulsiva und CGRP-Antikörper.")],
   "Sich selbst zu kennen ist der stärkste Schritt im Umgang mit Migräne."),
 'es': D("DIAGNÓSTICO Y TRATAMIENTO", "Migraña menstrual", "Los cambios hormonales del ciclo menstrual pueden desencadenar crisis de migraña. Con un diagnóstico correcto y un tratamiento individualizado puede controlarse", None, None,
   [("Diagnóstico:", "historia detallada, criterios de migraña (ICHD-3), relación con el ciclo menstrual, exclusión de otras causas y diario de cefaleas."),
    ("Desencadenantes:", "fluctuaciones hormonales (caída de estrógenos), estrés, sueño irregular, ejercicio intenso y hábitos alimentarios."),
    ("Tratamiento agudo:", "analgésicos (AINE), triptanes y antieméticos."),
    ("Prevención perimenstrual:", "uso breve de triptanes, AINE o modulación hormonal."),
    ("Prevención a largo plazo:", "betabloqueantes, antidepresivos, anticonvulsivantes y anticuerpos anti-CGRP.")],
   "Conocerse a una misma es el paso más poderoso para manejar la migraña."),
 'ru': D("ДИАГНОСТИКА И ЛЕЧЕНИЕ", "Менструальная мигрень", "Гормональные изменения, связанные с менструальным циклом, могут провоцировать приступы мигрени. При верном диагнозе и индивидуальном лечении её можно контролировать", None, None,
   [("Диагностика:", "подробный анамнез, критерии мигрени (МКГБ-3), связь с циклом, исключение других причин и дневник головной боли."),
    ("Триггеры:", "гормональные колебания (падение эстрогенов), стресс, нерегулярный сон, интенсивные нагрузки и особенности питания."),
    ("Лечение приступа:", "обезболивающие (НПВП), триптаны и противорвотные."),
    ("Перименструальная профилактика:", "краткосрочное применение триптанов, НПВП или гормональная модуляция."),
    ("Длительная профилактика:", "бета-блокаторы, антидепрессанты, противосудорожные средства и антитела к CGRP.")],
   "Знать себя: самый сильный шаг в управлении мигренью."),
 'zh': D("诊断与治疗", "月经性偏头痛", "与月经周期相关的激素变化可诱发偏头痛发作。正确诊断并个体化治疗可以控制病情", None, None,
   [("诊断：", "详细病史、偏头痛诊断标准（ICHD-3）、与月经周期的关系、排除其他原因以及头痛日记。"),
    ("诱因：", "激素波动（雌激素下降）、压力、睡眠不规律、剧烈运动和饮食习惯。"),
    ("急性期治疗：", "止痛药（非甾体抗炎药）、曲普坦类和止吐药。"),
    ("围月经期预防：", "短期使用曲普坦类、非甾体抗炎药或激素调节。"),
    ("长期预防：", "β受体阻滞剂、抗抑郁药、抗惊厥药和CGRP抗体。")],
   "了解自己，是管理偏头痛最有力的一步。"),
 'hi': D("निदान और उपचार", "मासिक धर्म से जुड़ा माइग्रेन", "मासिक चक्र से जुड़े हार्मोनल बदलाव माइग्रेन का दौरा शुरू कर सकते हैं। सही निदान और व्यक्ति-विशेष उपचार से इसे नियंत्रित किया जा सकता है", None, None,
   [("निदान:", "विस्तृत इतिहास, माइग्रेन के मानदंड (ICHD-3), मासिक चक्र से संबंध, अन्य कारणों को बाहर करना और सिरदर्द डायरी।"),
    ("उत्प्रेरक:", "हार्मोन का उतार-चढ़ाव (एस्ट्रोजन में गिरावट), तनाव, अनियमित नींद, तीव्र व्यायाम और खान-पान की आदतें।"),
    ("दौरे का उपचार:", "दर्द-निवारक (NSAID), ट्रिप्टान और वमनरोधी।"),
    ("मासिक के आसपास रोकथाम:", "ट्रिप्टान, NSAID या हार्मोन मॉड्यूलेशन का अल्पकालिक उपयोग।"),
    ("दीर्घकालिक रोकथाम:", "बीटा ब्लॉकर, अवसादरोधी, आक्षेपरोधी और CGRP एंटीबॉडी।")],
   "ख़ुद को जानना माइग्रेन के प्रबंधन का सबसे मज़बूत क़दम है।"),
 'ja': D("診断と治療", "月経関連片頭痛", "月経周期に伴うホルモン変化が片頭痛発作の引き金になることがある。正しい診断と個別の治療でコントロールできる", None, None,
   [("診断：", "詳しい問診、片頭痛の診断基準（ICHD-3）、月経周期との関連、他の原因の除外、頭痛ダイアリー。"),
    ("誘因：", "ホルモンの変動（エストロゲンの低下）、ストレス、不規則な睡眠、激しい運動、食習慣。"),
    ("急性期治療：", "鎮痛薬（NSAIDs）、トリプタン、制吐薬。"),
    ("月経周辺期の予防：", "トリプタン、NSAIDsの短期使用、またはホルモン調整。"),
    ("長期予防：", "β遮断薬、抗うつ薬、抗てんかん薬、CGRP抗体。")],
   "自分を知ることが、片頭痛と付き合う最も力強い一歩。"),
})

# 52 — Corruption in drug regulation
CARDS['yozlasma'] = ('burg', {
 'en': D("INSTITUTIONAL CORRUPTION FILE", "Corruption in drug regulation", "Cognitive dissonance, institutional corruption and the blind spot of drug regulation in Türkiye",
   [("10 of 32", "members of the FDA's Vioxx/Bextra panel had financial ties to drug companies: the difference that decided the vote"), ("93%", "of FDA panel members with financial ties backed the drug, against 56% of those without"), ("2019", "the fake Iclusig case: TİTCK's own laboratory said 'not counterfeit'; an independent university laboratory gave the correct report")], "LAWRENCE LESSIG'S DISTINCTION",
   [("The bad apple:", "a single politician who takes a bribe. An individual offence; the person is punished and the matter ends."),
    ("The bad barrel:", "nobody breaks the law, but whom the institution serves slowly changes.")],
   None, "Based on Cosgrove & Whitaker (2013), Safra Working Paper No. 9"),
 'de': D("DOSSIER INSTITUTIONELLE KORRUPTION", "Korruption in der Arzneimittelregulierung", "Kognitive Dissonanz, institutionelle Korruption und der blinde Fleck der Arzneimittelregulierung in der Türkei",
   [("10 von 32", "Mitglieder des FDA-Gremiums zu Vioxx/Bextra hatten finanzielle Verbindungen zu Pharmafirmen: der Unterschied, der die Abstimmung entschied"), ("93 %", "der FDA-Mitglieder mit finanziellen Verbindungen unterstützten das Medikament, gegenüber 56 % ohne solche"), ("2019", "der Fall des gefälschten Iclusig: Das eigene Labor der TİTCK sagte „nicht gefälscht“; ein unabhängiges Universitätslabor lieferte den richtigen Befund")], "DIE UNTERSCHEIDUNG VON LAWRENCE LESSIG",
   [("Der faule Apfel:", "ein einzelner Politiker, der Bestechungsgeld nimmt. Eine individuelle Tat; die Person wird bestraft, die Sache ist erledigt."),
    ("Das faule Fass:", "Niemand bricht das Gesetz, aber wem die Institution dient, verschiebt sich langsam.")],
   None, "Auf Grundlage von Cosgrove & Whitaker (2013), Safra Working Paper Nr. 9"),
 'es': D("EXPEDIENTE DE CORRUPCIÓN INSTITUCIONAL", "Corrupción en la regulación de los medicamentos", "Disonancia cognitiva, corrupción institucional y el punto ciego de la regulación de medicamentos en Turquía",
   [("10 de 32", "miembros del panel de la FDA sobre Vioxx/Bextra tenían vínculos económicos con farmacéuticas: la diferencia que decidió la votación"), ("93 %", "de los miembros de la FDA con vínculos económicos apoyó el fármaco, frente al 56 % de los que no los tenían"), ("2019", "el caso del Iclusig falso: el laboratorio de la propia TİTCK dijo «no es falso»; un laboratorio universitario independiente dio el informe correcto")], "LA DISTINCIÓN DE LAWRENCE LESSIG",
   [("La manzana podrida:", "un solo político que acepta un soborno. Delito individual; se castiga a la persona y el asunto termina."),
    ("El barril podrido:", "nadie infringe la ley, pero a quién sirve la institución cambia poco a poco.")],
   None, "Basado en Cosgrove y Whitaker (2013), Safra Working Paper n.º 9"),
 'ru': D("ДОСЬЕ ОБ ИНСТИТУЦИОНАЛЬНОЙ КОРРУПЦИИ", "Перерождение в регулировании лекарств", "Когнитивный диссонанс, институциональная коррупция и слепое пятно лекарственного регулирования в Турции",
   [("10 из 32", "членов комиссии FDA по Vioxx/Bextra имели финансовые связи с фармкомпаниями: разница, решившая исход голосования"), ("93 %", "членов комиссий FDA с финансовыми связями поддержали препарат против 56 % без таких связей"), ("2019", "дело о поддельном Айклусиге: собственная лаборатория TİTCK заявила «не подделка»; верное заключение дала независимая университетская лаборатория")], "РАЗЛИЧИЕ ЛОУРЕНСА ЛЕССИГА",
   [("Гнилое яблоко:", "один политик берёт взятку. Индивидуальное преступление: человека наказывают, вопрос закрыт."),
    ("Гнилая бочка:", "никто не нарушает закон, но то, кому служит учреждение, постепенно меняется.")],
   None, "По материалам Cosgrove & Whitaker (2013), Safra Working Paper № 9"),
 'zh': D("制度性腐败档案", "药品监管中的蜕变", "认知失调、制度性腐败与土耳其药品监管的盲点",
   [("32人中10人", "FDA关于Vioxx/Bextra专家委员会成员与制药公司有财务联系：这一差别决定了表决结果"), ("93%", "有财务联系的FDA委员支持药物，无联系者为56%"), ("2019年", "假Iclusig事件：TİTCK自己的实验室称“不是假药”；独立的大学实验室给出了正确报告")], "劳伦斯·莱西格的区分",
   [("坏苹果：", "某个政客收受贿赂。这是个人犯罪，处罚当事人，事情就结束了。"),
    ("坏桶：", "没有人违法，但机构为谁服务却在慢慢改变。")],
   None, "依据Cosgrove和Whitaker（2013），Safra工作论文第9号"),
 'hi': D("संस्थागत भ्रष्टाचार फ़ाइल", "दवा विनियमन में सड़न", "संज्ञानात्मक असंगति, संस्थागत भ्रष्टाचार और तुर्किये में दवा विनियमन का अंधा बिंदु",
   [("32 में से 10", "FDA की Vioxx/Bextra समिति के सदस्यों के दवा कंपनियों से वित्तीय संबंध थे: वही अंतर जिसने मतदान तय किया"), ("93%", "वित्तीय संबंध वाले FDA सदस्यों ने दवा का समर्थन किया, बिना संबंध वालों में 56%"), ("2019", "नक़ली Iclusig मामला: TİTCK की अपनी प्रयोगशाला ने कहा “नक़ली नहीं”; सही रिपोर्ट एक स्वतंत्र विश्वविद्यालय प्रयोगशाला ने दी")], "लॉरेंस लेसिग का भेद",
   [("ख़राब सेब:", "रिश्वत लेने वाला अकेला राजनेता। व्यक्तिगत अपराध; व्यक्ति को दंड मिलता है और बात ख़त्म।"),
    ("ख़राब पीपा:", "कोई कानून नहीं तोड़ता, पर संस्था किसकी सेवा करती है, यह धीरे-धीरे बदल जाता है।")],
   None, "Cosgrove और Whitaker (2013), Safra Working Paper सं. 9 पर आधारित"),
 'ja': D("制度的腐敗ファイル", "医薬品規制の腐敗", "認知的不協和、制度的腐敗、そしてトルコの医薬品規制の死角",
   [("32人中10人", "FDAのVioxx/Bextra諮問委員会の委員が製薬企業と金銭的関係を持っていた。この差が採決を左右した"), ("93%", "金銭的関係のあるFDA委員が薬を支持した割合。関係のない委員では56%"), ("2019年", "偽造アイクルシグ事件：TİTCK自身の検査室は「偽造ではない」と判定し、正しい報告を出したのは独立した大学の検査室だった")], "ローレンス・レッシグの区別",
   [("腐ったリンゴ：", "賄賂を受け取る一人の政治家。個人の犯罪であり、本人が罰せられて終わる。"),
    ("腐った樽：", "誰も法を破らないが、機関が誰に仕えるのかが少しずつ変わっていく。")],
   None, "Cosgrove & Whitaker（2013）Safra Working Paper No. 9 に基づく"),
})

# 53 — Who should run the trials needed for licensing
CARDS['kimyapmali'] = ('navy', {
 'en': D(BM['en'], "Who should conduct the clinical trials needed to license drugs?", "What does independent research mean? Proposals for Türkiye", None, None,
   [("The principle:", "the party that pays should not decide who does the testing."),
    ("Why:", "the reliability of evidence depends not on the intentions of whoever produces it, but on the independence of the conditions under which it is produced.")]),
 'de': D(BM['de'], "Wer sollte die für die Zulassung nötigen klinischen Studien durchführen?", "Was bedeutet unabhängige Forschung? Vorschläge für die Türkei", None, None,
   [("Der Grundsatz:", "Wer bezahlt, sollte nicht entscheiden, wer prüft."),
    ("Warum:", "Die Verlässlichkeit von Evidenz hängt nicht von der Absicht dessen ab, der sie erzeugt, sondern von der Unabhängigkeit der Bedingungen, unter denen sie entsteht.")]),
 'es': D(BM['es'], "¿Quién debe realizar los ensayos clínicos necesarios para autorizar los medicamentos?", "¿Qué significa investigación independiente? Propuestas para Turquía", None, None,
   [("El principio:", "quien paga no debería decidir quién hace las pruebas."),
    ("Por qué:", "la fiabilidad de una prueba no depende de la intención de quien la genera, sino de la independencia de las condiciones en que se genera.")]),
 'ru': D(BM['ru'], "Кто должен проводить клинические исследования, необходимые для регистрации лекарств?", "Что значит независимое исследование? Предложения для Турции", None, None,
   [("Принцип:", "тот, кто платит, не должен решать, кто проводит испытания."),
    ("Почему:", "надёжность доказательств зависит не от намерений того, кто их получает, а от независимости условий, в которых они получены.")]),
 'zh': D(BM['zh'], "药品上市所需的临床试验应该由谁来做？", "什么是独立研究？给土耳其的建议", None, None,
   [("原则：", "出钱的一方不应决定由谁来做试验。"),
    ("原因：", "证据是否可靠，不取决于产生证据者的意图，而取决于产生证据的条件是否独立。")]),
 'hi': D(BM['hi'], "दवाओं के लाइसेंस के लिए ज़रूरी क्लिनिकल ट्रायल किसे करने चाहिए?", "स्वतंत्र अनुसंधान का क्या अर्थ है? तुर्किये के लिए सुझाव", None, None,
   [("सिद्धांत:", "जो पैसा देता है, उसे यह तय नहीं करना चाहिए कि परीक्षण कौन करेगा।"),
    ("क्यों:", "प्रमाण की विश्वसनीयता उसे तैयार करने वाले की नीयत पर नहीं, बल्कि उसके तैयार होने की परिस्थितियों की स्वतंत्रता पर निर्भर है।")]),
 'ja': D(BM['ja'], "医薬品の承認に必要な臨床試験は誰が行うべきか", "独立した研究とは何か。トルコへの提言", None, None,
   [("原則：", "費用を払う側が、誰が試験するかを決めるべきではない。"),
    ("理由：", "エビデンスの信頼性は、それを生み出す者の意図ではなく、生み出される条件の独立性にかかっている。")]),
})
