from batch1 import D
from batch2 import BM
CARDS = {}

# 22 — Vurdum duymazlar
CARDS['vurdum'] = ('navy', {
 'en': D(BM['en'], "Turning a deaf ear", "Findings from 2008, updates from 2026: transparency has changed, the model has not",
   [("$2.6 bn", "paid to more than 665,000 physicians in 2025 (Open Payments)"), ("$1.3 bn", "to teaching hospitals and non-physician health professionals"), ("$3.9 bn", "in total: up 18.4% on the previous year"), ("$72.8 bn", "cumulative since 2013, in more than 84 million records")], None,
   [("Bribery is now the rule, not the exception.", "OECD analysis 1999–2025: 21 bribery investigations into 19 companies and affiliates in 5 OECD countries; more than 1 billion dollars in penalties."),
    ("US False Claims Act, fiscal 2025:", "a record 6.8 billion dollars in settlements and judgments, 3.7 billion of it against drug companies and pharmacies."),
    ("The new face of inventing diseases:", "biomarker tests sold directly to consumers turn risk factors into 'diseases'. More than 50% of marketed tests cannot show clinical benefit.")],
   "Transparency shines a light. But light does not automatically put out corruption."),
 'de': D(BM['de'], "Die Unbelehrbaren", "Befunde von 2008, Aktualisierungen von 2026: Die Transparenz hat sich geändert, das Modell nicht",
   [("2,6 Mrd. $", "Zahlungen an über 665.000 Ärzte im Jahr 2025 (Open Payments)"), ("1,3 Mrd. $", "an Lehrkrankenhäuser und nichtärztliche Gesundheitsberufe"), ("3,9 Mrd. $", "insgesamt: 18,4 % mehr als im Vorjahr"), ("72,8 Mrd. $", "kumuliert seit 2013, in über 84 Millionen Datensätzen")], None,
   [("Bestechung ist nun die Regel, nicht die Ausnahme.", "OECD-Analyse 1999–2025: 21 Bestechungsverfahren gegen 19 Firmen und Tochtergesellschaften in 5 OECD-Ländern; über 1 Milliarde Dollar Strafen."),
    ("US False Claims Act, Haushaltsjahr 2025:", "Rekord von 6,8 Milliarden Dollar an Vergleichen und Urteilen, davon 3,7 Milliarden gegen Pharmafirmen und Apotheken."),
    ("Das neue Gesicht der Krankheitserfindung:", "Direkt an Verbraucher verkaufte Biomarkertests machen Risikofaktoren zu „Krankheiten“. Über 50 % der vermarkteten Tests können keinen klinischen Nutzen belegen.")],
   "Transparenz wirft Licht. Aber Licht löscht Korruption nicht automatisch."),
 'es': D(BM['es'], "Los que hacen oídos sordos", "Hallazgos de 2008, actualizaciones de 2026: ha cambiado la transparencia, no el modelo",
   [("2.600 M$", "pagados a más de 665.000 médicos en 2025 (Open Payments)"), ("1.300 M$", "a hospitales universitarios y otros profesionales sanitarios"), ("3.900 M$", "en total: un 18,4 % más que el año anterior"), ("72.800 M$", "acumulados desde 2013, en más de 84 millones de registros")], None,
   [("El soborno ya es la regla, no la excepción.", "Análisis de la OCDE 1999–2025: 21 investigaciones por soborno a 19 empresas y filiales en 5 países de la OCDE; más de 1.000 millones de dólares en sanciones."),
    ("False Claims Act de EE. UU., ejercicio 2025:", "récord de 6.800 millones de dólares en acuerdos y sentencias, 3.700 millones contra farmacéuticas y farmacias."),
    ("La nueva cara de la invención de enfermedades:", "las pruebas de biomarcadores vendidas directamente al consumidor convierten factores de riesgo en «enfermedades». Más del 50 % de las pruebas comercializadas no puede demostrar beneficio clínico.")],
   "La transparencia arroja luz. Pero la luz no apaga automáticamente la corrupción."),
 'ru': D(BM['ru'], "Те, кому хоть кол на голове теши", "Выводы 2008 года, обновления 2026 года: прозрачность изменилась, модель осталась прежней",
   [("2,6 млрд $", "выплачено более чем 665 000 врачей в 2025 году (Open Payments)"), ("1,3 млрд $", "клиническим больницам и другим медработникам"), ("3,9 млрд $", "всего: на 18,4 % больше, чем годом ранее"), ("72,8 млрд $", "накопленным итогом с 2013 года, более 84 млн записей")], None,
   [("Взятка теперь правило, а не исключение.", "Анализ ОЭСР за 1999–2025 годы: 21 расследование о подкупе в отношении 19 компаний и их филиалов в 5 странах ОЭСР; санкции более 1 млрд долларов."),
    ("Закон США о ложных требованиях, 2025 финансовый год:", "рекордные 6,8 млрд долларов по соглашениям и решениям судов, из них 3,7 млрд к фармкомпаниям и аптекам."),
    ("Новое лицо изобретения болезней:", "тесты на биомаркеры, продаваемые напрямую потребителю, превращают факторы риска в «болезни». Более 50 % таких тестов не могут доказать клиническую пользу.")],
   "Прозрачность проливает свет. Но свет сам по себе коррупцию не гасит."),
 'zh': D(BM['zh'], "充耳不闻的人", "2008年的发现，2026年的更新：透明度变了，模式没变",
   [("26亿美元", "2025年支付给66.5万多名医生（Open Payments）"), ("13亿美元", "支付给教学医院和非医生医务人员"), ("39亿美元", "合计：比上一年增长18.4%"), ("728亿美元", "2013年以来累计，记录超过8400万条")], None,
   [("行贿已成常规，而非例外。", "经合组织1999–2025年分析：5个经合组织国家针对19家公司及其关联机构开展了21项行贿调查；处罚金额超过10亿美元。"),
    ("美国《虚假申报法》，2025财年：", "和解与判决金额创纪录，达68亿美元，其中37亿美元针对制药公司和药店。"),
    ("“发明疾病”的新面孔：", "直接卖给消费者的生物标志物检测把风险因素变成“疾病”。市场上超过50%的检测无法证明临床获益。")],
   "透明带来光亮，但光亮并不会自动消除腐败。"),
 'hi': D(BM['hi'], "अनसुनी करने वाले", "2008 के निष्कर्ष, 2026 के अद्यतन: पारदर्शिता बदली, मॉडल नहीं",
   [("2.6 अरब डॉलर", "2025 में 6,65,000 से अधिक चिकित्सकों को भुगतान (Open Payments)"), ("1.3 अरब डॉलर", "शिक्षण अस्पतालों और अन्य स्वास्थ्यकर्मियों को"), ("3.9 अरब डॉलर", "कुल: पिछले वर्ष से 18.4% अधिक"), ("72.8 अरब डॉलर", "2013 से संचयी, 8.4 करोड़ से अधिक अभिलेख")], None,
   [("रिश्वत अब अपवाद नहीं, नियम है।", "OECD विश्लेषण 1999–2025: 5 OECD देशों में 19 कंपनियों और संबद्ध संस्थाओं पर 21 रिश्वत जाँचें; 1 अरब डॉलर से अधिक के दंड।"),
    ("अमेरिकी फ़ॉल्स क्लेम्स एक्ट, वित्त वर्ष 2025:", "समझौतों और फ़ैसलों में रिकॉर्ड 6.8 अरब डॉलर, जिनमें 3.7 अरब दवा कंपनियों और फ़ार्मेसियों के विरुद्ध।"),
    ("बीमारी गढ़ने का नया चेहरा:", "सीधे उपभोक्ता को बेचे जाने वाले बायोमार्कर टेस्ट जोखिम कारकों को “बीमारी” बना देते हैं। बाज़ार के 50% से अधिक टेस्ट नैदानिक लाभ सिद्ध नहीं कर पाते।")],
   "पारदर्शिता रोशनी डालती है। पर रोशनी भ्रष्टाचार को अपने-आप नहीं बुझाती।"),
 'ja': D(BM['ja'], "聞く耳を持たない人々", "2008年の指摘と2026年の更新：透明性は変わったが、モデルは変わっていない",
   [("26億ドル", "2025年に66万5千人超の医師へ支払われた額（Open Payments）"), ("13億ドル", "教育病院と医師以外の医療従事者へ"), ("39億ドル", "合計：前年比18.4%増"), ("728億ドル", "2013年からの累計、8,400万件超の記録")], None,
   [("贈賄は例外ではなく常態になった。", "OECDの分析（1999〜2025年）：OECD5か国で19社とその関連会社に対する21件の贈賄捜査。制裁は10億ドル超。"),
    ("米国の不正請求防止法、2025会計年度：", "和解と判決の合計は過去最高の68億ドル。うち37億ドルは製薬企業と薬局が対象。"),
    ("病気づくりの新しい顔：", "消費者に直接販売されるバイオマーカー検査がリスク因子を「病気」に変える。市販検査の50%超は臨床的有用性を示せない。")],
   "透明性は光を当てる。しかし光が自動的に腐敗を消すわけではない。"),
})

# 23 — Competition Authority confirms
_RS = "Rekabet Kurumu"
CARDS['rekabet2'] = ('burg', {
 'en': D("CLINICAL PHARMACOLOGY", "Does the Competition Authority confirm what we said?", "Pharmaceutical Sector Preliminary Report, August 2026: on four issues an independent public authority reaches the same conclusions", None, None,
   [("1. Reference pricing:", "the '1% market share' threshold does not show that a drug is really accessible. (Article 278, p. 97)"),
    ("2. Public institution discount:", "uncertainty about the stage at which it is applied is a structural problem in the price chain. (Article 438 ff., p. 164)"),
    ("3. Patent clusters and delay:", "2015–2025: dozens of patent lawsuits and settlements are now in the official record. (§3.1.2, Table 9, pp. 54–65)"),
    ("4. Industry discourse:", "for the first time, an official document records a counter-view to the 'we cannot access' narrative. (Article 227, p. 80)")],
   None, "Source: Competition Authority (" + _RS + "), Pharmaceutical Sector Inquiry Preliminary Report, August 2026"),
 'de': D("KLINISCHE PHARMAKOLOGIE", "Bestätigt die Wettbewerbsbehörde, was wir gesagt haben?", "Vorbericht zum Arzneimittelsektor, August 2026: In vier Punkten kommt eine unabhängige Behörde zu denselben Ergebnissen", None, None,
   [("1. Referenzpreisbildung:", "Die Schwelle „1 % Marktanteil“ zeigt nicht, dass ein Medikament wirklich verfügbar ist. (Artikel 278, S. 97)"),
    ("2. Rabatt für öffentliche Einrichtungen:", "Die Unklarheit über die Anwendungsstufe ist ein strukturelles Problem der Preiskette. (Artikel 438 ff., S. 164)"),
    ("3. Patentcluster und Verzögerung:", "2015–2025: Dutzende Patentklagen und Vergleiche stehen nun in offiziellen Unterlagen. (§3.1.2, Tabelle 9, S. 54–65)"),
    ("4. Diskurs der Industrie:", "Erstmals hält ein amtliches Dokument eine Gegenposition zur Erzählung „wir haben keinen Zugang“ fest. (Artikel 227, S. 80)")],
   None, "Quelle: Wettbewerbsbehörde (" + _RS + "), Vorbericht zur Sektoruntersuchung Arzneimittel, August 2026"),
 'es': D("FARMACOLOGÍA CLÍNICA", "¿Confirma la Autoridad de Competencia lo que dijimos?", "Informe preliminar del sector farmacéutico, agosto de 2026: en cuatro puntos, una autoridad pública independiente llega a las mismas conclusiones", None, None,
   [("1. Precios de referencia:", "el umbral del «1 % de cuota de mercado» no demuestra que un fármaco sea realmente accesible. (Artículo 278, p. 97)"),
    ("2. Descuento a instituciones públicas:", "la incertidumbre sobre la fase en que se aplica es un problema estructural de la cadena de precios. (Artículo 438 y ss., p. 164)"),
    ("3. Marañas de patentes y retrasos:", "2015–2025: decenas de litigios y acuerdos sobre patentes constan ya en registros oficiales. (§3.1.2, Tabla 9, pp. 54–65)"),
    ("4. Discurso de la industria:", "por primera vez un documento oficial recoge una opinión contraria al relato «no tenemos acceso». (Artículo 227, p. 80)")],
   None, "Fuente: Autoridad de Competencia (" + _RS + "), informe preliminar del sector farmacéutico, agosto de 2026"),
 'ru': D("КЛИНИЧЕСКАЯ ФАРМАКОЛОГИЯ", "Подтверждает ли Управление по конкуренции то, что мы говорили?", "Предварительный отчёт о фармсекторе, август 2026 г.: по четырём темам независимый государственный орган приходит к тем же выводам", None, None,
   [("1. Референтное ценообразование:", "порог «1 % доли рынка» не показывает, что лекарство действительно доступно. (Статья 278, с. 97)"),
    ("2. Скидка для госучреждений:", "неясность этапа её применения является структурной проблемой ценовой цепочки. (Статья 438 и далее, с. 164)"),
    ("3. Патентные кластеры и задержки:", "2015–2025 гг.: десятки патентных исков и мировых соглашений теперь отражены в официальных документах. (§3.1.2, таблица 9, с. 54–65)"),
    ("4. Риторика индустрии:", "впервые в официальном документе зафиксировано возражение против тезиса «у нас нет доступа». (Статья 227, с. 80)")],
   None, "Источник: Управление по конкуренции (" + _RS + "), предварительный отчёт по фармсектору, август 2026 г."),
 'zh': D("临床药理学", "竞争管理局证实了我们说过的话吗？", "医药行业初步报告，2026年8月：在四个问题上，一个独立的公共机构得出了相同的结论", None, None,
   [("1. 参考定价：", "“1%市场份额”门槛并不能说明药品真正可及。（第278条，第97页）"),
    ("2. 公共机构折扣：", "适用环节不明确，是价格链条中的结构性问题。（第438条及以下，第164页）"),
    ("3. 专利丛林与拖延：", "2015–2025年：数十起专利诉讼与和解如今已载入官方记录。（§3.1.2，表9，第54–65页）"),
    ("4. 行业话语：", "官方文件首次记录了对“我们无法获得药品”这一说法的反对意见。（第227条，第80页）")],
   None, "来源：竞争管理局（" + _RS + "），医药行业调查初步报告，2026年8月"),
 'hi': D("क्लिनिकल फार्माकोलॉजी", "क्या प्रतिस्पर्धा प्राधिकरण हमारी कही बातों की पुष्टि करता है?", "दवा क्षेत्र की प्रारंभिक रिपोर्ट, अगस्त 2026: चार मुद्दों पर एक स्वतंत्र सार्वजनिक प्राधिकरण उन्हीं निष्कर्षों पर पहुँचता है", None, None,
   [("1. संदर्भ मूल्य निर्धारण:", "“1% बाज़ार हिस्सेदारी” की सीमा यह नहीं दिखाती कि दवा वास्तव में उपलब्ध है। (अनुच्छेद 278, पृ. 97)"),
    ("2. सार्वजनिक संस्था छूट:", "यह किस चरण पर लागू होती है, इसकी अस्पष्टता मूल्य शृंखला की संरचनात्मक समस्या है। (अनुच्छेद 438 आदि, पृ. 164)"),
    ("3. पेटेंट समूह और विलंब:", "2015–2025: दर्जनों पेटेंट मुकदमे और समझौते अब आधिकारिक अभिलेखों में हैं। (§3.1.2, तालिका 9, पृ. 54–65)"),
    ("4. उद्योग का कथन:", "पहली बार एक आधिकारिक दस्तावेज़ में “हमें पहुँच नहीं मिलती” वाले कथन के विरुद्ध मत दर्ज हुआ। (अनुच्छेद 227, पृ. 80)")],
   None, "स्रोत: प्रतिस्पर्धा प्राधिकरण (" + _RS + "), दवा क्षेत्र जाँच की प्रारंभिक रिपोर्ट, अगस्त 2026"),
 'ja': D("臨床薬理学", "競争当局は私たちの指摘を裏づけているか", "医薬品セクター中間報告（2026年8月）：4つの論点で、独立した公的機関が同じ結論に達している", None, None,
   [("1. 参照価格制度：", "「市場シェア1%」という基準は、薬が実際に入手可能であることを示さない。（第278項、97頁）"),
    ("2. 公的機関割引：", "どの段階で適用されるかが不明確なことは、価格連鎖の構造的問題である。（第438項以下、164頁）"),
    ("3. 特許の束と遅延：", "2015〜2025年：数十件の特許訴訟と和解が公式記録に載った。（§3.1.2、表9、54〜65頁）"),
    ("4. 業界の言説：", "「アクセスできない」という主張への反対意見が、初めて公式文書に記録された。（第227項、80頁）")],
   None, "出典：競争当局（" + _RS + "）医薬品セクター調査中間報告、2026年8月"),
})

# 24 — Acne
CARDS['akne'] = ('purple', {
 'en': D("CLINICAL UPDATE", "Acne vulgaris", "Early and effective treatment prevents scarring and reduces the psychosocial burden. Acne affects up to 85% of adolescents and can continue into adulthood", None, None,
   [("1. Topical treatment (first line):", "combination therapy, benzoyl peroxide plus a topical retinoid. Topical antibiotics should not be used alone or long term."),
    ("2. Oral antibiotics (limited use):", "short courses of up to 3 months in moderate to severe inflammatory acne, always together with non-antibiotic topical treatment. First choice: tetracyclines."),
    ("3. Hormonal treatment (women):", "combined oral contraceptives; spironolactone 25–150 mg/day."),
    ("4. Isotretinoin (most effective option):", "for severe, scarring or treatment-resistant acne. Pregnancy must be prevented; monitor mental health and sexual side effects."),
    ("Refer to a dermatologist:", "severe nodulocystic acne, rapid scarring, no response to appropriate treatment, or a heavy psychological burden.")],
   "Treatment takes patience. Regular use brings success."),
 'de': D("KLINISCHES UPDATE", "Acne vulgaris", "Frühe und wirksame Behandlung verhindert Narben und verringert die psychosoziale Belastung. Akne betrifft bis zu 85 % der Jugendlichen und kann bis ins Erwachsenenalter anhalten", None, None,
   [("1. Topische Therapie (erste Wahl):", "Kombination aus Benzoylperoxid und topischem Retinoid. Topische Antibiotika nicht allein und nicht langfristig anwenden."),
    ("2. Orale Antibiotika (begrenzt):", "kurzzeitig (bis 3 Monate) bei mittelschwerer bis schwerer entzündlicher Akne, immer zusammen mit nicht-antibiotischer topischer Therapie. Erste Wahl: Tetrazykline."),
    ("3. Hormonelle Therapie (Frauen):", "kombinierte orale Kontrazeptiva; Spironolacton 25–150 mg/Tag."),
    ("4. Isotretinoin (wirksamste Option):", "bei schwerer, narbenbildender oder therapieresistenter Akne. Schwangerschaft muss verhütet werden; psychische Gesundheit und sexuelle Nebenwirkungen überwachen."),
    ("Überweisung zum Dermatologen:", "schwere nodulozystische Akne, rasche Narbenbildung, kein Ansprechen auf angemessene Therapie oder starke psychische Belastung.")],
   "Die Behandlung braucht Geduld. Regelmäßige Anwendung bringt den Erfolg."),
 'es': D("ACTUALIZACIÓN CLÍNICA", "Acné vulgar", "El tratamiento precoz y eficaz previene las cicatrices y reduce la carga psicosocial. El acné afecta hasta al 85 % de los adolescentes y puede persistir en la edad adulta", None, None,
   [("1. Tratamiento tópico (primera línea):", "terapia combinada, peróxido de benzoilo más un retinoide tópico. Los antibióticos tópicos no deben usarse solos ni a largo plazo."),
    ("2. Antibióticos orales (uso limitado):", "ciclos cortos (hasta 3 meses) en el acné inflamatorio moderado o grave, siempre junto con tratamiento tópico no antibiótico. Primera elección: tetraciclinas."),
    ("3. Tratamiento hormonal (mujeres):", "anticonceptivos orales combinados; espironolactona 25–150 mg/día."),
    ("4. Isotretinoína (la opción más eficaz):", "en acné grave, cicatricial o resistente al tratamiento. Es imprescindible evitar el embarazo; vigilar la salud mental y los efectos sexuales."),
    ("Derivar al dermatólogo:", "acné noduloquístico grave, cicatrización rápida, falta de respuesta al tratamiento adecuado o carga psicológica importante.")],
   "El tratamiento exige paciencia. El uso regular es lo que da resultado."),
 'ru': D("КЛИНИЧЕСКОЕ ОБНОВЛЕНИЕ", "Обыкновенные угри (акне)", "Раннее и эффективное лечение предотвращает рубцы и снижает психосоциальное бремя. Акне встречается у 85 % подростков и может сохраняться во взрослом возрасте", None, None,
   [("1. Местное лечение (первая линия):", "комбинация бензоилпероксида и топического ретиноида. Топические антибиотики нельзя применять отдельно и длительно."),
    ("2. Пероральные антибиотики (ограниченно):", "короткими курсами (до 3 месяцев) при среднетяжёлом и тяжёлом воспалительном акне, всегда вместе с неантибиотическим местным лечением. Первый выбор: тетрациклины."),
    ("3. Гормональное лечение (у женщин):", "комбинированные оральные контрацептивы; спиронолактон 25–150 мг/сут."),
    ("4. Изотретиноин (самый эффективный вариант):", "при тяжёлом, рубцующемся или резистентном акне. Обязательна защита от беременности; следить за психическим здоровьем и сексуальными побочными эффектами."),
    ("Направить к дерматологу:", "тяжёлое узловато-кистозное акне, быстрое рубцевание, отсутствие ответа на адекватное лечение или тяжёлое психологическое бремя.")],
   "Лечение требует терпения. Успех приносит регулярное применение."),
 'zh': D("临床进展", "寻常痤疮", "及早有效治疗可以预防瘢痕、减轻心理社会负担。痤疮影响多达85%的青少年，并可持续到成年", None, None,
   [("1. 外用治疗（一线）：", "联合治疗，过氧化苯甲酰加外用维A酸类。外用抗生素不应单独或长期使用。"),
    ("2. 口服抗生素（限制使用）：", "用于中重度炎症性痤疮，短期（不超过3个月），且必须联合非抗生素外用治疗。首选四环素类。"),
    ("3. 激素治疗（女性）：", "复方口服避孕药；螺内酯25–150毫克/天。"),
    ("4. 异维A酸（最有效的选择）：", "用于重度、瘢痕性或难治性痤疮。必须避孕；需监测精神健康和性功能方面的副作用。"),
    ("转诊皮肤科：", "重度结节囊肿性痤疮、瘢痕进展迅速、规范治疗无效，或心理负担沉重。")],
   "治疗需要耐心，坚持规律用药才能成功。"),
 'hi': D("क्लिनिकल अपडेट", "एक्ने वल्गैरिस (मुँहासे)", "जल्द और प्रभावी उपचार दाग़ बनने से रोकता है और मनोसामाजिक बोझ घटाता है। मुँहासे 85% तक किशोरों को प्रभावित करते हैं और वयस्कता तक रह सकते हैं", None, None,
   [("1. त्वचा पर लगाने वाला उपचार (पहली पंक्ति):", "संयुक्त उपचार, बेंज़ोइल परॉक्साइड और टॉपिकल रेटिनॉइड। टॉपिकल एंटीबायोटिक अकेले या लंबे समय तक न दें।"),
    ("2. मौखिक एंटीबायोटिक (सीमित उपयोग):", "मध्यम से गंभीर सूजनयुक्त मुँहासों में कम अवधि (3 महीने तक), हमेशा गैर-एंटीबायोटिक टॉपिकल उपचार के साथ। पहली पसंद: टेट्रासाइक्लिन।"),
    ("3. हार्मोनल उपचार (महिलाओं में):", "संयुक्त मौखिक गर्भनिरोधक; स्पाइरोनोलैक्टोन 25–150 मि.ग्रा./दिन।"),
    ("4. आइसोट्रेटिनॉइन (सबसे प्रभावी विकल्प):", "गंभीर, दाग़ छोड़ने वाले या उपचार-प्रतिरोधी मुँहासों में। गर्भधारण से बचाव अनिवार्य; मानसिक स्वास्थ्य और यौन दुष्प्रभावों की निगरानी करें।"),
    ("त्वचा विशेषज्ञ के पास भेजें:", "गंभीर नोड्यूलोसिस्टिक मुँहासे, तेज़ी से दाग़ बनना, उचित उपचार से लाभ न होना, या भारी मानसिक बोझ।")],
   "उपचार में धैर्य चाहिए। नियमित उपयोग से ही सफलता मिलती है।"),
 'ja': D("臨床アップデート", "尋常性ざ瘡（にきび）", "早期の効果的な治療は瘢痕を防ぎ、心理社会的な負担を減らす。にきびは思春期の最大85%にみられ、成人期まで続くことがある", None, None,
   [("1. 外用療法（第一選択）：", "過酸化ベンゾイルと外用レチノイドの併用。外用抗菌薬は単独でも長期でも使わない。"),
    ("2. 経口抗菌薬（限定的に使用）：", "中等症〜重症の炎症性ざ瘡に短期間（3か月以内）、必ず抗菌薬以外の外用療法と併用。第一選択はテトラサイクリン系。"),
    ("3. ホルモン療法（女性）：", "混合型経口避妊薬、スピロノラクトン25〜150mg/日。"),
    ("4. イソトレチノイン（最も有効な選択肢）：", "重症、瘢痕形成性、または治療抵抗性のざ瘡に。避妊は必須。精神面と性機能の副作用を観察する。"),
    ("皮膚科へ紹介：", "重症の結節嚢腫性ざ瘡、急速な瘢痕形成、適切な治療に反応しない場合、または心理的負担が大きい場合。")],
   "治療には根気が必要。規則正しく使うことが成功につながる。"),
})

# 26 — Council of State decision on SGK internal reference pricing
CARDS['danistay'] = ('burg', {
 'en': D("COUNCIL OF STATE DECISION · 10 AUGUST 2026", "SGK's internal reference pricing", "The 5 provisions whose execution was suspended, and what they really mean",
   [("2022", "The 'therapeutic reference' (TR) group definition is introduced"), ("2023", "The Council of State suspends the TR group"), ("2024", "A new structure is built using 'group'"), ("2026", "Execution of 5 provisions is suspended")], None,
   [("Suspended provisions:", "the band range (Art. 3/1-a), a group definition going beyond equivalent groups (3/1-i), the 1% market-share filter (3/1-p), the Reimbursement Commission's power to create groups (5/1-e) and TEDK opinions (9/1-g)."),
    ("The point:", "the Council of State's intervention is about how, and with what authority, the group that sets the price is formed, before the price itself."),
    ("Clinical pharmacology:", "therapeutic equivalence ≠ pharmaceutical equivalence ≠ bioequivalence. Putting different active substances into one reimbursement group cannot be defended.")]),
 'de': D("ENTSCHEIDUNG DES STAATSRATS · 10. AUGUST 2026", "Die interne Referenzpreisbildung der SGK", "Die 5 Bestimmungen, deren Vollzug ausgesetzt wurde, und ihre wirkliche Bedeutung",
   [("2022", "Die Gruppendefinition „therapeutische Referenz“ (TR) wird eingeführt"), ("2023", "Der Staatsrat setzt die TR-Gruppe aus"), ("2024", "Mit „Gruppe“ wird eine neue Struktur aufgebaut"), ("2026", "Der Vollzug von 5 Bestimmungen wird ausgesetzt")], None,
   [("Ausgesetzte Bestimmungen:", "Preisband (Art. 3/1-a), Gruppendefinition über Äquivalenzgruppen hinaus (3/1-i), 1-%-Marktanteilsfilter (3/1-p), Befugnis der Erstattungskommission zur Gruppenbildung (5/1-e) und TEDK-Stellungnahmen (9/1-g)."),
    ("Der Kern:", "Der Eingriff des Staatsrats betrifft, noch vor dem Preis selbst, wie und mit welcher Befugnis die preisbestimmende Gruppe gebildet wird."),
    ("Klinische Pharmakologie:", "therapeutische Äquivalenz ≠ pharmazeutische Äquivalenz ≠ Bioäquivalenz. Verschiedene Wirkstoffe in eine Erstattungsgruppe zu stellen, ist nicht vertretbar.")]),
 'es': D("DECISIÓN DEL CONSEJO DE ESTADO · 10 DE AGOSTO DE 2026", "Los precios de referencia internos de la SGK", "Las 5 disposiciones cuya ejecución se suspendió y su verdadero significado",
   [("2022", "Se introduce la definición de grupo de «referencia terapéutica» (TR)"), ("2023", "El Consejo de Estado suspende el grupo TR"), ("2024", "Se construye una nueva estructura con «grupo»"), ("2026", "Se suspende la ejecución de 5 disposiciones")], None,
   [("Disposiciones suspendidas:", "la banda de precios (art. 3/1-a), una definición de grupo que va más allá de los grupos equivalentes (3/1-i), el filtro del 1 % de cuota de mercado (3/1-p), la facultad de la Comisión de Reembolso de crear grupos (5/1-e) y los dictámenes de la TEDK (9/1-g)."),
    ("La cuestión de fondo:", "la intervención del Consejo de Estado se refiere, antes que al precio, a cómo y con qué competencia se forma el grupo que lo determina."),
    ("Farmacología clínica:", "equivalencia terapéutica ≠ equivalencia farmacéutica ≠ bioequivalencia. No es defendible poner principios activos distintos en un mismo grupo de reembolso.")]),
 'ru': D("РЕШЕНИЕ ГОССОВЕТА · 10 АВГУСТА 2026", "Внутреннее референтное ценообразование SGK", "5 положений, исполнение которых приостановлено, и их реальный смысл",
   [("2022", "Вводится определение группы «терапевтической референции» (TR)"), ("2023", "Госсовет приостанавливает группу TR"), ("2024", "Создаётся новая конструкция с понятием «группа»"), ("2026", "Приостановлено исполнение 5 положений")], None,
   [("Приостановленные положения:", "ценовой диапазон (ст. 3/1-a), определение группы шире эквивалентных групп (3/1-i), фильтр 1 % доли рынка (3/1-p), полномочие Комиссии по возмещению формировать группы (5/1-e) и заключения TEDK (9/1-g)."),
    ("Суть:", "вмешательство Госсовета касается не столько самой цены, сколько того, как и на каком основании формируется группа, определяющая цену."),
    ("Клиническая фармакология:", "терапевтическая эквивалентность ≠ фармацевтическая эквивалентность ≠ биоэквивалентность. Объединять разные действующие вещества в одну группу возмещения нельзя обосновать.")]),
 'zh': D("国务委员会（最高行政法院）裁定 · 2026年8月10日", "社保机构（SGK）的内部参考定价", "被中止执行的5项条款及其真实含义",
   [("2022年", "引入“治疗参考”（TR）分组定义"), ("2023年", "国务委员会中止TR分组"), ("2024年", "以“组”为名建立新结构"), ("2026年", "5项条款被中止执行")], None,
   [("被中止的条款：", "价格区间（第3/1-a条）、超出等效组范围的分组定义（3/1-i）、1%市场份额筛选（3/1-p）、报销委员会设立分组的权限（5/1-e）以及TEDK意见（9/1-g）。"),
    ("要点：", "国务委员会的干预首先针对的不是价格本身，而是决定价格的分组如何形成、依据何种权限形成。"),
    ("临床药理学：", "治疗等效 ≠ 药学等效 ≠ 生物等效。把不同的有效成分放进同一个报销组是站不住脚的。")]),
 'hi': D("राज्य परिषद का निर्णय · 10 अगस्त 2026", "SGK का आंतरिक संदर्भ मूल्य निर्धारण", "जिन 5 प्रावधानों के क्रियान्वयन पर रोक लगी, और उनका असली अर्थ",
   [("2022", "“चिकित्सीय संदर्भ” (TR) समूह की परिभाषा लाई गई"), ("2023", "राज्य परिषद ने TR समूह पर रोक लगाई"), ("2024", "“समूह” नाम से नई संरचना बनाई गई"), ("2026", "5 प्रावधानों के क्रियान्वयन पर रोक")], None,
   [("रोके गए प्रावधान:", "मूल्य बैंड (अनु. 3/1-a), समतुल्य समूहों से आगे जाने वाली समूह परिभाषा (3/1-i), 1% बाज़ार हिस्सेदारी का फ़िल्टर (3/1-p), प्रतिपूर्ति आयोग का समूह बनाने का अधिकार (5/1-e) और TEDK की राय (9/1-g)।"),
    ("मूल बात:", "राज्य परिषद का हस्तक्षेप कीमत से पहले इस पर है कि कीमत तय करने वाला समूह कैसे और किस अधिकार से बनाया जाता है।"),
    ("क्लिनिकल फार्माकोलॉजी:", "चिकित्सीय समतुल्यता ≠ औषधीय समतुल्यता ≠ जैव-समतुल्यता। अलग-अलग सक्रिय पदार्थों को एक ही प्रतिपूर्ति समूह में रखना उचित नहीं ठहराया जा सकता।")]),
 'ja': D("国家評議会（最高行政裁判所）決定 · 2026年8月10日", "SGKの内部参照価格制度", "執行が停止された5つの規定と、その本当の意味",
   [("2022年", "「治療参照（TR）」グループの定義を導入"), ("2023年", "国家評議会がTRグループを停止"), ("2024年", "「グループ」という名で新たな仕組みを構築"), ("2026年", "5つの規定の執行を停止")], None,
   [("停止された規定：", "価格帯（第3/1-a条）、同等グループを超えるグループ定義（3/1-i）、市場シェア1%による絞り込み（3/1-p）、償還委員会のグループ設定権限（5/1-e）、TEDKの意見（9/1-g）。"),
    ("要点：", "国家評議会の介入は、価格そのものより前に、価格を決めるグループがどのように、どの権限で作られるかに向けられている。"),
    ("臨床薬理学：", "治療学的同等性 ≠ 製剤学的同等性 ≠ 生物学的同等性。異なる有効成分を一つの償還グループに入れることは正当化できない。")]),
})

# 27 — Orphan drugs: 44 years
CARDS['orphan'] = ('teal', {
 'en': D("HISTORICAL ANALYSIS", "44 years earlier, 44 years later", "'Orphan drugs' entered the Turkish literature a month before the United States passed its own law. Today the same concept is at the centre of a billion-dollar debate on regulatory exemptions",
   [("4 Dec 1982", "Assoc. Prof. F. Cankat Tulunay publishes 'Orphan Drugs' in the newspaper Milliyet"), ("4 Jan 1983", "The US Orphan Drug Act enters into force, exactly one month after the article"), ("2026", "The same concept, in the CBO's analysis of an 8.8-billion-dollar exemption")], "THE SAME QUESTION IN 2026, IN A NEW CONTEXT",
   [("USA:", "the Orphan Cures Act raised the CBO estimate from 4.9 to 8.8 billion dollars; mechanisms of abuse have been documented."),
    ("Türkiye:", "the Secretary General of AIFD and the President of TİTCK sit on the board of the same advocacy association, DETESADER."),
    ("The call of 1982 still stands:", "who sets drug policy, and with what transparency?")]),
 'de': D("HISTORISCHE ANALYSE", "44 Jahre davor, 44 Jahre danach", "„Orphan Drugs“ kamen einen Monat vor dem US-Gesetz in die türkische Literatur. Heute steht derselbe Begriff im Zentrum einer Milliardendebatte über regulatorische Ausnahmen",
   [("4. Dez. 1982", "Doz. Dr. F. Cankat Tulunay veröffentlicht „Waisen-Arzneimittel“ in der Zeitung Milliyet"), ("4. Jan. 1983", "Der US Orphan Drug Act tritt in Kraft, genau einen Monat nach dem Artikel"), ("2026", "Derselbe Begriff in der CBO-Analyse einer Ausnahme im Wert von 8,8 Milliarden Dollar")], "DIESELBE FRAGE 2026, IN NEUEM KONTEXT",
   [("USA:", "Der Orphan Cures Act erhöhte die CBO-Schätzung von 4,9 auf 8,8 Milliarden Dollar; Missbrauchsmechanismen sind dokumentiert."),
    ("Türkei:", "Der Generalsekretär der AIFD und der Präsident der TİTCK sitzen im Vorstand desselben Interessenverbands, DETESADER."),
    ("Der Appell von 1982 gilt weiter:", "Wer bestimmt die Arzneimittelpolitik, und mit welcher Transparenz?")]),
 'es': D("ANÁLISIS HISTÓRICO", "44 años antes, 44 años después", "Los «medicamentos huérfanos» entraron en la literatura turca un mes antes de la ley estadounidense. Hoy el mismo concepto está en el centro de un debate de miles de millones sobre exenciones regulatorias",
   [("4 dic. 1982", "El Dr. F. Cankat Tulunay publica «Medicamentos huérfanos» en el diario Milliyet"), ("4 ene. 1983", "Entra en vigor la Orphan Drug Act de EE. UU., justo un mes después del artículo"), ("2026", "El mismo concepto, en el análisis de la CBO de una exención de 8.800 millones de dólares")], "LA MISMA PREGUNTA EN 2026, EN UN NUEVO CONTEXTO",
   [("EE. UU.:", "la Orphan Cures Act elevó la estimación de la CBO de 4.900 a 8.800 millones de dólares; se han documentado mecanismos de abuso."),
    ("Turquía:", "el secretario general de la AIFD y el presidente de la TİTCK están en la junta de la misma asociación de defensa, DETESADER."),
    ("El llamamiento de 1982 sigue vigente:", "¿quién fija la política farmacéutica y con qué transparencia?")]),
 'ru': D("ИСТОРИЧЕСКИЙ АНАЛИЗ", "44 года назад и 44 года спустя", "Понятие «орфанные лекарства» вошло в турецкую литературу за месяц до принятия закона в США. Сегодня оно в центре миллиардного спора о регуляторных исключениях",
   [("4 дек. 1982", "Доцент Ф. Джанкат Тулунай публикует статью «Лекарства-сироты» в газете Milliyet"), ("4 янв. 1983", "В США вступает в силу Orphan Drug Act, ровно через месяц после статьи"), ("2026", "То же понятие в анализе CBO об исключении стоимостью 8,8 млрд долларов")], "ТОТ ЖЕ ВОПРОС В 2026 ГОДУ, В НОВОМ КОНТЕКСТЕ",
   [("США:", "Orphan Cures Act повысил оценку CBO с 4,9 до 8,8 млрд долларов; механизмы злоупотреблений задокументированы."),
    ("Турция:", "генеральный секретарь AIFD и глава TİTCK входят в правление одной и той же ассоциации DETESADER."),
    ("Призыв 1982 года актуален:", "кто определяет лекарственную политику и насколько прозрачно?")]),
 'zh': D("历史分析", "44年前，44年后", "“孤儿药”一词进入土耳其文献，比美国通过本国法律还早一个月。如今同一概念正处于数十亿美元监管豁免之争的中心",
   [("1982年12月4日", "F. Cankat Tulunay副教授在《国民报》（Milliyet）发表《孤儿药》一文"), ("1983年1月4日", "美国《孤儿药法案》生效，恰在文章发表一个月之后"), ("2026年", "同一概念出现在美国国会预算办公室关于88亿美元豁免的分析中")], "2026年，同样的问题，新的背景",
   [("美国：", "《孤儿药治愈法案》使国会预算办公室的估算从49亿美元升至88亿美元；滥用机制已有记录。"),
    ("土耳其：", "AIFD秘书长和TİTCK主席同在倡导团体DETESADER的理事会任职。"),
    ("1982年的呼吁依然有效：", "药品政策由谁制定，又有多大透明度？")]),
 'hi': D("ऐतिहासिक विश्लेषण", "44 वर्ष पहले, 44 वर्ष बाद", "“ऑर्फन ड्रग्स” शब्द अमेरिका के अपने कानून से एक महीना पहले तुर्की साहित्य में आया था। आज वही अवधारणा अरबों डॉलर की नियामकीय छूट की बहस के केंद्र में है",
   [("4 दिसं. 1982", "डॉ. एफ. जानकात तुलुनाय ने अख़बार Milliyet में “अनाथ दवाएँ” लेख प्रकाशित किया"), ("4 जन. 1983", "अमेरिका का ऑर्फन ड्रग एक्ट लागू हुआ, लेख के ठीक एक महीने बाद"), ("2026", "वही अवधारणा, CBO के 8.8 अरब डॉलर की छूट के विश्लेषण में")], "2026 में वही प्रश्न, नए संदर्भ में",
   [("अमेरिका:", "ऑर्फन क्योर्स एक्ट ने CBO का अनुमान 4.9 से बढ़ाकर 8.8 अरब डॉलर कर दिया; दुरुपयोग के तरीक़े दर्ज किए गए हैं।"),
    ("तुर्किये:", "AIFD के महासचिव और TİTCK के अध्यक्ष एक ही पैरोकार संस्था DETESADER के बोर्ड में हैं।"),
    ("1982 की पुकार आज भी प्रासंगिक:", "दवा नीति कौन तय करता है, और कितनी पारदर्शिता से?")]),
 'ja': D("歴史的分析", "44年前と44年後", "「オーファンドラッグ」は、米国が自国の法律を制定する1か月前にトルコの文献に登場した。今日、同じ概念が数十億ドル規模の規制上の特例をめぐる議論の中心にある",
   [("1982年12月4日", "F・ジャンカット・トゥルナイ准教授がミリエット紙に「オーファンドラッグ」を寄稿"), ("1983年1月4日", "米国オーファンドラッグ法が施行。記事のちょうど1か月後"), ("2026年", "同じ概念が、CBOによる88億ドルの特例の分析に登場")], "2026年、同じ問いを新しい文脈で",
   [("米国：", "Orphan Cures ActによりCBOの試算は49億ドルから88億ドルに増えた。悪用の仕組みも記録されている。"),
    ("トルコ：", "AIFDの事務局長とTİTCKの長官が、同じ擁護団体DETESADERの理事会に名を連ねている。"),
    ("1982年の呼びかけは今も有効：", "医薬品政策を誰が、どの程度の透明性で決めているのか。")]),
})
