from batch1 import D
CARDS = {}

# 99: Drug-free intranasal treatment of migraine attacks (Mi-Helper)
CARDS['b22_migren'] = ('teal', {
 'en': D("MIGRAINE", "Drug-free intranasal treatment of migraine attacks", "Transnasal cooling with dry air (Mi-Helper), 10 litres per minute, presented at the AAN Annual Meeting",
   [("70.6%", "pain relief at 2 hours (sham 56%)"), ("47.1%", "pain freedom at 2 hours (sham 16%)"), ("41.2%", "sustained pain freedom without rescue medication (sham 16%)")], None,
   [("How it works:", "dry room-temperature air cools the nasal cavity and calms the sphenopalatine ganglion, a nerve bundle behind the nasal passages."),
    ("The study:", "randomised, double-blind, sham-controlled; 172 people aged 18 to 65 with acute migraine, 74 in the final efficacy analysis."),
    ("Treatment:", "one attack treated for 15 minutes, within 1 hour of onset."),
    ("Significance:", "only pain freedom at 2 hours was statistically significant."),
    ("Tolerability:", "well tolerated; nobody stopped treatment and no serious adverse event was recorded.")],
   "A non-invasive home device may be an alternative for acute migraine.",
   "Mays MA, et al. American Academy of Neurology Annual Meeting, April 5-9, 2025, San Diego."),
 'de': D("MIGRÄNE", "Medikamentenfreie intranasale Behandlung der Migräneattacke", "Transnasale Kühlung mit trockener Luft (Mi-Helper), 10 Liter pro Minute, vorgestellt auf der AAN-Jahrestagung",
   [("70,6 %", "Schmerzlinderung nach 2 Stunden (Schein 56 %)"), ("47,1 %", "Schmerzfreiheit nach 2 Stunden (Schein 16 %)"), ("41,2 %", "anhaltende Schmerzfreiheit ohne Notfallmedikation (Schein 16 %)")], None,
   [("Wirkprinzip:", "trockene Luft mit Raumtemperatur kühlt die Nasenhöhle und beruhigt das Ganglion sphenopalatinum, ein Nervengeflecht hinter den Nasengängen."),
    ("Die Studie:", "randomisiert, doppelblind, scheinkontrolliert; 172 Personen von 18 bis 65 Jahren mit akuter Migräne, 74 in der abschließenden Wirksamkeitsanalyse."),
    ("Behandlung:", "eine Attacke, 15 Minuten lang, innerhalb von 1 Stunde nach Beginn."),
    ("Signifikanz:", "nur die Schmerzfreiheit nach 2 Stunden war statistisch signifikant."),
    ("Verträglichkeit:", "gut verträglich; kein Therapieabbruch und kein schwerwiegendes unerwünschtes Ereignis.")],
   "Nichtinvasives Heimgerät: mögliche Alternative bei akuter Migräne.",
   "Mays MA, et al. Jahrestagung der American Academy of Neurology, 5.-9. April 2025, San Diego."),
 'es': D("MIGRAÑA", "Tratamiento intranasal sin fármacos de la crisis de migraña", "Enfriamiento transnasal con aire seco (Mi-Helper), 10 litros por minuto, presentado en la reunión anual de la AAN",
   [("70,6 %", "alivio del dolor a las 2 horas (simulado 56 %)"), ("47,1 %", "ausencia de dolor a las 2 horas (simulado 16 %)"), ("41,2 %", "ausencia de dolor sostenida sin medicación de rescate (simulado 16 %)")], None,
   [("Cómo actúa:", "aire seco a temperatura ambiente enfría la cavidad nasal y calma el ganglio esfenopalatino, un haz nervioso situado detrás de las fosas nasales."),
    ("El estudio:", "aleatorizado, doble ciego, controlado con dispositivo simulado; 172 personas de 18 a 65 años con migraña aguda, 74 en el análisis final de eficacia."),
    ("Tratamiento:", "una crisis tratada durante 15 minutos, en la primera hora tras el inicio."),
    ("Significación:", "solo la ausencia de dolor a las 2 horas fue estadísticamente significativa."),
    ("Tolerabilidad:", "bien tolerado; nadie abandonó el tratamiento y no se registró ningún acontecimiento adverso grave.")],
   "Un dispositivo doméstico no invasivo puede ser una alternativa en la migraña aguda.",
   "Mays MA, et al. Reunión anual de la American Academy of Neurology, 5-9 de abril de 2025, San Diego."),
 'ru': D("МИГРЕНЬ", "Интраназальное лечение приступа мигрени без лекарств", "Трансназальное охлаждение сухим воздухом (Mi-Helper), 10 литров в минуту, доклад на ежегодном конгрессе AAN",
   [("70,6 %", "облегчение боли через 2 часа (имитация 56 %)"), ("47,1 %", "отсутствие боли через 2 часа (имитация 16 %)"), ("41,2 %", "стойкое отсутствие боли без препаратов резерва (имитация 16 %)")], None,
   [("Как это работает:", "сухой воздух комнатной температуры охлаждает полость носа и успокаивает крылонёбный ганглий, нервный узел позади носовых ходов."),
    ("Исследование:", "рандомизированное, двойное слепое, с имитацией в контроле; 172 человека 18-65 лет с острой мигренью, 74 в итоговом анализе эффективности."),
    ("Лечение:", "один приступ, 15 минут, в течение 1 часа от начала."),
    ("Значимость:", "статистически значимым было только отсутствие боли через 2 часа."),
    ("Переносимость:", "хорошая; никто не прекратил лечение, серьёзных нежелательных явлений не отмечено.")],
   "Неинвазивное домашнее устройство может стать альтернативой при острой мигрени.",
   "Mays MA, et al. Ежегодный конгресс American Academy of Neurology, 5-9 апреля 2025 г., Сан-Диего."),
 'zh': D("偏头痛", "偏头痛发作的无药物鼻内治疗", "经鼻干燥空气冷却（Mi-Helper），每分钟10升，在美国神经病学学会（AAN）年会上报告",
   [("70.6%", "2小时疼痛缓解（假治疗组56%）"), ("47.1%", "2小时疼痛消失（假治疗组16%）"), ("41.2%", "未用补救药物的持续疼痛消失（假治疗组16%）")], None,
   [("作用原理：", "室温干燥空气使鼻腔局部降温，抑制位于鼻道后方的神经节，即蝶腭神经节。"),
    ("研究设计：", "随机、双盲、假治疗对照；纳入172名18至65岁急性偏头痛患者，74人进入最终疗效分析。"),
    ("治疗方法：", "发作开始后1小时内治疗一次发作，持续15分钟。"),
    ("统计学意义：", "只有2小时疼痛消失率的差异具有统计学意义。"),
    ("耐受性：", "耐受良好；无人中止治疗，未记录到严重不良事件。")],
   "无创家用设备可能成为急性偏头痛的一种替代选择。",
   "Mays MA, et al. 美国神经病学学会年会，2025年4月5-9日，圣迭戈。"),
 'hi': D("माइग्रेन", "माइग्रेन के दौरे का बिना दवा का इंट्रानेज़ल उपचार", "सूखी हवा से ट्रांसनेज़ल कूलिंग (Mi-Helper), 10 लीटर प्रति मिनट, AAN की वार्षिक बैठक में प्रस्तुत",
   [("70.6%", "2 घंटे में दर्द में राहत (शैम 56%)"), ("47.1%", "2 घंटे में दर्द से पूर्ण मुक्ति (शैम 16%)"), ("41.2%", "रेस्क्यू दवा के बिना बनी रही दर्द से मुक्ति (शैम 16%)")], None,
   [("कैसे काम करता है:", "कमरे के तापमान की सूखी हवा नाक की गुहा को ठंडा करती है और नाक के मार्गों के पीछे स्थित तंत्रिका गुच्छ, स्फीनोपैलेटाइन गैंग्लियन, को शांत करती है।"),
    ("अध्ययन:", "रैंडमाइज़्ड, डबल-ब्लाइंड, शैम-नियंत्रित; तीव्र माइग्रेन वाले 18 से 65 वर्ष के 172 लोग, अंतिम प्रभावकारिता विश्लेषण में 74।"),
    ("उपचार:", "एक दौरे का 15 मिनट तक उपचार, शुरू होने के 1 घंटे के भीतर।"),
    ("सार्थकता:", "केवल 2 घंटे में दर्द से पूर्ण मुक्ति सांख्यिकीय रूप से सार्थक थी।"),
    ("सहनशीलता:", "अच्छी तरह सहन हुआ; किसी ने उपचार नहीं छोड़ा और कोई गंभीर प्रतिकूल घटना दर्ज नहीं हुई।")],
   "घर पर उपयोग होने वाला गैर-आक्रामक उपकरण तीव्र माइग्रेन में एक विकल्प हो सकता है।",
   "Mays MA, et al. American Academy of Neurology वार्षिक बैठक, 5-9 अप्रैल 2025, सैन डिएगो।"),
 'ja': D("片頭痛", "片頭痛発作に対する薬を使わない経鼻治療", "乾燥空気による経鼻冷却（Mi-Helper）、毎分10リットル、米国神経学会（AAN）年次総会で発表",
   [("70.6%", "2時間後の疼痛軽減（シャム群56%）"), ("47.1%", "2時間後の疼痛消失（シャム群16%）"), ("41.2%", "レスキュー薬なしでの持続的な疼痛消失（シャム群16%）")], None,
   [("作用の仕組み：", "室温の乾燥空気で鼻腔を局所的に冷却し、鼻道の奥にある神経の束である翼口蓋神経節を鎮める。"),
    ("試験：", "無作為化、二重盲検、シャム対照。18～65歳の急性片頭痛患者172人、最終有効性解析は74人。"),
    ("治療：", "発作開始から1時間以内に、1回の発作を15分間治療。"),
    ("有意性：", "統計学的に有意だったのは2時間後の疼痛消失のみ。"),
    ("忍容性：", "忍容性は良好で、治療中止例はなく、重篤な有害事象も記録されなかった。")],
   "非侵襲的な家庭用機器は急性片頭痛の代替手段になりうる。",
   "Mays MA, et al. 米国神経学会年次総会、2025年4月5～9日、サンディエゴ。"),
})
