from batch1 import D
CARDS = {}

# i=11: Why rational drug use stayed on paper (Turkey)
CARDS['b14_aikkagit'] = ('teal', {
 'en': D("RATIONAL DRUG USE", "Why did rational drug use stay on paper?", "In Turkey, rational drug use policy drifted away from the WHO model and became bureaucratic", None, None,
   [("Oversight came without training:", "training in rational prescribing is lacking in and after medical school; audit pressure turned the prescription into a tool of self-defence."),
    ("No transparent, trusted licensing:", "a drug licensing system the public can trust was never built; licensing processes remain disputed."),
    ("The reimbursement problem:", "the drug industry can indirectly influence reimbursement policy; expensive drugs of debatable clinical value entered the lists."),
    ("Polypharmacy grew, no deprescribing:", "new drugs are added while unnecessary old ones are not stopped; older people are at risk."),
    ("Public expectations did not change:", "leaving without a prescription is seen as a failing, and consultations are short."),
    ("Weak laboratory infrastructure:", "non-accredited, non-standardised tests prepare the ground for irrational drug use.")],
   "Rational drug use has been reduced to a bureaucratic showcase."),
 'de': D("RATIONALER ARZNEIMITTELEINSATZ", "Warum blieb der rationale Arzneimitteleinsatz auf dem Papier?", "In der Türkei hat sich die Politik vom WHO-Modell entfernt und ist bürokratisch geworden", None, None,
   [("Kontrolle statt Ausbildung:", "Schulung im rationalen Verordnen fehlt im Medizinstudium und danach; der Prüfdruck machte das Rezept zu einem Mittel der Selbstverteidigung."),
    ("Keine transparente, verlässliche Zulassung:", "ein Zulassungssystem, dem die Öffentlichkeit vertrauen kann, wurde nie aufgebaut; die Verfahren sind umstritten."),
    ("Das Erstattungsproblem:", "die Pharmaindustrie kann die Erstattungspolitik indirekt beeinflussen; teure Arzneimittel mit fraglichem klinischem Wert kamen auf die Listen."),
    ("Mehr Polypharmazie, kein Deprescribing:", "neue Arzneimittel kommen hinzu, unnötige alte werden nicht abgesetzt; ältere Menschen sind gefährdet."),
    ("Erwartungen der Bevölkerung unverändert:", "ohne Rezept zu gehen gilt als Mangel, und die Untersuchungszeiten sind kurz."),
    ("Schwache Laborinfrastruktur:", "nicht akkreditierte, nicht standardisierte Tests bereiten den Boden für irrationalen Arzneimitteleinsatz.")],
   "Der rationale Arzneimitteleinsatz wurde auf ein bürokratisches Schaufenster reduziert."),
 'es': D("USO RACIONAL DE MEDICAMENTOS", "¿Por qué el uso racional de medicamentos se quedó en el papel?", "En Turquía, la política se apartó del modelo de la OMS y se volvió burocrática", None, None,
   [("Control sin formación:", "falta formación en prescripción racional en la facultad de medicina y después; la presión de las inspecciones convirtió la receta en una herramienta de defensa."),
    ("Sin un registro transparente y fiable:", "nunca se creó un sistema de autorización de medicamentos en el que la sociedad pueda confiar; los procesos siguen siendo discutidos."),
    ("El problema del reembolso:", "la industria farmacéutica puede influir indirectamente en la política de reembolso; entraron en las listas fármacos caros de valor clínico discutible."),
    ("Más polifarmacia, sin deprescripción:", "se añaden fármacos nuevos y no se retiran los antiguos innecesarios; las personas mayores están en riesgo."),
    ("Las expectativas del público no cambiaron:", "salir sin receta se ve como una carencia y las consultas son breves."),
    ("Infraestructura de laboratorio débil:", "pruebas no acreditadas ni estandarizadas preparan el terreno para el uso irracional de medicamentos.")],
   "El uso racional de medicamentos ha quedado reducido a un escaparate burocrático."),
 'ru': D("РАЦИОНАЛЬНОЕ ПРИМЕНЕНИЕ ЛЕКАРСТВ", "Почему рациональное применение лекарств осталось на бумаге?", "В Турции эта политика отошла от модели ВОЗ и стала бюрократической", None, None,
   [("Контроль без обучения:", "обучения рациональному назначению не хватает в медицинском вузе и после него; давление проверок превратило рецепт в средство самозащиты."),
    ("Нет прозрачной и надёжной регистрации:", "система регистрации лекарств, которой общество могло бы доверять, не создана; процедуры остаются спорными."),
    ("Проблема возмещения:", "фармацевтическая индустрия может косвенно влиять на политику возмещения; в списки попали дорогие препараты со спорной клинической ценностью."),
    ("Полипрагмазия выросла, депрескрайбинга нет:", "новые лекарства добавляются, ненужные старые не отменяются; пожилые люди под угрозой."),
    ("Ожидания населения не изменились:", "уйти без рецепта считается недостатком, а время приёма короткое."),
    ("Слабая лабораторная база:", "неаккредитованные, нестандартизированные тесты создают почву для нерационального применения лекарств.")],
   "Рациональное применение лекарств сведено к бюрократической витрине."),
 'zh': D("合理用药", "合理用药为何停留在纸面上？", "在土耳其，合理用药政策偏离了世界卫生组织的模式，变得官僚化", None, None,
   [("只有监管，没有培训：", "医学院在校期间和毕业后都缺乏合理处方培训；监管压力使处方变成了“自我保护”的工具。"),
    ("缺乏透明可信的药品审批：", "始终没有建立起公众可以信赖的药品审批制度，审批过程仍有争议。"),
    ("医保报销问题：", "制药业可以间接影响报销政策；临床价值存在争议的昂贵药物进入了报销目录。"),
    ("多重用药增加，没有“减停处方”：", "新药不断加上，不必要的旧药却没有停用；老年人面临风险。"),
    ("公众的用药期待没有改变：", "看病没开药被视为欠缺，而且就诊时间很短。"),
    ("实验室基础薄弱：", "未经认证、未标准化的检验为不合理用药埋下了隐患。")],
   "合理用药已沦为一个“官僚橱窗”。"),
 'hi': D("दवाओं का तर्कसंगत उपयोग", "दवाओं का तर्कसंगत उपयोग कागज़ पर ही क्यों रह गया?", "तुर्की में यह नीति WHO के मॉडल से भटककर नौकरशाही बन गई", None, None,
   [("प्रशिक्षण नहीं, निगरानी आई:", "मेडिकल कॉलेज में और उसके बाद तर्कसंगत प्रिस्क्रिप्शन का प्रशिक्षण कम है; जाँच के दबाव ने पर्चे को “बचाव” का साधन बना दिया।"),
    ("पारदर्शी और भरोसेमंद लाइसेंस प्रणाली नहीं:", "ऐसी दवा लाइसेंस प्रणाली नहीं बनी जिस पर जनता भरोसा कर सके; प्रक्रियाएँ विवादित हैं।"),
    ("प्रतिपूर्ति की समस्या:", "दवा उद्योग प्रतिपूर्ति नीतियों को परोक्ष रूप से प्रभावित कर सकता है; विवादित नैदानिक मूल्य वाली महँगी दवाएँ सूचियों में आ गईं।"),
    ("पॉलीफार्मेसी बढ़ी, डीप्रिस्क्राइबिंग नहीं:", "नई दवाएँ जुड़ती हैं पर अनावश्यक पुरानी दवाएँ बंद नहीं होतीं; बुज़ुर्ग जोखिम में हैं।"),
    ("जनता की अपेक्षा नहीं बदली:", "बिना पर्चे के लौटना कमी माना जाता है और जाँच का समय कम है।"),
    ("कमज़ोर प्रयोगशाला ढाँचा:", "बिना मान्यता वाले, गैर-मानकीकृत परीक्षण दवाओं के अतार्किक उपयोग की ज़मीन तैयार करते हैं।")],
   "दवाओं का तर्कसंगत उपयोग एक “नौकरशाही शोकेस” बनकर रह गया है।"),
 'ja': D("医薬品の適正使用", "医薬品の適正使用はなぜ紙の上にとどまったのか", "トルコの適正使用政策はWHOのモデルから外れ、官僚化した", None, None,
   [("教育はなく、監査が来た：", "医学部でも卒後でも適正処方の教育が不足し、監査の圧力によって処方箋は「自己防衛」の手段になった。"),
    ("透明で信頼できる承認制度がない：", "社会が信頼できる医薬品承認制度は築かれず、承認の過程には議論が残っている。"),
    ("保険償還の問題：", "製薬産業は償還政策に間接的に影響を与えうる。臨床的価値に議論のある高額な薬が償還リストに入った。"),
    ("多剤併用が増え、減薬がない：", "新しい薬が追加される一方、不要な古い薬は中止されず、高齢者が危険にさらされている。"),
    ("国民の薬への期待は変わらなかった：", "処方なしで帰ることは不足とみなされ、診察時間は短い。"),
    ("検査体制が弱い：", "認定も標準化もされていない検査が、不適正な薬の使用の下地になっている。")],
   "医薬品の適正使用は「官僚的なショーウィンドウ」に成り下がった。"),
})

# i=12: Migraine book cover (EN image = twin from the English article)
CARDS['b14_migren'] = ('blue', {
 'de': D("PROF. DR. F. CANKAT TULUNAY", "Diagnose und Behandlung von Migräneattacken", "„Nicht jeder halbseitige Kopfschmerz ist eine Migräne, und nicht jede Migräne ist ein halbseitiger Kopfschmerz.“"),
 'es': D("PROF. DR. F. CANKAT TULUNAY", "Diagnóstico y tratamiento de las crisis de migraña", "«No todo dolor de cabeza unilateral es migraña, ni toda migraña es un dolor de cabeza unilateral.»"),
 'ru': D("ПРОФ. Д-Р Ф. ДЖАНКАТ ТУЛУНАЙ", "Диагностика и лечение приступов мигрени", "«Не всякая односторонняя головная боль является мигренью, и не всякая мигрень является односторонней головной болью.»"),
 'zh': D("F. CANKAT TULUNAY 教授", "偏头痛发作的诊断与治疗", "“并非每一次单侧头痛都是偏头痛，也并非每一次偏头痛都是单侧头痛。”"),
 'hi': D("प्रो. डॉ. एफ. जानकात तुलुनाय", "माइग्रेन के दौरों का निदान और उपचार", "“हर आधे सिर का दर्द माइग्रेन नहीं होता, और हर माइग्रेन आधे सिर का दर्द नहीं होता।”"),
 'ja': D("F. CANKAT TULUNAY 教授", "片頭痛発作の診断と治療", "「片側の頭痛がすべて片頭痛とは限らず、片頭痛がすべて片側の頭痛とも限らない」"),
})

# i=13: Tulunay primary headache diagnostic form (EN image = twin)
CARDS['b14_basform'] = ('dark', {
 'de': D("PRIMÄRE KOPFSCHMERZEN", "Tulunay-Diagnosebogen für primäre Kopfschmerzen", "Strukturierter Anamnesebogen für Hausärzte"),
 'es': D("CEFALEAS PRIMARIAS", "Formulario diagnóstico Tulunay de cefaleas primarias", "Formulario estructurado de anamnesis para médicos de atención primaria"),
 'ru': D("ПЕРВИЧНЫЕ ГОЛОВНЫЕ БОЛИ", "Диагностическая форма Тулуная для первичных головных болей", "Структурированная форма сбора анамнеза для врачей первичного звена"),
 'zh': D("原发性头痛", "Tulunay 原发性头痛诊断表", "供基层医生使用的结构化病史采集表"),
 'hi': D("प्राथमिक सिरदर्द", "तुलुनाय प्राथमिक सिरदर्द निदान प्रपत्र", "प्राथमिक देखभाल के चिकित्सकों के लिए संरचित रोग-इतिहास प्रपत्र"),
 'ja': D("一次性頭痛", "Tulunay 一次性頭痛診断フォーム", "プライマリ・ケア医のための構造化問診票"),
})

# i=15: What I did for rational drug use
CARDS['b14_neyaptim'] = ('burg', {
 'en': D("PROF. DR. CANKAT TULUNAY", "What I did for rational drug use", "A struggle for rational drug use that began in Turkey in the late 1970s", None, None,
   [("WHO essential drugs list:", "translated into Turkish and published in Turkey for the first time in 1978."),
    ("\"Waste of drugs in Turkey\" (1979):", "a field study with medical students at Ankara University on unused drugs kept in homes."),
    ("Milliyet, 23 April 1979:", "\"Turkey is a drug dump. There are 8,000 kinds of drugs on the market.\" 400 to 500 essential drugs are enough."),
    ("Cumhuriyet, 15 October 1978:", "\"Allowing wealth to be transferred at the expense of public health is against a scientist's honour.\""),
    ("The \"five rights\":", "right diagnosis, right drug, right patient, right dose and duration, right cost.")],
   "Science wins, but it takes time."),
 'de': D("PROF. DR. CANKAT TULUNAY", "Was ich für den rationalen Arzneimitteleinsatz getan habe", "Ein Kampf für rationalen Arzneimitteleinsatz, der in der Türkei Ende der 1970er-Jahre begann", None, None,
   [("WHO-Liste der unentbehrlichen Arzneimittel:", "1978 erstmals ins Türkische übersetzt und in der Türkei veröffentlicht."),
    ("„Waste of drugs in Turkey“ (1979):", "eine Feldstudie mit Medizinstudierenden der Universität Ankara über ungenutzte Arzneimittel in den Haushalten."),
    ("Milliyet, 23. April 1979:", "„Die Türkei ist eine Arzneimittelmüllhalde. Auf dem Markt gibt es 8000 Arzneimittel.“ 400 bis 500 unentbehrliche Arzneimittel genügen."),
    ("Cumhuriyet, 15. Oktober 1978:", "„Einen Vermögenstransfer auf Kosten der Gesundheit der Bevölkerung zuzulassen, widerspricht der Ehre eines Wissenschaftlers.“"),
    ("Die „fünf Richtigen“:", "richtige Diagnose, richtiges Arzneimittel, richtiger Patient, richtige Dosis und Dauer, richtige Kosten.")],
   "Die Wissenschaft gewinnt, aber es braucht Zeit."),
 'es': D("PROF. DR. CANKAT TULUNAY", "Lo que hice por el uso racional de medicamentos", "Una lucha por el uso racional de medicamentos que comenzó en Turquía a finales de los años setenta", None, None,
   [("Lista de medicamentos esenciales de la OMS:", "traducida al turco y publicada en Turquía por primera vez en 1978."),
    ("«Waste of drugs in Turkey» (1979):", "un estudio de campo con estudiantes de medicina de la Universidad de Ankara sobre los medicamentos sin usar guardados en los hogares."),
    ("Milliyet, 23 de abril de 1979:", "«Turquía es un vertedero de medicamentos. Hay 8000 tipos de medicamentos en el mercado.» Bastan entre 400 y 500 medicamentos esenciales."),
    ("Cumhuriyet, 15 de octubre de 1978:", "«Permitir una transferencia de riqueza a costa de la salud del pueblo es contrario al honor de un científico.»"),
    ("Los «cinco correctos»:", "diagnóstico correcto, medicamento correcto, paciente correcto, dosis y duración correctas, coste correcto.")],
   "La ciencia gana, pero lleva tiempo."),
 'ru': D("ПРОФ. Д-Р ДЖАНКАТ ТУЛУНАЙ", "Что я сделал для рационального применения лекарств", "Борьба за рациональное применение лекарств, начавшаяся в Турции в конце 1970-х годов", None, None,
   [("Перечень основных лекарственных средств ВОЗ:", "в 1978 году впервые переведён на турецкий язык и опубликован в Турции."),
    ("«Waste of drugs in Turkey» (1979):", "полевое исследование со студентами-медиками Анкарского университета о неиспользованных лекарствах в домах."),
    ("Milliyet, 23 апреля 1979 года:", "«Турция является лекарственной свалкой. На рынке 8000 наименований лекарств». Достаточно 400–500 основных лекарств."),
    ("Cumhuriyet, 15 октября 1978 года:", "«Позволять перекачивать богатство за счёт здоровья народа противоречит чести учёного»."),
    ("«Пять правильных»:", "правильный диагноз, правильное лекарство, правильный пациент, правильные доза и длительность, правильная стоимость.")],
   "Наука побеждает, но на это нужно время."),
 'zh': D("CANKAT TULUNAY 教授", "我为合理用药做了什么", "一场始于20世纪70年代末土耳其的合理用药斗争", None, None,
   [("世界卫生组织基本药物目录：", "1978年首次译成土耳其语并在土耳其发表。"),
    ("《Waste of drugs in Turkey》（1979年）：", "与安卡拉大学医学院学生一起开展的实地调查，研究家中闲置不用的药品。"),
    ("《Milliyet》，1979年4月23日：", "“土耳其是一个药品垃圾场。市场上有8000种药。”400至500种基本药物就足够了。"),
    ("《Cumhuriyet》，1978年10月15日：", "“容许借民众的健康转移财富，有违科学家的操守。”"),
    ("“五个正确”：", "正确的诊断、正确的药物、正确的患者、正确的剂量和疗程、正确的费用。")],
   "科学终会获胜，但需要时间。"),
 'hi': D("प्रो. डॉ. जानकात तुलुनाय", "दवाओं के तर्कसंगत उपयोग के लिए मैंने क्या किया", "दवाओं के तर्कसंगत उपयोग का संघर्ष, जो तुर्की में 1970 के दशक के अंत में शुरू हुआ", None, None,
   [("WHO की आवश्यक दवाओं की सूची:", "1978 में पहली बार तुर्की भाषा में अनूदित होकर तुर्की में प्रकाशित हुई।"),
    ("“Waste of drugs in Turkey” (1979):", "अंकारा विश्वविद्यालय के मेडिकल छात्रों के साथ घरों में पड़ी अप्रयुक्त दवाओं पर किया गया क्षेत्रीय अध्ययन।"),
    ("Milliyet, 23 अप्रैल 1979:", "“तुर्की दवाओं का कूड़ाघर है। बाज़ार में 8000 तरह की दवाएँ हैं।” 400 से 500 आवश्यक दवाएँ पर्याप्त हैं।"),
    ("Cumhuriyet, 15 अक्टूबर 1978:", "“जनता के स्वास्थ्य की कीमत पर धन के हस्तांतरण की अनुमति देना एक वैज्ञानिक के सम्मान के विरुद्ध है।”"),
    ("“पाँच सही”:", "सही निदान, सही दवा, सही रोगी, सही खुराक और अवधि, सही लागत।")],
   "विज्ञान जीतता है, पर इसमें समय लगता है।"),
 'ja': D("CANKAT TULUNAY 教授", "医薬品の適正使用のために私がしたこと", "1970年代末のトルコで始まった、医薬品の適正使用を求める闘い", None, None,
   [("WHO必須医薬品リスト：", "1978年に初めてトルコ語に翻訳され、トルコで発表された。"),
    ("「Waste of drugs in Turkey」（1979年）：", "アンカラ大学医学部の学生とともに、家庭に眠る未使用の薬を調べた現地調査。"),
    ("Milliyet紙、1979年4月23日：", "「トルコは薬のごみ捨て場だ。市場には8000種類の薬がある」。必須医薬品は400から500で足りる。"),
    ("Cumhuriyet紙、1978年10月15日：", "「国民の健康を利用した富の移転を許すことは、科学者の名誉に反する」"),
    ("「5つの正しさ」：", "正しい診断、正しい薬、正しい患者、正しい用量と期間、正しい費用。")],
   "科学は勝つ。ただし時間がかかる。"),
})

# i=17: World map of metamizole use (paired English article has a different picture, so EN is written here)
CARDS['b14_metamap'] = ('navy', {
 'en': D("METAMIZOLE (NOVALGIN)", "Metamizole (Novalgin) use around the world", "Map legend: blue countries use it, red countries do not, orange countries allow limited use", None, None,
   [("Sweden:", "banned in 1974 after a limited number of agranulocytosis case reports; Finland and Norway also restricted it severely."),
    ("Germany and Switzerland:", "0.6 to 1.0 cases per million person-years; controlled use instead of a ban."),
    ("Bulgaria:", "high consumption, with a maximum attributable risk of 0.2 to 0.5 cases per million person-years."),
    ("Latin America:", "among the regions of widest use; low agranulocytosis incidence in Mexico, Argentina and Brazil."),
    ("Turkey:", "widely used for many years; very few reported cases, but reliable national data are limited.")],
   "In most studies the absolute risk of agranulocytosis is 0.2 to 1.0 cases per million person-years."),
 'de': D("METAMIZOL (NOVALGIN)", "Metamizol (Novalgin) weltweit", "Kartenlegende: blaue Länder verwenden es, rote nicht, orangefarbene erlauben eine eingeschränkte Anwendung", None, None,
   [("Schweden:", "1974 nach einer begrenzten Zahl von Agranulozytose-Fallberichten verboten; auch Finnland und Norwegen schränkten es stark ein."),
    ("Deutschland und Schweiz:", "0,6 bis 1,0 Fälle pro Million Personenjahre; kontrollierte Anwendung statt Verbot."),
    ("Bulgarien:", "hoher Verbrauch, maximal zurechenbares Risiko 0,2 bis 0,5 Fälle pro Million Personenjahre."),
    ("Lateinamerika:", "eine der Regionen mit der breitesten Anwendung; niedrige Agranulozytose-Inzidenz in Mexiko, Argentinien und Brasilien."),
    ("Türkei:", "seit vielen Jahren weit verbreitet; sehr wenige gemeldete Fälle, aber verlässliche nationale Daten sind begrenzt.")],
   "In den meisten Studien liegt das absolute Agranulozytose-Risiko bei 0,2 bis 1,0 Fällen pro Million Personenjahre."),
 'es': D("METAMIZOL (NOVALGIN)", "Uso del metamizol (Novalgin) en el mundo", "Leyenda del mapa: los países en azul lo usan, los rojos no, los naranjas permiten un uso limitado", None, None,
   [("Suecia:", "prohibido en 1974 tras un número limitado de notificaciones de casos de agranulocitosis; Finlandia y Noruega también lo restringieron mucho."),
    ("Alemania y Suiza:", "de 0,6 a 1,0 casos por millón de personas-año; uso controlado en lugar de prohibición."),
    ("Bulgaria:", "consumo elevado, con un riesgo máximo atribuible de 0,2 a 0,5 casos por millón de personas-año."),
    ("América Latina:", "una de las regiones donde más se usa; baja incidencia de agranulocitosis en México, Argentina y Brasil."),
    ("Turquía:", "uso extendido desde hace muchos años; muy pocos casos notificados, pero los datos nacionales fiables son limitados.")],
   "En la mayoría de los estudios, el riesgo absoluto de agranulocitosis es de 0,2 a 1,0 casos por millón de personas-año."),
 'ru': D("МЕТАМИЗОЛ (NOVALGIN)", "Применение метамизола (Novalgin) в мире", "Легенда карты: синие страны применяют, красные не применяют, оранжевые допускают ограниченное применение", None, None,
   [("Швеция:", "запрещён в 1974 году после ограниченного числа сообщений о случаях агранулоцитоза; Финляндия и Норвегия также резко ограничили его применение."),
    ("Германия и Швейцария:", "0,6–1,0 случая на миллион человеко-лет; контролируемое применение вместо запрета."),
    ("Болгария:", "высокое потребление, максимальный приписываемый риск 0,2–0,5 случая на миллион человеко-лет."),
    ("Латинская Америка:", "один из регионов самого широкого применения; низкая заболеваемость агранулоцитозом в Мексике, Аргентине и Бразилии."),
    ("Турция:", "широко применяется много лет; зарегистрированных случаев очень мало, но надёжные национальные данные ограничены.")],
   "В большинстве исследований абсолютный риск агранулоцитоза составляет 0,2–1,0 случая на миллион человеко-лет."),
 'zh': D("安乃近（NOVALGIN）", "安乃近（Novalgin）在世界各国的使用情况", "地图图例：蓝色国家使用，红色国家不使用，橙色国家限制使用", None, None,
   [("瑞典：", "在出现数量有限的粒细胞缺乏症病例报告后，于1974年禁用；芬兰和挪威也严格限制使用。"),
    ("德国和瑞士：", "每百万人年0.6至1.0例；采取控制使用而非禁用。"),
    ("保加利亚：", "用量很大，可归因的最大风险为每百万人年0.2至0.5例。"),
    ("拉丁美洲：", "使用最广泛的地区之一；墨西哥、阿根廷和巴西的粒细胞缺乏症发病率较低。"),
    ("土耳其：", "多年来广泛使用；报告病例极少，但可靠的全国性数据有限。")],
   "在多数研究中，粒细胞缺乏症的绝对风险为每百万人年0.2至1.0例。"),
 'hi': D("मेटामिज़ोल (NOVALGIN)", "दुनिया में मेटामिज़ोल (Novalgin) का उपयोग", "मानचित्र संकेत: नीले देश इसका उपयोग करते हैं, लाल नहीं करते, नारंगी देशों में सीमित उपयोग है", None, None,
   [("स्वीडन:", "एग्रैनुलोसाइटोसिस के सीमित मामलों की रिपोर्टों के बाद 1974 में प्रतिबंधित; फ़िनलैंड और नॉर्वे ने भी इसे कड़ाई से सीमित किया।"),
    ("जर्मनी और स्विट्ज़रलैंड:", "प्रति दस लाख व्यक्ति-वर्ष 0.6 से 1.0 मामले; प्रतिबंध के बजाय नियंत्रित उपयोग।"),
    ("बुल्गारिया:", "खपत अधिक, अधिकतम संभावित जोखिम प्रति दस लाख व्यक्ति-वर्ष 0.2 से 0.5 मामले।"),
    ("लैटिन अमेरिका:", "सबसे व्यापक उपयोग वाले क्षेत्रों में से एक; मेक्सिको, अर्जेंटीना और ब्राज़ील में एग्रैनुलोसाइटोसिस की घटना दर कम।"),
    ("तुर्की:", "कई वर्षों से व्यापक उपयोग; दर्ज मामले बहुत कम, पर विश्वसनीय राष्ट्रीय आँकड़े सीमित हैं।")],
   "अधिकांश अध्ययनों में एग्रैनुलोसाइटोसिस का निरपेक्ष जोखिम प्रति दस लाख व्यक्ति-वर्ष 0.2 से 1.0 मामले है।"),
 'ja': D("メタミゾール（NOVALGIN）", "世界におけるメタミゾール（Novalgin）の使用状況", "地図の凡例：青の国は使用、赤の国は不使用、オレンジの国は限定的に使用", None, None,
   [("スウェーデン：", "限られた数の無顆粒球症の症例報告を受けて1974年に禁止。フィンランドとノルウェーも厳しく制限した。"),
    ("ドイツとスイス：", "100万人年あたり0.6から1.0例。禁止ではなく管理下での使用。"),
    ("ブルガリア：", "消費量は多いが、帰属しうる最大リスクは100万人年あたり0.2から0.5例。"),
    ("ラテンアメリカ：", "最も広く使われている地域の一つ。メキシコ、アルゼンチン、ブラジルでは無顆粒球症の発生率は低い。"),
    ("トルコ：", "長年にわたり広く使用。報告例はごく少ないが、信頼できる全国データは限られている。")],
   "多くの研究で、無顆粒球症の絶対リスクは100万人年あたり0.2から1.0例である。"),
})

# i=18: Cocaine in hair
CARDS['b14_sackokain'] = ('purple', {
 'en': D("FORENSIC TOXICOLOGY", "Cocaine in hair: the scientific and forensic side", "A metabolite found in hair is not, on its own, proof of use", None, None,
   [("Sample types:", "blood and urine show acute or recent exposure; hair shows roughly the past 1 to 2 months; nails show longer-term exposure."),
    ("Gold standard:", "confirmation by LC-MS/MS, Orbitrap or GC/MS. The amount (pg/mg) must be reported."),
    ("False-positive risks:", "environmental contamination, insufficient washing of the sample, cosmetic factors such as dye, bleach and perms."),
    ("Evidence of active use:", "the metabolite (benzoylecgonine), wash fluid analysis and SoHT cut-off values. Positive hair with negative blood and urine seriously weakens the likelihood of active or recent use."),
    ("Accreditation:", "a result from a laboratory without ISO/IEC 17025 accreditation can easily be refuted in court.")],
   "Nobody should be exposed to the public until drug use has been scientifically proven."),
 'de': D("FORENSISCHE TOXIKOLOGIE", "Kokain im Haar: die wissenschaftliche und forensische Seite", "Ein Metabolit im Haar ist für sich allein kein Beweis für Konsum", None, None,
   [("Probenarten:", "Blut und Urin zeigen akute oder kürzliche Exposition; Haare etwa die letzten 1 bis 2 Monate; Nägel eine längerfristige Exposition."),
    ("Goldstandard:", "Bestätigung mit LC-MS/MS, Orbitrap oder GC/MS. Die Menge (pg/mg) muss angegeben werden."),
    ("Risiken für falsch positive Befunde:", "Kontamination aus der Umgebung, unzureichendes Waschen der Probe, kosmetische Faktoren wie Färben, Bleichen und Dauerwelle."),
    ("Nachweis aktiven Konsums:", "der Metabolit (Benzoylecgonin), die Analyse der Waschflüssigkeit und die SoHT-Cut-off-Werte. Positives Haar bei negativem Blut und Urin schwächt die Wahrscheinlichkeit eines aktiven oder kürzlichen Konsums erheblich."),
    ("Akkreditierung:", "das Ergebnis eines Labors ohne Akkreditierung nach ISO/IEC 17025 lässt sich vor Gericht leicht widerlegen.")],
   "Niemand sollte öffentlich bloßgestellt werden, bevor der Drogenkonsum wissenschaftlich bewiesen ist."),
 'es': D("TOXICOLOGÍA FORENSE", "Cocaína en el cabello: la dimensión científica y forense", "Un metabolito hallado en el cabello no es, por sí solo, prueba de consumo", None, None,
   [("Tipos de muestra:", "la sangre y la orina indican exposición aguda o reciente; el cabello, aproximadamente los últimos 1 a 2 meses; las uñas, una exposición más prolongada."),
    ("Patrón de referencia:", "confirmación por LC-MS/MS, Orbitrap o GC/MS. Es obligatorio indicar la cantidad (pg/mg)."),
    ("Riesgos de falso positivo:", "contaminación ambiental, lavado insuficiente de la muestra, factores cosméticos como tintes, decolorantes y permanentes."),
    ("Prueba de consumo activo:", "el metabolito (benzoilecgonina), el análisis del líquido de lavado y los valores de corte de la SoHT. Cabello positivo con sangre y orina negativas debilita seriamente la probabilidad de consumo activo o reciente."),
    ("Acreditación:", "el resultado de un laboratorio sin acreditación ISO/IEC 17025 puede refutarse fácilmente ante un tribunal.")],
   "Nadie debería ser expuesto ante la opinión pública hasta que el consumo de drogas esté científicamente probado."),
 'ru': D("СУДЕБНАЯ ТОКСИКОЛОГИЯ", "Кокаин в волосах: научная и судебная сторона", "Метаболит, найденный в волосах, сам по себе не доказывает употребление", None, None,
   [("Виды образцов:", "кровь и моча показывают острое или недавнее воздействие; волосы показывают примерно последние 1–2 месяца; ногти показывают более длительное воздействие."),
    ("Золотой стандарт:", "подтверждение методами LC-MS/MS, Orbitrap или GC/MS. Количество (пг/мг) должно быть указано обязательно."),
    ("Риски ложноположительного результата:", "загрязнение из окружающей среды, недостаточная отмывка образца, косметические факторы: окрашивание, осветление, химическая завивка."),
    ("Доказательства активного употребления:", "метаболит (бензоилэкгонин), анализ промывной жидкости и пороговые значения SoHT. Положительные волосы при отрицательных крови и моче серьёзно снижают вероятность активного или недавнего употребления."),
    ("Аккредитация:", "результат лаборатории без аккредитации по ISO/IEC 17025 легко опровергнуть в суде.")],
   "Никого не следует выставлять перед общественностью, пока употребление наркотиков не доказано научно."),
 'zh': D("法医毒理学", "毛发中的可卡因：科学与法医层面", "毛发中检出代谢物，本身并不能证明吸食", None, None,
   [("检材类型：", "血液和尿液反映急性或近期暴露；毛发反映过去约1至2个月；指甲反映更长期的暴露。"),
    ("金标准：", "用LC-MS/MS、Orbitrap或GC/MS进行确证。必须报告含量（pg/mg）。"),
    ("假阳性风险：", "环境污染、检材清洗不充分，以及染发、漂白、烫发等美发因素。"),
    ("主动吸食的证据：", "代谢物（苯甲酰爱康宁）、洗涤液分析和SoHT阈值。毛发阳性而血液和尿液阴性，会大大削弱主动或近期吸食的可能性。"),
    ("实验室认可：", "未获ISO/IEC 17025认可的实验室所出的结果，在法庭上很容易被推翻。")],
   "在吸毒未经科学证实之前，任何人都不应被公开曝光。"),
 'hi': D("फ़ोरेंसिक विष विज्ञान", "बालों में कोकीन: वैज्ञानिक और फ़ोरेंसिक पहलू", "बालों में मेटाबोलाइट मिलना अपने आप में सेवन का प्रमाण नहीं है", None, None,
   [("नमूनों के प्रकार:", "रक्त और मूत्र तीव्र या हाल का संपर्क दिखाते हैं; बाल लगभग पिछले 1 से 2 महीने; नाखून लंबी अवधि का संपर्क।"),
    ("स्वर्ण मानक:", "LC-MS/MS, Orbitrap या GC/MS से पुष्टि। मात्रा (pg/mg) बताना अनिवार्य है।"),
    ("झूठे पॉज़िटिव के जोखिम:", "पर्यावरणीय संदूषण, नमूने की अपर्याप्त धुलाई, और रंगाई, ब्लीच तथा पर्म जैसे कॉस्मेटिक कारक।"),
    ("सक्रिय सेवन का प्रमाण:", "मेटाबोलाइट (बेंज़ोइलेक्गोनिन), धुलाई द्रव का विश्लेषण और SoHT के कट-ऑफ़ मान। बाल पॉज़िटिव और रक्त व मूत्र नेगेटिव हों तो सक्रिय या हाल के सेवन की संभावना बहुत कमज़ोर हो जाती है।"),
    ("मान्यता:", "ISO/IEC 17025 मान्यता के बिना प्रयोगशाला का परिणाम अदालत में आसानी से खारिज किया जा सकता है।")],
   "जब तक नशीले पदार्थ का सेवन वैज्ञानिक रूप से सिद्ध न हो, किसी को भी जनता के सामने उजागर नहीं किया जाना चाहिए।"),
 'ja': D("法中毒学", "毛髪中のコカイン：科学的・法医学的側面", "毛髪から代謝物が検出されても、それだけでは使用の証拠にならない", None, None,
   [("試料の種類：", "血液と尿は急性または最近の曝露を、毛髪は過去およそ1から2か月を、爪はより長期の曝露を示す。"),
    ("ゴールドスタンダード：", "LC-MS/MS、OrbitrapまたはGC/MSによる確認。量（pg/mg）の記載は必須である。"),
    ("偽陽性のリスク：", "環境からの汚染、試料の洗浄不足、染毛・脱色・パーマなどの美容的要因。"),
    ("能動的使用の証拠：", "代謝物（ベンゾイルエクゴニン）、洗浄液の分析、SoHTのカットオフ値。毛髪が陽性でも血液と尿が陰性なら、能動的または最近の使用の可能性は大きく弱まる。"),
    ("認定：", "ISO/IEC 17025の認定を受けていない検査機関の結果は、法廷で容易に覆されうる。")],
   "薬物使用が科学的に証明されるまでは、誰も世間にさらされるべきではない。"),
})

# i=19: Journavx (suzetrigine)
CARDS['b14_journavx'] = ('teal', {
 'en': D("NON-OPIOID ANALGESIC", "JOURNAVX (suzetrigine)", "A new-generation non-opioid painkiller that stops pain at its source",
   [("NaV1.8", "Target: sodium channels in peripheral nerves"), ("FDA", "Approved on 30 January 2025"), ("Oral", "Tablet for acute moderate to severe pain")], None,
   [("Peripheral action:", "it blocks the NaV1.8 sodium channels that carry the pain signal and stops pain at its source."),
    ("It does not reach the brain:", "no addiction, no drowsiness, no effect on the reward centre."),
    ("JOURNAVX:", "addiction risk none; side effects mild (nausea, headache); no respiratory depression."),
    ("Opioids (e.g. morphine):", "target the central nervous system; addiction risk high; side effects serious (drowsiness, constipation); respiratory depression present, a risk to life.")],
   "Not stronger than opioids, but similar in strength and much safer."),
 'de': D("NICHT-OPIOID-ANALGETIKUM", "JOURNAVX (Suzetrigin)", "Ein Nicht-Opioid-Schmerzmittel der neuen Generation, das den Schmerz an der Quelle stoppt",
   [("NaV1.8", "Ziel: Natriumkanäle in peripheren Nerven"), ("FDA", "Zulassung am 30. Januar 2025"), ("Oral", "Tablette bei akuten mäßigen bis starken Schmerzen")], None,
   [("Periphere Wirkung:", "es blockiert die NaV1.8-Natriumkanäle, die das Schmerzsignal leiten, und stoppt den Schmerz an der Quelle."),
    ("Es erreicht das Gehirn nicht:", "keine Abhängigkeit, keine Benommenheit, keine Wirkung auf das Belohnungszentrum."),
    ("JOURNAVX:", "kein Abhängigkeitsrisiko; leichte Nebenwirkungen (Übelkeit, Kopfschmerzen); keine Atemdepression."),
    ("Opioide (z. B. Morphin):", "Ziel ist das zentrale Nervensystem; hohes Abhängigkeitsrisiko; schwere Nebenwirkungen (Benommenheit, Verstopfung); Atemdepression möglich, mit Lebensgefahr.")],
   "Nicht stärker als Opioide, aber ähnlich stark und deutlich sicherer."),
 'es': D("ANALGÉSICO NO OPIOIDE", "JOURNAVX (suzetrigina)", "Un analgésico no opioide de nueva generación que detiene el dolor en su origen",
   [("NaV1.8", "Diana: canales de sodio de los nervios periféricos"), ("FDA", "Aprobado el 30 de enero de 2025"), ("Oral", "Comprimido para el dolor agudo moderado o intenso")], None,
   [("Acción periférica:", "bloquea los canales de sodio NaV1.8 que transmiten la señal de dolor y detiene el dolor en su origen."),
    ("No llega al cerebro:", "no produce adicción ni aturdimiento y no afecta al centro de recompensa."),
    ("JOURNAVX:", "sin riesgo de adicción; efectos adversos leves (náuseas, cefalea); sin depresión respiratoria."),
    ("Opioides (p. ej., morfina):", "actúan sobre el sistema nervioso central; riesgo alto de adicción; efectos adversos graves (aturdimiento, estreñimiento); hay depresión respiratoria, con riesgo vital.")],
   "No es más potente que los opioides, pero tiene una potencia similar y es mucho más seguro."),
 'ru': D("НЕОПИОИДНЫЙ АНАЛЬГЕТИК", "JOURNAVX (сузетригин)", "Неопиоидное обезболивающее нового поколения, которое останавливает боль в её источнике",
   [("NaV1.8", "Мишень: натриевые каналы периферических нервов"), ("FDA", "Одобрен 30 января 2025 года"), ("Внутрь", "Таблетки при острой умеренной и сильной боли")], None,
   [("Периферическое действие:", "блокирует натриевые каналы NaV1.8, проводящие болевой сигнал, и останавливает боль в её источнике."),
    ("Не достигает мозга:", "не вызывает зависимости и оглушённости, не влияет на центр вознаграждения."),
    ("JOURNAVX:", "риска зависимости нет; побочные эффекты лёгкие (тошнота, головная боль); угнетения дыхания нет."),
    ("Опиоиды (например, морфин):", "мишень: центральная нервная система; высокий риск зависимости; серьёзные побочные эффекты (оглушённость, запор); есть угнетение дыхания, опасное для жизни.")],
   "Не сильнее опиоидов, но сопоставим по силе и намного безопаснее."),
 'zh': D("非阿片类镇痛药", "JOURNAVX（suzetrigine）", "在源头阻断疼痛的新一代非阿片类镇痛药",
   [("NaV1.8", "靶点：外周神经的钠通道"), ("FDA", "2025年1月30日获批"), ("口服", "片剂，用于急性中度至重度疼痛")], None,
   [("外周作用：", "阻断传导疼痛信号的NaV1.8钠通道，在源头止住疼痛。"),
    ("不进入大脑：", "不成瘾，不引起昏沉，不影响奖赏中枢。"),
    ("JOURNAVX：", "无成瘾风险；不良反应轻微（恶心、头痛）；无呼吸抑制。"),
    ("阿片类药物（如吗啡）：", "作用于中枢神经系统；成瘾风险高；不良反应严重（昏沉、便秘）；有呼吸抑制，可危及生命。")],
   "并不比阿片类药物更强，但强度相近，而且安全得多。"),
 'hi': D("गैर-ओपिओइड दर्द निवारक", "JOURNAVX (सुज़ेट्रिजीन)", "नई पीढ़ी की गैर-ओपिओइड दर्द निवारक दवा, जो दर्द को उसके स्रोत पर रोकती है",
   [("NaV1.8", "लक्ष्य: परिधीय तंत्रिकाओं के सोडियम चैनल"), ("FDA", "30 जनवरी 2025 को स्वीकृत"), ("मौखिक", "तीव्र, मध्यम से गंभीर दर्द के लिए गोली")], None,
   [("परिधीय प्रभाव:", "यह दर्द का संकेत ले जाने वाले NaV1.8 सोडियम चैनलों को अवरुद्ध करती है और दर्द को स्रोत पर रोकती है।"),
    ("मस्तिष्क तक नहीं पहुँचती:", "लत नहीं लगती, सुस्ती नहीं होती, रिवार्ड केंद्र पर असर नहीं पड़ता।"),
    ("JOURNAVX:", "लत का जोखिम नहीं; दुष्प्रभाव हल्के (मतली, सिरदर्द); श्वसन अवसाद नहीं।"),
    ("ओपिओइड (जैसे मॉर्फ़ीन):", "लक्ष्य केंद्रीय तंत्रिका तंत्र; लत का जोखिम अधिक; दुष्प्रभाव गंभीर (सुस्ती, कब्ज़); श्वसन अवसाद होता है, जो जानलेवा हो सकता है।")],
   "ओपिओइड से अधिक शक्तिशाली नहीं, पर लगभग उतनी ही असरदार और कहीं अधिक सुरक्षित।"),
 'ja': D("非オピオイド鎮痛薬", "JOURNAVX（スゼトリジン）", "痛みをその発生源で止める、新世代の非オピオイド鎮痛薬",
   [("NaV1.8", "標的：末梢神経のナトリウムチャネル"), ("FDA", "2025年1月30日に承認"), ("経口", "急性の中等度から重度の痛みに用いる錠剤")], None,
   [("末梢での作用：", "痛みの信号を伝えるNaV1.8ナトリウムチャネルを遮断し、痛みを発生源で止める。"),
    ("脳には届かない：", "依存を生じず、ふらつきもなく、報酬中枢に影響しない。"),
    ("JOURNAVX：", "依存のリスクなし。副作用は軽度（吐き気、頭痛）。呼吸抑制なし。"),
    ("オピオイド（例：モルヒネ）：", "標的は中枢神経系。依存のリスクが高い。副作用は重い（ふらつき、便秘）。呼吸抑制があり、生命に関わる。")],
   "オピオイドより強いわけではないが、同程度の強さで、はるかに安全である。"),
})
