from batch1 import D
CARDS = {}

# 52 - Paracetamol: useful or harmful? (collage: newspaper clipping, toxic dose chart, brand packs)
B = "Parol, Tylenol, Panadol, Minoset Plus, Calpol"
CARDS['b18_parasetamol'] = ('teal', {
 'en': D("PARACETAMOL (ACETAMINOPHEN)", "Paracetamol: useful or harmful?", "Considered safe, but the therapeutic margin is narrow",
   [(">10 g", "or >200 mg/kg, taken at once or within 24 hours: toxic dose"), (">6 g", "or >150 mg/kg per day for at least 2 consecutive days: toxic dose"), ("≤ 4 g/day", "standard maximum for healthy adults; many bodies advise 3 g/day for chronic use")], None,
   [("In the press:", "\"Paracetamol is worthless: 9 out of 10 pains do not go away\" and \"The painkiller's effect is psychological\" (Vatan newspaper)."),
    ("Liver:", "paracetamol poisoning is the most common cause of acute liver failure in the USA and the UK."),
    ("UK pack limits (1998):", "poisoning deaths fell by 21-43% and liver transplants by 61-66%."),
    ("Turkey:", "paracetamol caused 9.5% of acute liver failure cases (8 of 84)."),
    ("Brands shown:", B + ".")],
   "Sensible restrictions and public education may work better than making it prescription-only."),
 'de': D("PARACETAMOL (ACETAMINOPHEN)", "Paracetamol: nützlich oder schädlich?", "Gilt als sicher, aber die therapeutische Breite ist gering",
   [(">10 g", "oder >200 mg/kg, auf einmal oder innerhalb von 24 Stunden: toxische Dosis"), (">6 g", "oder >150 mg/kg pro Tag an mindestens 2 aufeinanderfolgenden Tagen: toxische Dosis"), ("≤ 4 g/Tag", "Standardmaximum für gesunde Erwachsene; bei Dauergebrauch oft 3 g/Tag empfohlen")], None,
   [("In der Presse:", "„Paracetamol taugt nichts: 9 von 10 Schmerzen vergehen nicht“ und „Die Wirkung des Schmerzmittels ist psychologisch“ (Zeitung Vatan)."),
    ("Leber:", "Die Paracetamolvergiftung ist in den USA und im Vereinigten Königreich die häufigste Ursache des akuten Leberversagens."),
    ("Packungsgrenzen in Großbritannien (1998):", "Vergiftungstodesfälle sanken um 21-43 %, Lebertransplantationen um 61-66 %."),
    ("Türkei:", "Paracetamol verursachte 9,5 % der Fälle von akutem Leberversagen (8 von 84)."),
    ("Abgebildete Marken:", B + ".")],
   "Vernünftige Beschränkungen und Aufklärung können wirksamer sein als eine Verschreibungspflicht."),
 'es': D("PARACETAMOL (ACETAMINOFÉN)", "Paracetamol: ¿útil o perjudicial?", "Se considera seguro, pero su margen terapéutico es estrecho",
   [(">10 g", "o >200 mg/kg, de una vez o en 24 horas: dosis tóxica"), (">6 g", "o >150 mg/kg al día durante al menos 2 días consecutivos: dosis tóxica"), ("≤ 4 g/día", "máximo estándar en adultos sanos; muchas entidades aconsejan 3 g/día en uso crónico")], None,
   [("En la prensa:", "«El paracetamol no vale nada: 9 de cada 10 dolores no se alivian» y «El efecto del analgésico es psicológico» (diario Vatan)."),
    ("Hígado:", "la intoxicación por paracetamol es la causa más frecuente de insuficiencia hepática aguda en EE. UU. y el Reino Unido."),
    ("Límites de envase en el Reino Unido (1998):", "las muertes por intoxicación bajaron un 21-43 % y los trasplantes hepáticos un 61-66 %."),
    ("Turquía:", "el paracetamol causó el 9,5 % de los casos de insuficiencia hepática aguda (8 de 84)."),
    ("Marcas mostradas:", B + ".")],
   "Las restricciones razonables y la educación del público pueden ser más eficaces que exigir receta."),
 'ru': D("ПАРАЦЕТАМОЛ (АЦЕТАМИНОФЕН)", "Парацетамол: польза или вред?", "Считается безопасным, но терапевтический диапазон узок",
   [(">10 г", "или >200 мг/кг, однократно или в течение 24 часов: токсическая доза"), (">6 г", "или >150 мг/кг в сутки не менее 2 дней подряд: токсическая доза"), ("≤ 4 г/сут", "стандартный максимум для здоровых взрослых; при длительном приёме часто советуют 3 г/сут")], None,
   [("В прессе:", "«Парацетамол ничего не стоит: 9 из 10 болей не проходят» и «Действие обезболивающего психологическое» (газета Vatan)."),
    ("Печень:", "отравление парацетамолом является самой частой причиной острой печёночной недостаточности в США и Великобритании."),
    ("Ограничение упаковок в Великобритании (1998):", "смертность от отравлений снизилась на 21-43 %, трансплантации печени на 61-66 %."),
    ("Турция:", "парацетамол вызвал 9,5 % случаев острой печёночной недостаточности (8 из 84)."),
    ("Препараты на фото:", B + ".")],
   "Разумные ограничения и просвещение населения могут быть эффективнее, чем отпуск только по рецепту."),
 'zh': D("对乙酰氨基酚（扑热息痛）", "对乙酰氨基酚：有益还是有害？", "被认为安全，但治疗窗较窄",
   [(">10 g", "或 >200 mg/kg，一次服用或 24 小时内：中毒剂量"), (">6 g", "或每日 >150 mg/kg，连续至少 2 天：中毒剂量"), ("≤ 4 g/日", "健康成人的标准上限；长期使用时许多机构建议 3 g/日")], None,
   [("报纸标题：", "“对乙酰氨基酚不值钱：10 种疼痛中有 9 种不缓解”以及“止痛药的作用是心理性的”（Vatan 报）。"),
    ("肝脏：", "对乙酰氨基酚中毒是美国和英国急性肝衰竭最常见的原因。"),
    ("英国包装限量（1998 年）：", "中毒死亡减少 21-43%，肝移植减少 61-66%。"),
    ("土耳其：", "对乙酰氨基酚占急性肝衰竭病例的 9.5%（84 例中 8 例）。"),
    ("图中品牌：", B + "。")],
   "合理的限制和公众教育可能比改为处方药更有效。"),
 'hi': D("पैरासिटामोल (एसिटामिनोफेन)", "पैरासिटामोल: लाभदायक या हानिकारक?", "सुरक्षित मानी जाती है, पर इसकी चिकित्सीय सीमा संकरी है",
   [(">10 g", "या >200 mg/kg, एक बार में या 24 घंटे के भीतर: विषाक्त खुराक"), (">6 g", "या >150 mg/kg प्रतिदिन, लगातार कम से कम 2 दिन: विषाक्त खुराक"), ("≤ 4 g/दिन", "स्वस्थ वयस्कों के लिए मानक अधिकतम; लंबे उपयोग में कई संस्थाएँ 3 g/दिन सुझाती हैं")], None,
   [("अख़बार में:", "\"पैरासिटामोल किसी काम की नहीं: 10 में से 9 दर्द ठीक नहीं होते\" और \"दर्द निवारक का असर मनोवैज्ञानिक है\" (Vatan अख़बार)।"),
    ("यकृत:", "अमेरिका और ब्रिटेन में पैरासिटामोल विषाक्तता तीव्र यकृत विफलता का सबसे आम कारण है।"),
    ("ब्रिटेन में पैक की सीमा (1998):", "विषाक्तता से मौतें 21-43% और यकृत प्रत्यारोपण 61-66% घटे।"),
    ("तुर्की:", "तीव्र यकृत विफलता के 9.5% मामलों (84 में से 8) का कारण पैरासिटामोल थी।"),
    ("चित्र में ब्रांड:", B + "।")],
   "केवल पर्चे पर देने के बजाय समझदारी भरी सीमाएँ और जन शिक्षा अधिक कारगर हो सकती हैं।"),
 'ja': D("パラセタモール（アセトアミノフェン）", "パラセタモール：有益か、有害か", "安全とされるが、治療域は狭い",
   [(">10 g", "または >200 mg/kg を一度に、もしくは24時間以内：中毒量"), (">6 g", "または1日 >150 mg/kg を2日以上連続：中毒量"), ("≤ 4 g/日", "健康な成人の標準的な上限。長期使用では 3 g/日を勧める機関が多い")], None,
   [("新聞の見出し：", "「パラセタモールは役に立たない：10の痛みのうち9は治まらない」「鎮痛薬の効果は心理的なもの」（Vatan紙）。"),
    ("肝臓：", "パラセタモール中毒は米国と英国で急性肝不全の最も多い原因である。"),
    ("英国の包装制限（1998年）：", "中毒死は21-43%、肝移植は61-66%減少した。"),
    ("トルコ：", "急性肝不全症例の9.5%（84例中8例）がパラセタモールによるものだった。"),
    ("画像の製品：", B + "。")],
   "処方箋医薬品にするより、合理的な制限と一般への啓発のほうが有効かもしれない。"),
})
