from batch1 import D
from batch2 import BM
CARDS = {}

# 28 — Oveporexton
CARDS['orzeyful'] = ('teal', {
 'en': D("NEW APPROVALS", "Oveporexton (Orzeyful)", "An orphan drug and the gateway to an orexin franchise. Approved by the FDA; DEA scheduling is awaited",
   [("OX2R", "selective orexin receptor 2 agonist"), ("~120,000", "estimated patients in the US"), ("60%", "insomnia, the most common side effect")], None,
   [("Indication:", "narcolepsy type 1."), ("Approval in China (NMPA):", "22 July 2026."), ("Approval in the US (FDA):", "5 August 2026."), ("DEA scheduling:", "pending, expected around 3 November.")]),
 'de': D("NEUE ZULASSUNGEN", "Oveporexton (Orzeyful)", "Ein Orphan-Arzneimittel und das Tor zu einer Orexin-Produktfamilie. Von der FDA zugelassen; die DEA-Einstufung steht aus",
   [("OX2R", "selektiver Orexin-Rezeptor-2-Agonist"), ("~120.000", "geschätzte Patienten in den USA"), ("60 %", "Schlaflosigkeit, häufigste Nebenwirkung")], None,
   [("Indikation:", "Narkolepsie Typ 1."), ("Zulassung in China (NMPA):", "22. Juli 2026."), ("Zulassung in den USA (FDA):", "5. August 2026."), ("DEA-Einstufung:", "ausstehend, erwartet um den 3. November.")]),
 'es': D("NUEVAS AUTORIZACIONES", "Oveporexton (Orzeyful)", "Un medicamento huérfano y la puerta de entrada a una franquicia de orexina. Aprobado por la FDA; pendiente de clasificación por la DEA",
   [("OX2R", "agonista selectivo del receptor 2 de orexina"), ("~120.000", "pacientes estimados en EE. UU."), ("60 %", "insomnio, el efecto adverso más frecuente")], None,
   [("Indicación:", "narcolepsia tipo 1."), ("Aprobación en China (NMPA):", "22 de julio de 2026."), ("Aprobación en EE. UU. (FDA):", "5 de agosto de 2026."), ("Clasificación de la DEA:", "pendiente, prevista hacia el 3 de noviembre.")]),
 'ru': D("НОВЫЕ РЕГИСТРАЦИИ", "Овепорекстон (Orzeyful)", "Орфанный препарат и входной билет в орексиновую франшизу. Одобрен FDA; классификация DEA ожидается",
   [("OX2R", "селективный агонист орексиновых рецепторов 2-го типа"), ("~120 000", "пациентов в США по оценке"), ("60 %", "бессонница, самый частый побочный эффект")], None,
   [("Показание:", "нарколепсия 1-го типа."), ("Одобрение в Китае (NMPA):", "22 июля 2026 г."), ("Одобрение в США (FDA):", "5 августа 2026 г."), ("Классификация DEA:", "ожидается примерно 3 ноября.")]),
 'zh': D("新获批药物", "Oveporexton（Orzeyful）", "一种孤儿药，也是食欲素产品线的入口。已获FDA批准，DEA管制分级待定",
   [("OX2R", "选择性食欲素2型受体激动剂"), ("约12万", "美国估计患者数"), ("60%", "失眠，最常见的副作用")], None,
   [("适应症：", "1型发作性睡病。"), ("中国（NMPA）批准：", "2026年7月22日。"), ("美国（FDA）批准：", "2026年8月5日。"), ("DEA管制分级：", "待定，预计在11月3日前后。")]),
 'hi': D("नई मंज़ूरियाँ", "ओवेपोरेक्सटन (Orzeyful)", "एक ऑर्फन दवा और ऑरेक्सिन श्रृंखला का प्रवेश-द्वार। FDA से स्वीकृत; DEA का वर्गीकरण प्रतीक्षित",
   [("OX2R", "चयनात्मक ऑरेक्सिन रिसेप्टर-2 एगोनिस्ट"), ("~1,20,000", "अमेरिका में अनुमानित मरीज़"), ("60%", "अनिद्रा, सबसे आम दुष्प्रभाव")], None,
   [("संकेत:", "नार्कोलेप्सी टाइप 1।"), ("चीन (NMPA) की मंज़ूरी:", "22 जुलाई 2026।"), ("अमेरिका (FDA) की मंज़ूरी:", "5 अगस्त 2026।"), ("DEA वर्गीकरण:", "लंबित, लगभग 3 नवंबर तक अपेक्षित।")]),
 'ja': D("新規承認", "オベポレキストン（Orzeyful）", "オーファンドラッグであり、オレキシン製品群への入口。FDAが承認し、DEAの規制区分は未定",
   [("OX2R", "選択的オレキシン2受容体作動薬"), ("約12万人", "米国の推定患者数"), ("60%", "不眠。最も多い副作用")], None,
   [("適応症：", "ナルコレプシー1型。"), ("中国（NMPA）の承認：", "2026年7月22日。"), ("米国（FDA）の承認：", "2026年8月5日。"), ("DEAの規制区分：", "未定。11月3日頃の見込み。")]),
})

# 29 — Bribery and corruption (poster)
_J = "Bribery and the Global Pharmaceutical Industry (Journal of Law, Medicine & Ethics)"
CARDS['rusvet'] = ('dark', {
 'en': D(BM['en'], "Bribery and corruption in the pharmaceutical sector", "On the study " + _J + ": regulations and penalties in the OECD reports"),
 'de': D(BM['de'], "Bestechung und Korruption im Arzneimittelsektor", "Zur Studie " + _J + ": Regelungen und Sanktionen in den OECD-Berichten"),
 'es': D(BM['es'], "Soborno y corrupción en el sector farmacéutico", "Sobre el estudio " + _J + ": normas y sanciones en los informes de la OCDE"),
 'ru': D(BM['ru'], "Взятки и коррупция в фармацевтическом секторе", "Об исследовании " + _J + ": нормы и санкции в отчётах ОЭСР"),
 'zh': D(BM['zh'], "医药行业的贿赂与腐败", "关于研究 " + _J + "：经合组织报告中的规则与处罚"),
 'hi': D(BM['hi'], "दवा क्षेत्र में रिश्वत और भ्रष्टाचार", "अध्ययन " + _J + " पर: OECD रिपोर्टों में नियम और दंड"),
 'ja': D(BM['ja'], "医薬品業界の贈賄と腐敗", "研究 " + _J + " について：OECD報告書にみる規制と制裁"),
})

# 30 — Dupixent in court
CARDS['dupixent'] = ('burg', {
 'en': D("DUPIXENT (DUPILUMAB)", "An innovative drug in court", "Dupixent faces US multidistrict litigation (MDL No. 3180) over alleged cutaneous T-cell lymphoma (CTCL)",
   [("MDL No. 3180", "consolidated in New Jersey. Discovery stage: no expert ruling, bellwether trial or settlement yet"), ("50,908.80 TL", "list price incl. VAT, 2 × 300 mg/2 mL; about 661,814 TL a year"), ("3.3–3.7×", "dearer than Rinvoq (~200,432 TL) and Cibinqo (~178,846 TL) in atopic dermatitis")], None,
   [("Allegation:", "CTCL risk and delayed diagnosis, citing 7 epidemiological studies. FDA FAERS signal in March 2025; the label is still unchanged."),
    ("Licensed in Türkiye for only 3 indications:", "atopic dermatitis, prurigo nodularis and COPD. Asthma, CRSwNP, EoE, CSU and AFRS are approved by the FDA/EMA but not licensed in Türkiye."),
    ("SGK reimbursement:", "through the Alternative Reimbursement Model; the actual amount is not public. Indication compliance became mandatory on 9 November 2024.")],
   None, "Note: the case has not been decided. This reflects allegations and regulatory records, not a court ruling."),
 'de': D("DUPIXENT (DUPILUMAB)", "Ein innovatives Medikament vor Gericht", "Dupixent im US-Sammelverfahren (MDL Nr. 3180) wegen des Vorwurfs eines kutanen T-Zell-Lymphoms (CTCL)",
   [("MDL Nr. 3180", "in New Jersey zusammengeführt. Stadium Discovery: noch keine Gutachterentscheidung, kein Musterprozess, kein Vergleich"), ("50.908,80 TL", "Listenpreis inkl. MwSt., 2 × 300 mg/2 ml; etwa 661.814 TL pro Jahr"), ("3,3–3,7×", "teurer als Rinvoq (~200.432 TL) und Cibinqo (~178.846 TL) bei atopischer Dermatitis")], None,
   [("Vorwurf:", "CTCL-Risiko und verzögerte Diagnose, gestützt auf 7 epidemiologische Studien. FDA-FAERS-Signal im März 2025; die Fachinformation ist weiterhin unverändert."),
    ("In der Türkei nur für 3 Indikationen zugelassen:", "atopische Dermatitis, Prurigo nodularis und COPD. Asthma, CRSwNP, EoE, CSU und AFRS sind von FDA/EMA zugelassen, in der Türkei aber nicht."),
    ("SGK-Erstattung:", "über das Alternative Erstattungsmodell; der tatsächliche Betrag ist nicht öffentlich. Seit 9. November 2024 ist die Indikationskonformität verpflichtend.")],
   None, "Hinweis: Der Fall ist nicht entschieden. Dargestellt sind Vorwürfe und behördliche Unterlagen, kein Gerichtsurteil."),
 'es': D("DUPIXENT (DUPILUMAB)", "Un fármaco innovador ante los tribunales", "Dupixent afronta en EE. UU. un litigio multidistrito (MDL n.º 3180) por presunto linfoma cutáneo de células T (LCCT)",
   [("MDL n.º 3180", "consolidado en Nueva Jersey. Fase de discovery: sin decisión pericial, juicio piloto ni acuerdo todavía"), ("50.908,80 TL", "precio de lista con IVA, 2 × 300 mg/2 ml; unos 661.814 TL al año"), ("3,3–3,7×", "más caro que Rinvoq (~200.432 TL) y Cibinqo (~178.846 TL) en dermatitis atópica")], None,
   [("Acusación:", "riesgo de LCCT y diagnóstico tardío, con referencia a 7 estudios epidemiológicos. Señal en FAERS de la FDA en marzo de 2025; la ficha técnica sigue sin cambios."),
    ("En Turquía solo está autorizado para 3 indicaciones:", "dermatitis atópica, prurigo nodular y EPOC. Asma, RSCcPN, EoE, UCE y RSFA están aprobadas por la FDA/EMA, pero no en Turquía."),
    ("Reembolso de la SGK:", "mediante el Modelo Alternativo de Reembolso; el importe real no es público. Desde el 9 de noviembre de 2024 es obligatorio ajustarse a la indicación.")],
   None, "Nota: el caso no está resuelto. Se recogen alegaciones y registros regulatorios, no una sentencia."),
 'ru': D("ДУПИКСЕНТ (ДУПИЛУМАБ)", "Инновационный препарат в суде", "Против Дупиксента в США ведётся многоокружное разбирательство (MDL № 3180) по поводу предполагаемой кожной Т-клеточной лимфомы (КТКЛ)",
   [("MDL № 3180", "объединено в Нью-Джерси. Стадия раскрытия доказательств: решений по экспертизе, показательных процессов и мировых соглашений пока нет"), ("50 908,80 лиры", "прейскурантная цена с НДС, 2 × 300 мг/2 мл; около 661 814 лир в год"), ("в 3,3–3,7 раза", "дороже Ринвока (~200 432 лиры) и Сибинко (~178 846 лир) при атопическом дерматите")], None,
   [("Обвинение:", "риск КТКЛ и запоздалая диагностика со ссылкой на 7 эпидемиологических исследований. Сигнал FAERS FDA в марте 2025 г.; инструкция до сих пор не изменена."),
    ("В Турции зарегистрирован только по 3 показаниям:", "атопический дерматит, узловатая почесуха и ХОБЛ. Астма, хронический риносинусит с полипами, ЭоЭ, ХСК и АГРС одобрены FDA/EMA, но не в Турции."),
    ("Возмещение SGK:", "по Альтернативной модели возмещения; фактическая сумма не раскрывается. С 9 ноября 2024 г. соответствие показанию обязательно.")],
   None, "Примечание: дело не рассмотрено. Здесь приведены обвинения и регуляторные документы, а не решение суда."),
 'zh': D("达必妥（度普利尤单抗）", "创新药上了法庭", "达必妥因涉嫌引起皮肤T细胞淋巴瘤（CTCL）在美国面临多地区合并诉讼（MDL第3180号）",
   [("MDL第3180号", "已在新泽西州合并审理。处于证据开示阶段：尚无专家证据裁定、示范性审判或和解"), ("50,908.80里拉", "含增值税标价，2支×300毫克/2毫升；每年约661,814里拉"), ("3.3–3.7倍", "在特应性皮炎中比Rinvoq（约200,432里拉）和Cibinqo（约178,846里拉）更贵")], None,
   [("指控：", "CTCL风险和诊断延误，援引7项流行病学研究。2025年3月出现FDA FAERS信号；说明书至今未改。"),
    ("在土耳其仅获批3个适应症：", "特应性皮炎、结节性痒疹和慢阻肺。哮喘、慢性鼻窦炎伴鼻息肉、嗜酸性食管炎、慢性自发性荨麻疹和变应性真菌性鼻窦炎已获FDA/EMA批准，但在土耳其未获批。"),
    ("SGK报销：", "通过“替代报销模式”；实际金额不公开。自2024年11月9日起必须符合适应症。")],
   None, "说明：此案尚未判决。这里反映的是指控和监管记录，而不是法院裁决。"),
 'hi': D("डुपिक्सेंट (डुपिलुमैब)", "नवोन्मेषी दवा अदालत में", "त्वचीय टी-सेल लिंफोमा (CTCL) के आरोप में डुपिक्सेंट अमेरिका में बहु-ज़िला मुक़दमे (MDL सं. 3180) का सामना कर रही है",
   [("MDL सं. 3180", "न्यू जर्सी में समेकित। डिस्कवरी चरण: अभी विशेषज्ञ-निर्णय, नमूना सुनवाई या समझौता नहीं"), ("50,908.80 TL", "वैट सहित सूची मूल्य, 2 × 300 मि.ग्रा./2 मि.ली.; लगभग 6,61,814 TL प्रति वर्ष"), ("3.3–3.7 गुना", "एटोपिक डर्मेटाइटिस में Rinvoq (~2,00,432 TL) और Cibinqo (~1,78,846 TL) से महँगी")], None,
   [("आरोप:", "CTCL का जोखिम और देर से निदान, 7 महामारी-विज्ञान अध्ययनों के हवाले से। मार्च 2025 में FDA FAERS संकेत; लेबल अब भी नहीं बदला।"),
    ("तुर्किये में केवल 3 संकेतों के लिए लाइसेंस:", "एटोपिक डर्मेटाइटिस, प्रुरिगो नोड्यूलैरिस और COPD। अस्थमा, CRSwNP, EoE, CSU और AFRS को FDA/EMA की मंज़ूरी है, पर तुर्किये में नहीं।"),
    ("SGK प्रतिपूर्ति:", "वैकल्पिक प्रतिपूर्ति मॉडल के ज़रिये; वास्तविक राशि सार्वजनिक नहीं। 9 नवंबर 2024 से संकेत के अनुरूप होना अनिवार्य।")],
   None, "टिप्पणी: मामला अभी तय नहीं हुआ। यहाँ आरोप और नियामकीय अभिलेख हैं, अदालत का फ़ैसला नहीं।"),
 'ja': D("デュピクセント（デュピルマブ）", "革新的医薬品、法廷へ", "デュピクセントは皮膚T細胞リンパ腫（CTCL）の疑いをめぐり、米国で広域係属訴訟（MDL第3180号）に直面している",
   [("MDL第3180号", "ニュージャージー州に統合。証拠開示の段階で、専門家証言の判断、先行審理、和解はまだない"), ("50,908.80リラ", "税込み定価、300mg/2mL×2本。年間約661,814リラ"), ("3.3〜3.7倍", "アトピー性皮膚炎でRinvoq（約200,432リラ）やCibinqo（約178,846リラ）より高い")], None,
   [("主張：", "CTCLのリスクと診断の遅れ。7件の疫学研究を引用。2025年3月にFDAのFAERSでシグナル。添付文書は今も変更なし。"),
    ("トルコでの承認は3適応のみ：", "アトピー性皮膚炎、結節性痒疹、COPD。喘息、鼻茸を伴う慢性副鼻腔炎、好酸球性食道炎、慢性特発性蕁麻疹、アレルギー性真菌性副鼻腔炎はFDA/EMAで承認済みだが、トルコでは未承認。"),
    ("SGKの償還：", "代替償還モデルによる。実際の金額は非公開。2024年11月9日から適応の遵守が義務化。")],
   None, "注：訴訟は未決。ここに示すのは主張と規制上の記録であり、判決ではない。"),
})

# 31 — mFlusiva
CARDS['mflusiva'] = ('navy', {
 'en': D("FDA APPROVAL · 5 AUGUST 2026 · MODERNA (mRNA-1010)", "mFlusiva: the first mRNA flu vaccine", None,
   [("26.6%", "relative efficacy difference versus a standard-dose vaccine (RT-PCR confirmed, ages 50–64)"), ("40,805", "participants in the FLUENT trial: 11 countries, 301 sites"), ("2 routes", "standard approval for ages 50–64; accelerated approval for 65 and over")], None,
   [("Ages 65+:", "accelerated approval based on a surrogate endpoint (antibody response), on condition that a Phase 4 study confirms clinical benefit."),
    ("Critical point:", "there are no clinical efficacy data against the high-dose or adjuvanted vaccines actually preferred in older adults."),
    ("Price:", "no official list price yet. CDC contract prices: standard dose about 25–45 dollars, high dose or adjuvanted about 55–75 dollars."),
    ("The process:", "a refusal-to-file notice in February 2026 was reversed within a week; the advisory committee voted unanimously in June.")],
   None, "The figures come from secondary news sources; the FDA approval letter and the full clinical data are not yet public."),
 'de': D("FDA-ZULASSUNG · 5. AUGUST 2026 · MODERNA (mRNA-1010)", "mFlusiva: der erste mRNA-Grippeimpfstoff", None,
   [("26,6 %", "relativer Wirksamkeitsunterschied gegenüber Standarddosis-Impfstoff (RT-PCR-bestätigt, 50–64 Jahre)"), ("40.805", "Teilnehmer der FLUENT-Studie: 11 Länder, 301 Zentren"), ("2 Wege", "reguläre Zulassung für 50–64 Jahre; beschleunigte Zulassung ab 65")], None,
   [("Ab 65 Jahren:", "beschleunigte Zulassung auf Basis eines Surrogatendpunkts (Antikörperantwort), unter der Bedingung, dass eine Phase-4-Studie den klinischen Nutzen bestätigt."),
    ("Kritischer Punkt:", "Es gibt keine klinischen Wirksamkeitsdaten gegenüber den bei Älteren tatsächlich bevorzugten Hochdosis- oder adjuvantierten Impfstoffen."),
    ("Preis:", "noch kein offizieller Listenpreis. CDC-Vertragspreise: Standarddosis etwa 25–45 Dollar, Hochdosis/adjuvantiert etwa 55–75 Dollar."),
    ("Der Ablauf:", "Ein Refusal-to-file-Bescheid im Februar 2026 wurde binnen einer Woche zurückgenommen; einstimmiges Votum des Beratungsausschusses im Juni.")],
   None, "Die Zahlen stammen aus sekundären Nachrichtenquellen; Zulassungsschreiben und vollständige Daten sind noch nicht öffentlich."),
 'es': D("APROBACIÓN DE LA FDA · 5 DE AGOSTO DE 2026 · MODERNA (mRNA-1010)", "mFlusiva: la primera vacuna antigripal de ARNm", None,
   [("26,6 %", "diferencia de eficacia relativa frente a una vacuna de dosis estándar (confirmada por RT-PCR, 50–64 años)"), ("40.805", "participantes en el ensayo FLUENT: 11 países, 301 centros"), ("2 vías", "aprobación estándar para 50–64 años; aprobación acelerada para 65 o más")], None,
   [("65 años o más:", "aprobación acelerada basada en un criterio indirecto (respuesta de anticuerpos), condicionada a que un estudio de fase 4 confirme el beneficio clínico."),
    ("Punto crítico:", "no hay datos de eficacia clínica frente a las vacunas de alta dosis o adyuvadas que realmente se prefieren en los mayores."),
    ("Precio:", "aún sin precio de lista oficial. Precios de contrato de los CDC: dosis estándar unos 25–45 dólares; alta dosis o adyuvada unos 55–75 dólares."),
    ("El proceso:", "una notificación de rechazo a trámite en febrero de 2026 se revirtió en una semana; voto unánime del comité asesor en junio.")],
   None, "Las cifras proceden de fuentes periodísticas secundarias; la carta de aprobación y los datos completos aún no son públicos."),
 'ru': D("ОДОБРЕНИЕ FDA · 5 АВГУСТА 2026 · MODERNA (mRNA-1010)", "mFlusiva: первая мРНК-вакцина от гриппа", None,
   [("26,6 %", "относительная разница в эффективности по сравнению со стандартной вакциной (подтверждено ОТ-ПЦР, 50–64 года)"), ("40 805", "участников исследования FLUENT: 11 стран, 301 центр"), ("2 пути", "стандартное одобрение для 50–64 лет; ускоренное для 65 лет и старше")], None,
   [("65 лет и старше:", "ускоренное одобрение по суррогатной конечной точке (антительный ответ) при условии, что исследование 4-й фазы подтвердит клиническую пользу."),
    ("Ключевой момент:", "нет данных о клинической эффективности в сравнении с высокодозными или адъювантными вакцинами, которые реально предпочитают у пожилых."),
    ("Цена:", "официальной прейскурантной цены пока нет. Контрактные цены CDC: стандартная доза около 25–45 долларов, высокодозная или адъювантная около 55–75 долларов."),
    ("Процесс:", "отказ в приёме заявки в феврале 2026 г. был отменён в течение недели; в июне консультативный комитет проголосовал единогласно.")],
   None, "Цифры взяты из вторичных новостных источников; письмо FDA об одобрении и полные данные пока не опубликованы."),
 'zh': D("FDA批准 · 2026年8月5日 · MODERNA（mRNA-1010）", "mFlusiva：首个mRNA流感疫苗", None,
   [("26.6%", "相对于标准剂量疫苗的相对效力差异（RT-PCR确诊，50–64岁）"), ("40,805名", "FLUENT试验受试者：11个国家，301个中心"), ("2条路径", "50–64岁为常规批准；65岁及以上为加速批准")], None,
   [("65岁及以上：", "基于替代终点（抗体应答）的加速批准，条件是通过4期研究确认临床获益。"),
    ("关键点：", "没有与老年人实际首选的高剂量或含佐剂疫苗相比较的临床效力数据。"),
    ("价格：", "尚无官方标价。CDC合同价：标准剂量约25–45美元，高剂量或含佐剂约55–75美元。"),
    ("过程：", "2026年2月的“拒绝受理”通知在一周内被撤回；6月咨询委员会一致投票通过。")],
   None, "数字来自二手新闻来源；FDA批准函和完整临床数据尚未公开。"),
 'hi': D("FDA की मंज़ूरी · 5 अगस्त 2026 · MODERNA (mRNA-1010)", "mFlusiva: पहला mRNA फ़्लू टीका", None,
   [("26.6%", "मानक खुराक वाले टीके की तुलना में सापेक्ष प्रभावकारिता का अंतर (RT-PCR से पुष्ट, 50–64 वर्ष)"), ("40,805", "FLUENT अध्ययन के प्रतिभागी: 11 देश, 301 केंद्र"), ("2 रास्ते", "50–64 वर्ष के लिए सामान्य मंज़ूरी; 65 और अधिक के लिए त्वरित मंज़ूरी")], None,
   [("65 वर्ष और अधिक:", "सरोगेट अंतिम बिंदु (एंटीबॉडी प्रतिक्रिया) पर आधारित त्वरित मंज़ूरी, इस शर्त पर कि चरण 4 का अध्ययन नैदानिक लाभ की पुष्टि करे।"),
    ("अहम बिंदु:", "बुज़ुर्गों में वास्तव में पसंद किए जाने वाले उच्च-खुराक या एडजुवेंट वाले टीकों के मुक़ाबले नैदानिक प्रभावकारिता का डेटा नहीं है।"),
    ("कीमत:", "अभी आधिकारिक सूची मूल्य नहीं। CDC अनुबंध कीमतें: मानक खुराक लगभग 25–45 डॉलर, उच्च खुराक या एडजुवेंट वाला लगभग 55–75 डॉलर।"),
    ("प्रक्रिया:", "फ़रवरी 2026 का “आवेदन अस्वीकार” नोटिस एक सप्ताह में पलट दिया गया; जून में सलाहकार समिति ने सर्वसम्मति से मत दिया।")],
   None, "आँकड़े द्वितीयक समाचार स्रोतों से हैं; FDA का मंज़ूरी-पत्र और पूरा डेटा अभी सार्वजनिक नहीं।"),
 'ja': D("FDA承認 · 2026年8月5日 · モデルナ（mRNA-1010）", "mFlusiva：初のmRNAインフルエンザワクチン", None,
   [("26.6%", "標準用量ワクチンに対する相対的な有効性の差（RT-PCR確定、50〜64歳）"), ("40,805人", "FLUENT試験の参加者：11か国、301施設"), ("2つの経路", "50〜64歳は通常承認、65歳以上は迅速承認")], None,
   [("65歳以上：", "代替評価項目（抗体反応）に基づく迅速承認。第4相試験で臨床的有用性を確認することが条件。"),
    ("重要な点：", "高齢者で実際に選ばれている高用量またはアジュバント添加ワクチンと比べた臨床的有効性のデータはない。"),
    ("価格：", "公式の定価は未発表。CDCの契約価格は標準用量が約25〜45ドル、高用量・アジュバント添加が約55〜75ドル。"),
    ("経緯：", "2026年2月の申請受理拒否の通知は1週間以内に撤回され、6月に諮問委員会が全会一致で賛成した。")],
   None, "数値は二次的な報道に基づく。FDAの承認書と完全な臨床データはまだ公開されていない。"),
})

# 34 — DiMasi R&D cost myth
_DS = "DiMasi, Grabowski, Hansen. Journal of Health Economics 2016;47"
CARDS['dimasi'] = ('navy', {
 'en': D("TO THOSE WHO USE THIS FIGURE WITHOUT QUESTION", "Distorting hidden figures, deceiving with false ones", "Joseph DiMasi and the myth of the cost of drug R&D",
   [("$1,395 m", "actually paid out of pocket: preclinical 430 + clinical (Phase I–III) 965"), ("$2,558 m", "the capitalized figure: preclinical 1,098 + clinical 1,460"), ("45.5%", "of the '2.6 billion dollars' was never spent")], None,
   [("The gap:", "1,163 million dollars of the figure is only a hypothetical 'opportunity cost', not real spending."),
    ("The data are secret:", "they come from 10 drug companies, and no independent team has been able to verify them."),
    ("Conclusion:", "presenting this figure as 'scientific fact' is marketing, not science.")],
   None, "Source: " + _DS + " (2013 dollars)"),
 'de': D("AN ALLE, DIE DIESE ZAHL UNGEPRÜFT VERWENDEN", "Geheime Zahlen verzerren, mit falschen Zahlen täuschen", "Joseph DiMasi und der Mythos der Arzneimittel-F&E-Kosten",
   [("1.395 Mio. $", "tatsächlich ausgegeben: Präklinik 430 + Klinik (Phase I–III) 965"), ("2.558 Mio. $", "kapitalisierter Betrag: Präklinik 1.098 + Klinik 1.460"), ("45,5 %", "der „2,6 Milliarden Dollar“ wurden nie ausgegeben")], None,
   [("Die Lücke:", "1.163 Millionen Dollar der Zahl sind nur hypothetische „Opportunitätskosten“, keine realen Ausgaben."),
    ("Die Daten sind geheim:", "Sie stammen von 10 Pharmaunternehmen, und kein unabhängiges Team konnte sie überprüfen."),
    ("Fazit:", "Diese Zahl als „wissenschaftliche Tatsache“ darzustellen, ist Marketing, keine Wissenschaft.")],
   None, "Quelle: " + _DS + " (Dollar von 2013)"),
 'es': D("A QUIENES USAN ESTA CIFRA SIN CUESTIONARLA", "Distorsionar cifras ocultas, engañar con cifras falsas", "Joseph DiMasi y el mito del coste de la I+D farmacéutica",
   [("1.395 M$", "realmente desembolsados: preclínica 430 + clínica (fases I–III) 965"), ("2.558 M$", "cifra capitalizada: preclínica 1.098 + clínica 1.460"), ("45,5 %", "de los «2.600 millones de dólares» nunca se gastó")], None,
   [("La diferencia:", "1.163 millones de dólares de la cifra son solo un «coste de oportunidad» hipotético, no un gasto real."),
    ("Los datos son secretos:", "proceden de 10 compañías farmacéuticas y ningún equipo independiente ha podido verificarlos."),
    ("Conclusión:", "presentar esta cifra como «hecho científico» es marketing, no ciencia.")],
   None, "Fuente: " + _DS + " (dólares de 2013)"),
 'ru': D("ТЕМ, КТО ИСПОЛЬЗУЕТ ЭТУ ЦИФРУ БЕЗ ВОПРОСОВ", "Искажать скрытые цифры, обманывать фальшивыми", "Джозеф ДиМази и миф о стоимости разработки лекарств",
   [("1395 млн $", "реально потрачено: доклинический этап 430 + клинический (фазы I–III) 965"), ("2558 млн $", "капитализированная сумма: доклинический этап 1098 + клинический 1460"), ("45,5 %", "от «2,6 млрд долларов» никогда не были потрачены")], None,
   [("Разница:", "1163 млн долларов в этой цифре лишь гипотетические «альтернативные издержки», а не реальные расходы."),
    ("Данные засекречены:", "они получены от 10 фармкомпаний, и ни одна независимая группа не смогла их проверить."),
    ("Вывод:", "подавать эту цифру как «научный факт» означает заниматься маркетингом, а не наукой.")],
   None, "Источник: " + _DS + " (в долларах 2013 г.)"),
 'zh': D("致不加质疑就引用这个数字的人", "歪曲不公开的数字，用虚假数字骗人", "约瑟夫·迪马西与药物研发成本的神话",
   [("13.95亿美元", "实际支出：临床前4.30亿 + 临床（I–III期）9.65亿"), ("25.58亿美元", "资本化后的数字：临床前10.98亿 + 临床14.60亿"), ("45.5%", "所谓“26亿美元”中从未真正花出去的部分")], None,
   [("差额：", "其中11.63亿美元只是假设的“机会成本”，并非真实支出。"),
    ("数据保密：", "数据来自10家制药公司，没有任何独立团队能够核实。"),
    ("结论：", "把这个数字当作“科学事实”来宣传，是营销，不是科学。")],
   None, "来源：" + _DS + "（2013年美元）"),
 'hi': D("उनके लिए जो इस आँकड़े को बिना सवाल इस्तेमाल करते हैं", "छिपे आँकड़ों को तोड़ना-मरोड़ना, झूठे आँकड़ों से छलना", "जोसेफ़ डिमासी और दवा अनुसंधान लागत का मिथक",
   [("139.5 करोड़ डॉलर", "वास्तव में खर्च: प्रीक्लिनिकल 43 + क्लिनिकल (चरण I–III) 96.5 करोड़"), ("255.8 करोड़ डॉलर", "पूँजीकृत आँकड़ा: प्रीक्लिनिकल 109.8 + क्लिनिकल 146 करोड़"), ("45.5%", "“2.6 अरब डॉलर” का यह हिस्सा कभी खर्च ही नहीं हुआ")], None,
   [("अंतर:", "इस आँकड़े के 116.3 करोड़ डॉलर केवल काल्पनिक “अवसर लागत” हैं, वास्तविक खर्च नहीं।"),
    ("डेटा गोपनीय है:", "यह 10 दवा कंपनियों से आया है और कोई स्वतंत्र दल इसकी पुष्टि नहीं कर सका।"),
    ("निष्कर्ष:", "इस आँकड़े को “वैज्ञानिक तथ्य” बताना विज्ञान नहीं, विपणन है।")],
   None, "स्रोत: " + _DS + " (2013 के डॉलर)"),
 'ja': D("この数字を疑わずに使う人たちへ", "隠された数字を歪め、偽の数字で欺く", "ジョセフ・ディマシと医薬品研究開発費の神話",
   [("13億9,500万ドル", "実際の支出：前臨床4.30億＋臨床（第I〜III相）9.65億"), ("25億5,800万ドル", "資本化後の数字：前臨床10.98億＋臨床14.60億"), ("45.5%", "「26億ドル」のうち、実際には支出されなかった割合")], None,
   [("差額：", "この数字のうち11億6,300万ドルは仮定上の「機会費用」にすぎず、実際の支出ではない。"),
    ("データは非公開：", "出どころは製薬企業10社で、独立したチームは検証できていない。"),
    ("結論：", "この数字を「科学的事実」として示すのは科学ではなく、マーケティングである。")],
   None, "出典：" + _DS + "（2013年ドル）"),
})
