from batch1 import D
from batch2 import BM
CARDS = {}

# 72 — Scientific fraud handbook (poster)
CARDS['sahtekarlik'] = ('navy', {
 'en': D("HANDBOOK · 2026", "Scientific fraud: a handbook for diagnosis and treatment", "The anatomy of scientific fraud and how to recognise it early"),
 'de': D("HANDBUCH · 2026", "Wissenschaftlicher Betrug: ein Handbuch für Diagnose und Therapie", "Die Anatomie wissenschaftlichen Betrugs und wie man ihn früh erkennt"),
 'es': D("MANUAL · 2026", "Fraude científico: manual de diagnóstico y tratamiento", "La anatomía del fraude científico y cómo reconocerlo a tiempo"),
 'ru': D("РУКОВОДСТВО · 2026", "Научное мошенничество: руководство по диагностике и лечению", "Анатомия научного мошенничества и его раннее распознавание"),
 'zh': D("手册 · 2026", "科研造假：诊断与治疗手册", "科研造假的解剖与早期识别"),
 'hi': D("पुस्तिका · 2026", "वैज्ञानिक धोखाधड़ी: निदान और उपचार पुस्तिका", "वैज्ञानिक धोखाधड़ी की शारीरिकी और उसकी शीघ्र पहचान"),
 'ja': D("ハンドブック · 2026", "科学不正：診断と治療のハンドブック", "科学不正の解剖と早期発見"),
})

# 73 — Phase 3 vs real-world data
CARDS['faz3'] = ('blue', {
 'en': D("ONE OF THE GREAT CONTRADICTIONS OF MODERN MEDICINE", "The differences between Phase 3 trials and real-world data", "A drug's real story is written not on the day it is licensed, but after millions of people have used it for years", None, None,
   [("Phase 3:", "ideal patients are selected, the drug is free, follow-up is strict and adherence high. Strong internal validity, but it does not always represent real life."),
    ("Real life:", "older patients with comorbidities and many drugs, adherence problems, economic and social factors; side effects are noticed late."),
    ("Efficacy is not effectiveness:", "the effect measured under ideal conditions differs from the effect seen in daily practice."),
    ("Examples:", "Vioxx, Fournier's gangrene with SGLT2 inhibitors, antidepressants and publication bias, the opioid crisis, immunotherapy toxicities and GLP-1 agonists."),
    ("The surrogate endpoint problem:", "a laboratory result can improve without real clinical benefit.")],
   "Real science begins on the bridge between controlled research and real life."),
 'de': D("EINER DER GROSSEN WIDERSPRÜCHE DER MODERNEN MEDIZIN", "Die Unterschiede zwischen Phase-3-Studien und Daten aus dem Versorgungsalltag", "Die wahre Geschichte eines Medikaments wird nicht am Tag der Zulassung geschrieben, sondern nachdem Millionen Menschen es jahrelang angewendet haben", None, None,
   [("Phase 3:", "ideale Patienten, kostenloses Medikament, enge Nachbeobachtung und hohe Therapietreue. Hohe interne Validität, aber nicht immer repräsentativ für den Alltag."),
    ("Alltag:", "ältere Patienten mit Begleiterkrankungen und vielen Medikamenten, Probleme mit der Therapietreue, wirtschaftliche und soziale Faktoren; Nebenwirkungen werden spät bemerkt."),
    ("Efficacy ist nicht Effectiveness:", "Die unter Idealbedingungen gemessene Wirkung unterscheidet sich von der im Praxisalltag beobachteten."),
    ("Beispiele:", "Vioxx, Fournier-Gangrän unter SGLT2-Hemmern, Antidepressiva und Publikationsbias, Opioidkrise, Toxizitäten der Immuntherapie und GLP-1-Agonisten."),
    ("Das Problem der Surrogatendpunkte:", "Ein Laborwert kann sich bessern, ohne echten klinischen Nutzen.")],
   "Echte Wissenschaft beginnt auf der Brücke zwischen kontrollierter Forschung und dem wirklichen Leben."),
 'es': D("UNA DE LAS GRANDES CONTRADICCIONES DE LA MEDICINA MODERNA", "Las diferencias entre los ensayos de fase 3 y los datos de la vida real", "La verdadera historia de un fármaco no se escribe el día en que se autoriza, sino después de que millones de personas lo hayan usado durante años", None, None,
   [("Fase 3:", "se seleccionan pacientes ideales, el fármaco es gratuito, el seguimiento es estricto y la adherencia alta. Gran validez interna, pero no siempre representa la vida real."),
    ("Vida real:", "pacientes mayores, con comorbilidades y polimedicados, problemas de adherencia, factores económicos y sociales; los efectos adversos se detectan tarde."),
    ("Eficacia no es efectividad:", "el efecto medido en condiciones ideales difiere del observado en la práctica diaria."),
    ("Ejemplos:", "Vioxx, gangrena de Fournier con inhibidores de SGLT2, antidepresivos y sesgo de publicación, crisis de los opioides, toxicidades de la inmunoterapia y agonistas de GLP-1."),
    ("El problema de los criterios indirectos:", "un resultado de laboratorio puede mejorar sin beneficio clínico real.")],
   "La ciencia real empieza en el puente entre la investigación controlada y la vida real."),
 'ru': D("ОДНО ИЗ ГЛАВНЫХ ПРОТИВОРЕЧИЙ СОВРЕМЕННОЙ МЕДИЦИНЫ", "Различия между исследованиями 3-й фазы и данными реальной практики", "Настоящая история лекарства пишется не в день регистрации, а после того, как миллионы людей годами его применяют", None, None,
   [("3-я фаза:", "отбираются идеальные пациенты, препарат бесплатен, наблюдение строгое, приверженность высокая. Высокая внутренняя валидность, но реальную жизнь это отражает не всегда."),
    ("Реальная жизнь:", "пожилые пациенты с сопутствующими болезнями и полипрагмазией, проблемы приверженности, экономические и социальные факторы; побочные эффекты замечают поздно."),
    ("Efficacy не равно effectiveness:", "эффект в идеальных условиях отличается от эффекта в повседневной практике."),
    ("Примеры:", "Vioxx, гангрена Фурнье при ингибиторах SGLT2, антидепрессанты и публикационное смещение, опиоидный кризис, токсичность иммунотерапии и агонисты ГПП-1."),
    ("Проблема суррогатных конечных точек:", "лабораторный показатель может улучшиться без реальной клинической пользы.")],
   "Настоящая наука начинается на мосту между контролируемым исследованием и реальной жизнью."),
 'zh': D("现代医学最大的矛盾之一", "3期试验与真实世界数据之间的差别", "一种药物真正的故事，不是写在获批那天，而是写在数百万人使用多年之后", None, None,
   [("3期试验：", "挑选理想患者，药物免费，随访严格，依从性高。内部效度强，但不一定代表真实情况。"),
    ("真实世界：", "高龄、合并症多、多药并用的患者，依从性问题，经济和社会因素；副作用发现得晚。"),
    ("效力不等于效果：", "理想条件下测得的效应与日常临床中观察到的效果不同。"),
    ("实例：", "万络（Vioxx）、SGLT2抑制剂与福尼尔坏疽、抗抑郁药与发表偏倚、阿片危机、免疫治疗毒性以及GLP-1激动剂。"),
    ("替代终点问题：", "化验指标可以改善，却未必带来真正的临床获益。")],
   "真正的科学，始于对照研究与真实生活之间的那座桥。"),
 'hi': D("आधुनिक चिकित्सा के सबसे बड़े विरोधाभासों में से एक", "चरण 3 के अध्ययनों और वास्तविक जीवन के आँकड़ों के बीच अंतर", "दवा की असली कहानी लाइसेंस मिलने के दिन नहीं, बल्कि लाखों लोगों द्वारा वर्षों तक उपयोग के बाद लिखी जाती है", None, None,
   [("चरण 3:", "आदर्श मरीज़ चुने जाते हैं, दवा मुफ़्त होती है, निगरानी कड़ी और अनुपालन ऊँचा होता है। आंतरिक वैधता मज़बूत, पर यह हमेशा वास्तविक जीवन का प्रतिनिधित्व नहीं करता।"),
    ("वास्तविक जीवन:", "बुज़ुर्ग, सह-रोगों वाले, कई दवाएँ लेने वाले मरीज़; अनुपालन की समस्याएँ, आर्थिक और सामाजिक कारक; दुष्प्रभाव देर से पहचाने जाते हैं।"),
    ("एफ़िकेसी, इफ़ेक्टिवनेस नहीं है:", "आदर्श परिस्थितियों में मापा गया प्रभाव रोज़मर्रा के व्यवहार में दिखने वाले प्रभाव से अलग होता है।"),
    ("उदाहरण:", "Vioxx, SGLT2 अवरोधकों के साथ फ़ोर्नियर गैंग्रीन, अवसादरोधी और प्रकाशन पूर्वाग्रह, ओपिओइड संकट, इम्यूनोथेरेपी की विषाक्तताएँ और GLP-1 एगोनिस्ट।"),
    ("सरोगेट अंतिम बिंदु की समस्या:", "प्रयोगशाला का परिणाम सुधर सकता है, पर वास्तविक नैदानिक लाभ नहीं मिलता।")],
   "असली विज्ञान नियंत्रित शोध और वास्तविक जीवन के बीच के पुल पर शुरू होता है।"),
 'ja': D("現代医学の大きな矛盾のひとつ", "第3相試験とリアルワールドデータの違い", "薬の本当の物語は承認の日ではなく、何百万人もが何年も使った後に書かれる", None, None,
   [("第3相試験：", "理想的な患者が選ばれ、薬は無償で、追跡は厳密、服薬遵守率も高い。内的妥当性は高いが、実臨床を常に代表するわけではない。"),
    ("実臨床：", "高齢で併存疾患があり多剤を使う患者、服薬遵守の問題、経済的・社会的要因。副作用は遅れて気づかれる。"),
    ("有効性と有用性は別物：", "理想的な条件で測った効果は、日常診療で観察される効果とは異なる。"),
    ("実例：", "バイオックス、SGLT2阻害薬とフルニエ壊疽、抗うつ薬と出版バイアス、オピオイド危機、免疫療法の毒性、GLP-1受容体作動薬。"),
    ("代替評価項目の問題：", "検査値が改善しても、実際の臨床的利益がないことがある。")],
   "本当の科学は、管理された研究と実生活を結ぶ橋の上で始まる。"),
})

# 74 — Secret deals of global pharma giants are being exposed
CARDS['gizlianlasma'] = ('dark', {
 'en': D("USA · MOST FAVORED NATION", "The 'secret deals' of the global drug giants are being exposed", "The bargaining behind closed doors between the White House and Big Pharma is coming to light. How will this billion-dollar fight affect our pockets?",
   [("17", "giant drug companies at the table, signing 'voluntary discount' agreements"), ("$350 a month", "new price of weight-loss and diabetes drugs (was $1,000–1,350): 50–75% cheaper"), ("$353,000", "launch prices of new rare-disease drugs remain astronomical"), ("4%", "average annual list-price rise on hundreds of chronic-disease drugs outside the deals")], None,
   [("What is happening:", "the 'American citizen will not pay more than the cheapest price in Europe' policy has shaken the industry. The Senate and health authorities are preparing to expose 'secret concessions' behind the deals."),
    ("The contradiction:", "a price lowered on one side is raised on the other."),
    ("The industry's threat:", "'if prices are squeezed, we will close laboratories': less investment, less discovery.")],
   "The solution: real transparency, independent oversight and patient-centred policies."),
 'de': D("USA · MOST FAVORED NATION", "Die „Geheimabkommen“ der globalen Pharmariesen fliegen auf", "Die Verhandlungen hinter verschlossenen Türen zwischen Weißem Haus und Big Pharma kommen ans Licht. Wie trifft dieser Milliardenkampf unseren Geldbeutel?",
   [("17", "Pharmariesen am Tisch, die „freiwillige Rabatt“-Abkommen unterzeichnen"), ("350 $ im Monat", "neuer Preis für Abnehm- und Diabetesmittel (zuvor 1.000–1.350 $): 50–75 % billiger"), ("353.000 $", "Einführungspreise neuer Medikamente für seltene Krankheiten bleiben astronomisch"), ("4 %", "durchschnittliche jährliche Listenpreiserhöhung bei Hunderten Medikamenten außerhalb der Abkommen")], None,
   [("Was geschieht:", "Die Politik „Amerikaner zahlen nicht mehr als den niedrigsten Preis in Europa“ erschüttert die Branche. Senat und Gesundheitsbehörden wollen „geheime Zugeständnisse“ hinter den Abkommen offenlegen."),
    ("Der Widerspruch:", "Ein Preis wird auf der einen Seite gesenkt und auf der anderen wieder herausgeholt."),
    ("Die Drohung der Branche:", "„Wenn die Preise so gedrückt werden, schließen wir Labore“: weniger Investition, weniger Entdeckung.")],
   "Die Lösung: echte Transparenz, unabhängige Kontrolle und patientenorientierte Politik."),
 'es': D("EE. UU. · NACIÓN MÁS FAVORECIDA", "Salen a la luz los «acuerdos secretos» de los gigantes farmacéuticos", "Las negociaciones a puerta cerrada entre la Casa Blanca y la gran industria farmacéutica empiezan a conocerse. ¿Cómo afectará a nuestro bolsillo esta guerra de miles de millones?",
   [("17", "gigantes farmacéuticos en la mesa, firmando acuerdos de «descuento voluntario»"), ("350 $ al mes", "nuevo precio de los fármacos para adelgazar y la diabetes (antes 1.000–1.350 $): 50–75 % más baratos"), ("353.000 $", "los precios de lanzamiento de nuevos fármacos para enfermedades raras siguen siendo astronómicos"), ("4 %", "subida anual media del precio de lista en cientos de fármacos crónicos fuera de los acuerdos")], None,
   [("Qué está pasando:", "la política de que «el ciudadano estadounidense no pagará más que el precio más bajo de Europa» sacude al sector. El Senado y las autoridades sanitarias preparan la revelación de «concesiones secretas»."),
    ("La contradicción:", "el precio que se baja por un lado se recupera por otro."),
    ("La amenaza del sector:", "«si se presionan tanto los precios, cerraremos laboratorios»: menos inversión, menos descubrimiento.")],
   "La solución: transparencia real, control independiente y políticas centradas en el paciente."),
 'ru': D("США · РЕЖИМ НАИБОЛЬШЕГО БЛАГОПРИЯТСТВОВАНИЯ", "«Тайные соглашения» мировых фармгигантов выходят наружу", "Закулисный торг между Белым домом и «Биг Фармой» становится достоянием гласности. Как эта война на миллиарды отразится на нашем кошельке?",
   [("17", "фармгигантов за столом переговоров подписывают соглашения о «добровольных скидках»"), ("350 $ в месяц", "новая цена препаратов для похудения и от диабета (было 1000–1350 $): дешевле на 50–75 %"), ("353 000 $", "стартовые цены новых лекарств от редких болезней остаются астрономическими"), ("4 %", "среднее годовое повышение цен на сотни препаратов вне соглашений")], None,
   [("Что происходит:", "политика «американец не заплатит больше самой низкой цены в Европе» потрясла отрасль. Сенат и органы здравоохранения готовятся раскрыть «тайные уступки»."),
    ("Противоречие:", "сниженную в одном месте цену отыгрывают в другом."),
    ("Угроза отрасли:", "«если цены так зажмут, мы закроем лаборатории»: меньше инвестиций, меньше открытий.")],
   "Решение: реальная прозрачность, независимый контроль и политика, ориентированная на пациента."),
 'zh': D("美国 · 最惠国政策", "全球制药巨头的“秘密协议”正在曝光", "白宫与大型制药企业之间的闭门谈判正浮出水面。这场数十亿美元的博弈将怎样影响我们的钱包？",
   [("17家", "制药巨头坐上谈判桌，签署“自愿降价”协议"), ("每月350美元", "减重和糖尿病药物的新价格（原为1000–1350美元）：便宜50–75%"), ("35.3万美元", "罕见病新药的上市价仍是天文数字"), ("4%", "协议之外数百种慢性病药物的年均标价涨幅")], None,
   [("发生了什么：", "“美国公民支付的药价不得高于欧洲最低价”的政策震动了整个行业。参议院和卫生主管部门正准备披露协议背后的“秘密让步”。"),
    ("矛盾之处：", "一边降下来的价格，在另一边又涨了回去。"),
    ("行业的威胁：", "“价格压得这么低，我们就关闭实验室”：投资减少，发现减少。")],
   "出路：真正的透明、独立的监督和以患者为中心的政策。"),
 'hi': D("अमेरिका · मोस्ट फेवर्ड नेशन", "वैश्विक दवा दिग्गजों के “गोपनीय समझौते” उजागर हो रहे हैं", "व्हाइट हाउस और बड़ी दवा कंपनियों के बीच बंद दरवाज़ों के पीछे की सौदेबाज़ी सामने आ रही है। अरबों डॉलर की यह लड़ाई हमारी जेब पर क्या असर डालेगी?",
   [("17", "बड़ी दवा कंपनियाँ मेज़ पर, “स्वैच्छिक छूट” समझौतों पर हस्ताक्षर"), ("350 डॉलर प्रति माह", "वज़न और मधुमेह की दवाओं की नई कीमत (पहले 1,000–1,350 डॉलर): 50–75% सस्ती"), ("3,53,000 डॉलर", "दुर्लभ रोगों की नई दवाओं की शुरुआती कीमतें अब भी आसमान पर"), ("4%", "समझौतों से बाहर सैकड़ों दवाओं की सूची-कीमत में औसत वार्षिक वृद्धि")], None,
   [("क्या हो रहा है:", "“अमेरिकी नागरिक यूरोप की सबसे कम कीमत से अधिक नहीं देगा” नीति ने उद्योग को हिला दिया है। सीनेट और स्वास्थ्य प्राधिकरण समझौतों के पीछे की “गोपनीय रियायतें” उजागर करने की तैयारी में हैं।"),
    ("विरोधाभास:", "एक तरफ़ घटाई गई कीमत दूसरी तरफ़ वसूल ली जाती है।"),
    ("उद्योग की धमकी:", "“कीमतें इतनी दबाईं तो प्रयोगशालाएँ बंद कर देंगे”: कम निवेश, कम खोज।")],
   "समाधान: सच्ची पारदर्शिता, स्वतंत्र निगरानी और मरीज़-केंद्रित नीतियाँ।"),
 'ja': D("米国 · 最恵国待遇", "世界的製薬大手の「秘密合意」が明るみに", "ホワイトハウスと巨大製薬企業の密室での取引が表に出つつある。数十億ドル規模のこの攻防は、私たちの財布にどう響くのか",
   [("17社", "の製薬大手が交渉の席に着き、「自主的値下げ」の合意に署名"), ("月350ドル", "肥満・糖尿病治療薬の新価格（従来は1,000〜1,350ドル）：50〜75%安い"), ("35万3千ドル", "希少疾患の新薬の発売価格は依然として桁外れ"), ("4%", "合意の対象外となる数百の慢性疾患薬での年平均の定価引き上げ")], None,
   [("何が起きているか：", "「米国民は欧州の最安値より高く払わない」という政策が業界を揺さぶっている。上院と保健当局は、合意の裏にある「秘密の譲歩」を明らかにしようとしている。"),
    ("矛盾：", "一方で下げた価格が、他方で上乗せされる。"),
    ("業界の脅し：", "「これほど価格を抑えるなら研究所を閉じる」。投資が減り、発見も減る。")],
   "解決策：本当の透明性、独立した監督、患者中心の政策。"),
})

# 75 — Vitamin B12
CARDS['b12'] = ('navy', {
 'en': D("VITAMIN B12", "B12 deficiency, or a B12 testing epidemic?", "Not every low B12 result means disease", None, None,
   [("Real risk groups:", "the very old, vegans and strict vegetarians, pernicious anaemia, stomach or bowel surgery, diabetics on metformin, long-term PPI users, coeliac and Crohn's disease."),
    ("Alarm signs:", "numbness and tingling in hands and feet, balance and walking problems, memory problems, fatigue and breathlessness, pallor and macrocytic anaemia, a sore tongue."),
    ("What you should know:", "no single test proves deficiency; a normal level does not rule it out; a low result is not always disease and does not always need injections."),
    ("Testing:", "serum B12 first; for borderline results, methylmalonic acid and homocysteine. Do not test without clinical findings."),
    ("Treatment:", "necessary if deficiency is certain. High-dose oral B12 works in most patients; injections are preferred in malabsorption.")],
   "Treat the patient, not the laboratory result."),
 'de': D("VITAMIN B12", "B12-Mangel oder eine Epidemie der B12-Tests?", "Nicht jeder niedrige B12-Wert bedeutet Krankheit", None, None,
   [("Echte Risikogruppen:", "Hochbetagte, Veganer und strenge Vegetarier, perniziöse Anämie, Magen- oder Darmoperationen, Diabetiker unter Metformin, Langzeitanwender von PPI, Zöliakie und Morbus Crohn."),
    ("Alarmzeichen:", "Taubheit und Kribbeln an Händen und Füßen, Gleichgewichts- und Gangstörungen, Gedächtnisprobleme, Müdigkeit und Atemnot, Blässe und makrozytäre Anämie, Zungenbrennen."),
    ("Was man wissen sollte:", "Kein einzelner Test beweist den Mangel; ein normaler Wert schließt ihn nicht aus; ein niedriger Wert ist nicht immer Krankheit und erfordert nicht immer Spritzen."),
    ("Tests:", "zuerst Serum-B12; bei Grenzwerten Methylmalonsäure und Homocystein. Kein Test ohne klinischen Befund."),
    ("Therapie:", "nötig bei gesichertem Mangel. Hochdosiertes orales B12 wirkt bei den meisten; bei Malabsorption sind Injektionen vorzuziehen.")],
   "Behandeln Sie den Patienten, nicht den Laborwert."),
 'es': D("VITAMINA B12", "¿Déficit de B12 o epidemia de análisis de B12?", "No todo resultado bajo de B12 significa enfermedad", None, None,
   [("Grupos de riesgo reales:", "personas muy mayores, veganos y vegetarianos estrictos, anemia perniciosa, cirugía gástrica o intestinal, diabéticos con metformina, uso prolongado de IBP, celiaquía y Crohn."),
    ("Signos de alarma:", "entumecimiento y hormigueo en manos y pies, alteraciones del equilibrio y la marcha, problemas de memoria, cansancio y disnea, palidez y anemia macrocítica, glositis."),
    ("Lo que conviene saber:", "no hay una única prueba definitiva; un nivel normal no descarta el déficit; un resultado bajo no siempre es enfermedad ni exige siempre inyecciones."),
    ("Pruebas:", "primero B12 sérica; en resultados limítrofes, ácido metilmalónico y homocisteína. No pida la prueba sin hallazgos clínicos."),
    ("Tratamiento:", "necesario si el déficit es seguro. La B12 oral a dosis altas es eficaz en la mayoría; en la malabsorción se prefieren las inyecciones.")],
   "Trate al paciente, no al resultado de laboratorio."),
 'ru': D("ВИТАМИН B12", "Дефицит B12 или эпидемия анализов на B12?", "Не каждый низкий результат B12 означает болезнь", None, None,
   [("Настоящие группы риска:", "люди преклонного возраста, веганы и строгие вегетарианцы, пернициозная анемия, операции на желудке или кишечнике, диабетики на метформине, длительный приём ИПП, целиакия и болезнь Крона."),
    ("Тревожные признаки:", "онемение и покалывание в кистях и стопах, нарушения равновесия и ходьбы, проблемы с памятью, слабость и одышка, бледность и макроцитарная анемия, воспаление языка."),
    ("Что нужно знать:", "нет одного теста, который точно доказывает дефицит; нормальный уровень его не исключает; низкий результат не всегда болезнь и не всегда требует инъекций."),
    ("Анализы:", "сначала B12 в сыворотке; при пограничных значениях метилмалоновая кислота и гомоцистеин. Не назначайте анализ без клинических признаков."),
    ("Лечение:", "необходимо при подтверждённом дефиците. Высокие дозы B12 внутрь эффективны у большинства; при мальабсорбции предпочтительны инъекции.")],
   "Лечите пациента, а не результат анализа."),
 'zh': D("维生素B12", "是B12缺乏，还是B12检测泛滥？", "并非每个偏低的B12结果都意味着疾病", None, None,
   [("真正的高危人群：", "高龄老人、纯素和严格素食者、恶性贫血、做过胃肠手术者、服用二甲双胍的糖尿病患者、长期使用质子泵抑制剂者、乳糜泻和克罗恩病患者。"),
    ("警示表现：", "手脚麻木刺痛、平衡和行走困难、记忆问题、乏力气短、面色苍白和大细胞性贫血、舌炎。"),
    ("需要知道：", "没有单一检测能确诊缺乏；水平正常不能排除缺乏；结果偏低不一定是疾病，也不一定需要打针。"),
    ("检测：", "先查血清B12；临界结果再查甲基丙二酸和同型半胱氨酸。没有临床表现不要检测。"),
    ("治疗：", "确诊缺乏时必须治疗。大剂量口服B12对多数患者有效；吸收不良者首选注射。")],
   "治疗的是患者，而不是化验单。"),
 'hi': D("विटामिन B12", "B12 की कमी, या B12 जाँच की महामारी?", "हर कम B12 परिणाम का मतलब रोग नहीं होता", None, None,
   [("असली जोखिम समूह:", "बहुत बुज़ुर्ग, वीगन और सख़्त शाकाहारी, पर्निशियस एनीमिया, पेट या आँत की सर्जरी, मेटफ़ॉर्मिन लेने वाले मधुमेह रोगी, लंबे समय से PPI लेने वाले, सीलिएक और क्रोन रोग।"),
    ("चेतावनी के लक्षण:", "हाथ-पैरों में सुन्नपन और झुनझुनी, संतुलन और चलने में कठिनाई, याददाश्त की समस्या, थकान और साँस फूलना, पीलापन और मैक्रोसाइटिक एनीमिया, जीभ में सूजन।"),
    ("जानने योग्य:", "कमी सिद्ध करने वाली कोई एक निश्चित जाँच नहीं; सामान्य स्तर कमी को ख़ारिज नहीं करता; कम परिणाम हमेशा रोग नहीं और हमेशा इंजेक्शन की ज़रूरत नहीं।"),
    ("जाँच:", "पहले सीरम B12; सीमांत परिणाम में मिथाइलमैलोनिक एसिड और होमोसिस्टीन। नैदानिक लक्षणों के बिना जाँच न कराएँ।"),
    ("उपचार:", "कमी निश्चित हो तो ज़रूरी। अधिकांश मरीज़ों में ऊँची खुराक की मौखिक B12 प्रभावी है; अवशोषण की गड़बड़ी में इंजेक्शन बेहतर।")],
   "प्रयोगशाला के परिणाम का नहीं, मरीज़ का इलाज करें।"),
 'ja': D("ビタミンB12", "B12不足か、それともB12検査の流行か", "B12の値が低いからといって、必ずしも病気ではない", None, None,
   [("本当のリスク群：", "超高齢者、ヴィーガンと厳格な菜食の人、悪性貧血、胃や腸の手術歴、メトホルミン服用中の糖尿病患者、PPIの長期使用者、セリアック病・クローン病の患者。"),
    ("警告所見：", "手足のしびれやチクチク感、平衡・歩行の障害、記憶の問題、倦怠感と息切れ、蒼白と大球性貧血、舌炎。"),
    ("知っておくべきこと：", "欠乏を確定できる単一の検査はない。正常値でも欠乏は否定できない。低値が常に病気とは限らず、常に注射が必要なわけでもない。"),
    ("検査：", "まず血清B12。境界値ならメチルマロン酸とホモシステイン。臨床所見がなければ検査しない。"),
    ("治療：", "欠乏が確実なら治療が必要。高用量の経口B12は多くの患者で有効。吸収障害がある場合は注射を選ぶ。")],
   "検査結果ではなく、患者を治療する。"),
})

# 76 — Branded doctors, branded fraudsters
CARDS['markali'] = ('dark', {
 'en': D(BM['en'], "Branded doctors, branded fraudsters", "Both protect their own interests, not your health", None, None,
   [("Branded doctors", "carry the brand of drug companies, the industry and the system: congresses, hotels and luxury invitations, sponsored training, consultancy fees, free samples and marketing dressed up as science. They inflate diseases, write prescriptions and feed the system."),
    ("Branded fraudsters", "sell the unscientific, fear and hope: unscientific treatments, serums, injections and detoxes, 'ancient natural wisdom', unlicensed practitioners and fake information from social-media influencers. They trade in hope and steal your health and your money."),
    ("Whether with a drug or a miracle, the aim is the same:", "to turn you into a customer.")],
   "Your health is not a brand. Trust scientific evidence, get a second opinion, look at information rather than advertising."),
 'de': D(BM['de'], "Marken-Ärzte, Marken-Betrüger", "Beide schützen ihre eigenen Interessen, nicht Ihre Gesundheit", None, None,
   [("Marken-Ärzte", "tragen die Marke der Pharmafirmen, der Industrie und des Systems: Kongresse, Hotels und Luxuseinladungen, gesponserte Fortbildungen, Beraterhonorare, Gratismuster und als Wissenschaft getarntes Marketing. Sie blähen Krankheiten auf, verordnen und nähren das System."),
    ("Marken-Betrüger", "verkaufen Unwissenschaftliches, Angst und Hoffnung: unwissenschaftliche Therapien, Seren, Spritzen und Detox, „uraltes Naturwissen“, Anwender ohne Zulassung und Falschinformation von Influencern. Sie handeln mit Hoffnung und stehlen Gesundheit und Geld."),
    ("Ob mit Medikament oder Wunder, das Ziel ist dasselbe:", "Sie zum Kunden zu machen.")],
   "Ihre Gesundheit ist keine Marke. Vertrauen Sie wissenschaftlicher Evidenz, holen Sie eine Zweitmeinung ein, achten Sie auf Information statt auf Werbung."),
 'es': D(BM['es'], "Médicos de marca, estafadores de marca", "Ambos protegen sus propios intereses, no su salud", None, None,
   [("Los médicos de marca", "llevan la marca de las farmacéuticas, la industria y el sistema: congresos, hoteles e invitaciones de lujo, formación patrocinada, honorarios de consultoría, muestras gratuitas y marketing disfrazado de ciencia. Agrandan las enfermedades, recetan y alimentan el sistema."),
    ("Los estafadores de marca", "venden lo acientífico, el miedo y la esperanza: tratamientos sin base científica, sueros, inyecciones y «detox», «sabiduría natural ancestral», practicantes sin titulación e información falsa de influencers. Trafican con la esperanza y le roban la salud y el dinero."),
    ("Con un fármaco o con un milagro, el objetivo es el mismo:", "convertirle en cliente.")],
   "Su salud no es una marca. Confíe en la evidencia científica, pida una segunda opinión y fíjese en la información, no en la publicidad."),
 'ru': D(BM['ru'], "Брендовые врачи, брендовые мошенники", "И те и другие защищают свои интересы, а не ваше здоровье", None, None,
   [("Брендовые врачи", "несут на себе марку фармкомпаний, индустрии и системы: конгрессы, отели и роскошные приглашения, спонсируемое обучение, гонорары за консультации, бесплатные образцы и маркетинг под видом науки. Они раздувают болезни, выписывают лекарства и кормят систему."),
    ("Брендовые мошенники", "продают ненаучное, страх и надежду: ненаучные методы, сыворотки, уколы и «детокс», «древнюю природную мудрость», практиков без лицензий и ложную информацию от блогеров. Они торгуют надеждой и крадут ваше здоровье и деньги."),
    ("С лекарством или с чудом, цель одна:", "превратить вас в клиента.")],
   "Ваше здоровье не бренд. Доверяйте научным данным, получайте второе мнение, смотрите на информацию, а не на рекламу."),
 'zh': D(BM['zh'], "“名牌”医生与“名牌”骗子", "两者保护的都是自己的利益，而不是你的健康", None, None,
   [("“名牌”医生", "身上贴着药企、行业和体制的牌子：学术会议、酒店和豪华招待、赞助培训、咨询费、免费样品，以及伪装成科学的营销。他们夸大疾病、开出处方、喂养这套体系。"),
    ("“名牌”骗子", "兜售反科学、恐惧和希望：没有科学依据的疗法、点滴、针剂和排毒、“古老的自然智慧”、无资质的从业者，以及网红散布的虚假信息。他们贩卖希望，偷走你的健康和金钱。"),
    ("不管靠药物还是靠奇迹，目的都一样：", "把你变成顾客。")],
   "你的健康不是品牌。相信科学证据，寻求第二诊疗意见，看信息而不是看广告。"),
 'hi': D(BM['hi'], "ब्रांडेड डॉक्टर, ब्रांडेड ठग", "दोनों आपके स्वास्थ्य की नहीं, अपने हितों की रक्षा करते हैं", None, None,
   [("ब्रांडेड डॉक्टर", "दवा कंपनियों, उद्योग और व्यवस्था का ब्रांड ढोते हैं: सम्मेलन, होटल और आलीशान न्योते, प्रायोजित प्रशिक्षण, परामर्श शुल्क, मुफ़्त नमूने और विज्ञान के वेश में विपणन। वे बीमारियों को बढ़ा-चढ़ाकर दिखाते, दवाएँ लिखते और व्यवस्था को पोसते हैं।"),
    ("ब्रांडेड ठग", "अवैज्ञानिक बातें, डर और उम्मीद बेचते हैं: अवैज्ञानिक उपचार, सीरम, इंजेक्शन और डिटॉक्स, “प्राचीन प्राकृतिक ज्ञान”, बिना लाइसेंस के उपचारक और सोशल मीडिया इन्फ़्लुएंसरों की झूठी जानकारी। वे उम्मीद का धंधा करते और आपका स्वास्थ्य और पैसा चुराते हैं।"),
    ("दवा से हो या चमत्कार से, मक़सद एक ही है:", "आपको ग्राहक बनाना।")],
   "आपका स्वास्थ्य कोई ब्रांड नहीं। वैज्ञानिक प्रमाण पर भरोसा करें, दूसरी राय लें, विज्ञापन नहीं, जानकारी देखें।"),
 'ja': D(BM['ja'], "ブランドを背負う医師、ブランドを売るペテン師", "どちらも守っているのはあなたの健康ではなく、自分の利益である", None, None,
   [("ブランドを背負う医師は、", "製薬企業、業界、制度のブランドを身にまとう。学会、ホテル、豪華な接待、協賛付きの研修、コンサルタント料、試供品、科学を装ったマーケティング。病気を大きく見せ、薬を処方し、仕組みを肥やす。"),
    ("ブランドを売るペテン師は、", "非科学と恐怖と希望を売る。科学的根拠のない治療、点滴、注射、デトックス、「古来の自然の知恵」、無資格の施術者、インフルエンサーの偽情報。希望を商売にし、健康とお金を奪う。"),
    ("薬であれ奇跡であれ、目的は同じ：", "あなたを顧客に変えること。")],
   "あなたの健康はブランドではない。科学的根拠を信頼し、セカンドオピニオンを求め、広告ではなく情報を見よう。"),
})

# 77 — Bribery in the pharmaceutical industry
CARDS['rusvet2'] = ('burg', {
 'en': D("HEALTH, OR TRADE?", "Bribery scandals in the pharmaceutical industry", "Dark relationships in the drug sector threaten both patients and public health",
   [("Up to 10%", "of global health spending is lost to corruption in the health sector, according to the World Health Organization")], None,
   [("Bribes for prescriptions:", "doctors are given money, gifts, holidays and congress support in return for prescriptions."),
    ("The result:", "unnecessary and expensive drugs are prescribed and drug companies earn millions; the social security system loses and resources are wasted."),
    ("Patients are harmed:", "they are exposed to unnecessary drugs, side effects and wrong treatments."),
    ("Society loses trust:", "confidence in the health system is shaken and ethical values collapse."),
    ("Who benefits?", "companies distort competition with unfair gains and capture the market.")],
   "Is our health for sale?"),
 'de': D("GESUNDHEIT ODER GESCHÄFT?", "Bestechungsskandale in der Pharmaindustrie", "Dunkle Beziehungen im Arzneimittelsektor bedrohen Patienten und die öffentliche Gesundheit",
   [("Bis zu 10 %", "der weltweiten Gesundheitsausgaben gehen laut Weltgesundheitsorganisation durch Korruption im Gesundheitswesen verloren")], None,
   [("Bestechung für Rezepte:", "Ärzte erhalten Geld, Geschenke, Urlaube und Kongressunterstützung im Gegenzug für Verordnungen."),
    ("Die Folge:", "Unnötige und teure Medikamente werden verordnet, Pharmafirmen verdienen Millionen; die Sozialversicherung verliert, Ressourcen werden verschwendet."),
    ("Patienten nehmen Schaden:", "Sie sind unnötigen Medikamenten, Nebenwirkungen und falschen Behandlungen ausgesetzt."),
    ("Die Gesellschaft verliert Vertrauen:", "Das Vertrauen in das Gesundheitssystem wird erschüttert, ethische Werte brechen zusammen."),
    ("Wer profitiert?", "Unternehmen verzerren mit unlauteren Gewinnen den Wettbewerb und erobern den Markt.")],
   "Ist unsere Gesundheit käuflich?"),
 'es': D("¿SALUD O NEGOCIO?", "Escándalos de soborno en la industria farmacéutica", "Las relaciones oscuras del sector farmacéutico amenazan a los pacientes y a la salud pública",
   [("Hasta el 10 %", "del gasto sanitario mundial se pierde por la corrupción en el sector salud, según la Organización Mundial de la Salud")], None,
   [("Sobornos por recetas:", "se ofrece a los médicos dinero, regalos, vacaciones y apoyo para congresos a cambio de recetar."),
    ("El resultado:", "se recetan fármacos innecesarios y caros y las compañías ganan millones; la seguridad social pierde y se derrochan recursos."),
    ("Los pacientes salen perjudicados:", "quedan expuestos a fármacos innecesarios, efectos adversos y tratamientos equivocados."),
    ("La sociedad pierde confianza:", "se resiente la confianza en el sistema sanitario y se derrumban los valores éticos."),
    ("¿A quién beneficia?", "las empresas distorsionan la competencia con ganancias ilícitas y se adueñan del mercado.")],
   "¿Está en venta nuestra salud?"),
 'ru': D("ЗДОРОВЬЕ ИЛИ ТОРГОВЛЯ?", "Скандалы со взятками в фармацевтической промышленности", "Тёмные связи в фармсекторе угрожают и пациентам, и общественному здоровью",
   [("До 10 %", "мировых расходов на здравоохранение теряется из-за коррупции в отрасли, по данным Всемирной организации здравоохранения")], None,
   [("Взятки за рецепты:", "врачам дают деньги, подарки, отдых и поддержку участия в конгрессах в обмен на назначения."),
    ("Результат:", "назначаются ненужные и дорогие лекарства, компании зарабатывают миллионы; система соцстрахования несёт убытки, ресурсы расходуются впустую."),
    ("Страдают пациенты:", "они получают ненужные лекарства, побочные эффекты и неверное лечение."),
    ("Общество теряет доверие:", "подрывается доверие к системе здравоохранения, рушатся этические ценности."),
    ("Кому это выгодно?", "компании искажают конкуренцию нечестной прибылью и захватывают рынок.")],
   "Наше здоровье продаётся?"),
 'zh': D("是健康，还是生意？", "制药业的贿赂丑闻", "医药行业的暗箱关系既威胁患者，也威胁公众健康",
   [("高达10%", "世界卫生组织称，全球卫生支出中有这么大一部分因卫生领域的腐败而流失")], None,
   [("处方回扣：", "以金钱、礼品、度假和会议赞助换取医生开处方。"),
    ("结果：", "不必要的昂贵药品被开出，药企赚取巨额利润；社保受损，资源被浪费。"),
    ("患者受害：", "他们被迫使用不必要的药物，承受副作用和错误治疗。"),
    ("社会失去信任：", "人们对卫生体系的信心动摇，伦理价值崩塌。"),
    ("谁在受益？", "企业靠不正当收益扭曲竞争、占领市场。")],
   "我们的健康是可以出售的吗？"),
 'hi': D("स्वास्थ्य, या व्यापार?", "दवा उद्योग में रिश्वत कांड", "दवा क्षेत्र के अँधेरे रिश्ते मरीज़ों और जनस्वास्थ्य, दोनों के लिए ख़तरा हैं",
   [("10% तक", "विश्व स्वास्थ्य संगठन के अनुसार वैश्विक स्वास्थ्य खर्च का इतना हिस्सा स्वास्थ्य क्षेत्र के भ्रष्टाचार में चला जाता है")], None,
   [("नुस्खे के बदले रिश्वत:", "डॉक्टरों को नुस्खे के बदले पैसा, उपहार, छुट्टियाँ और सम्मेलनों का खर्च दिया जाता है।"),
    ("नतीजा:", "अनावश्यक और महँगी दवाएँ लिखी जाती हैं, कंपनियाँ करोड़ों कमाती हैं; सामाजिक सुरक्षा को नुकसान और संसाधनों की बर्बादी होती है।"),
    ("मरीज़ों को नुकसान:", "वे अनावश्यक दवाओं, दुष्प्रभावों और ग़लत उपचार के शिकार होते हैं।"),
    ("समाज का भरोसा टूटता है:", "स्वास्थ्य व्यवस्था पर विश्वास डगमगाता है और नैतिक मूल्य ढहते हैं।"),
    ("फ़ायदा किसे?", "कंपनियाँ अनुचित कमाई से प्रतिस्पर्धा बिगाड़ती और बाज़ार पर क़ब्ज़ा करती हैं।")],
   "क्या हमारा स्वास्थ्य बिकाऊ है?"),
 'ja': D("健康か、商売か", "製薬業界の贈賄スキャンダル", "医薬品業界の不透明な関係は、患者と公衆衛生の両方を脅かす",
   [("最大10%", "世界保健機関によれば、世界の医療費のこれだけの割合が医療分野の腐敗で失われている")], None,
   [("処方の見返りの賄賂：", "医師に、処方と引き換えに金銭、贈り物、旅行、学会参加の支援が提供される。"),
    ("その結果：", "不要で高価な薬が処方され、製薬企業は巨額の利益を得る。社会保障は損失を被り、資源が浪費される。"),
    ("患者が害を受ける：", "不要な薬、副作用、誤った治療にさらされる。"),
    ("社会は信頼を失う：", "医療制度への信頼が揺らぎ、倫理的価値が崩れる。"),
    ("得をするのは誰か：", "企業は不当な利益で競争をゆがめ、市場を手に入れる。")],
   "私たちの健康は売り物なのか。"),
})

# 78 — Sanofi withdraws from the fast-track voucher programme
CARDS['sanofi'] = ('navy', {
 'en': D("AN FDA EARTHQUAKE", "Sanofi pulls out of a fast-track approval programme 'in the shadow of politics'", "Based on reporting by STAT News and other media", None, None,
   [("The drug:", "teplizumab (Tzield), a type 1 diabetes drug intended to halt progression of the disease."),
    ("A split inside the FDA:", "career scientists said yes, concluding that benefit outweighed risk and approval should be granted; senior management said no, citing uncertainties, cancer risk and virus activation."),
    ("Sanofi's request:", "it withdrew the application under the programme, to protect the drug's reputation and to avoid political conflict, and moved to the standard route."),
    ("The voucher programme (CNPV):", "a fast route with reviews lasting weeks. Reported consequences: rushed scientific reviews, administrative chaos and political interference.")]),
 'de': D("EIN FDA-BEBEN", "Sanofi zieht sich aus einem Schnellzulassungsprogramm „im Schatten der Politik“ zurück", "Nach Berichten von STAT News und anderen Medien", None, None,
   [("Das Medikament:", "Teplizumab (Tzield), ein Mittel bei Typ-1-Diabetes, das das Fortschreiten der Krankheit aufhalten soll."),
    ("Riss innerhalb der FDA:", "Die Fachwissenschaftler sagten Ja (Nutzen größer als Risiko, Zulassung erteilen); die Leitungsebene sagte Nein und verwies auf Unsicherheiten, Krebsrisiko und Virusaktivierung."),
    ("Sanofis Antrag:", "Rücknahme des Antrags im Programm, um den Ruf des Medikaments zu schützen und politische Konflikte zu vermeiden; Wechsel auf den Standardweg."),
    ("Das Gutscheinprogramm (CNPV):", "ein Schnellverfahren mit Prüfungen binnen Wochen. Berichtete Folgen: überhastete wissenschaftliche Prüfungen, Verwaltungschaos und politische Einflussnahme.")]),
 'es': D("TERREMOTO EN LA FDA", "Sanofi se retira de un programa de aprobación rápida «a la sombra de la política»", "Según informaciones de STAT News y otros medios", None, None,
   [("El fármaco:", "teplizumab (Tzield), para la diabetes tipo 1, destinado a detener la progresión de la enfermedad."),
    ("Fractura dentro de la FDA:", "los científicos de carrera dijeron sí (beneficio mayor que el riesgo, debe aprobarse); la alta dirección dijo no, alegando incertidumbres, riesgo de cáncer y activación viral."),
    ("La petición de Sanofi:", "retiró la solicitud dentro del programa para proteger la reputación del fármaco y evitar conflictos políticos, y pasó a la vía estándar."),
    ("El programa de bonos (CNPV):", "una vía rápida con revisiones de semanas. Consecuencias señaladas: revisiones científicas apresuradas, caos administrativo e injerencia política.")]),
 'ru': D("ЗЕМЛЕТРЯСЕНИЕ В FDA", "Sanofi выходит из программы ускоренного одобрения «в тени политики»", "По сообщениям STAT News и других СМИ", None, None,
   [("Препарат:", "теплизумаб (Tzield), средство при диабете 1-го типа, призванное остановить прогрессирование болезни."),
    ("Раскол внутри FDA:", "кадровые учёные сказали «да» (польза превышает риск, нужно одобрить); высшее руководство сказало «нет», сославшись на неопределённости, риск рака и активацию вирусов."),
    ("Просьба Sanofi:", "компания отозвала заявку в рамках программы, чтобы защитить репутацию препарата и избежать политических конфликтов, и перешла на стандартный путь."),
    ("Ваучерная программа (CNPV):", "ускоренный путь с рассмотрением за недели. Сообщаемые последствия: спешка в научной экспертизе, административный хаос и политическое вмешательство.")]),
 'zh': D("FDA大地震", "赛诺菲退出“政治阴影下”的快速审批项目", "据STAT News等媒体报道", None, None,
   [("药物：", "替普利珠单抗（Tzield），一种旨在阻止病情进展的1型糖尿病药物。"),
    ("FDA内部的裂痕：", "职业科学家表示同意，认为获益大于风险，应予批准；高层管理者表示反对，理由是存在不确定性、癌症风险和病毒激活。"),
    ("赛诺菲的请求：", "为保护药物声誉、避免政治纷争，撤回了在该项目下的申请，改走常规途径。"),
    ("凭证项目（CNPV）：", "审评只需数周的快速通道。据报道的后果：科学审评仓促、行政混乱和政治干预。")]),
 'hi': D("FDA में भूचाल", "सनोफ़ी “राजनीति की छाया” वाले त्वरित मंज़ूरी कार्यक्रम से हट रही है", "STAT News और अन्य मीडिया की रिपोर्टों के अनुसार", None, None,
   [("दवा:", "टेप्लिज़ुमैब (Tzield), टाइप 1 मधुमेह की दवा, जिसका उद्देश्य रोग की प्रगति रोकना है।"),
    ("FDA के भीतर दरार:", "कैरियर वैज्ञानिकों ने हाँ कहा (लाभ जोखिम से अधिक, मंज़ूरी दी जाए); शीर्ष प्रबंधन ने नहीं कहा और अनिश्चितताओं, कैंसर के जोखिम और वायरस सक्रियण का हवाला दिया।"),
    ("सनोफ़ी का अनुरोध:", "दवा की साख बचाने और राजनीतिक खींचतान से बचने के लिए कार्यक्रम के तहत आवेदन वापस लिया और सामान्य मार्ग अपनाया।"),
    ("वाउचर कार्यक्रम (CNPV):", "हफ़्तों में समीक्षा वाला तेज़ मार्ग। बताए गए परिणाम: जल्दबाज़ी में वैज्ञानिक समीक्षा, प्रशासनिक अराजकता और राजनीतिक दख़ल।")]),
 'ja': D("FDAに激震", "サノフィ、「政治の影」が差す迅速承認プログラムから撤退", "STAT Newsほかの報道による", None, None,
   [("対象の薬：", "テプリズマブ（Tzield）。病気の進行を止めることを目指す1型糖尿病治療薬。"),
    ("FDA内部の亀裂：", "生え抜きの科学者は賛成（利益がリスクを上回り、承認すべき）。上層部は不確実性、がんリスク、ウイルスの活性化を理由に反対した。"),
    ("サノフィの申し出：", "薬の評価を守り、政治的な対立を避けるため、プログラムでの申請を取り下げ、通常の審査経路に移った。"),
    ("バウチャー制度（CNPV）：", "審査が数週間で終わる迅速経路。報じられた結果は、拙速な科学的審査、事務の混乱、政治的介入。")]),
})

# 79 — Alcohol kills
CARDS['alkol'] = ('dark', {
 'en': D("THE EPIDEMIC IN PLAIN SIGHT", "Is alcohol the deadliest drug of modern society?", "STAT News's series 'The Deadliest Drug' shows that alcohol is the substance causing the most death and disease in the US",
   [("178,000", "deaths a year in the US directly or indirectly linked to alcohol"), ("~3 million", "deaths a year worldwide; about 5% of all deaths"), ("13%", "of deaths among 20- to 39-year-olds are attributed to alcohol"), ("~30%", "rise in alcohol-related death rates from 2016–2017 to 2020–2021")], "ANNUAL DEATHS IN THE US, APPROXIMATE",
   [("Alcohol 178,000;", "opioids (prescription and illegal) 80,000; fentanyl 73,000; cocaine 24,000; methamphetamine 17,000; benzodiazepines 12,000."),
    ("Why it stays invisible:", "it is legal and easily available, culturally normalised, and protected by advertising, sponsorship and a strong industry lobby."),
    ("Is any amount safe?", "even low intake raises cancer risk; no level is risk-free.")],
   "Alcohol alone causes more deaths than many other substances combined."),
 'de': D("DIE EPIDEMIE VOR ALLER AUGEN", "Ist Alkohol die tödlichste Droge der modernen Gesellschaft?", "Die STAT-News-Serie „The Deadliest Drug“ zeigt: Alkohol verursacht in den USA die meisten Todesfälle und die größte Krankheitslast",
   [("178.000", "Todesfälle pro Jahr in den USA stehen direkt oder indirekt mit Alkohol in Verbindung"), ("~3 Millionen", "Todesfälle pro Jahr weltweit; etwa 5 % aller Todesfälle"), ("13 %", "der Todesfälle bei 20- bis 39-Jährigen werden Alkohol zugeschrieben"), ("~30 %", "Anstieg der alkoholbedingten Sterberaten von 2016–2017 bis 2020–2021")], "JÄHRLICHE TODESFÄLLE IN DEN USA, UNGEFÄHR",
   [("Alkohol 178.000;", "Opioide (verordnet und illegal) 80.000; Fentanyl 73.000; Kokain 24.000; Methamphetamin 17.000; Benzodiazepine 12.000."),
    ("Warum es unsichtbar bleibt:", "legal und leicht erhältlich, kulturell normalisiert und durch Werbung, Sponsoring und eine starke Industrielobby geschützt."),
    ("Gibt es eine sichere Menge?", "Schon geringer Konsum erhöht das Krebsrisiko; ein risikofreies Niveau gibt es nicht.")],
   "Alkohol allein verursacht mehr Todesfälle als viele andere Substanzen zusammen."),
 'es': D("LA EPIDEMIA A LA VISTA DE TODOS", "¿Es el alcohol la droga más mortífera de la sociedad moderna?", "La serie de STAT News «The Deadliest Drug» muestra que el alcohol es la sustancia que causa más muertes y enfermedad en EE. UU.",
   [("178.000", "muertes al año en EE. UU. relacionadas directa o indirectamente con el alcohol"), ("~3 millones", "de muertes al año en el mundo; cerca del 5 % de todas las muertes"), ("13 %", "de las muertes entre los 20 y los 39 años se atribuye al alcohol"), ("~30 %", "de aumento de las tasas de muerte por alcohol entre 2016–2017 y 2020–2021")], "MUERTES ANUALES EN EE. UU., APROXIMADAS",
   [("Alcohol 178.000;", "opioides (con receta e ilegales) 80.000; fentanilo 73.000; cocaína 24.000; metanfetamina 17.000; benzodiacepinas 12.000."),
    ("Por qué pasa inadvertido:", "es legal y fácil de conseguir, está normalizado culturalmente y lo protegen la publicidad, el patrocinio y un potente lobby."),
    ("¿Hay alguna cantidad segura?", "incluso un consumo bajo aumenta el riesgo de cáncer; no existe un nivel sin riesgo.")],
   "El alcohol por sí solo causa más muertes que muchas otras sustancias juntas."),
 'ru': D("ЭПИДЕМИЯ У ВСЕХ НА ВИДУ", "Алкоголь самый смертоносный наркотик современного общества?", "Серия STAT News «The Deadliest Drug» показывает: алкоголь вызывает в США больше всего смертей и болезней",
   [("178 000", "смертей в год в США прямо или косвенно связаны с алкоголем"), ("~3 млн", "смертей в год в мире; около 5 % всех смертей"), ("13 %", "смертей в возрасте 20–39 лет связывают с алкоголем"), ("~30 %", "рост смертности, связанной с алкоголем, с 2016–2017 по 2020–2021 гг.")], "ЕЖЕГОДНЫЕ СМЕРТИ В США, ПРИБЛИЗИТЕЛЬНО",
   [("Алкоголь 178 000;", "опиоиды (рецептурные и нелегальные) 80 000; фентанил 73 000; кокаин 24 000; метамфетамин 17 000; бензодиазепины 12 000."),
    ("Почему это остаётся незаметным:", "алкоголь легален и доступен, культурно нормализован и защищён рекламой, спонсорством и сильным отраслевым лобби."),
    ("Есть ли безопасная доза?", "даже небольшое потребление повышает риск рака; безопасного уровня нет.")],
   "Один только алкоголь вызывает больше смертей, чем многие другие вещества вместе взятые."),
 'zh': D("就在眼前的流行病", "酒精是现代社会最致命的毒品吗？", "STAT News系列报道《最致命的毒品》显示，酒精是在美国造成死亡和疾病负担最多的物质",
   [("17.8万", "美国每年与酒精直接或间接相关的死亡人数"), ("约300万", "全球每年的相关死亡；约占全部死亡的5%"), ("13%", "20–39岁人群的死亡归因于酒精"), ("约30%", "2016–2017年至2020–2021年酒精相关死亡率的升幅")], "美国每年死亡人数（约数）",
   [("酒精17.8万；", "阿片类（处方及非法）8万；芬太尼7.3万；可卡因2.4万；甲基苯丙胺1.7万；苯二氮䓬类1.2万。"),
    ("为什么视而不见：", "合法且容易获得，在文化上被视为正常，并受到广告、赞助和强大行业游说的保护。"),
    ("有没有安全剂量？", "即使少量饮酒也会增加患癌风险；不存在无风险的饮酒量。")],
   "仅酒精一项造成的死亡，就超过许多其他物质的总和。"),
 'hi': D("आँखों के सामने की महामारी", "क्या शराब आधुनिक समाज का सबसे घातक नशा है?", "STAT News की शृंखला “The Deadliest Drug” दिखाती है कि अमेरिका में सबसे अधिक मौतों और बीमारियों का कारण शराब है",
   [("1,78,000", "अमेरिका में हर वर्ष शराब से प्रत्यक्ष या परोक्ष रूप से जुड़ी मौतें"), ("~30 लाख", "दुनिया में हर वर्ष मौतें; कुल मौतों का लगभग 5%"), ("13%", "20–39 वर्ष के लोगों की मौतें शराब से जुड़ी"), ("~30%", "2016–2017 से 2020–2021 के बीच शराब-संबंधी मृत्यु दर में वृद्धि")], "अमेरिका में वार्षिक मौतें, लगभग",
   [("शराब 1,78,000;", "ओपिओइड (नुस्खे वाले और अवैध) 80,000; फ़ेंटेनिल 73,000; कोकीन 24,000; मेथैम्फ़ेटामीन 17,000; बेंज़ोडायज़ेपीन 12,000।"),
    ("यह अदृश्य क्यों रहती है:", "क़ानूनी और आसानी से उपलब्ध, सांस्कृतिक रूप से सामान्य, और विज्ञापन, प्रायोजन तथा मज़बूत उद्योग लॉबी से संरक्षित।"),
    ("क्या कोई सुरक्षित मात्रा है?", "थोड़ा सेवन भी कैंसर का जोखिम बढ़ाता है; कोई भी स्तर जोखिम-मुक्त नहीं।")],
   "अकेली शराब कई अन्य पदार्थों के कुल योग से अधिक मौतों का कारण बनती है।"),
 'ja': D("目の前にある流行", "アルコールは現代社会で最も致命的な薬物か", "STAT Newsの連載「The Deadliest Drug」は、米国で最も多くの死亡と疾病負担をもたらす物質がアルコールであることを示している",
   [("17万8千人", "米国で毎年、直接または間接にアルコールに関連する死亡"), ("約300万人", "世界で毎年。全死亡の約5%"), ("13%", "20〜39歳の死亡のうちアルコールに起因する割合"), ("約30%", "2016〜2017年から2020〜2021年にかけてのアルコール関連死亡率の上昇")], "米国の年間死亡数（概数）",
   [("アルコール17万8千人、", "オピオイド（処方薬と違法薬物）8万人、フェンタニル7万3千人、コカイン2万4千人、メタンフェタミン1万7千人、ベンゾジアゼピン1万2千人。"),
    ("なぜ見えにくいのか：", "合法で手に入りやすく、文化的に当たり前とされ、広告やスポンサーシップ、強力な業界ロビーに守られている。"),
    ("安全な量はあるのか：", "少量でもがんのリスクは上がる。リスクのない量はない。")],
   "アルコールだけで、他の多くの物質を合わせたよりも多くの死亡を引き起こしている。"),
})

# 80 — White House MFN savings report
CARDS['mfnrapor'] = ('blue', {
 'en': D("WHITE HOUSE REPORT · 5 MAY 2026", "Savings from Most-Favored-Nation drug pricing policy", "US drug prices are to be tied to the lowest or similar price levels in other developed countries",
   [("$529 billion", "estimated total savings over 10 years"), ("$64.3 billion", "Medicaid savings (federal and state)"), ("2–5×", "what Americans pay for the same drug, according to the White House")], None,
   [("Which drugs:", "biologics, oncology drugs and GLP-1 drugs (Ozempic, Wegovy, Mounjaro, Zepbound, Trulicity)."),
    ("What is disputed:", "the 529-billion-dollar estimate is considered optimistic; companies may raise prices in other countries; innovation and product launches may suffer."),
    ("Why it matters for Türkiye:", "Türkiye already uses low reference prices. If MFN widens, our low prices could affect US prices, raising the risk that some drugs arrive late, face supply problems or are withdrawn from the market.")]),
 'de': D("BERICHT DES WEISSEN HAUSES · 5. MAI 2026", "Einsparungen durch die Most-Favored-Nation-Preispolitik", "Die US-Arzneimittelpreise sollen an die niedrigsten oder ähnliche Preisniveaus anderer Industrieländer gekoppelt werden",
   [("529 Mrd. $", "geschätzte Gesamteinsparung in 10 Jahren"), ("64,3 Mrd. $", "Einsparung bei Medicaid (Bund und Bundesstaaten)"), ("2–5×", "so viel mehr zahlen Amerikaner laut Weißem Haus für dasselbe Medikament")], None,
   [("Welche Medikamente:", "Biologika, Onkologika und GLP-1-Medikamente (Ozempic, Wegovy, Mounjaro, Zepbound, Trulicity)."),
    ("Was umstritten ist:", "Die Schätzung von 529 Milliarden gilt als optimistisch; Firmen könnten die Preise in anderen Ländern anheben; Innovation und Markteinführungen könnten leiden."),
    ("Warum es für die Türkei wichtig ist:", "Die Türkei nutzt bereits niedrige Referenzpreise. Weitet sich MFN aus, könnten unsere niedrigen Preise die US-Preise beeinflussen, mit dem Risiko verspäteter Einführung, von Lieferproblemen oder Marktrückzügen.")]),
 'es': D("INFORME DE LA CASA BLANCA · 5 DE MAYO DE 2026", "Ahorros de la política de precios de «nación más favorecida»", "Los precios de los medicamentos en EE. UU. se vincularán a los niveles más bajos o similares de otros países desarrollados",
   [("529.000 M$", "ahorro total estimado en 10 años"), ("64.300 M$", "ahorro de Medicaid (federal y estatal)"), ("2–5×", "lo que pagan de más los estadounidenses por el mismo fármaco, según la Casa Blanca")], None,
   [("Qué fármacos:", "biológicos, oncológicos y GLP-1 (Ozempic, Wegovy, Mounjaro, Zepbound, Trulicity)."),
    ("Qué se discute:", "la estimación de 529.000 millones se considera optimista; las empresas podrían subir precios en otros países; la innovación y los lanzamientos podrían resentirse."),
    ("Por qué importa a Turquía:", "Turquía ya usa precios de referencia bajos. Si la MFN se amplía, nuestros precios bajos podrían influir en los de EE. UU., con riesgo de retrasos, problemas de suministro o retirada de fármacos del mercado.")]),
 'ru': D("ДОКЛАД БЕЛОГО ДОМА · 5 МАЯ 2026", "Экономия от политики цен «наибольшего благоприятствования»", "Цены на лекарства в США будут привязаны к самым низким или близким уровням цен в других развитых странах",
   [("529 млрд $", "оценка общей экономии за 10 лет"), ("64,3 млрд $", "экономия Medicaid (федеральная и штатов)"), ("в 2–5 раз", "больше платят американцы за то же лекарство, по данным Белого дома")], None,
   [("Какие препараты:", "биологические, онкологические и препараты ГПП-1 (Ozempic, Wegovy, Mounjaro, Zepbound, Trulicity)."),
    ("О чём спорят:", "оценку в 529 млрд считают оптимистичной; компании могут поднять цены в других странах; могут пострадать инновации и вывод новых продуктов."),
    ("Почему это важно для Турции:", "Турция уже использует низкие референтные цены. При расширении MFN наши низкие цены могут влиять на цены в США, что повышает риск задержек, перебоев с поставками или ухода препаратов с рынка.")]),
 'zh': D("白宫报告 · 2026年5月5日", "最惠国药品定价政策带来的节省", "美国药价将与其他发达国家的最低价或相近价格水平挂钩",
   [("5290亿美元", "10年总节省额估计"), ("643亿美元", "医疗补助节省额（联邦和州）"), ("2–5倍", "白宫称美国人为同一种药多付的倍数")], None,
   [("涉及哪些药：", "生物制剂、肿瘤药和GLP-1类药物（Ozempic、Wegovy、Mounjaro、Zepbound、Trulicity）。"),
    ("争议所在：", "5290亿美元的估算被认为过于乐观；企业可能提高在其他国家的价格；创新和新品上市可能受影响。"),
    ("对土耳其为何重要：", "土耳其本来就采用较低的参考价。如果最惠国政策扩大，我们的低价可能影响美国价格，部分药品推迟上市、供应不畅或撤出市场的风险会上升。")]),
 'hi': D("व्हाइट हाउस रिपोर्ट · 5 मई 2026", "“मोस्ट फेवर्ड नेशन” दवा मूल्य नीति से बचत", "अमेरिका में दवाओं की कीमतें अन्य विकसित देशों के सबसे कम या मिलते-जुलते मूल्य स्तर से जोड़ी जाएँगी",
   [("529 अरब डॉलर", "10 वर्षों में कुल बचत का अनुमान"), ("64.3 अरब डॉलर", "मेडिकेड की बचत (संघीय और राज्य)"), ("2–5 गुना", "व्हाइट हाउस के अनुसार अमेरिकी उसी दवा के लिए इतना अधिक चुकाते हैं")], None,
   [("कौन-सी दवाएँ:", "जैविक दवाएँ, कैंसर की दवाएँ और GLP-1 दवाएँ (Ozempic, Wegovy, Mounjaro, Zepbound, Trulicity)।"),
    ("विवाद किस पर:", "529 अरब डॉलर का अनुमान आशावादी माना जा रहा है; कंपनियाँ दूसरे देशों में कीमतें बढ़ा सकती हैं; नवाचार और नई दवाओं की शुरुआत प्रभावित हो सकती है।"),
    ("तुर्किये के लिए क्यों अहम:", "तुर्किये पहले से कम संदर्भ कीमतें अपनाता है। MFN का दायरा बढ़ा तो हमारी कम कीमतें अमेरिकी कीमतों को प्रभावित कर सकती हैं, जिससे दवाओं के देर से आने, आपूर्ति की दिक़्क़त या बाज़ार से हटने का जोखिम बढ़ेगा।")]),
 'ja': D("ホワイトハウス報告書 · 2026年5月5日", "最恵国待遇による薬価政策がもたらす節減", "米国の薬価を、他の先進国の最低または同等の価格水準に連動させる",
   [("5,290億ドル", "10年間の節減総額の推計"), ("643億ドル", "メディケイドの節減額（連邦と州）"), ("2〜5倍", "ホワイトハウスによると、米国民が同じ薬に支払っている倍率")], None,
   [("対象となる薬：", "生物学的製剤、がん治療薬、GLP-1製剤（オゼンピック、ウゴービ、マンジャロ、ゼップバウンド、トルリシティ）。"),
    ("議論の的：", "5,290億ドルという推計は楽観的とみられている。企業は他国で価格を引き上げるかもしれない。イノベーションや新製品の発売に悪影響が出るおそれがある。"),
    ("トルコにとっての意味：", "トルコはすでに低い参照価格を用いている。MFNが拡大すれば、トルコの低価格が米国の価格に影響し、発売の遅れ、供給問題、市場撤退のリスクが高まる。")]),
})
