#!/usr/bin/env python3
"""Language versions of article pictures (infographics, covers).

Google's page translation can not translate words inside a picture. To give a picture an
English version, put a file with ".en" before the extension next to the Turkish one:

    sites/default/files/yazi-gorselleri/2026-09/abc.png      (Turkish, the original)
    sites/default/files/yazi-gorselleri/2026-09/abc.en.png   (English)

This tool finds every such pair, makes the 750x400 list picture of the English version and
writes /sites/default/files/kfd-img-lang.js. That script is loaded only on translated pages
(see tools/language_switch.py) and swaps the Turkish picture for the English one. Other
languages (de, es, ...) can be added the same way (abc.de.png); a language without its own
version falls back to English. Turkish pages are never touched.
Usage: python3 tools/image_lang.py     (safe to re-run; also run by tools/publish_article.py)
"""
import os, re, json, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = 'sites/default/files/yazi-gorselleri'
STYLE = 'sites/default/files/styles/manset_resim_stili_750x400/public/yazi-gorselleri'
OUT = os.path.join(ROOT, 'sites/default/files/kfd-img-lang.js')
LANGS = ('en', 'de', 'es', 'ru', 'zh', 'hi', 'ja')
PAIR = re.compile(r'^(.*)\.(%s)\.(png|jpe?g|webp|gif)$' % '|'.join(LANGS), re.I)

JS = r'''/* generated by tools/image_lang.py - do not edit */
(function(){
  var MAP=__MAP__;
  var tl=(new URLSearchParams(location.search).get('_x_tr_tl')||'en').toLowerCase().split('-')[0];
  var m=MAP[tl]||MAP.en; if(!m) return;
  var ORIGIN='https://klinikfarmakoloji.com';
  function path(u){ try{ return decodeURIComponent(new URL(u,location.href).pathname); }catch(e){ return ''; } }
  function swap(){
    var im=document.getElementsByTagName('img');
    for(var i=0;i<im.length;i++){ var el=im[i]; if(el.getAttribute('data-kfd-lang')) continue;
      var p=path(el.getAttribute('src')||''); var to=m[p]; if(!to) continue;
      el.setAttribute('data-kfd-lang',tl); el.removeAttribute('srcset'); el.src=ORIGIN+encodeURI(to); }
  }
  swap(); document.addEventListener('DOMContentLoaded',swap); window.addEventListener('load',swap);
  setTimeout(swap,1500); setTimeout(swap,4000);
})();
'''


def make_750(src, out):
    from PIL import Image
    os.makedirs(os.path.dirname(out), exist_ok=True)
    im = Image.open(src)
    if im.mode not in ('RGB', 'RGBA'): im = im.convert('RGB')
    w, h = im.size; target = 750 / 400
    if w / h > target:
        nw = int(h * target); box = ((w - nw) // 2, 0, (w - nw) // 2 + nw, h)
    else:
        nh = int(w / target); box = (0, (h - nh) // 2, w, (h - nh) // 2 + nh)
    im.crop(box).resize((750, 400), Image.LANCZOS).save(out)


def main():
    table = {}
    for fp in sorted(glob.glob(os.path.join(ROOT, BASE, '**', '*.*'), recursive=True)):
        rel = os.path.relpath(fp, os.path.join(ROOT, BASE)).replace(os.sep, '/')
        m = PAIR.match(rel)
        if not m: continue
        stem, lang, ext = m.group(1), m.group(2).lower(), m.group(3)
        orig = next((f'{stem}.{e}' for e in (ext, 'png', 'jpg', 'jpeg', 'webp') if os.path.exists(os.path.join(ROOT, BASE, f'{stem}.{e}'))), None)
        if not orig:
            print(f'  {rel}: no Turkish original found, skipped'); continue
        t = table.setdefault(lang, {})
        t[f'/{BASE}/{orig}'] = f'/{BASE}/{rel}'
        if os.path.exists(os.path.join(ROOT, STYLE, orig)):
            out = os.path.join(ROOT, STYLE, rel)
            if not os.path.exists(out) or os.path.getmtime(out) < os.path.getmtime(fp): make_750(fp, out)
            t[f'/{STYLE}/{orig}'] = f'/{STYLE}/{rel}'
    js = JS.replace('__MAP__', json.dumps(table, ensure_ascii=False, sort_keys=True))
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if js != old: open(OUT, 'w', encoding='utf-8').write(js)
    print('picture languages: ' + (', '.join(f'{k}: {sum(1 for p in v if "/styles/" not in p)}' for k, v in sorted(table.items())) or 'none'))


if __name__ == '__main__':
    main()
